### DISCUSSION TITLE
Running directus in subdirectory is not working

### DISCUSSION THREAD

**Discussion by Myrmod** [directus/directus#10159] [Archive]
Hello,

currently I am trying to get directus running locally in a subdirectory, because I couldn't get it to work on the server. 

What could be the reason for this?

My `package.json` looks like this:

```json
{
  "name": "cms",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "directus start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "^9.1.2",
    "mysql": "^2.18.1"
  }
}
```

My `.env` is written the same on the server:

```env
####################################################################################################
## General

PORT=4000
PUBLIC_URL=http://localhost:4000/cms

####################################################################################################
## Database

DB_CLIENT="mysql"
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_DATABASE="directus"
DB_USER="root"
DB_PASSWORD="root"


####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="f39fd07e-38b5-4406-be53-c096377a2554"
SECRET="V_A7Ry0U3ozPcN2LmMljrjSTcRAreClE"


ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"

####################################################################################################
## Auth Providers

AUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"
```

After I started the application using `npm run start` the server starts without any error messages. However if I open `http://localhost:4000/cms` I do get a 404 error.

<details>
<summary>Additional Info</summary>

### Errors Shown

```json
{"errors":[{"message":"Route /cms/ doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}
```

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

17.0.1

### What database are you using?

mysql8

### What browser are you using?

tested all of them

### What operating system are you using?

Ubuntu 20.04, Windows10 and Debian 11

### How are you deploying Directus?

running locally

</details>

**Comment by azrikahar** [comment]
Hi! [As the docs described](https://docs.directus.io/configuration/config-options/#general) (the `[1]` footnote there), The `PUBLIC_URL` environment variable doesn't really work that way, nor does it actually changes the routes. In you current scenario, you will still only be able to access the admin app via `http://localhost:4000/admin/` instead of `http://localhost:4000/cms/admin/`.

If you would like to have Directus on a subdirectory, using a reverse proxy such as Caddy, Nginx, Traefik etc should be the best tool for this particular use case 👍 Once you have it setup behind a reverse proxy under a subdirectory, the `PUBLIC_URL` can then be used to complement it to ensure URLs are working properly.

**Reply by duel-adn** [reply]
How should a reverse proxy be used?
One option is to use url rewrite (in the example /cms/admin should be rewritten as /admin). Is there a simpler option?
Thanks in advance

**Reply by azrikahar** [reply]
> One option is to use url rewrite (in the example /cms/admin should be rewritten as /admin). Is there a simpler option?

I believe a URL rewrite is still necessary since it will end up passing `/cms/admin` instead of `/admin` to directus which is an invalid route. On that note, there is also a draft (https://github.com/directus/directus/pull/10641) where we will be able configure the app to be served elsewhere rather than the current hardcoded `/admin` path.

> How should a reverse proxy be used?

Just to share a simple example using Caddy and docker compose:

## Caddyfile

```
https://test.<subdomain>.duckdns.org {
    handle /directus/* {
        uri strip_prefix /directus # alternative to rewrite in Caddy
        reverse_proxy directus:8055
    }
    handle {
        reverse_proxy whoami:80
    }
}
```

## docker-compose.yml

```yaml
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data

  directus:
    image: directus/directus:9.4.3
    container_name: directus
    restart: unless-stopped
    environment:
      - KEY=123456
      - SECRET=123456
      - PUBLIC_URL=https://test.<subdomain>.duckdns.org/directus
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
```

## Result

![chrome_Es2m36y56Q](https://user-images.githubusercontent.com/42867097/150783714-876253c6-48fe-44d3-bfbc-2a95d007ca92.png)
