### DISCUSSION TITLE
CONTENT_SECURITY_POLICY Help

### DISCUSSION THREAD

**Discussion by mark-james** [directus/directus#10833] [Archive]
Hi,
With the latest update, I'm running into some trouble that I assume is related to the #10776 change. I have a number of custom extensions that access outside services using iframe. 

I've tried to set up the CONTENT_SECURITY_POLICY env variable, but it appears according to the helmet doco that I need to use a JSON value such as -

> {
>     useDefaults: true,
>     directives: {
>       "script-src": ["'self'", "example.com"],
>       "style-src": null,
>     },
>  }

How do I do this in the env?

Thanks
Mark

**Comment by rijkvanzanten** [comment]
Heya!

[JSON can be passed in two ways](https://docs.directus.io/configuration/config-options/#type-casting-and-nesting): as a JSON literal string, or as a "nested" environment variable syntax, for example:

```bash
# Regular
KEY=123

# JSON
KEY="{\"nested\":123}"

# "Nested" env var:
KEY__NESTED=123
```

(see above linked docs for more information)

With this in mind, you can set any of those directives in helmet's config through:

`CONTENT_SECURITY_POLICY_USE_DEFAULTS=true`
`CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC=example.com`
`CONTENT_SECURITY_POLICY_DIRECTIVES__STYLE_SRC=example.com`

**Reply by mark-james** [reply]
Thanks for your help @rijkvanzanten.

For those with a similar use case. I was able to get iframes to work with the following variables.

      CONTENT_SECURITY_POLICY_USE_DEFAULTS: true
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "[\"example1.com\",\"example2.com\",\"example3.com\"]"

**Reply by AaronBeaudoin** [reply]
How exactly do these environment variables get transformed into a Helmet config? Is it documented somewhere, or at least where is the relevant logic in the source code?

**Reply by AaronBeaudoin** [reply]
See [this](https://github.com/directus/directus/issues/12879#issuecomment-1104052937) reply on a related thread for the documentation on how these variables are transformed.

**Reply by AaronBeaudoin** [reply]
So it turns out at least in my experience that the first way of passing JSON discussed above **does not work**. You **must** use the second way. For example, assuming a YAML config:

```yaml
# This will work.
CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: youtube.com,www.youtube.com

# This will also work.
CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC:
  - youtube.com
  - www.youtube.com

# This will NOT work.
CONTENT_SECURITY_POLICY_DIRECTIVES: "{\"frame-src\": [\"youtube.com\", \"www.youtube.com\"]"

# This also will NOT work.
CONTENT_SECURITY_POLICY: "{\"directives\":{\"frame-src\":[\"youtube.com\",\"www.youtube.com\"]}}"
```

If I'm just doing it wrong, let me know. As a side note, in my opinion the dream would be to be able to do this:

```yaml
CONTENT_SECURITY_POLICY:
  directives:
    frame-src:
      - youtube.com
      - www.youtube.com
```

So basically, if the config is in YAML or JSON, pass inner objects straight on to the third-party library. Beautiful. ✨
