### DISCUSSION TITLE
Migrations not being applied when running via Docker

### DISCUSSION THREAD

**Discussion by CoenWarmer** [directus/directus#11502] [Archive]
I am using the Directus 9.5.1 docker image with docker-compose, using Postgres as DB.

I have created a migration script which I am trying to apply. Directus says it is applied, but I am not seeing the results of the migration.

I am following the instructions on https://docs.directus.io/extensions/migrations/#structure:
* I've created a file (`202202071543-add-MDL-questionnaire.js`)
* I've placed it in the `/directus/extensions/migrations` folder.
* To test I have used the same structure as provided in the docs:

```js
module.exports = {
	async up(knex) {
		await knex.schema.createTable('test', (table) => {
			table.increments();
			table.string('rijk');
		});
	},

	async down(knex) {
		await knex.schema.dropTable('test');
	},
};
```

I then run `npx directus database migrate:latest`:

```
15:12:00 ✨ Running migrations...
15:12:00 ✨ Database up to date
```

However, there is no sign the migration is actually applied; I'm not seeing any table being created in the Directus App.

Am I doing something wrong or is something broken?

### To Reproduce

1. Create a folder `/migrations/migrations`
3. Create a file in that folder: `202202071543-add-MDL-questionnaire.js` with the aforementioned contents
2. Create docker-compose file: 

```yaml
version: '3.2'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.5.1
    ports:
      - 8055:8055
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume When using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
      - "./migrations/snapshots/snapshot.yaml:/directus/snapshot.yaml:ro"
      - "./migrations/migrations:/directus/extensions/migrations:ro"      
    command:
        - /bin/sh
        - -c
        - |
          npx directus schema apply --yes ./snapshot.yaml
          echo 'migrating things'
          npx directus database migrate:latest
          npx directus start
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:
```
3. Start container by running `docker-compose up -d`
4. Check to see if migration is applied -> does not seem like it
5. Shell into the running container, navigate to `/directus/extensions/migrations`. Run `ls` to confirm file is viewable
6. Run `npx directus database migrate:latest` again
7. Check to see if migration is applied -> does not seem like it

<details>
<summary>More Info</summary>

### Errors Shown

No errors, command completes successfully but seems like nothing happened.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Locally with Docker

</details>

**Comment by azrikahar** [comment]
Moving this to discussion as it should be a config/usage thing rather than an actual bug, but will move it back again once we gather more info 👍

---

During such cases, I'd recommended trimming things down as an attempt to remove any unneeded variables 1st. That said, I have tried with the following setup and it worked for me, can you verify if it works for you as well?

### Host machine

```
.
├── migrations
│   └── 202202071543-add-MDL-questionnaire.js    
└── docker-compose.yml
```

### docker-compose.yml

```yaml
services:
    directus:
        image: directus/directus:9.5.1
        container_name: directus
        ports:
            - 8055:8055
        volumes:
            - ./migrations:/directus/extensions/migrations:ro
        command:
            - /bin/sh
            - -c
            - |
              npx directus database install &&
              echo 'migrating things' &&
              npx directus database migrate:latest &&
              npx directus start
        environment:
            - KEY=5faf43c8-f154-42ec-93ef-8d2a5ecfc95b
            - SECRET=f2w7xBOWOjaXqm5yfDD0P0C8fgcqXQ5i
            - ADMIN_EMAIL=admin@example.com
            - ADMIN_PASSWORD=d1r3ctu5
```

### Terminal result showing the migration is ran:

 
![WindowsTerminal_EHNAGPLGtn](https://user-images.githubusercontent.com/42867097/152934054-705bde26-be07-4e8c-b406-086212dbfe2f.png)
 
---

Some potential differences that I can think of:

- try to add `&&` when chaining commands just to be safe
- As we are overriding the original command, we need to add `npx directus database install` to install directus tables

Another important thing of note is since you _are not_ doing `npx directus database install` at all and you are not seeing any "directus tables are not installed" errors, I'm suspecting you are applying migration to an existing database that **ALREADY RAN** `202202071543-add-MDL-questionnaire` migration! You should check your `directus_migrations` to verify this.
