### DISCUSSION TITLE
Set custom max-http-header-size for NodeJS

### DISCUSSION THREAD

**Discussion by nathanhere** [directus/directus#11661] [Archive]
I have many specific fields that I'm querying, and recently ran into a limit that returned a Socket Hangup Error on the client side(431 Request Header Fields Too Large). After quite some research, I discovered that there is a limit in NodeJS (`max-http-header-size`) that can be set upon NodeJS startup, however, I'm using Directus via Docker Compose.

**How can this setting be adjusted using Directus in docker?**

**Comment by nathanhere** [comment]
Got it :) Setting `NODE_OPTIONS: "--max-http-header-size=32768"` in the environment section of the dockercompose.yaml worked!

```
  directus:
    ...
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      NODE_OPTIONS: "--max-http-header-size=32768"
   ...
```
