### DISCUSSION TITLE
Add dropdown to select a application `color theme` like `default | blue | red | green`

### DISCUSSION THREAD

**Discussion by LasseRosenow** [directus/directus#11969] [Feature Requests]
I do want this feature for some time already, but especially with the new 9.6 release, which introduced a new theme, that is pink in dark mode, I would really much like this feature rather soon then late :D.
While we do like most of the new design changes, my team thinks that the new default pink theme looks a bit `too silly` in dark mode, which is why we are now overriding the css variables in all our directus instances.

I am glad however, that it is already very easy by just using the already defined css variables like so:

```css

* {
    --primary-alt: var(--blue-alt) !important;
    --primary-10: var(--blue-10) !important;
    --primary-25: var(--blue-20) !important;
    --primary-50: var(--blue-50) !important;
    --primary-75: var(--blue-75) !important;
    --primary-90: var(--blue-90) !important;
    
    --primary: var(--blue) !important;
    
    --primary-110: var(--blue-110) !important;
    --primary-125: var(--blue-125) !important;
    --primary-150: var(--blue-150) !important;
    --primary-175: var(--blue-175) !important;
    --primary-190: var(--blue-190) !important;
}

```

Now there are 3 things that I would like to be changed:

 1. those variables like `--blue-10` etc. should be a bit brighter in dark mode to have a better contrast.
 2. We already have css variables for multiple basic colors pre-defined inside directus. why not create a dropdown to select which theme to use instead of heaving to write css code?
 3. Set default theme via env-variable. This way our company would not have to change the theme for every new website and would just be set up straightaway with the theme that fits our needs best :)
