### DISCUSSION TITLE
How to install/use custom fonts in Directus?

### DISCUSSION THREAD

**Discussion by arladmin** [directus/directus#12355] [Archive]
I would like to make use of certain fonts which are currently unavailable in the Input/WYSIWIG interfaces.
To start with, i would like to import particular google fonts.

Is it currently possible to achieve this?
If yes, how?

**Comment by rijkvanzanten** [comment]
You can use CSS' `@import` in the Custom CSS option in project settings, for example:

```css
@import url('https://fonts.googleapis.com/css2?family=Palette+Mosaic&display=swap');

body {
    --family-sans-serif: 'Palette Mosaic', cursive;
}
```

![CleanShot 2022-03-24 at 14 16 32@2x](https://user-images.githubusercontent.com/9141017/159983838-53b3ff37-e723-4f72-addf-793db9454586.png)

**Reply by benhaynes** [reply]
🤮

**Reply by aidenfoxx** [reply]
New default? 🤩

**Reply by arladmin** [reply]
@rijkvanzanten 

Thanks a lot for your reply.

Could you also tell me how to apply the font, as a selection, only in the Input/WYSIWIG interfaces, and not the entire project?

**Reply by rijkvanzanten** [reply]
It should be regular css scoping at that point. You can inspect the element you'd like to set it for, and override the env-vars based on that scope 👍🏻 

```css
.any-selector #you [need] {
  --family-monospace: 'comic sans ms';
}
```
