### DISCUSSION TITLE
CONTENT_SECURITY_POLICY config is broken

### DISCUSSION THREAD

**Discussion by justrealmilk** [directus/directus#12474] [Archive]
After several attempts at discerning documentation and previous issues, I've concluded it must be broken.

Here's an [image asset](https://directus.upliftnaturereserve.com/bt03/assets/a5515b77-593d-4868-8e44-8aa3fe92383d) (works)
Here's a [video asset](https://directus.upliftnaturereserve.com/bt03/assets/d96dc263-2991-4788-82d5-41d68162c637) (does not work)

I've attempted to set various values.

```yaml
CONTENT_SECURITY_POLICY: "media-src 'self' https://patreon.com https://bray.tech https://beta.bray.tech"
CONTENT_SECURITY_POLICY_DIRECTIVES__MEDIA_SRC: "media-src 'self' https://patreon.com https://bray.tech https://beta.bray.tech"
CONTENT_SECURITY_POLICY: "{ directives: { mediaSrc: ['self', 'https://patreon.com', 'https://bray.tech', 'https://beta.bray.tech'], }, }"
ASSETS_CONTENT_SECURITY_POLICY: "media-src 'self' https://patreon.com https://bray.tech https://beta.bray.tech"
```

And so on. None of these properties are reflected once the container has been recreated and started. The `content-security-policy: default-src none` response header does not change.

Cloudflare caching is off.

<details>
<summary>More Info</summary>

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

14.17.3

### What database are you using?

--

### What browser are you using?

--

### What operating system are you using?

--

### How are you deploying Directus?

Docker

</details>
