### DISCUSSION TITLE
Where do extension logs go?

### DISCUSSION THREAD

**Discussion by AaronBeaudoin** [directus/directus#12855] [Archive]
I'm probably missing something, but when I create a new "hook" extension and copy the `dist/index.js` file to `extensions/hooks/<name>/index.js` as instructed, I don't actually get any logs. I can see that the extension was loaded successfully in the server log, but I don't actually get the message my extension is supposed to log. Here is the `src/index.js` file:

```js
export default ({ filter }) => {
  filter("items.create", () => {
    console.log("test");
  });
};
```

To test it, I simply create a new item in a test collection I created in the admin UI. When I do, no "test" message is outputted in the server log. Do I need to change the log level or something?

_EDIT: Changing the log level doesn't seem to solve the problem._

**Comment by rijkvanzanten** [comment]
Console logs should still be rendered in stdout of wherever you're running Directus 🤔 Console.log doesn't use the same logger as regular Directus, so the log_level configuration doesn't affect it

**Reply by AaronBeaudoin** [reply]
Well maybe it's a thing with the Directus Docker container because I'm running using that. Here is my `docker-compose.yaml`:

```yaml
services:
  directus-database:
    image: postgres:14
    container_name: directus-database
    ports: [5433:5432]
    volumes:
      - directus-database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=directus
      - POSTGRES_PASSWORD=directus
  directus-server:
    image: directus/directus:9.9.0
    container_name: directus-server
    depends_on: [directus-database]
    ports: [8055:8055]
    volumes:
      - ./directus-uploads/:/directus/uploads/
      - ./directus-extensions/:/directus/extensions/
    environment:
      - KEY=directus
      - SECRET=directus
      - ADMIN_EMAIL=directus@example.com
      - ADMIN_PASSWORD=directus
      - DB_CLIENT=postgres
      - DB_HOST=directus-database
      - DB_PORT=5432
      - DB_DATABASE=directus
      - DB_USER=directus
      - DB_PASSWORD=directus
      - EXTENSIONS_AUTO_RELOAD=true

volumes:
  directus-database-data:
    name: directus-database-data

networks:
  default:
    name: directus
```

I run Directus with simply `docker compose up`.

The exact output in `./directus-extensions/hooks/<name>/index.js` is:

```js
"use strict";module.exports=({filter:e})=>{e("items.create",(()=>{console.log("test")}))};
```

I see `Loaded extensions: <name>` in my server log, so I know it was initialized. Not sure what else to try at the moment.
