### DISCUSSION TITLE
Directus Docker latest: Cannot find module 'oracledb'

### DISCUSSION THREAD

**Discussion by CHSchuepfer** [directus/directus#13216] [Archive]
Hey everyone,

i was trying to setup Directus in a Container with an Oracle Connection.
Sadly i always get the "Cannot find module" Erro thrown (full Stacktrace below).

I dont have these problems with mssql or Postgres.
Is that the problem u wrote which is written here https://docs.directus.io/getting-started/installation/docker/#supported-databases which links to https://blogs.oracle.com/opal/post/dockerfiles-for-node-oracledb-are-easy-and-simple   ?

Any idea how i can fix that? Bc as is looks to me the npm installer just simply cant fide the package?

Thanks and so long :)

### To Reproduce

```yaml
version: '3'
services:
  direct_cache:
    restart: unless-stopped
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    
    restart: unless-stopped
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8080:8055
    volumes:
      - ./file_store:/directus/uploads
    networks:
      - directus
    depends_on:
      - direct_cache
    environment:

      DB_CLIENT: 'oracledb'
      DB_HOST: 'IP_ADRESS'
      DB_PORT: '1521'
      DB_DATABASE: 'DB123'
      DB_USER: 'DB_USER'
      DB_PASSWORD: 'USER_PW'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'my_@e.mail'
      ADMIN_PASSWORD: 'my_password'

networks:
  directus:
```

### Errors Shown

```
directus  | 01:29:29 ✨ Initializing bootstrap...
directus  | 01:29:29 🚨 Knex: run
directus  | $ npm install oracledb --save
directus  | Cannot find module 'oracledb'
directus  | Require stack:
directus  | - /directus/node_modules/knex/lib/dialects/oracledb/index.js
directus  | - /directus/node_modules/knex/lib/knex-builder/internal/config-resolver.js
directus  | - /directus/node_modules/knex/lib/knex-builder/Knex.js
directus  | - /directus/node_modules/knex/lib/index.js
directus  | - /directus/node_modules/knex/knex.js
directus  | - /directus/node_modules/directus/dist/database/index.js
directus  | - /directus/node_modules/directus/dist/services/items.js
directus  | - /directus/node_modules/directus/dist/services/index.js
directus  | - /directus/node_modules/directus/dist/middleware/respond.js
directus  | - /directus/node_modules/directus/dist/controllers/activity.js
directus  | - /directus/node_modules/directus/dist/app.js
directus  | - /directus/node_modules/directus/dist/server.js
directus  | - /directus/node_modules/directus/dist/cli/index.js
directus  | - /directus/node_modules/directus/dist/cli/run.js
directus  | - /directus/node_modules/directus/cli.js
directus  | Error: Cannot find module 'oracledb'
directus  | Require stack:
directus  | - /directus/node_modules/knex/lib/dialects/oracledb/index.js
directus  | - /directus/node_modules/knex/lib/knex-builder/internal/config-resolver.js
directus  | - /directus/node_modules/knex/lib/knex-builder/Knex.js
directus  | - /directus/node_modules/knex/lib/index.js
directus  | - /directus/node_modules/knex/knex.js
directus  | - /directus/node_modules/directus/dist/database/index.js
directus  | - /directus/node_modules/directus/dist/services/items.js
directus  | - /directus/node_modules/directus/dist/services/index.js
directus  | - /directus/node_modules/directus/dist/middleware/respond.js
directus  | - /directus/node_modules/directus/dist/controllers/activity.js
directus  | - /directus/node_modules/directus/dist/app.js
directus  | - /directus/node_modules/directus/dist/server.js
directus  | - /directus/node_modules/directus/dist/cli/index.js
directus  | - /directus/node_modules/directus/dist/cli/run.js
directus  | - /directus/node_modules/directus/cli.js
directus  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
directus  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
directus  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
directus  |     at require (node:internal/modules/cjs/helpers:102:18)
directus  |     at Client_Oracledb._driver (/directus/node_modules/knex/lib/dialects/oracledb/index.js:37:22)
directus  |     at Client_Oracledb.initializeDriver (/directus/node_modules/knex/lib/client.js:190:26)
directus  |     at new Client (/directus/node_modules/knex/lib/client.js:75:12)
directus  |     at new Client_Oracle (/directus/node_modules/knex/lib/dialects/oracle/index.js:14:1)
directus  |     at new Client_Oracledb (/directus/node_modules/knex/lib/dialects/oracledb/index.js:27:5)
directus  |     at knex (/directus/node_modules/knex/lib/knex-builder/Knex.js:12:28)
directus  | Error: Knex: run
directus  | $ npm install oracledb --save
directus  | Cannot find module 'oracledb'
directus  | Require stack:
directus  | - /directus/node_modules/knex/lib/dialects/oracledb/index.js
directus  | - /directus/node_modules/knex/lib/knex-builder/internal/config-resolver.js
directus  | - /directus/node_modules/knex/lib/knex-builder/Knex.js
directus  | - /directus/node_modules/knex/lib/index.js
directus  | - /directus/node_modules/knex/knex.js
directus  | - /directus/node_modules/directus/dist/database/index.js
directus  | - /directus/node_modules/directus/dist/services/items.js
directus  | - /directus/node_modules/directus/dist/services/index.js
directus  | - /directus/node_modules/directus/dist/middleware/respond.js
directus  | - /directus/node_modules/directus/dist/controllers/activity.js
directus  | - /directus/node_modules/directus/dist/app.js
directus  | - /directus/node_modules/directus/dist/server.js
directus  | - /directus/node_modules/directus/dist/cli/index.js
directus  | - /directus/node_modules/directus/dist/cli/run.js
directus  | - /directus/node_modules/directus/cli.js
directus  |     at Client_Oracledb.initializeDriver (/directus/node_modules/knex/lib/client.js:194:13)
directus  |     at new Client (/directus/node_modules/knex/lib/client.js:75:12)
directus  |     at new Client_Oracle (/directus/node_modules/knex/lib/dialects/oracle/index.js:14:1)
directus  |     at new Client_Oracledb (/directus/node_modules/knex/lib/dialects/oracledb/index.js:27:5)
directus  |     at knex (/directus/node_modules/knex/lib/knex-builder/Knex.js:12:28)
directus  |     at getDatabase (/directus/node_modules/directus/dist/database/index.js:106:32)
directus  |     at Command.bootstrap (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:36:45)
directus  |     at Command.listener [as _actionHandler] (/directus/node_modules/commander/lib/command.js:488:17)
directus  |     at /directus/node_modules/commander/lib/command.js:1227:65
directus  |     at Command._chainOrCall (/directus/node_modules/commander/lib/command.js:1144:12)
directus exited with code 1

```

<details>
<summary>More info</summary>

### What version of Directus are you using?

latest, 9, 9.10

### What version of Node.js are you using?

included in Docker Image

### What database are you using?

Oracle 19 C

### What browser are you using?

Chrome/Firefox

### How are you deploying Directus?

Docker

</details>

**Comment by azrikahar** [comment]
> Is that the problem u wrote which is written here https://docs.directus.io/getting-started/installation/docker/#supported-databases which links to https://blogs.oracle.com/opal/post/dockerfiles-for-node-oracledb-are-easy-and-simple ?

That is correct! It's also mentioned in the CLI installation section (the 3rd footnote): https://docs.directus.io/getting-started/installation/cli/

> Make sure to install `node-oracledb` and it's system dependencies when using OracleDB

Which probably feels clearer on the "install" call to action. You should be able to refer to the `Update #3` section towards the end of the blog post https://blogs.oracle.com/opal/post/dockerfiles-for-node-oracledb-are-easy-and-simple and extend the current Directus docker image to add/install them in a Dockerfile.

**Reply by CHSchuepfer** [reply]
Hey,

thanks for the answer. I got it running. Pretty much the same as you suggested.
For anyone in the future searching for an "okay" but not production ready fix, here is my current quick and dirty way:

### Dockerfile

```Dockerfile
FROM directus/directus:latest

USER root
RUN (apk update && apk upgrade && apk --no-cache add bash libaio curl libnsl libc6-compat unzip && \
    curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -SL && \
      unzip instantclient-basiclite.zip && \
      mv instantclient*/ /usr/lib/instantclient && \
      ln -s /usr/lib/instantclient/libclntsh.so.19.1 /usr/lib/libclntsh.so && \
      ln -s /usr/lib/instantclient/libocci.so.19.1 /usr/lib/libocci.so && \
      ln -s /usr/lib/instantclient/libociicus.so /usr/lib/libociicus.so && \
      ln -s /usr/lib/instantclient/libnnz19.so /usr/lib/libnnz19.so && \
      ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 && \
      ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
      ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2 && \
      npm install node-oracledb)
```

### docker-compose.yml

```yaml
version: '3'
services:
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    build: ./directus/
    ports:
      - 8055:8055
    volumes:
      - ./file_storage:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      ADMIN_EMAIL: 'my@e.mail'
      ADMIN_PASSWORD: 'super_secure_password'
    env_file:
      - .env

networks:
  directus:
```


Just to reiterate, this is not production ready as seen by the KEY & SECRET Vars. Also i dont like the current Runlevel (root). But that is something i can fix relatively quickly. For now its ok.

Thanks again @azrikahar for the quick answer!


So long
