### DISCUSSION TITLE
Not able to upgrade from 9.9.0 to 9.9.1

### DISCUSSION THREAD

**Discussion by coignite-user** [directus/directus#13361] [Archive]
### Describe the Bug

Directus is not able to connect to database when upgrading from version 9.9.0 to version 9.9.1 on App Platform (Digital Ocean). Everything works until I `npm install directus@9.9.1` and push it to App Platform.

Nothing changed in connection to the database. It all works for version 9.9.0, but obviously not for the next minor. Could it be some environment variable that is required? I can't read it from the docs. Otherwise I don't know what it could be.

### To Reproduce

Install version 9.9.0 on App Platform and then upgrade to version 9.9.1.

### Errors Shown

I tried to upgrade from version 9.6.0 to version 9.10.0 but it failed with the following error:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/28866431/168747651-0b5580f2-a5b2-48e3-9c45-16c10bc1b927.png">

Then I tried to update one version at a time and reached version 9.9.0. When I upgraded to version 9.9.1 I experienced the error above.

When running `npx directus database migrate:latest` it states that the database is up-to-date, but I believe it should be sufficient  running `npx directus bootstrap && npx directus start` when initialising Directus, it does all the required migrations.

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

App Platform (Digital Ocean)

**Comment by superhp** [comment]
We have same issue when upgrading 9.9.0 -> 9.9.1 and 9.9.0 -> 9.10.0 . We host Directus in Azure App Service and use Azure SQL Server for database. It is strange that the upgrade works locally (even when pointing to the same DB) but not when deployed. So the issue seems to be related to application hosting environment.

**Comment by rijkvanzanten** [comment]
What are your environment variables for connecting to the database?

**Reply by coignite-user** [reply]
Hi @rijkvanzanten, it is:

```yaml
envs:
- key: DB_CLIENT
  scope: RUN_AND_BUILD_TIME
  value: "pg"
- key: DB_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.HOSTNAME}
- key: DB_SSL__REJECT_UNAUTHARIZED
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: DB_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.PORT}
- key: DB_DATABASE
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.DATABASE}
- key: DB_USER
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.USERNAME}
- key: DB_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.PASSWORD}
- key: DB_SSL__CA
  scope: RUN_AND_BUILD_TIME
  value: ${test-database.CA_CERT}
```
It is working now, but stops working when updating to the new version of Directus. No changes are done to the setup at all. All the upgrades successfully installed until 9.9.1.
