### DISCUSSION TITLE
The extension manifest of "@directus/extension-toolkit" is not valid.

### DISCUSSION THREAD

**Discussion by lukeliasi** [directus/directus#13753] [Archive]
### Describe the Bug

I created a blank fresh interface extension following this guide: [Creating Extensions
](https://docs.directus.io/extensions/creating-extensions/#creating-extensions) I get the error **The extension manifest of "@directus/extension-toolkit" is not valid.** when  directus starts up. I am using docker compose.

I exec'd into the docker container and can see my extension in the folder but it doesn't seem to load it. In the admin UI when going to add a new input type string and go to the Interface menu, I do not see my custom interface.

Extension index.js src file:
```js
import InterfaceComponent from './interface.vue';

export default {
	id: 'custom',
	name: 'Custom',
	icon: 'box',
	description: 'This is my custom interface!',
	component: InterfaceComponent,
	options: null,
	types: ['string'],
};
```
interface.vue
```vue
<template>
	<input :value="value" @input="handleChange($event.target.value)" />
</template>

<script>
export default {
	props: {
		value: {
			type: String,
			default: null,
		},
	},
	emits: ['input'],
	setup(props, { emit }) {
		return { handleChange };

		function handleChange(value) {
			emit('input', value);
		}
	},
};
</script>
```

Compiled extension which I put in the extensions/interfaces/test folder
```js
import{openBlock as e,createElementBlock as n}from"vue";var t={props:{value:{type:String,default:null}},emits:["input"],setup:(e,{emit:n})=>({handleChange:function(e){n("input",e)}})};const u=["value"];t.render=function(t,i,a,o,r,l){return e(),n("input",{value:a.value,onInput:i[0]||(i[0]=e=>o.handleChange(e.target.value))},null,40,u)},t.__file="src/interface.vue";var i={id:"custom",name:"Custom",icon:"box",description:"This is my custom interface!",component:t,options:null,types:["string"]};export{i as default};

```

My docker-compose.yml:
```yml
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_DB: 'directus'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    build: .
    restart: always
    container_name: directus
    image: directus/directus:9.12.1
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      PUBLIC_URL: ${PUBLIC_URL}

      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      
networks:
  directus:
```

### To Reproduce

I created a new blank interface extension called "test" with `npm init directus-extension` (did not change any code) I then `cd test` and `npm run build`. I copied the `dist/index.js` into the extensions folder - `extensions/interfaces/test/index.js`.

I then run `docker compose up` and get the following warning: **The extension manifest of "@directus/extension-toolkit" is not valid.**

### Errors Shown

```
database  | 2022-06-05 15:30:22.913 UTC [1] LOG:  database system is ready to accept connections
directus  | 15:30:25 ⚠️  Couldn't load extensions
directus  | 15:30:25 ⚠️  The extension manifest of "@directus/extension-toolkit" is not valid.
directus  | 15:30:25 ✨ Initializing bootstrap...
directus  | 15:30:25 ✨ Database already initialized, skipping install
directus  | 15:30:25 ✨ Running migrations...
directus  | 15:30:25 ✨ Done
directus  | 15:30:27 ⚠️  Couldn't load extensions
directus  | 15:30:27 ⚠️  The extension manifest of "@directus/extension-toolkit" is not valid.
directus  | 15:30:28 ✨ Server started at http://0.0.0.0:8055
```

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

postgis:13-master

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
I've tested your compiled extension and it seems to work without any issue:

### Truncated logs for brevity

```
directus    | 13:08:19 ✨ Applying Add Default Language...
directus    | 13:08:19 ✨ Applying Remove Default Value Panel Icon...
directus    | 13:08:19 ✨ Applying Add Flows...
directus    | 13:08:19 ✨ Applying Add Color to Insights Icon...
directus    | 13:08:19 ✨ Applying Drop Non Null from IP of Activity...
directus    | 13:08:19 ✨ Applying Drop Non Null from Sender of Notifications...
directus    | 13:08:19 ✨ Setting up first admin role...
directus    | 13:08:19 ✨ Adding first admin user...
directus    | 13:08:19 ✨ Done
directus    | 13:08:24 ✨ Loaded extensions: test
directus    | 13:08:24 ⚠️  PUBLIC_URL should be a full URL
directus    | 13:08:25 ✨ Server started at http://0.0.0.0:8055
```

### Custom interface shown in App

![chrome_hoPhwdC0ow](https://user-images.githubusercontent.com/42867097/172170269-7d1462e4-7545-472b-a3aa-96728b42b46a.png)


---

Based on the error, I believe it stems from:

https://github.com/directus/directus/blob/b6a33891abc3f901c735715d02ce4e9dceead8aa/packages/shared/src/utils/node/get-extensions.ts#L28-L30

This is because Directus will load packages as extensions based on the name which matches:

https://github.com/directus/directus/blob/b6a33891abc3f901c735715d02ce4e9dceead8aa/packages/shared/src/constants/extensions.ts#L22

and for some reason it seems like you have `@directus/extension-toolkit` installed which is being attempted to load as an extension but it isn't? 🤔 Are you using a custom image by any chance (even though your compose file says otherwise)? It doesn't seem like that package should exist unless it's added manually. cc @nickrum in case I'm mistaken here.

**Reply by lukeliasi** [reply]
I notice `@directus/extension-toolkit` was in my package.json, after removing this line and running `npm install` it now works! I'm not sure how it got there but after doing a fresh install it doesn't include this line in package.json so I must have somehow accidentally installed this package manually.

Thanks for your help!

**Comment by cedricDevWP** [comment]
hello I try to do the same thing however the extension is not added to my directus project...

My structure project : 

```code
- api
   - extensions
       - packages
           - interfaces
               - dist
                   - index.js
               
docker-compose.yml
```

and in my yml i have : 

```yml
 api:
    container_name: api
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./api/uploads:/api/uploads
      - ./api/extensions/packages/interfaces:/api/extensions
  ```

and in my index.js : 

```js
import{defineInterface as e}from"@directus/extensions-sdk";import{defineComponent as t,openBlock as n,createElementBlock as u}from"vue";var i=t({props:{value:{type:String,default:null}},emits:["input"],setup:(e,{emit:t})=>({handleChange:function(e){t("input",e)}})});const o=["value"];i.render=function(e,t,i,r,s,a){return n(),u("input",{value:e.value,onInput:t[0]||(t[0]=t=>e.handleChange(t.target.value))},null,40,o)},i.__file="src/interface.vue";var r=e({id:"custom",name:"Custom",icon:"box",description:"This is my custom interface!",component:i,options:null,types:["string"]});export{r as default};

```

but when i start my docker i didn't see the install of my extension :

```log
20:24:15 ✨ Initializing bootstrap...
20:24:15 ✨ Database already initialized, skipping install
20:24:15 ✨ Running migrations...
20:24:15 ✨ Done
20:24:17 ⚠️  PUBLIC_URL should be a full URL
```
