### DISCUSSION TITLE
Resetting/creating password - error message is too ambiguous

### DISCUSSION THREAD

**Discussion by shipsides-sparknel** [directus/directus#13896] [Archive]
From the external login, the error message shown when a user is creating or updating their password to one that doesn't meet the policy is too ambiguous. All it says is "Unexpected error".

When the password doesn't meet the policy requirements, could this error perhaps say "Your password needs to match *auth policy*" so "Unexpected error" can be saved for edge cases? 

### To Reproduce

Auth password policy set to "Strong - Upper / lower / numbers / special"
Invite a user, or do a password reset request
Enter a password that doesn't meet the policy. "Unexpected error" is displayed
Enter a password that meets this: success

**Comment by azrikahar** [comment]
Definitely a valid point. This has been brought up in issue #8661 (which was then moved to discussion #12788) and there's still the open PR #8946 aimed at customizing this error message directly for added flexibility 👍

**Reply by benhaynes** [reply]
I think we should add a `Password Requirements Message` (input/varchar) to Settings under security to allow admins to customize what a user sees when password format fails. Also, the "Other" option for password policy should hint at the format to be used (regex?).

**Comment by shipsides-sparknel** [comment]
on a related note - when someone uses the "Create password" link for a second time after they have already created a password, the error they get is "Invalid payload". It would be great if it said something like "your password has already been created, use the <a>login page</a> instead"

I am unfortunately 2/2 on people who have been tripped up by this!

**Comment by abernh** [comment]
This is a desperate attempt to get this solved via the custom CSS settings.

Assuming
1)  this very specific layout, form, fields (especially the 2 input fields, first one is disabled) then danger-notice box is only on the reset-password page
2) this is the only important error message on that screen

then this is a CSS hack that allows for an extended error message.
Even with translation options.

```css
/* move the red-bar to the ::before pseudo element */ 
.branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width + .v-notice.danger::before{
    content: "";
    display: inherit;
    position: absolute;
    top: 0;
    left: 0;
    width: 4px;
    height: 100%;
    background-color: var(--v-notice-border-color);    
}

/* use the ::after pseudo element to hold an inline message */
.branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width + .v-notice.danger::after{
    content: "min 8 chars, lower, Upper, number & special char";
    display: inline;
    height: auto;
    position: relative;
    background-color: transparent;
    width: auto;
    padding-left: 2px;
    color: var(--foreground-subdued);
}

/* add translations for other languages */
[lang=de-DE] .branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width + .v-notice.danger::after{
    content: "min. 8 Zeichen, klein, Groß, Zahl & Sonderz.";
}
``` 

And as "making the user guess what to do" is bad UX here is the CSS to add an instruction block below the input element

```css
.branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width{
    display: block;
    height: auto;
    position: relative;
}
.branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width::before {
    content: "\01F6C8";
    position: absolute;
    top: calc(var(--input-padding) * 2 + 15px + 2px + 0.5rem + 12px);
    left: 17px;
    color: var(--v-notice-color);
    z-index: 1;
    font-size: 22px;
}
.branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width::after {
    content: "min 8 chars, lower, Upper, number & special chars";    
    margin: 0.5rem 0;    
    position: relative;
    display: flex;
    align-items: center;
    justify-content: flex-start;
    width: auto;
    padding: 12px 16px;
    padding-left: 56px;
    color: var(--v-notice-color);
    line-height: 22px;
    background-color: var(--v-notice-background-color);
    border-radius: var(--border-radius);
    overflow: hidden;
}
[lang=de-DE] .branded > .container > .title-box + .content > .type-title + form > .v-input.full-width.disabled + .v-input.full-width::after {
    content: "min. 8 Zeichen, klein, Groß, Zahl & Sonderzeichen";
}
```

**Preview**

![image](https://github.com/directus/directus/assets/2691946/952748bb-f661-422a-bbc5-b5bf9db4d734) --> ![image](https://github.com/directus/directus/assets/2691946/982b9659-e46d-4238-b54d-36275cfac723)
