### DISCUSSION TITLE
Custom Optional Default Fields

### DISCUSSION THREAD

**Discussion by imiskolee** [directus/directus#14114] [Feature Requests]
hi,all:

the directus already support optional default fields on create collection panel

<img width="338" alt="image" src="https://user-images.githubusercontent.com/4303880/175802018-c74af1b6-6324-4ba5-86f8-885996a8ae4f.png">

and I think we can easy to support custom default fields from the configuration file:

```yaml
custom_optional_fields:
   - name: MY_DEFAULT_FIELD_NAME_1
     data_type:   int | datetime | string | ...
     default_value: 1 | now() | uuid() ....
  - name: MY_DEFAULT_FIELD_NAME_2
     data_type:   int | datetime | string | ...
     default_value: 1 | now() | uuid() ....
```
