### DISCUSSION TITLE
Create nested object structure

### DISCUSSION THREAD

**Discussion by dimitarkolev** [directus/directus#14247] [Archive]
I want to model an item with the following structure (when returned by an API call)
```
title: Pricing
footer:
  next:
    href: /web/services
    title: Services
    image: /storage/animations/icon-process-v2.json
  action:
    href: /web/request
    title: Request
    image: /storage/animations/icon-contact-v2.json
```
I thought that it might possible to do it with detail group but it looks like that it does not nest the fields inside the name of the detail field. I don't want to build a relation for such a simple task. May be a repeater can bring something similar but it will not have the right semantics.
