### DISCUSSION TITLE
Match the options of dropdown interface in display

### DISCUSSION THREAD

**Discussion by aaron-manning** [directus/directus#15555] [Feature Requests]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It seems that dropdown value > text translation is only working when viewing a nested relationship one level away from where the dropdown is defined.

Exploring any deeper nesting results in displaying only the value (eg 0 for an integer dropdown, the same issue applies for string dropdowns)

### To Reproduce

create table A

create table B that has a dropdown (named size) of type int (string is also affected) with values "small" > 0
add a m2o field to table B that references table A, tick the box to add the reverse, o2m, relationship to table A (advanced view)

Edit table A
configure the o2m relationship interface display template to show the 'size' dropdown.
save table A

Table a should now be as follows:

![image](https://user-images.githubusercontent.com/32957675/152639166-ee403cd2-2767-47ff-bed5-08a2d2c83c56.png)
![image](https://user-images.githubusercontent.com/32957675/152639180-c23d4334-bc31-4ec9-b457-22f71b047faf.png)

Table b should now be as follows:

![image](https://user-images.githubusercontent.com/32957675/152639194-6c6c098d-4e54-4d0a-a862-952cbc705935.png)
![image](https://user-images.githubusercontent.com/32957675/152639202-9824c741-7f91-4088-874e-e2d6d31557f5.png)
![image](https://user-images.githubusercontent.com/32957675/152639204-bbc62de9-7997-4e2c-89a3-785f6cb15039.png)

Create a record for table A and B (with o2m/m2o relationship). set the table B record 'size' dropdown to 'small'

View the table A record (detail view) and observe that the displayed output for 'size' is 0 instead of 'small'
Click on the related table B record to open the side panel and observe that the displayed output for 'size' is now correctly 'small'

end result

![image](https://user-images.githubusercontent.com/32957675/152639231-bfc12657-3744-49a6-9890-df41e1614520.png)

![image](https://user-images.githubusercontent.com/32957675/152639238-1286858a-59b3-4cba-8944-7148c082e4a4.png)

Expected outcome:
'small' is displayed in all parts of the UI.
0 is meaningless to users and will cause confusion.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.8.1

### What database are you using?

postgres:14.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by aaron-manning** [comment]
A workaround is to use a string type dropdown and use a label display setting, but it requires duplicating the dropdown options (this is a pain when there are many options)

![image](https://user-images.githubusercontent.com/32957675/152639614-1bab5090-b75d-4a92-a6f2-e2fd61f5fa21.png)

non-string dropdowns do not have the 'label' display option and I cannot find a workaround.

![image](https://user-images.githubusercontent.com/32957675/152639665-62b56ac7-e3dd-448e-87a7-35fe4be6afc8.png)

A fix would be to add the 'label' display option to the non-string dropdown data-types.
It doesn't result in the best UX however. I feel like the default should be that dropdowns simply work everywhere and translate their values without needing to duplicate the dropdown mapping. 
The label display setting should be there if we want to customize/override what is displayed, but not be required simply to make the dropdowns work properly when viewing nested records throughout Directus.

**Comment by azrikahar** [comment]
<details>
<summary>Schema snapshot for above issue</summary>

```yaml
version: 1
directus: 9.5.1
collections:
  - collection: a
    meta:
      collection: a
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: a
      comment: null
  - collection: b
    meta:
      collection: b
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: b
      comment: null
fields:
  - collection: a
    field: id
    type: integer
    schema:
      name: id
      table: a
      schema: public
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('a_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: a
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: b
    field: id
    type: integer
    schema:
      name: id
      table: b
      schema: public
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('b_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: b
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: b
    field: size
    type: integer
    schema:
      name: size
      table: b
      schema: public
      data_type: integer
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: b
      field: size
      special: null
      interface: select-dropdown
      options:
        choices:
          - text: small
            value: 0
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: b
    field: a
    type: integer
    schema:
      name: a
      table: b
      schema: public
      data_type: integer
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: public
      foreign_key_table: a
      foreign_key_column: id
    meta:
      collection: b
      field: a
      special:
        - m2o
      interface: select-dropdown-m2o
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: a
    field: b
    type: alias
    schema: null
    meta:
      collection: a
      field: b
      special:
        - o2m
      interface: list-o2m
      options:
        template: '{{size}}'
      display: related-values
      display_options:
        template: '{{size}}'
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations:
  - collection: b
    field: a
    related_collection: a
    schema:
      constraint_name: b_a_foreign
      table: b
      column: a
      foreign_key_schema: public
      foreign_key_table: a
      foreign_key_column: id
      on_update: NO ACTION
      on_delete: SET NULL
    meta:
      many_collection: b
      many_field: a
      one_collection: a
      one_field: b
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
```

</details>

Notes: We may need a display component for dropdowns, though currently a Field object doesn't have way to distinguish dropdowns and only view them as integer/string, so a possible route may be to use the `special` flag such as `['dropdown']` and render a display component which will pull in interface options to replace values with texts 🤔 Or alternatively, somehow make labels display to auto-populate based on dropdown options when applicable.
