### DISCUSSION TITLE
Oracle Autonomous Database Not Working

### DISCUSSION THREAD

**Discussion by stevefan1999-personal** [directus/directus#16041] [Archive]
I have been experimenting with Directus and Oracle Cloud, and more specifically, integrating their free ARM64 instance with a free Autonomous DB (actually two but another one for something else). 

Now, to connect to their database you don't have any kind of classical connection string, but rather they gave you login wallets and you should keep those files to a safe location. 

Me myself uploaded it to my free Kubernetes Cluster and stored it as a `Secret` object. 

Then I expose this secret as a volume mount to a specific folder `/etc/secrets/oracle`, and then I set my `TNS_ADMIN` environmental variables over to `/etc/secrets/oracle`. This way the ODPI should start looking for the wallet over the specific location and so we can use the short form.

Here's the `sqlnet.ora` and `tnsnames.ora`, the core files needed to suffice `TNS_ADMIN` requirement:

sqlnet.ora:
```
WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="/etc/secrets/oracle")))
SSL_SERVER_DN_MATCH=yes
```

tnsnames.ora (redaced form)
```
apps_high = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=xxx.adb.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com, OU=Oracle ADB SEOUL, O=Oracle Corporation, L=Redwood City, ST=California, C=US")))

apps_low = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=xxx.adb.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com, OU=Oracle ADB SEOUL, O=Oracle Corporation, L=Redwood City, ST=California, C=US")))

apps_medium = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=xxx.adb.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com, OU=Oracle ADB SEOUL, O=Oracle Corporation, L=Redwood City, ST=California, C=US")))

apps_tp = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=xxx.adb.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com, OU=Oracle ADB SEOUL, O=Oracle Corporation, L=Redwood City, ST=California, C=US")))

apps_tpurgent = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=xxx.adb.oraclecloud.com))(security=(ssl_server_cert_dn="CN=adb.ap-seoul-1.oraclecloud.com, OU=Oracle ADB SEOUL, O=Oracle Corporation, L=Redwood City, ST=California, C=US")))
```

Here's my Kubernetes Pod environmental variables configuration:

```yaml
          env:
            - name: DB_CLIENT
              value: oracledb
            - name: DB_HOST
              value: apps_medium
            - name: DB_PORT
              value: '1522'
            - name: DB_DATABASE
              value: directus
            - name: DB_EXTERNAL_AUTH
              value: 'true'
            - name: DB_USER
              value: directus
            - name: DB_PASSWORD
              value: <REDACTED>
            - name: TNS_ADMIN
              value: /etc/secrets/oracle
            - name: DPI_DEBUG_LEVEL
              value: '93'
```
However, I failed to connect to the database using the given name.
```
12:14:11 🚨 Can't connect to the database.
12:14:11 🚨 ORA-12154: TNS:could not resolve the connect identifier specified 
Error: ORA-12154: TNS:could not resolve the connect identifier specified
```

Notice I have also consulted Directus docs, more specifically Knex config. I first suspect that it is due to externalAuth not enabled, thus I added the environmental variables `DB_EXTERNAL_AUTH` to it. It seems like there aren't any effect whatsoever. I wonder if anyone had successfully connected Directus to their Oracle Autonomous Database as well, and let's share the solution shall we?
