### DISCUSSION TITLE
How to customize columns'width in relational tables?

### DISCUSSION THREAD

**Discussion by Pachat** [directus/directus#16885] [Archive]
1°) How to distinguish between tables? I tried to put the following custom CSS
```
div.v-table.no-last-border[data-v-abd8295c=""]  /*Group Presentation*/
th.cell[data-v-37187eb8=""]:first-child,
div.v-table.no-last-border[data-v-abd8295c=""]  /*Group Presentation*/
td.cell[data-v-37187eb8=""]:first-child {
	width: 64px;
}

```
but since I have 2 relational tables in the group, this applies to both. I didn't find any difference in the DOM hierarchy between the 2 relational tables. As Directus puts the right data in each, there is certainly some node that makes the difference.
So I wonder if there is a better way to distinguish them (apart by setting some `:nth-child`) in order to have a more stable rule in case another relational table is added in the group?

---

2°) The previous CSS rule and alike applied to each column, in addition to acting on the two tables, produces strange empty spaces (in red below).
How to avoid this?
In particular, how to make the last (n-1 in fact) column (like "Comment" below) occupy all the width left by the others?
![tables](https://user-images.githubusercontent.com/13746133/209113511-ce067201-d7fb-46cd-9c8e-5c475c74f60b.png)

**Comment by rijkvanzanten** [comment]
There's currently no included unique identifiers for columns or particular tables in this case. The `nth-child` hack is the only way I can think of making that css work.

**Reply by Pachat** [reply]
Understood.
Is it possible to set presets on relational tables?

**Reply by rijkvanzanten** [reply]
Presets are saved for any collection, though those presets aren't used for the inline table, so that won't resolve your use case above

**Reply by Pachat** [reply]
Thank you for your time. I think I'll have to build an extension for this use case.

**Reply by fourthdimension** [reply]
Was anyone able to solve this issue? I'm having a similar problem and unable to preset the column widths, when using one-to-many table layout within a data model.

**Reply by pedrofnts** [reply]
Same problem here.

**Comment by maazamaani** [comment]
## Solution

I used this trick to change table "a" columns widths (columns are ID and Title):

```css
.one-to-many table[summary="ID, Title"] tbody,
.one-to-many table[summary="ID, Title"] thead {
	--table-a-custom-width: 36px 36px  90px 200px 1fr min-content; /* change this based on your desired width */
	--8cfa525e: var(--table-a-custom-width); 
	--5280d985: var(--table-a-custom-width);
}
.one-to-many table[summary="ID, Title"] thead .cell {
	width: unset !important;
}
```

## Problem

Unfortunately any trick that changes width, disables column dragging functionality.
