### DISCUSSION TITLE
Support running docker image in rootless mode

### DISCUSSION THREAD

**Discussion by navanshu** [directus/directus#16890] [Feature Requests]
### Describe the Bug

Directus unable to work in rootless docker

```
directus  | npm WARN exec The following package was not found and will be installed: directus@9.21.2
directus  | npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
directus  | npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
directus  | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
directus  | npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
directus  | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
directus  | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
directus  | npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
directus  | npm WARN deprecated keyv-memcache@1.2.5: This project has been renamed to @keyv/memcache which will be updated moving forward.
directus  | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
directus  | [17:08:56] WARN (89 on d6ebb81e6e6f): Couldn't load extensions
directus  | [17:08:56] WARN (89 on d6ebb81e6e6f): Current folder does not contain a package.json file
directus  |     err: {
directus  |       "type": "Error",
directus  |       "message": "Current folder does not contain a package.json file",
directus  |       "stack":
directus  |           Error: Current folder does not contain a package.json file
directus  |               at getPackageExtensions (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js:91:15)
directus  |               at async ExtensionManager.getExtensions (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:210:35)
directus  |               at async ExtensionManager.load (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:145:31)
directus  |               at async ExtensionManager.initialize (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:94:13)
directus  |               at async createCli (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/cli/index.js:27:5)
directus  |     }
directus  | [17:08:57] INFO (89 on d6ebb81e6e6f): Initializing bootstrap...
directus exited with code 1
```

I ran docker compose again, without cleaning the folder

```
Attaching to directus
directus  | npm WARN exec The following package was not found and will be installed: directus@9.21.2
directus  | npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
directus  | npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
directus  | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
directus  | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
directus  | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
directus  | npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
directus  | npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
directus  | npm WARN deprecated keyv-memcache@1.2.5: This project has been renamed to @keyv/memcache which will be updated moving forward.
directus  | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
directus  | [17:18:09] WARN (89 on f53e9b924698): Couldn't load extensions
directus  | [17:18:09] WARN (89 on f53e9b924698): Current folder does not contain a package.json file
directus  |     err: {
directus  |       "type": "Error",
directus  |       "message": "Current folder does not contain a package.json file",
directus  |       "stack":
directus  |           Error: Current folder does not contain a package.json file
directus  |               at getPackageExtensions (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js:91:15)
directus  |               at async ExtensionManager.getExtensions (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:210:35)
directus  |               at async ExtensionManager.load (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:145:31)
directus  |               at async ExtensionManager.initialize (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/extensions.js:94:13)
directus  |               at async createCli (/home/node/.npm/_npx/ebcc468e2b0f2b61/node_modules/directus/dist/cli/index.js:27:5)
directus  |     }
directus  | [17:18:09] INFO (89 on f53e9b924698): Initializing bootstrap...
directus exited with code 1
```

### To Reproduce

The database and s3 storage are on different machines

```yaml
services:
  directus:
    container_name: directus
    image: docker.io/directus/directus:9.21.2
    ports:
      - '8055:8055'
    volumes:
      - ~/extensions:/directus/extensions:Z
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: '${dbMachine}'
      DB_PORT: '5454'
      DB_DATABASE: 'directus'
      DB_USER: 'postgres'
      DB_PASSWORD: '1234'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'directus'
      STORAGE_LOCATIONS: s3
      STORAGE_S3_DRIVER: s3
      STORAGE_S3_KEY: ''----'
      STORAGE_S3_SECRET: '----'
      STORAGE_S3_BUCKET: 'directus'
      STORAGE_S3_ENDPOINT: 'http://${dbMachine}:9000'
      STORAGE_S3_S3_FORCE_PATH_STYLE: 'true'
```

### What version of Directus are you using?

9.21.2, 9

### What version of Node.js are you using?

18

### What database are you using?

Postgress with postgis v15

### What browser are you using?

Edge

### How are you deploying Directus?

Docker
