### DISCUSSION TITLE
How to run directus with MySQL via docker compose?

### DISCUSSION THREAD

**Discussion by ghost** [directus/directus#17005] [Archive]
I can’t get directus running with MySQL.

It works fine with PostgreSQL, but I haven’t worked with PostgreSQL databases before. So I am afraid that I can’t deal with it, when an accident happens. This is why I thought sticking to MySQL is a better choice — well, if it would work of course.

Here is my approach so far:

```yaml
# docker-compose.yaml

version: "3"

networks:
    default:
        name: directus

services:
    database:
        container_name: database
        image: mysql:8.0
        volumes:
            - ./data/database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: directus
            # MYSQL_USER: ${DB_USER}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_DATABASE: ${DB_DATABASE}

    cache:
        container_name: cache
        image: redis:7.0-alpine

    directus:
        container_name: directus
        image: directus/directus:9.22.1
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
        depends_on:
            - cache
            - database
        env_file:
            - .env

```

and my environment variables:

```.env
# .env

DB_CLIENT=mysql
DB_HOST=database
DB_PORT=3306
DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=directus

CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_REDIS=redis://cache:6379
CACHE_AUTO_PURGE=true
CACHE_TTL=1d

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=d1r3ctu5
```

Here is the container log of the directus container – which is the only one that is not running:

```
[15:41:38.777] INFO: Initializing bootstrap...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 192.168.144.3:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
    --------------------
    at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/directus/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/directus/node_modules/mysql/lib/Connection.js:116:18)
    at /directus/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/directus/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/directus/node_modules/knex/lib/client.js:249:39) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.144.3',
  port: 3306,
  fatal: true
}

Node.js v18.12.1
```

**Comment by br41nslug** [comment]
The config looks good, if i remember correctly there was something with authentication on `mysql:8`. Try adding 
```
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
``` 
to your mysql service (not 100% sure what the reasoning was but i have this in my test compose).

**Reply by ghost** [reply]
@br41nslug  Not working. I’m getting the same error …

**Reply by br41nslug** [reply]
Any errors on the mysql side? should be as the mysql server is refusing the connection

**Reply by ghost** [reply]
@br41nslug No, no errors. Here is the MySQL container log:
```
[Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
[Note] [Entrypoint]: Switching to dedicated user 'mysql'
[Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
'/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
[Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
[System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.31) starting as process 1
[Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
[System] [MY-013576] [InnoDB] InnoDB initialization has started.
[System] [MY-013577] [InnoDB] InnoDB initialization has ended.
[Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
[System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
[Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
[System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.31'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
[System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock

```

Does it work on your machine?

**Reply by br41nslug** [reply]
It is working on my machine, the only difference i see in configurations is that I have these set:
```
 environment:
            MYSQL_ROOT_PASSWORD: directus
            # MYSQL_USER: ${DB_USER}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_DATABASE: ${DB_DATABASE}
```
and am using the `MYSQL_USER` and `MYSQL_PASSWORD` for directus. Didnt notice it earlier but it looks like you've set the root password only but try to login under the `directus` user. Could it be that that user does not exist?

**Reply by ghost** [reply]
@br41nslug I forgot to uncomment the 3 lines when I pasted it here to github. Can you share your working docker-compose.yaml? Because I’ve tried everything, you’ve suggested, but it simply does not work …

**Reply by br41nslug** [reply]
@JonathanDoelan This configuration is working for me:
```yaml
version: '3.7'
services:
  cache:
    image: redis:6
    ports:
      - 6379:6379
  database:
    image: 'mysql:8'
    ports:
      - 3306:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - './mysql8:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '[ redacted ]'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '[ redacted ]'
      MYSQL_DATABASE: 'test'
  directus:
      image: directus/directus:9.22.1
      ports:
        - 8055:8055
      depends_on:
        - database
        - cache
      volumes:
        - './uploads:/directus/uploads'
      environment:
        KEY: '[ redacted ]'
        SECRET: '[ redacted ]'
        LOG_LEVEL: 'debug'
        PUBLIC_URL: 'http://localhost:8055'

        DB_CLIENT: 'mysql'
        DB_HOST: 'database'
        DB_PORT: '3306'
        DB_DATABASE: 'test'
        DB_USER: 'test'
        DB_PASSWORD: '[ redacted ]'
        
        ADMIN_EMAIL: 'admin@example.com'
        ADMIN_PASSWORD: 'd1r3ctu5'
 
        CACHE_ENABLED: 'true'
        CACHE_STORE: 'redis'
        CACHE_REDIS: 'redis://cache:6379/1'
```
I did however notice that when starting this project up first it can take a bit for the `mysql` server to actually become available resulting in the `directus` container stopping with that exact `ECONNREFUSED` error. Restarting the directus container resolves it for me and it didnt happen the second time (i suspect it is the delay of creating the database folder on disk).

**Reply by ghost** [reply]
> I did however notice that when starting this project up first it can take a bit for the `mysql` server to actually become available resulting in the `directus` container stopping with that exact `ECONNREFUSED` error. Restarting the directus container resolves it for me and it didnt happen the second time (i suspect it is the delay of creating the database folder on disk).

~~For me this happens every time.~~ But restarting the directus container again and again … then suddenly it works!

… so thanks a lot so far!

**Reply by br41nslug** [reply]
Hmmm that should not happen everytime 🤔 can you check the logs to see how long it takes for the mysql container to say "ready for connections"? after that the connection should definitely work flawlessly

**Reply by ghost** [reply]
@br41nslug Excuse me, it did not happen again … so it works fine now! THANKS!

**Reply by ghost** [reply]
@br41nslug one more thing to mention … I’ve added the following line to the docker compose file in the directus service section

```
restart: unless-stopped
```

This automatically restarts the directus container till the MySQL container is ready

**Reply by br41nslug** [reply]
Good solution, hadn't thought of that 😄

**Reply by ghost** [reply]
Additional note: Make sure to delete the persistant mysql volume (`/var/lib/mysql`) before you apply the changes

**Comment by ghost** [comment]
I’ll try to summarize all options we have with `MySQL`, I have figured out.

# Option 1: Using Version 5

This is the easiest solution, because we don’t have to do anything else.

```yaml
# docker-compose.yaml

version: "3"

networks:
    default:
        name: ${STACK_PRFX}

services:
    # Database, Option 1: MySQL Version 5
    database:
        container_name: ${STACK_PRFX}-database
        image: mysql:5.7
        # Uncomment for local macOS development
        # platform: linux/amd64
        volumes:
            - ./data:/var/lib/mysql
        env_file:
            - .env

    # Cache
    cache:
        container_name: ${STACK_PRFX}-cache
        image: redis:7.0-alpine

    # Directus
    directus:
        container_name: ${STACK_PRFX}-directus
        image: directus/directus:9.22.1
        restart: unless-stopped
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
        depends_on:
            - cache
            - database
        env_file:
            - .env
```

# Option 2: MySQL Version 8

For Version 8 we have to set `--default-authentication-plugin` to `mysql_native_password` in order to get `directus` working.

```yaml
    # Database, Option 2: MySQL Version 8
    database:
        container_name: ${STACK_PRFX}-database
        image: mysql:8.0
        volumes:
            - ./data:/var/lib/mysql
        command:
            [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--default-authentication-plugin=mysql_native_password",
            ]
        env_file:
            - .env
```

# Option 3: MySQL 8 image by bitnami

Here we have the same problem like in Option 2, but we can simply set the `--default-authentication-plugin` using a `.env` variable – have a look at the environment file below.

```yaml
    # Database, Option 3: MySQL image by bitnami
    database:
        container_name: database
        image: bitnami/mysql:8.0
        # Uncomment for local macOS development
        # platform: linux/amd64
        volumes:
            - ./data:/var/lib/mysql
        env_file:
            - .env
```

---

And here is the `.env` example file for all options above:

```env
# .env

# Docker Compose

STACK_PRFX=directus-app


# Directus

KEY=secret
SECRET=secret

PUBLIC_URL="http://localhost:8055"

DB_CLIENT=mysql
DB_HOST=database
DB_PORT=3306
DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=directus

CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_REDIS=redis://cache:6379

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=d1r3ctu5


# MySQL

MYSQL_ROOT_PASSWORD=secret
MYSQL_USER=${DB_USER}
MYSQL_PASSWORD=${DB_PASSWORD}
MYSQL_DATABASE=${DB_DATABASE}

# MySQL image by bitnami
MYSQL_AUTHENTICATION_PLUGIN="mysql_native_password"
```
