### DISCUSSION TITLE
Redis TLS Connection Error

### DISCUSSION THREAD

**Discussion by macntech** [directus/directus#17626] [Archive]
Good morning,

we need to enable cloud caching as e are scaling up within our k8s cluster for our Go-Live next week. However, I am really struggling by connecting to our Redis instance. I tried a lot different config options I found somewhere in the space (not mentioned in the docs unfortunately) but all seem not working. I am quite confused what is now the correct option to connect to Redis TLS instance.

Setup:
directus 9.22.4 in docker
Managed Redis 7.0.5

My current envs are:

```yaml
  CACHE_REDIS_HOST: "xx.xxx.xxx.xxx"
  CACHE_REDIS_PORT: "6379"
  CACHE_REDIS_USERNAME: "username"
  CACHE_REDIS_PASSWORD: "password"
  CACHE_REDIS_TLS__CA: "base64pem"
  CACHE_REDIS_TLS__REJECT_UNAUTHORIZED: "false"
```

The error:
```bash
WARN: [schema-cache] Couldn't retrieve cache. MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    err: {
      "type": "MaxRetriesPerRequestError",
      "message": "Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details.",
      "stack":
          MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
              at Socket.<anonymous> (/directus/node_modules/ioredis/built/redis/event_handler.js:175:37)
              at Object.onceWrapper (node:events:628:26)
              at Socket.emit (node:events:513:28)
              at TCP.<anonymous> (node:net:320:12)
```

Without the TLS options it's not connecting at all and gives self-signed certificate error. I tried also `CACHE_REDIS_TLS: "{rejectUnauthorized: false, ca: base64pem}"` which is not working at all. So my feeling is that the connection options above are correct but it seems directus cannot reach the Redis. I verified connection blocks via `Another Redis Desktop Manager` and this one connects without any issues from the same network. 

Another thought in my mind is that the conversion from my .pem file to base64 is not correct. My questions would be following:

1. Are the configs correct? 
2. What is the correct way to pass the .pem to directus container as Redis TLS CA?  

Cheers and thanks ahead!

**Comment by macntech** [comment]
Ok after try and error I was now able to connect. The trick is to only present the option `CACHE_REDIS_TLS__REJECT_UNAUTHORIZED: "false"` and skipping the CA. So the final working config is:

```yaml
  CACHE_REDIS_HOST: "xx.xxx.xxx.xxx"
  CACHE_REDIS_PORT: "6379"
  CACHE_REDIS_USERNAME: "username"
  CACHE_REDIS_PASSWORD: "password"
  CACHE_REDIS_TLS__REJECT_UNAUTHORIZED: "false"
```

obviously passing username and password in k8s secret not yaml. Maybe an update of the docs is usable as many Redis cloud services require TLS connection.
