### DISCUSSION TITLE
Cannot connect Directus container to database

### DISCUSSION THREAD

**Discussion by jmciso** [directus/directus#17859] [Archive]
Hi,

I am trying to setup a directus server using docker compose, based on the example presented in the Directus docs and another post (https://github.com/directus/directus/discussions/17005) but I can't make directus reach the database container. The docker-compose.yml is the following:

```
version: '3'

services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    env_file:
      - .env

  # cache:
  #   container_name: cache
  #   image: redis:6
  #   networks:
  #     - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      # - cache
      - database
    env_file:
      - .env

networks:
  directus:
    driver: bridge
```

and the corresponding .env:

```
# .env
# Directus

KEY=key
SECRET=secret

PUBLIC_URL="http://localhost:8055"

#DB_CLIENT=mysql
DB_CLIENT=pg
DB_HOST=database
#DB_HOST=172.24.0.2
#DB_PORT=3306
DB_PORT=5432

DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=<dbpwd>

DATABASE_POOL_MIN=2
DATABASE_POOL_MAX=10

CACHE_ENABLED=false
# CACHE_STORE=redis
# CACHE_REDIS=redis://cache:6379

ADMIN_EMAIL=<admin-email>
ADMIN_PASSWORD=<adminpassword>

# PG
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_DATABASE}
```

After running `docker-compose up`,  the database container starts fine but the directus container keeps timing out when trying to connect to the database. docker logs outputs the following:

```
[02:38:56.423] INFO: Initializing bootstrap...
[02:42:21.549] ERROR: Can't connect to the database.
[02:42:21.550] ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    err: {
      "type": "KnexTimeoutError",
      "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
      "stack":
          KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
              at Client_PG.acquireConnection (/directus/node_modules/knex/lib/client.js:312:26)
              at async Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:287:28)
              at async Runner.run (/directus/node_modules/knex/lib/execution/runner.js:30:19)
              at async validateDatabaseConnection (/directus/node_modules/directus/dist/database/index.js:170:13)
              at async waitForDatabase (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:77:5)
              at async Command.bootstrap (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:40:5)
              at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:935:5)
      "name": "KnexTimeoutError",
      "sql": "SELECT 1"
    }
[02:42:26.447] INFO: Initializing bootstrap...
```

I tried to ping 'database' from 'directus' container but it times out, although apparently it's resolving the 'database' IP correctly. Also tried setting the db pool but to no avail. 

The OS is a Ubuntu 22.10, running on a Linode VPS. FWIW, I was able to start the containers on my local machine (macOS).

Any help is highly appreciated!
Thanks
