### DISCUSSION TITLE
docker MySQL / Mariadb ECONNREFUSED error

### DISCUSSION THREAD

**Discussion by aiamk** [directus/directus#17929] [Archive]
### Describe the Bug

i am getting same issues when i try  to use Mysql 5.7 / 8.0 and mariadb 10.11.2 with Directus using docker:

> 2023-03-24 19:06:16 [16:06:16.354] INFO: Initializing bootstrap...
2023-03-24 19:06:17 node:internal/process/promises:288
2023-03-24 19:06:17             triggerUncaughtException(err, true /* fromPromise */);
2023-03-24 19:06:17             ^
2023-03-24 19:06:17 
2023-03-24 19:06:17 Error: connect ECONNREFUSED 172.30.0.3:3306
2023-03-24 19:06:17     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
2023-03-24 19:06:17     --------------------
2023-03-24 19:06:17     at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2023-03-24 19:06:17     at Protocol.handshake (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:51:23)
2023-03-24 19:06:17     at Connection.connect (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:116:18)
2023-03-24 19:06:17     at /directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/dialects/mysql/index.js:66:18
2023-03-24 19:06:17     at new Promise (<anonymous>)
2023-03-24 19:06:17     at Client_MySQL.acquireRawConnection (/directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/dialects/mysql/index.js:61:12)
2023-03-24 19:06:17     at create (/directus/node_modules/.pnpm/knex@2.4.2_gtxrszusl6tkjfynyc22baqi3i/node_modules/knex/lib/client.js:254:39) {
2023-03-24 19:06:17   errno: -111,
2023-03-24 19:06:17   code: 'ECONNREFUSED',
2023-03-24 19:06:17   syscall: 'connect',
2023-03-24 19:06:17   address: '172.30.0.3',
2023-03-24 19:06:17   port: 3306,
2023-03-24 19:06:17   fatal: true
2023-03-24 19:06:17 }
2023-03-24 19:06:17 
2023-03-24 19:06:17 Node.js v18.15.0

### To Reproduce

docker-compose.yml:
```

version: '3'
services:
  database:
    container_name: projectName-database
    image: mysql:5.7
    ports:
      - 3306:3306
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - projectName-directus
    environment:
      MYSQL_ROOT_PASSWORD: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      MYSQL_DB: 'directus'

  cache:
    container_name: projectName-cache
    image: redis:6
    networks:
      - projectName-directus

  directus:
    container_name: projectName-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/data/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/data/extensions
    networks:
      - projectName-directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  projectName-directus:


```

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by aiamk** [comment]
do I need a talisman to let directus works with mysql?

**Comment by aiamk** [comment]
Finally worked!

```
version: '3'
services:
  database:
    container_name: projectName-database
    image: mysql:8.0
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data:/var/lib/mysql
    command:
        [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--default-authentication-plugin=mysql_native_password",
        ]    
    networks:
      - directus
    environment:
      MYSQL_ROOT_PASSWORD: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      MYSQL_DATABASE: 'directus'     

  cache:
    container_name: projectName-cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: projectName-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
```
