### DISCUSSION TITLE
Text wrapped columns for the table layout

### DISCUSSION THREAD

**Discussion by danielduckworth** [directus/directus#18216] [Feature Requests]
### Summary

Toggle text wrapping as a column setting along with other column settings like text alignment.

### Basic Example

**Notion table with text wrapping off**
![image](https://user-images.githubusercontent.com/18698360/232495517-c20cf20c-fb29-4aa9-8e8c-3e6dab9da535.png)

**Notion table with text wrapping on**
![image](https://user-images.githubusercontent.com/18698360/232496518-f9cfa0f8-41c9-4cf1-9cf2-7fe8dee621b0.png)

**Column setting menu**
![image](https://user-images.githubusercontent.com/18698360/232495841-3e7a522e-159a-4957-82ed-04b1164394cf.png)

### Motivation

Text centric content viewed in a table with 4 or more properties displayed as columns forces the user to scroll horizontally which adds friction to the user experience.

### Detailed Design

Add a toggle to wrap text for individual columns.

```html
<p>4. <code>word-break: break-word</code></p>
<p class="breakWord narrow">
  This is a long and Honorificabilitudinitatibus califragilisticexpialidocious
  Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu
  グレートブリテンおよび北アイルランド連合王国という言葉は本当に長い言葉
</p>
```

```css
.narrow {
  padding: 10px;
  border: 1px solid;
  width: 500px;
  margin: 0 auto;
  font-size: 20px;
  line-height: 1.5;
  letter-spacing: 1px;
}

.breakWord {
  word-break: break-word;
}
```

**Sources**

1.  [https://developer.mozilla.org/en-US/docs/Web/CSS/word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)
2. [Wrapping and breaking text](https://developer.mozilla.org/en-US/docs/web/css/css_text/wrapping_text)

### Must Have:
- Text column wrapping
- B

### Should Have:
- tags column wrapping

### Drawbacks

Maybe not many people use the table view for text data.

### Alternatives

None

### Adoption Strategy

Default to disabled.
