### DISCUSSION TITLE
Customizing User Model Layout

### DISCUSSION THREAD

**Discussion by jeffsmonteiro** [directus/directus#19529] [Feature Requests]
### Summary

Allow system administrators to change the presentation layout of fields in the user model, or other system models.

### Basic Example

Add the phone field to the user template and place it next to the email field. 
Create a new session and locate it between session data and user preferences.

### Motivation

it is understandable that it is not possible to edit fields defined by default for the user model, however, it may be that the inclusion of new fields are complementary to a given session, or new sessions are better positioned among other existing sessions. This should contribute to the user experience when accessing the app, facilitating the reading and semantic understanding of the data on screen.

### Detailed Design

On the screen of a system model, it should be possible to drag and drop new custom fields to position them in the best possible place.

### Must Have:
- A drag and drop custom fields

### Drawbacks

Functionality already exists in the platform when using custom templates, it would be necessary to understand the risks about data structure and security

### Alternatives

The alternative would be to create fields in separate sessions, as is the case today. However, the user experience is poor.

### Adoption Strategy

Need for migration does not seem to exist. But it is necessary to study the technical feasibility considering data structure and security.

**Comment by gloribus** [comment]
+++
Just must have

**Comment by gloribus** [comment]
https://github.com/directus/directus/discussions/23076

**Reply by Mehdi-YC** [reply]
```css
/*removing user unneded infos*/
[data-collection="directus_users"][data-field="description"],
[data-collection="directus_users"][data-field="tags"],
[data-collection="directus_users"][data-field="preferences_divider"],
[data-collection="directus_users"][data-field="language"],
[data-collection="directus_users"][data-field="appearance"],
[data-collection="directus_users"][data-field="theme_light"],
[data-collection="directus_users"][data-field="theme_light_overrides"],
[data-collection="directus_users"][data-field="theme_dark"],
[data-collection="directus_users"][data-field="theme_dark_overrides"],
[data-collection="directus_users"][data-field="token"],
[data-collection="directus_users"][data-field="id"],
[data-collection="directus_users"][data-field="policies"],
[data-collection="directus_users"][data-field="provider"],
[data-collection="directus_users"][data-field="external_identifier"],
[data-collection="directus_users"][data-field="auth_data"],
[data-collection="directus_users"][data-field="theming_divider"],
[data-collection="directus_users"][data-field="admin_divider"],
[data-collection="directus_users"][data-field="title"],
[data-collection="directus_users"][data-field="tfa_secret"],
[data-collection="directus_users"][data-field="email_notifications"],
[data-collection="directus_users"][data-field="text_direction"]{
  display: none; !important
}
```
try this to remove them, we might be able to select them with the role if it is also somewhere displayed in the page i didn't try
