### DISCUSSION TITLE
Custom ports    in docker-compose.yml

### DISCUSSION THREAD

**Discussion by Pachat** [directus/directus#21015] [Feature Requests]
### Summary

Hi,
Why when I have
```
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8029:8029
```
in `docker-compose.yml` it says at the end of `docker compose up`
```
test-directus-1  | 2024-01-09T11:33:03: PM2 log: App [directus:0] online
test-directus-1  | [11:33:14.053] INFO: Server started at http://0.0.0.0:8055
```
Why still `:8055` instead of `:8029`?

### Motivation

Have different apps running on the server, each with its own port

### Detailed Design

Make the [Ports ](ports:) work

### Drawbacks

--

### Alternatives

--

### Adoption Strategy

--
