### DISCUSSION TITLE
Apply schema automatically from docker image

### DISCUSSION THREAD

**Discussion by tarmolehtpuu** [directus/directus#22052] [Feature Requests]
### Summary

Right now there seems to be no good way to move the schema from dev -> staging -> production when running in Docker/Kubernetes/Nomad.

### Motivation

The motivation is to build and test the docker image in dev, then in staging and then move it to production. As it moves through the stages there should be some mechanism to apply the schema changes automatically

### Detailed Design

The easiest way to do is would be to add some ENV variable like SCHEMA=foo/bar/schema.yaml which Directus could check during startup and apply changes automatically.

### Must Have:
- When docker starts it should apply the schema changes automatically
- Only one instance of Directus should apply the changes (probably use pessimistic locking to prevent multiple containers applying schema changes simultaneously)
- If the schema fails to apply the container should fail to start

### Drawbacks

If there is not a well defined testing process in place then applying schema changes automatically could be dangerous, however this should be up to each user of Directus to decide for themselves

### Alternatives

Current alternatives require accessing directus via https directly in staging and production. We also have prelive, so keeping all of these schemas in sync is complicated. If the schema gets applied with the Docker image things become simpler.

### Adoption Strategy

Not a breaking change, using this ENV variable would be optional

**Comment by br41nslug** [comment]
You can currently achieve this by overwriting the `command` in your `docker-compose` file:
```yaml
    directus:
      image: directus/directus:10.10.4
      command: >
        sh -c "node cli.js bootstrap &&
              node cli.js schema apply --yes /directus/snapshots/snapshot.yaml &&
              pm2-runtime start ecosystem.config.cjs"
      ports:
        - 8055:8055
```
