### DISCUSSION TITLE
Hide/arrange default fields on the Directus Files edit view

### DISCUSSION THREAD

**Discussion by jeremyzilar** [directus/directus#22097] [Feature Requests]
### Summary

Make it easier to access and edit additional fields on the Directus Files edit view.

### Motivation

As a Photo Editor, I find it difficult to access to the additional fields we've configured in the `directus_files` schema. 

Over the course of a month, I process and upload 200-300 images, and for some of them, I need go into the edit view multiple times to make copy edits, add photo credits, rights, etc.

The fields we added in the schema are at the bottom of the "files" edit screen and there is no way to move them up higher, or hide the default Directus fields we are not using. It would be nice to be able to hide some of the default fields and be able to sort/arrange the our fields with the default fields.

In fact, the only default field we are using (at the moment) is the `title` field. We would use `description` for our photo captions, but unfortunately we need need to be able to add links and make certain names and titles bold or italic. For us, the image is not the most important element in the Edit View.

#### Here is our current edit view:
<img width="1440" alt="image" src="https://github.com/directus/directus/assets/395641/16c9bc56-7c4c-4769-989d-3aa4c59bd8d5">
<img width="1440" alt="image" src="https://github.com/directus/directus/assets/395641/d7f346ca-eb66-4099-8b64-2e01ca521d61">
<img width="1440" alt="image" src="https://github.com/directus/directus/assets/395641/09c2b4bd-df6b-4158-a733-5f47f5ccf792">
<img width="1440" alt="image" src="https://github.com/directus/directus/assets/395641/1c3e1ab9-8876-43b2-949f-e3114574ee8c">

### Detailed Design

If possible, it would be great if we could define a "file type", and be able to configure the fields needed for just that type. The bulk of our files are images for our publication, but we do have the occasional PDF or Video, and I can see a day when we'd want access to the `description` field or possibly other fields for those specific media types.

### Must Have:
- the ability to configure Directus File fields so that when I open the edit view, I see the fields that are most important to my workflow.

### Could Have:
- the ability to configure/hide/show fields for different file types

### Drawbacks

Maybe if I had my files fields customized, it would make it more difficult for me to discover new fields that have been added in a recent release, like Focal Point?

### Alternatives

We considered adding all of our article images as a separate collection. Maybe that is the best way to go and the Files should really be thought of as the data store, not the source of truth for image data.

### Adoption Strategy

I don't want to assume that this is a simple change, but I would think that existing users would see the same fields they've always seen, and would then have the ability to hide some of those fields or rearrange them.

**Comment by dreerr** [comment]
We added this in the User CSS, this might be helpful for someone:
```css

.file-item .grid > :nth-child(n+3):nth-child(-n+10) {
    display: none;
}

[data-collection="directus_files"][data-field="tags"],
[data-collection="directus_files"][data-field="location"],
[data-collection="directus_files"][data-field="storage"],
[data-collection="directus_files"][data-field="focal_point_divider"],
[data-collection="directus_files"][data-field="storage_divider"],
[data-collection="directus_files"][data-field="filename_disk"],
[data-collection="directus_files"][data-field="filename_download"],
[data-collection="directus_files"][data-field="type"],
[data-collection="directus_files"][data-field="filesize"],
[data-collection="directus_files"][data-field="created_on"],
[data-collection="directus_files"][data-field="modified_by"],
[data-collection="directus_files"][data-field="modified_on"],
[data-collection="directus_files"][data-field="folder"],
[data-collection="directus_files"][data-field="width"],
[data-collection="directus_files"][data-field="height"],
[data-collection="directus_files"][data-field="duration"],
[data-collection="directus_files"][data-field="charset"] {
  display: none;
}
```
