### DISCUSSION TITLE
Cannot start Directus on Raspberry Pi

### DISCUSSION THREAD

**Discussion by Dominic-Preap** [directus/directus#25039] [Feature Requests]
### Describe the Bug

Hi, we are testing on running Directus on Raspberry Pi at home but cannot start. I'm assuming it might be CPU architecture.  https://forums.raspberrypi.com/viewtopic.php?t=335999

```
# docker logs -f my-directus

exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

Here the Raspberry Pi info:

```
# lshw
my-server
    description: Computer
    product: Raspberry Pi 4 Model B Rev 1.2
    serial: 10000000925e7348
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled
```

```
# lscpu
Architecture:             aarch64
  CPU op-mode(s):         32-bit, 64-bit
  Byte Order:             Little Endian
CPU(s):                   4
  On-line CPU(s) list:    0-3
Vendor ID:                ARM
  Model name:             Cortex-A72
    Model:                3
    Thread(s) per core:   1
    Core(s) per cluster:  4
    Socket(s):            -
    Cluster(s):           1
    Stepping:             r0p3
    CPU(s) scaling MHz:   47%
    CPU max MHz:          1500.0000
    CPU min MHz:          600.0000
    BogoMIPS:             108.00
    Flags:                fp asimd evtstrm crc32 cpuid
```

### To Reproduce

Run docker compose below in Raspberry Pi

```
services:
  #  ----------------------
  #  DIRECTUS
  #  ----------------------
  directus:
    image: "directus/directus:11.6.0"
    container_name: directus
    restart: always
    logging:
      options:
        max-size: "10m"
    depends_on:
      - mysql
    environment:
      GRAPHQL_INTROSPECTION: false
      WEBSOCKETS_ENABLED: false

      KEY: "${KEY}"
      SECRET: "${SECRET}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PUBLIC_URL: "${PUBLIC_URL}"
      BACKEND_URL: "${BACKEND_URL}"
      BACKEND_JWT_SECRET: "${BACKEND_JWT_SECRET}"

      DB_CLIENT: "mysql"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_SSL: "false"
      # DB_CHARSET: "utf8mb4_general_ci"

      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./uploads"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"

      CACHE_ENABLED: "false"
      CACHE_STORE: "memory"
    volumes:
      - /home/local/directus/uploads:/directus/uploads

  #  ----------------------
  #  DATABASE
  #  ----------------------
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    logging:
      options:
        max-size: "5m"
    ports:
      - "3309:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - /home/local/directus/database/mysql:/var/lib/mysql

networks:
  default:
    external: true
    name: local
```

```
#env
KEY=my-key
SECRET=my-secret-key
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=123456
PUBLIC_URL=https://example.com
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=directus
DB_USER=root
DB_PASSWORD=123456
```

### Directus Version

v11.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql
