### DISCUSSION TITLE
Why is Directus not reading configurations in config/api.php, attempting to deploy to GAE Standard

### DISCUSSION THREAD

**Discussion by isawk** [directus/directus#2761] [Archive]
What goes into Directus config folder, new clone has an _example.php. I need assistance with the following

- Changing log location (application fails to start if it can,t write to ./log)
- Does directus only support mysql no postgresql support?
- Need better understanding on how to configure so I can get running in Google App Engine (Will share full setup details e.t.c., sure a number of people would like to run in Google app engine,  AWS elasticbean stalk, e.t.c.

app.yaml contents

```yaml
runtime: php73
service: directus-api

handlers:
    - url: .*
      secure: always
      redirect_http_response_code: 301
      script: auto
```

Error am getting

"PHP message: PHP Fatal error: Uncaught Directus\Logger\Exception\InvalidLoggerConfigurationException: Invalid Configuration for logger "path" variable. in /srv/src/core/Directus/Application/CoreServicesProvider.php:145"

I believe configuring log path will help, I am however lost on how to accomplish that with details located below

https://docs.directus.io/advanced/source.html#api-source api.php the config/* folder appears to be ignored. also there is no api_sample.php only _example.php. Why are configurations in config/api.php ignored?
