### DISCUSSION TITLE
Postgres Support

### DISCUSSION THREAD

**Discussion by OfficialOzzy** [directus/directus#2863] [Feature Requests]
Hi :wave: 

I have been looking everywhere to get Postgres working, it states in the roadmap that it was completed 2019 Q2, did Directus ever get Postgres support?

I was trying the below docker-compose file and changed the type to Postgres/psql/pgsql but no luck in connecting to Postgres.

```yaml
  directus:
    image: directus/directus:v8-apache
    ports:
      - "8080:80"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"
      DIRECTUS_DATABASE_HOST: "localhost"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"
      DIRECTUS_DATABASE_TYPE: "postgres"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads    
```
