### DISCUSSION TITLE
How to setup docker compose for postgres on v9 RC?

### DISCUSSION THREAD

**Discussion by anand-kulk** [directus/directus#3269] [Archive]
Hello there - 
    I am using latest docker image(Node) and trying to connect to remote Postgres DB. When I run below docker compose, I get admin login page, but login doesn't work, I tried to reset password and that tells me email is sent but no email is received. I think it can't connect to DB. Could you tell what I may be missing? I already verified SMTP creds are correct. I am using "postgresql" as a database type. Any help is highly appreciated.

```
version: "3"

networks:
  directus:

services:
  directus:
    image: directus/directus:v9.0.0-rc.19
    ports:
      - "8055:8055"
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_AUTH_PUBLICKEY: "3c34db10-f565-0934-8536-gfds89743h98"
      DIRECTUS_AUTH_SECRETKEY: "FofptWoigjhfdoigzUx2Kv49xpio0G2"
      DIRECTUS_DATABASE_TYPE: "postgresql"
      DIRECTUS_DATABASE_HOST: "<postgres server address>"
      DIRECTUS_DATABASE_PORT: "5432"
      DIRECTUS_DATABASE_NAME: "directus-cms2"
      DIRECTUS_DATABASE_USERNAME: "<postgres user>"
      DIRECTUS_DATABASE_PASSWORD: "<Postgres pwd>"
      DIRECTUS_MAIL_DEFAULT_TRANSPORT: "smtp"
      DIRECTUS_MAIL_DEFAULT_FROM: "<from-address>"
      DIRECTUS_MAIL_DEFAULT_HOST: "<smtp-host>"
      DIRECTUS_MAIL_DEFAULT_PORT: "587"
      DIRECTUS_MAIL_DEFAULT_USERNAME: "<smtp-user>"
      DIRECTUS_MAIL_DEFAULT_PASSWORD: "<smtp-password>"
      DIRECTUS_MAIL_DEFAULT_ENCRYPTION: "ssl"
      DIRECTUS_INSTALL_EMAIL:  "<my email>"
      DIRECTUS_INSTALL_PASSWORD: "<password>"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads    
    networks:
      - directus
```

**Comment by rijkvanzanten** [comment]
Seems like you're using the v8 environment variables on a v9 installation. See https://docs.directus.io/reference/environment-variables.html for the correct environment variables

**Reply by anand-kulk** [reply]
Thanks @rijkvanzanten that was helpful, only suggestion that DB_SSL variable is still missing in above documentation.
That said, the container won't start for the 503 error I reported in other question , here is the trace - 

![Screen Shot 2020-12-02 at 10 10 37 AM](https://user-images.githubusercontent.com/70729249/100913434-a301d380-3486-11eb-9de3-2e850e141701.png)
Copy @benhaynes 

Also, for others who have same question, this was my final docker compose that worked except for the problem above -
(Sensitive info removed)
```
version: "3"

networks:
  directus:

services:
  directus:
    image: directus/directus:v9.0.0-rc.19
    ports:
      - "8055:8055"
    environment:
      KEY: ""
      SECRET: ""
      DB_CLIENT: "postgres"
      DB_HOST: "<DB Server>"
      DB_PORT: "5432"
      DB_DATABASE: "directus-cms2"
      DB_USER: ""
      DB_PASSWORD: ""
      DB_SSL: "true"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_FROM: ""
      EMAIL_SMTP_HOST: "smtp-relay.sendinblue.com"
      EMAIL_SMTP_PORT: "587"
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASSWORD: ""
      EMAIL_SMTP_POOL: "false"
      EMAIL_SMTP_SECURE: "false"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads    
    networks:
      - directus
```
