### DISCUSSION TITLE
Cannot Create Admin User via Docker ENV

### DISCUSSION THREAD

**Discussion by myzinsky** [directus/directus#3271] [Archive]
When I setup a docker, according to the readme:

```bash
docker run \
	-e DIRECTUS_ADMIN_EMAIL="test@test" \
	-e DIRECTUS_ADMIN_PASSWORD="xxxxxxxx" \
	-p 8055:8055 \
	directus/directus:v9.0.0-rc.19
```

I cannot login. What I'm doing wrong here?

**Comment by ialexs** [comment]
Use `docker-compose up` works for me. Upon the first start of `docker-compose up` it will spit out the default username & password

Below is my `docker-compose.yml` (still need to work on how the SMTP setting works)

```
networks:
  directus:

services:
  directus:
    image: directus/directus:v9.0.0-rc.18
    ports:
     - "8080:8055"
    environment:
      DB_CLIENT: "mysql"
      DB_HOST: ""
      DB_PORT: "3306"
      DB_DATABASE: ""
      DB_USER: ""
      DB_PASSWORD: ""

      RATE_LIMITER_ENABLED: "false"
      RATE_LIMITER_STORE: "memory"
      RATE_LIMITER_POINTS: "25"
      RATE_LIMITER_DURATION: "1"

      CACHE_ENABLED: "false"

      STORAGE_LOCATIONS: "s3,local"
      STORAGE_LOCAL_PUBLIC_URL: "/directus/uploads"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"

      STORAGE_S3_DRIVER: "s3"
      STORAGE_S3_KEY: ""
      STORAGE_S3_SECRET: ""
      STORAGE_S3_ENDPOINT: "s3-ap-southeast-1.amazonaws.com"
      STORAGE_S3_BUCKET: ""
      STORAGE_S3_REGION: ""

      KEY: ""
      SECRET: ""

      ACCESS_TOKEN_TTL: "15m"
      REFRESH_TOKEN_TTL: "7d"
      REFRESH_TOKEN_COOKIE_SECURE: "false"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"

      EXTENSIONS_PATH: "/directus/extensions"

      EMAIL_FROM: "email@domain.yours"
      EMAIL_TRANSPORT: "smtp"
      # EMAIL_SENDMAIL_NEW_LINE: "unix"
      # EMAIL_SENDMAIL_PATH: "/usr/sbin/sendmail"
      EMAIL_SMTP_POOL: "true"
      EMAIL_SMTP_HOST: ""
      EMAIL_SMTP_PORT: "2465"
      EMAIL_SMTP_SECURE: "true" # Use TLS
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASSWORD: ""

      TZ: "Asia/Jakarta"

    volumes:
      - ./directus9/uploads:/directus/uploads
      #- ./data/config:/var/directus/config
      #- ./data/uploads:/var/directus/public/uploads
    networks:
      - directus

```
