### DISCUSSION TITLE
[V9] Sqlite cannot login

### DISCUSSION THREAD

**Discussion by cupcakearmy** [directus/directus#3324] [Archive]
Hi there, I had a question about sqlite. I cannot get it to work

```yml
version: '3.2'
services:
    directus:
        image: directus/directus:v9.0.0-rc.20
        ports:
            - 80:8055
        volumes:
          - ./data/directus/uploads:/directus/uploads
        environment:
            KEY: '****'
            SECRET: '****'

            DB_CLIENT: 'sqlite3'
            DB_FILENAME: './data.db'

            DIRECTUS_ADMIN_EMAIL: "admin@example.org"
            DIRECTUS_ADMIN_PASSWORD: "d1r3ctu5"
```

Am I missing something?

It installs fine but I can't login
