### DISCUSSION TITLE
ARM32v7 build

### DISCUSSION THREAD

**Discussion by virgil9306** [directus/directus#3893] [Archive]
Doesn't work on ARM32v7 despite all dependencies existing. It should be easy to compile a build for ARM.

Also ARM builds would be useful for M1 Macs. Many of those are starting to appear.

**Comment by philleepflorence** [comment]
Greetings...
Do you mind listing or referencing what exactly happened:
Are you trying to create a project or are you trying to build?
Are you using Docker or was there a Node issue?

**Reply by virgil9306** [reply]
Hi @philleepflorence , I appreciate the reply a lot. 

I am using the following Dockerfile as a basis for my project, I am essentially just using the example `docker-compose.yml`

It works fine in AMD64.

To run it on ARM32v7, I swapped out Postgres and Redis for `arm32v7` versions, and those containers work fine. But the Directus container fails with `exec format` error, which usually indicates it doesn't support the processor:

```
version: '3.2'
services:
  database:
    image: arm32v7/postgres:12
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: arm32v7/redis:6
    networks:
      - directus
    ports:
      - 6379:6379

  directus: # This one fails with error
    image: directus/directus:v9.0.0-rc.24
    ports:
      - ${DIRECTUS_PORT}:8055
    networks:
      - directus
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

networks:
  directus:
```
