### DISCUSSION TITLE
When is v9 available aliyun-oss?

### DISCUSSION THREAD

**Discussion by cdwmhcc** [directus/directus#4642] [Feature Requests]
https://github.com/ali-sdk/ali-oss

It was supported in v8, but not in v9.

**Comment by rijkvanzanten** [comment]
Aliyun OSS should be S3 compatible, so I believe you can already use it by configuring a storage location using the s3 driver 🙂

**Reply by cdwmhcc** [reply]
Okay, let me try it.
The performance of V9 is amazing, I love it

**Reply by rijkvanzanten** [reply]
Thanks! ❤️

**Reply by MarvinXu** [reply]
@cdwmhcc I also need to use aliyun OSS. Did you make it work?

**Reply by cdwmhcc** [reply]
The documentation is very clear: https://docs.directus.io/self-hosted/config-options.html#file-storage

```env
STORAGE_LOCATIONS="aliyun-oss"
STORAGE_ALIYUN-OSS_DRIVER="s3"
STORAGE_ALIYUN-OSS_ROOT="/"
STORAGE_ALIYUN-OSS_PUBLIC_URL="https://xxx.oss-cn-hangzhou.aliyuncs.com"
STORAGE_ALIYUN-OSS_KEY="xxx"
STORAGE_ALIYUN-OSS_SECRET="xxxx"
STORAGE_ALIYUN-OSS_BUCKET="xxx"
STORAGE_ALIYUN-OSS_REGION="cn-hangzhou"
STORAGE_ALIYUN-OSS_ENDPOINT="oss-cn-hangzhou.aliyuncs.com"
```

**Reply by cdwmhcc** [reply]
You can modify `aliyun-oss` to any name you want.

``` env
STORAGE_LOCATIONS="marvin-xu"
STORAGE_MARVIN-XU_DRIVER="s3"
...
STORAGE_MARVIN-XU_ENDPOINT="oss-cn-hangzhou.aliyuncs.com"
```

**Reply by MarvinXu** [reply]
Thanks! I tried adding the config, but it kept getting an `SignatureDoesNotMatch` error.
```
[13:38:03.524] WARN: Couldn't save file 552d92fe-d547-4ecf-808a-ec6208afc8a7.png
[13:38:03.525] WARN: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    err: {
      "type": "S3ServiceException",
      "message": "The request signature we calculated does not match the signature you provided. Check your key and signing method.",
      "stack":
          SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Reply by cdwmhcc** [reply]
This error is that the signature is incorrect, please check the AccessKey ID and AccessKey Secret matches. I have been using aliyun oss and I think the configuration is correct. If you are using a sub-account, it‘s recommended that you try to use aliyun original AccessKey ID and AccessKey Secret to test whether it works.

**Reply by MarvinXu** [reply]
I tried using the same AccessKey id and secret in Node.js SDK, and it works. So I don't know what else to check..
Here is my config in docker-compose.yml:
```yml
# storage
      STORAGE_LOCATIONS: "aliyun-oss"
      STORAGE_ALIYUN-OSS_DRIVER: "s3"
      STORAGE_ALIYUN-OSS_ROOT: "/"
      STORAGE_ALIYUN-OSS_PUBLIC_URL: "https://<bucket-name>.oss-cn-shenzhen.aliyuncs.com"
      STORAGE_ALIYUN-OSS_KEY: "<key>"
      STORAGE_ALIYUN-OSS_SECRET: "<secret>"
      STORAGE_ALIYUN-OSS_BUCKET: "<bucket-name>"
      STORAGE_ALIYUN-OSS_REGION: "oss-cn-shenzhen"
      STORAGE_ALIYUN-OSS_ENDPOINT: "oss-cn-shenzhen.aliyuncs.com"
```
