### DISCUSSION TITLE
Permission error

### DISCUSSION THREAD

**Discussion by 3DIQE** [directus/directus#5177] [Archive]
hi
i created a collection in directus and added sth in it. i do every thing with admin user and update directus.
but when i want to edit, an error occures as this :+1: [FORBIDDEN] You don't have permission to access this.
and it's the same when i wanna to delete collection again  show this error.
what can i do?
![image](https://user-images.githubusercontent.com/82942259/115661545-d4563f80-a352-11eb-8913-cef5053c3496.png)

**Comment by benhaynes** [comment]
Not really enough info for us to help out here...

**Reply by 3DIQE** [reply]
what can i say more?

**Reply by rijkvanzanten** [reply]
@3DIQE Everything that's asked of you in the template when you create a new issue 👍🏻 

1) The issue and what you expected to happen
    The _ _ does _ _ when _ _ while it should _ _

2) Exact steps to reproduce this issue
    Click this, tap that, see error _ _

3) Your environment:
    What version of Directus you are using.
    Which DBMS are you using (MySQL 8, Postgres 12, ...).
    Which deployment are you using (npx, Docker, ...).
    What browser are you using (Chrome 87, Safari 14, ...).

4) Any other relevant information we might need to reproduce this issue
    A SQL dump of the setup.
    What third party services you rely on (S3, managed database, ...).

**Reply by ghezeli** [reply]
1. The Collection does Unexpected error when show or delete or change collection as admin user with full permission
2. when click on name of collection in collection tab
  when edit or delete collection on setting > data model
  
3. Docker Compose:
```
version: '3.3'
services:

  database:
    image: mysql:5.7
    ports:
      - 4406:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ' '
      MYSQL_DATABASE: ' '
      MYSQL_USER: ' '
      MYSQL_PASSWORD: ' '
    networks:
      - network

  cache:
    image: redis:6
    networks:
      - network
    restart: always

  directus:
    image: directus/directus:v9.0.0-rc.59
    ports:
      - 4405:8055
    networks:
      - network
    depends_on:
      - cache
      - database
    environment:
      KEY: ' '
      SECRET: ' '

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: ' '
      DB_USER: ' '
      DB_PASSWORD: ' '

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ' '
      ADMIN_PASSWORD: ' '
      
      ACCESS_TOKEN_TTL: '7d'
      
    restart: always

networks:
  network:

```

4. there aren't any 3rd party services
Sql dump :
DROP TABLE IF EXISTS `event`;
CREATE TABLE `event`  (
  `status` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'draft',
  `sort` int(11) NULL DEFAULT NULL,
  `user_created` char(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `date_created` timestamp(0) NULL DEFAULT NULL,
  `user_updated` char(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `date_updated` timestamp(0) NULL DEFAULT NULL,
  `name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `description` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `event_date` date NULL DEFAULT NULL,
  `start_time` time(0) NULL DEFAULT NULL,
  `end_time` time(0) NULL DEFAULT NULL,
  `normal_ticket_price` float(10, 5) NULL DEFAULT NULL,
  `vip_ticket_price` float(10, 5) NULL DEFAULT NULL,
  `address` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `map_location` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `category_id` char(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `shared_link` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `rate` float(10, 5) NULL DEFAULT NULL,
  `user_id` char(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;
`

`
