### DISCUSSION TITLE
Permission error running latest container image

### DISCUSSION THREAD

**Discussion by jakeceballos** [directus/directus#6480] [Archive]
If the above steps do not resolve your issue, please complete the following:

1) The issue and what you expected to happen
    Endpoint `/server/health` is returning an error instead of 200. 

2) Exact steps to reproduce this issue

- Using Directus v9.0.0-rc.69 container image, initialize system tables and run application.
- Upgrade Directus container image to latest version (v9.0.0-rc.80).
- Recreate containers and start application.
- Attempt GET request to `/server/health`

3) Your environment:
    v9.0.0-rc.69 and  v9.0.0-rc.80 container images
    Postgres
    Docker and docker-compose

4) Any other relevant information we might need to reproduce this issue
    ```
    15:31:50 🚨 storage:local:responseTime in ERROR state 
    UnknownException: E_UNKNOWN: An unknown error happened with the file health-3IHNN.
    Error code: EACCES
    Original stack:
      Error: EACCES: permission denied, open '/directus/uploads/health-3IHNN'
        at handleError (/directus/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:39:20)
        at LocalFileSystemStorage.put (/directus/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:205:19)
        at async testStorage (/directus/node_modules/directus/dist/services/server.js:244:21)
        at async Promise.all (index 3)
        at async ServerService.health (/directus/node_modules/directus/dist/services/server.js:90:40)
        at async /directus/node_modules/directus/dist/controllers/server.js:54:18
    15:31:50 ✨ request errored GET 503 /server/health 185ms
    ```

**Comment by rijkvanzanten** [comment]
What's the user that owns the local file system storage volume? As of [rc71](https://github.com/directus/directus/blob/main/changelog.md#v900-rc71-june-2-2021), the Docker image uses the `node` user instead of `root` for security reasons, which might require an update on your end, as per https://github.com/directus/directus/pull/5877.

@paescuj @t7tran any instructions on how to update the owner of the volume?

**Reply by andriusign** [reply]
Unexpected updates... just keep breaking our environments...

**Reply by paescuj** [reply]
@andriusign This is not unexpected - it has been announced as a breaking change in the changelog.

**Comment by t7tran** [comment]
While the Directus container is running (whichever version you can get it up and running), follow the steps below:

- Identify Directus container ID by running `docker ps`
- Run `docker exec -u root <directus-container-id> chown -R node:node /directus/database /directus/extensions /directus/uploads`

If you use `docker-compose`, run this command instead `docker-compose exec -u root <directus-service-name>chown -R node:node /directus/database /directus/extensions /directus/uploads`.

**Reply by justrealmilk** [reply]
This sadly does not work for me. I've even tried running the container as `privileged`!

On file upload:
```
directus     | 22:47:05 ⚠️  Couldn't save file b361c24a-4677-4b93-90e6-ae02f91910d9..jpg
directus     | 22:47:05 ⚠️  E_UNKNOWN: An unknown error happened with the file b361c24a-4677-4b93-90e6-ae02f91910d9..jpg.
directus     |
directus     | Error code: EACCES
directus     | Original stack:
directus     | Error: EACCES: permission denied, open '/directus/uploads/b361c24a-4677-4b93-90e6-ae02f91910d9..jpg'
```

I'm using docker-compose with 
```
volumes:
      - ./mnt/volume_sfo2_01/directus/uploads:/directus/uploads
```

**Reply by t7tran** [reply]
I think you are impacted by this issue #6584 (notice the double dots in the file path). Other than that, the `chown` command should apply to your host path volume.

**Reply by justrealmilk** [reply]
You were right about the .. - for some reason `image: directus/directus:latest` was pulling rc83 instead of rc85 so I've fixed that by specifying the release...

I didn't have a user or group named node, so I ran `useradd node` followed by `chown -R node:node /mnt/volume_sfo2_01/directus` to no avail

```
$ ls -ld /mnt/volume_sfo2_01/directus/
drwxr-xr-x 2 node node 4096 Jul 21 22:35 /mnt/volume_sfo2_01/directus/
```

**Reply by t7tran** [reply]
Ah, that's the common mistake people make. You can do it that way so long as your node user/group IDs matching the one inside the container. So the easiest option is to run the command inside the container using my suggested command.

If you really want to run `chown` from the host, you can use this command:

`sudo chown -R 1000:1000 /mnt/volume_sfo2_01/directus/`

`1000` is the UID of the `node` user/group inside Directus container.

**Reply by justrealmilk** [reply]
I wish I had just taken careful notes of my actions because while I had tried a combination of `docker-compose exec` to run the command from the container as you suggested and running the command on the host itself, neither were working. I need to find out what it actually means when I prepend a path with a period as I'm pretty sure it's related.

I changed
```
volumes:
      - ./mnt/volume_sfo2_01/directus/uploads:/directus/uploads
```
to
```
volumes:
      - /mnt/volume_sfo2_01/directus/uploads:/directus/uploads
```

All working!

Thanks so much for your prompt help, @t7tran!

**Reply by t7tran** [reply]
Spot on. I should have picked that up. One is relative to the `docker-compose.yml` file, and the other is from the root.

**Reply by rijkvanzanten** [reply]
cc @jacobrienstra

**Reply by andriusign** [reply]
This command helped
`docker exec -u root my-api chown -R node:node /directus/database /directus/extensions /directus/uploads
`
Also needed to restart my service with `docker restart my-api`

**Reply by GraphtyLove** [reply]
> While the Directus container is running (whichever version you can get it up and running), follow the steps below:
> 
> * Identify Directus container ID by running `docker ps`
> * Run `docker exec -u root <directus-container-id> chown -R node:node /directus/database /directus/extensions /directus/uploads`
> 
> If you use `docker-compose`, run this command instead `docker-compose exec -u root <directus-service-name>chown -R node:node /directus/database /directus/extensions /directus/uploads`.

I don't get it, it means that you will need to execute this command each time you pop Directus on a new server?
Shouldn't it be integrated in Directus' Dockerfile? I tried using the 9.X and the 9.5.X image and I'm still getting this error if I don't overwrite the permission with a `docker exec` command.

Did I miss something?

**Reply by paescuj** [reply]
> > While the Directus container is running (whichever version you can get it up and running), follow the steps below:
> > 
> > * Identify Directus container ID by running `docker ps`
> > * Run `docker exec -u root <directus-container-id> chown -R node:node /directus/database /directus/extensions /directus/uploads`
> > 
> > If you use `docker-compose`, run this command instead `docker-compose exec -u root <directus-service-name>chown -R node:node /directus/database /directus/extensions /directus/uploads`.
> 
> I don't get it, it means that you will need to execute this command each time you pop Directus on a new server? Shouldn't it be integrated in Directus' Dockerfile? I tried using the 9.X and the 9.5.X image and I'm still getting this error if I don't overwrite the permission with a `docker exec` command.
> 
> Did I miss something?

This depends on several factors: Do you use a volume or bind mount? What's the default `umask` on your Docker host? Do you mount a previous existing directory? Are there other security mechanisms like SELinux? Etc.

Usually, volumes are automatically created with the correct ownership.
If you're using a bind mount and have a rather restrictive umask setting on your host, the permissions on the directory might not be enough for Directus (e.g. `drwxr-xr-x﻿﻿  root  root`) - so in this case you need to adjust the ownership with the `docker exec ...` command. As you already wrote, this is only required once for a new Directus instance.

**Comment by mattes3** [comment]
The `docker exec` did not work for me. But when I change the docker compose file like this, it works, entirely without `docker exec`:

```
services:
  directus:
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - my_uploads:/directus/uploads
    ...etc..
 
volumes:
  my_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
```

**Reply by enzocomics** [reply]
I ran into this issue today, and your solution worked wonderfully for me. Thank you so much!

**Reply by zischler** [reply]
Worked for me too! thanks a lot! :)

**Comment by CalebBarnes** [comment]
This is an issue on the latest container version. `ERROR: Extension folder "/directus/extensions/interfaces" couldn't be opened`
This process then exits before I have the chance to open the container shell and edit the permissions. 👎

```
directus  | [23:45:02.190] ERROR: Failed to sync extensions
directus  | [23:45:02.190] ERROR: Extension folder "/directus/extensions/interfaces" couldn't be opened
directus  |     err: {
directus  |       "type": "Error",
directus  |       "message": "Extension folder \"/directus/extensions/interfaces\" couldn't be opened",
directus  |       "stack":
directus  |           Error: Extension folder "/directus/extensions/interfaces" couldn't be opened
directus  |               at ensureExtensionDirs (file:///directus/node_modules/.pnpm/file+packages+extensions_vue@3.3.4/node_modules/@directus/extensions/dist/node.js:11:13)
directus  |               at async ExtensionManager.load (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:137:13)
directus  |               at async ExtensionManager.initialize (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:123:13)
directus  |               at async loadExtensions (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/cli/load-extensions.js:17:5)
directus  |               at async createCli (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/cli/index.js:20:5)
directus  |     }
directus  | 2023-12-06T23:45:02: PM2 log: App name:directus id:0 disconnected
directus  | 2023-12-06T23:45:02: PM2 log: App [directus:0] exited with code [1] via signal [SIGINT]
directus  | 2023-12-06T23:45:08: PM2 log: 0 application online, retry = 3
directus  | 2023-12-06T23:45:10: PM2 log: 0 application online, retry = 2
directus  | 2023-12-06T23:45:12: PM2 log: 0 application online, retry = 1
directus  | 2023-12-06T23:45:14: PM2 log: 0 application online, retry = 0
directus  | 2023-12-06T23:45:14: PM2 log: PM2 successfully stopped
```

This is running on Ubuntu server by a user in the docker group.

Using the docker compose example provided in the docs:
```
services:
  directus:
    image: directus/directus:latest
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
```

**Fixed!! 🚀** 

@mattes3 solution worked after I pruned volumes and restarted the command a couple times! 🎉

Full docker-compose.yml for anyone who has same issue:
```
version: "3"
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - my_uploads:/directus/uploads
      - my_extensions:/directus/extensions
      # If you want to load extensions from the host
    depends_on:
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1" 
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263" # these are test keys 😏

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
volumes:
  my_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
  my_extensions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/extensions
```

**Reply by mattes3** [reply]
Wow, cool that it worked for you, too!

**Reply by mrfzd** [reply]
This worked for us too!
Thank you for saving us the trouble.

**Comment by mihaon** [comment]
It happens because docker "bind mount" host directory (in contrast to named volumes) is not initialized with owner/permissions taken from inside the container directory. It can be fixed via docker compose `post_start` hook.
```
services:
    directus:
        # ...
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        post_start:
            - command: chown node:node /directus/database /directus/uploads /directus/extensions
              user: root
        # ...

```

P.S.: see https://github.com/directus/docs/pull/428 for details
