### DISCUSSION TITLE
Docker ARM image

### DISCUSSION THREAD

**Discussion by sGerli** [directus/directus#6792] [Feature Requests]
Now that there are more ARM devices like M1 Macs, AWS Graviton 2 servers, and others there should be an arm compatible docker image.

In order to make this happen it would be necessary to modify the build action to use docker buildx and build all those platforms.

Buildx example: `docker buildx build --platform linux/arm64,linux/amd64 . -t [tag1] -t [tag2] --push`

To use buildx in Github actions you may need to add these build action:  [docker/setup-qemu-action@v1](https://github.com/docker/setup-qemu-action) (necessary in order to make arm builds) and [docker/setup-buildx-action@v1](https://github.com/docker/setup-buildx-action) (necessary to use buildx on github actions)

related to #3893 #2770

**Comment by rijkvanzanten** [comment]
@SeanDylanGoff @paescuj now that we're knee-deep in overhauling the build flow, is this something that's fairly easy to "throw in"?

**Reply by sGerli** [reply]
I think it shouldn't be difficult for you. I just added it to one of my projects by using those two actions, and a run action (that runs the buildx command), for me it was a change that only took a few minutes.

**Reply by SeanDylanGoff** [reply]
@rijkvanzanten I don't have a M1 Mac here right now, and I never worked with GitHub actions before anyways (we use GitLab...). Maybe @sGerli could make a PR based on https://github.com/cynova/directus/tree/build-improvements ?

**Reply by paescuj** [reply]
I'm trying to come up with something right now 😃

**Reply by sGerli** [reply]
I think that based on your new setup something like this should work:

```yml
  build-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Restore build artifacts
        uses: actions/cache@v2
        with:
          path: '**/dist'
          key: build-artifacts-${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ env.DOCKERHUB_IMAGE }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: ${{ env.GHCR_IMAGE }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './docker/Dockerfile'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          push: true

```
Reference: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
