### DISCUSSION TITLE
Best approach for multi-site with Docker

### DISCUSSION THREAD

**Discussion by justrealmilk** [directus/directus#6941] [Archive]
Hi! I'm a Docker newb. I've been learning a lot (fast) as I go.

I use NGINX for all my HTTP needs and as a proxy server for node applications like Directus.

Two questions...

### Docker

How/what is the best approach to achieving this: 
- Can I somehow run multiple containers as one service? 
- How could I configure multiple Directus containers with a singular compose?

_docker-compose.yaml_
```yaml
version: '3'
services:
  directus-cache:
    container_name: directus-cache
    image: redis:6
    networks:
      - directus

  directus-project1:
    container_name: directus-project1
    image: directus/directus:9.0.0-rc.85
    ports:
      - 8055:8055
    volumes:
      - /directus/project1/uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - directus-cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      PUBLIC_URL: '/project1'

      DB_CLIENT: 'mysql'
      DB_HOST: '172.20.0.1'
      DB_PORT: '3306'
      DB_DATABASE: 'directus_project1'
      DB_USER: 'directus'
      DB_PASSWORD: 'password'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://directus-cache:6379'

      ADMIN_EMAIL: 'email'
      ADMIN_PASSWORD: 'password'

  directus-project2:
    container_name: directus-project2
    image: directus/directus:9.0.0-rc.85
    ports:
      - 8056:8055
    volumes:
      - /directus/project2/uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - directus-cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      PUBLIC_URL: '/project2'

      DB_CLIENT: 'mysql'
      DB_HOST: '172.20.0.1'
      DB_PORT: '3306'
      DB_DATABASE: 'directus_project2'
      DB_USER: 'directus'
      DB_PASSWORD: 'password'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://directus-cache:6379'

      ADMIN_EMAIL: 'email'
      ADMIN_PASSWORD: 'password'

networks:
  directus:
```

### NGINX

Is this the best approach for a NGINX proxy for Directus in a Docker?

_nginx-site.conf_
```conf
server {
    server_name mydirectus.com;

    error_log off;
    access_log off;

    location ~* ^/project1/(.*)$ {
        rewrite ^/project1/(.*)$ /$1 break;

        proxy_pass http://localhost:8055;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }

    location ~* ^/project2/(.*)$ {
        rewrite ^/project2/(.*)$ /$1 break;

        proxy_pass http://localhost:8056;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by rijkvanzanten** [comment]
Heya! From my limited knowledge of both subjects, my general answer is: _yes_

> Can I somehow run multiple containers as one service?

That's where docker-compose (or another service, like Kubernetes) comes in 🙂 

> How could I configure multiple Directus containers with a singular compose?

The way you described it is how I would've done it. That being said, I'm sure there's a smart DevOps person out there somewhere that would be able to optimize this somehow

**Comment by danaketh** [comment]
> Can I somehow run multiple containers as one service?

Ofc you can.

> How could I configure multiple Directus containers with a singular compose?

Same way you have in your example. You can also create multiple files, each with a container configuration of its own and chain them.

`docker-compose.001.yaml`
```yaml
version: '3'
services:
  directus001-cache:
  directus001-app:
  directus001-db:

networks:
  directus001:
```

`docker-compose.002.yaml`
```yaml
version: '3'
services:
  directus002-cache:
  directus002-app:
  directus002-db:

networks:
  directus002:
```

And you can go on with as many you want. Then all you'd need to do would be to run `docker-compose up -d` with as many `-f <config_file>` as necessary. So, it would looks something like `docker-compose up -d -f docker-compose.001.yaml -f docker-compose.002.yaml`.

But you shouldn't. It's going to be pain to maintain and you'll hate yourself sooner or later. Just create a new directory for each new instance with `docker-compose.yaml` in it. This way you can keep them away from each other, easy to control and "easy" to maintain. However, if you wish/need to run multiple instances, I suggest you first check AWS, Google Cloud, or Azure. I'm saying this from a position of someone who is maintaining 40 containers for a client, running exactly like this. I would trade it for AWS any day (my main work is on project that runs on AWS, so I have the comparison).
