### DISCUSSION TITLE
Require NPM Package in Extensions using Docker-Compose

### DISCUSSION THREAD

**Discussion by NilsBaumgartner1994** [directus/directus#8584] [Archive]
Hello folks,

i fear that i already know my answer but maybe some smart ass here knows an answer. I am using directus with docker-compose and i wrote a file in the extension folder. But i want to require a package (from npm) in order to outsource some logic. Is that possible? 
An Idea of mine was, to make an axios request to an NodeJS Server (on localhost), in order to handle my logic there. The problem here would be maybe, that i cant transfer the directus objects like FilesService or MailsService.

Any Idea how that could be accomplished ?

**Comment by nickrum** [comment]
If the package you want to use is already a dependency of `directus`, you can simple `require()` it. If it is not, you have to either extend the Directus docker image and `npm install` the packages you want to use or bundle the packages you want to use into your extension's entrypoint. The extensions-sdk already supports this, but it is currently not documented.

**Reply by benhaynes** [reply]
CC @alesvaupotic

**Reply by NilsBaumgartner1994** [reply]
@nickrum how to extend the docker image ?

**Reply by nickrum** [reply]
Something like this should work:

```dockerfile
ARG DIRECTUS_VERSION
FROM directus/directus:${DIRECTUS_VERSION}
ENV NODE_ENV production
RUN npm install <package-name>
```

**Reply by NilsBaumgartner1994** [reply]
Found solution myself:
This will install it every start, which your solution is "better", but I would need to edit the Dockerfile instead of the docker-compose file

...
    command: >
      sh -c "
        <own npm installation>
        npx directus bootstrap && npx directus start
      "
    #image: directus/directus:9.0.0-rc.100
    image: directus/directus:latest

**Comment by NilsBaumgartner1994** [comment]
Docker-compose.yaml:


    command: >
      sh -c "
        <INSERT OWN NPM INSTALLATION HERE>
        npx directus bootstrap && npx directus start
      "
    #image: directus/directus:9.0.0-rc.100
    image: directus/directus:latest

**Reply by vilve-aman** [reply]
this is not working as of now 

MY docker-compose:
```
version: '3'
services:

  directus:
    command: >
      sh -c "
        npm i @google-cloud/storage
        npx directus bootstrap && npx directus start
      "  
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./stats/uploads:/directus/uploads
      - ./stats/database:/directus/database
    environment:

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
```


Error I am recieving:
```
directus_1  | npm ERR! Cannot read properties of null (reading 'matches')
directus_1  | 
directus_1  | npm ERR! A complete log of this run can be found in:
directus_1  | npm ERR!     /home/node/.npm/_logs/2023-06-19T13_24_29_116Z-debug-0.log
```
