### DISCUSSION TITLE
How to unhide a hidden field

### DISCUSSION THREAD

**Discussion by ndaidong** [directus/directus#8956] [Archive]
With v9.0.0-rc.96, once I set "Hide Field on Detail" to a field, how can I show it again? Thanks.

![Screenshot from 2021-10-20 11-15-43](https://user-images.githubusercontent.com/1809619/138027712-1a6cf19d-5f9d-4ffc-8c48-30911a575a6e.png)

**Comment by joselcvarela** [comment]
Hello @ndaidong,
Sure, after you click on `Hide field on Detail` there will be an option `Show field on Detail`.
And that is independent from the version you are.

**Comment by ndaidong** [comment]
@joselcvarela thanks, where I can see the option `Show field on Detail`? Actually that User model has 2 hidden fields: `Password` and `Salt`, but I have no way to get them display on the layout as before.

![Screenshot from 2021-10-21 21-28-18](https://user-images.githubusercontent.com/1809619/138298962-63d218b7-7921-492b-ada0-efd8034cdfd0.png)

**Reply by joselcvarela** [reply]
On the first screenshot you posted you were at `Data Model` configuring `User Model`.
In that view, you were trying to hide the `name` field. To do so you have to click on `Hide field on detail` (as shown on the screenshot).
If you want to show it again, you should do the same steps, but instead of appearing `Hide field on detail`, it will show `Show field on detail`

**Reply by ndaidong** [reply]
@joselcvarela once it disappeared, how I can do the same steps? where will it show `Show field on detail`? Here is my screen capture in which I created an example field and hide it.

https://www.youtube.com/watch?v=Iz34iMkdr78

**Reply by benhaynes** [reply]
Hahah, whaaaa... 👀 

It shouldn't disappear, it should just gray out and show an "eye crossed out" icon on the right. Not sure if this is a global bug, or just your instance.

**Reply by ndaidong** [reply]
@benhaynes I'm not sure. Maybe it happens with rc version only. I will test another version of directus later. 

it's running with docker-compose.yaml as below:

```yml
version: '3'

services:

  postgres:
    image: postgres:13.3-alpine
    container_name: directus-postgres
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.2.4-alpine3.14
    container_name: directus-redis
    volumes:
      - ./data/redis:/data
    restart: always

  directus:
    image: directus/directus:9.0.0-rc.96
    container_name: directus
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/extensions:/directus/extensions
    ports:
      - 8055:8055
    restart: always
    ```
