### DISCUSSION TITLE
Gateway Time-out with reverse proxy (Traefik)

### DISCUSSION THREAD

**Discussion by MaxenceMottard** [directus/directus#9152] [Archive]
Hello, I use directus with the latest version of the image _9.0.0-rc.99_. I use Traefik as a reverse proxy on my server. You can see my configuration below.

I have to delete and restart my container at least 5 times before my reverse-proxy works with Directus, it's quite random. When it doesn't work I get a _504 Gateway Time-out_ error (Traefik error). I tried to expose port _8055_ in my docker-compose file and it works.
I use the same configuration for all my services and the problem I am experiencing is only with this image.  So I am wondering if there is a problem with the proxy management with the docker image.

```yml
version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - directus-network
    env_file:
      - ./.env
  directus:
    image: directus/directus:9.0.0-rc.99
    restart: always
    networks:
      - reverse-proxy
      - directus-network
    volumes:
      - ./extensions:/directus/extensions
    env_file:
      - ./.env
    depends_on:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.services.EASYSELLING.loadbalancer.server.port=8055
      - traefik.http.routers.EASYSELLING.rule=Host(`domain.com`)
      - traefik.http.routers.EASYSELLING.entrypoints=http
      - traefik.http.routers.EASYSELLING.middlewares=https-redirect@file
      - traefik.http.routers.EASYSELLING-Https.rule=Host(`domain.com`)
      - traefik.http.routers.EASYSELLING-Https.entrypoints=https
      - traefik.http.routers.EASYSELLING-Https.middlewares=security@file, compression@file
      - traefik.http.routers.EASYSELLING-Https.tls=true
      - traefik.http.routers.EASYSELLING-Https.tls.certresolver=letsencrypt


networks:
  directus-network:
  reverse-proxy:
    external: true

```

### To Reproduce

Use the same docker-compose with Traefik 

### Errors Shown

504 Gateway Timeout

### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

Docker image version

### What database are you using?

Mariadb

### What browser are you using?

Safari + Chrome

### What operating system are you using?

linux (production server)

### How are you deploying Directus?

Docker

### My environment variables

```
#     Maria DB environment
MYSQL_DATABASE=
MYSQL_ROOT_PASSWORD=

#     Directus environment
KEY=
SECRET=
DB_CLIENT=mysql
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USER=
DB_PASSWORD=
ADMIN_EMAIL=
ADMIN_PASSWORD=
PUBLIC_URL=
#       OAuth
#OAUTH_PROVIDERS="apple"
#OAUTH_APPLE_AUTHORIZE_URL=
#OAUTH_APPLE_ACCESS_URL=
#OAUTH_APPLE_KEY=
#OAUTH_APPLE_SECRET=
#       SMTP
EMAIL_SMTP_HOST=
EMAIL_SMTP_PORT=
EMAIL_SMTP_USER=
EMAIL_SMTP_PASSWORD=
EMAIL_SMTP_SECURE=
EMAIL_TRANSPORT=
EMAIL_FROM=
```

**Comment by azrikahar** [comment]
Moved this to discussion as this seems to be more of a reverse proxy configuration issue, rather than an issue with Directus itself (). Will move this back to issues if it turns out to actually be something caused by Directus 👍

---

> So I am wondering if there is a problem with the proxy management with the docker image.

there have been users using Traefik with Directus without any issues AFAIK, so it's probably not Directus here, but we can never be sure without further info.

Hmm there seems to be quite a few moving parts here so it'll be hard for us to identify what is causing this issue. In addition, we also currently don't have visibility to the file configs, namely `https-redirect`, `security` and  `compression`. Likely they wouldn't really cause issue by themselves (I assume https-redirect simply redirects http to https), but perhaps they're somehow not meshing well to each other when combined together. 

Additionally it'll also be helpful if you can share more detail on "linux (production server)". Is it hosted in any cloud provider, or on premise? Are there anything sitting in front of the server like a hardware load balancer etc? Just throwing random speculations here.

With that said, would you mind trying to make a minimal setup instead? I'd recommend just to keep it simple first, with Traefik + Directus, HTTP only (provided you're not including any production or sensitive data when exposing this setup to the internet). Once we can verify this works, then we can work our way up by adding more things that you've previous configured.

**Reply by MaxenceMottard** [reply]
First of all I want to thank you for your answer.

Here is my Traefik configuration: 
```toml
[http]
  [http.middlewares.compression.compress]
    excludedContentTypes = ["text/event-stream"]

  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.security.headers]
    accessControlMaxAge = 100
    browserXssFilter = true
    contentTypeNosniff = true
    forceSTSHeader = true
    frameDeny = false
    stsIncludeSubdomains = true
    stsPreload = true
    stsSeconds = 315360000
    accessControlAllowMethods = ["GET", "OPTIONS", "PUT", "POST", "UPDATE", "DELETE", "PATCH"]
    accessControlAllowOriginList = ["*"]
    accessControlAllowHeaders = ["content-type", "authorization", "cache-control", "x-requested-with", "upload-source", "x-session-id", "x-lazy-pagination", "x-disable-pagination"]
```
