### DISCUSSION TITLE
Support "partial" schema migrations

### DISCUSSION THREAD

**Discussion by MiniDigger** [directus/directus#9214] [Feature Requests]
Been playing around with the schema snapshot/apply cli commands, they work really well, really like how the show exactly whats being changed.

One issue I have is that I have a cursed setup, where some but not all tables are shared between envs. A usecase would be only wanting to move one particular "feature" to staging, but have new changes for another feature in the dev DB already.

I tried creating a snapshot.yaml file with only the changes I want, but that then wants to delete all my other stuff:

```
? The following changes will be applied:

Collections:
  - Delete table_I_want_to_keep
  - Update test
    - Set comment to This is a test 2

Fields:
  - Delete test.field_I_want_to_keep
  - Update test.test
    - Set comment to This is a test

Relations:
  - Delete directus_collections.group -> directus_collections
```

<details>
<summary>snapshot.yaml</summary>

```yml
version: 1
directus: 9.0.0-rc.99
collections:
  - collection: test
    meta:
      collection: test
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: test
      schema: directus
      comment: This is a test 2
fields:
  - collection: test
    field: test
    type: text
    schema:
      name: test
      table: test
      data_type: text
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: This is a test
      schema: directus
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: test
      field: test
      special: null
      interface: go-wysiwyg
      options:
        presetName: test
      display: raw
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations: []
```
</details>

Maybe we could have a flag to never delete (named partial maybe) anything (that would prolly already solve my usecase), or alternatively, but way more time consuming, in the cli output, somehow be able to toggle every single change 🤯  (altho no clue how one would do that in a cli, plus meh for automating, bunch of questions there)

edit: maybe we can have a more involved UI for this in the app, that allows to select what to export/import
