### DISCUSSION TITLE
Auth login color

### DISCUSSION THREAD

**Discussion by NilsBaumgartner1994** [directus/directus#9688] [Feature Requests]
It would be nice or is it possible to set in the environment a color for the login button of an auth ?
Like:

AUTH_GOOGLE_COLOR: "#5588cc"

**Comment by joselcvarela** [comment]
Hello @NilsBaumgartner1994 
In `Project Settings` you can define custom css.
Try something like:
```css
.sso-link {
  background: blue !important;
}
```
