### DISCUSSION TITLE
Extensions cannot be loaded once deployed to Google App Engine

### DISCUSSION THREAD

**Discussion by rbraggaar** [directus/directus#9955] [Archive]
I have been running Directus on Google App Engine for a while now and it is working well.
However, when I try to add some custom logic with extensions I cannot get it to work with App Engine.

I'm trying to register a simple endpoint under /test which responds when I run Directus locally with `npm start` and visit the endpoint. However when App Engine starts it cannot load the extensions.

![image](https://user-images.githubusercontent.com/16044244/142741365-18434946-dc78-42c1-b540-562c890b1ce0.png)

```
module.exports = function registerEndpoint(router) {
	router.get('/', (req, res) => res.send('Test.'));
};
```

### To Reproduce

Upload Directus to Google App Engine with the following config and environment setting:

`EXTENSIONS_PATH="./extensions"` 

```
runtime: nodejs16
env: standard
instance_class: F1
inbound_services:
  - warmup
handlers:
  - url: .*
    script: auto
    secure: always
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: xxxx
```

### Errors Shown

**Frontend, when getting /test**
`{"errors":[{"message":"Route /test doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}`

**Server logs:**
` Couldn't load extensions`
` Extension folder "/workspace/extensions/interfaces" couldn't be opened`

<details>
<summary>Diagnostic details</summary>

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.9.1

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Google App Engine

</details>
