### ISSUE TITLE
Roles - error on clean installation 9.1.1

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#10055]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

## Maybe related with #10045

We perform a clean installation of the latest version, and when accessing the role management it gives the following error: 
![image](https://user-images.githubusercontent.com/17298604/143475921-ed663bb0-624e-42c3-b712-13fa149977f0.png)

```
{
  "errors": [
    {
      "message": "select * from (select \"directus_users\".\"role\", count(\"directus_users\".\"id\") as \"count->id\" from \"directus_users\" where \"directus_users\".\"role\" = $1 order by \"directus_users\".\"id\" asc limit $2) as \"foo\" - column \"directus_users.role\" must appear in the GROUP BY clause or be used in an aggregate function",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

1) docker-compose.yml
```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
```

2) login

3) go to roles page

### What version of Directus are you using?

9.1.1

### What version of Node.js are you using?

16

### What database are you using?

postgres 13

### What browser are you using?

edge

### What operating system are you using?

ubuntu

### How are you deploying Directus?

docker
