### ISSUE TITLE
Relationships images does not render in table list

### ISSUE THREAD

**Issue by danilopolani** [directus/directus#10105]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Similar to https://github.com/directus/directus/issues/9864, images in display templates for relationships are not being rendered anymore in the dropdown.

### To Reproduce

1. Create a collection "Tags"
1.1. Add an image field displayed as "Thumbnail"
1. Create a collection "Posts"
1.1. Create a M2M between posts <-> tags
1.1. Set the display of M2M tags to show the image thumbnail
1. Create a post with one or more tags
1. Go to the table list of posts, show the "tags" column and click on the cell to open the dropdown 

### Errors Shown

Browser error:

> TypeError: Cannot read properties of undefined (reading 'includes')

The file generating the issue is `File.vue` when checking for the image type and generating its URL: https://github.com/directus/directus/blob/8d87302f016828901c83fb19f4ed72c6d3235042/app/src/displays/file/file.vue#L47-L52

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL 8

### What browser are you using?

Opera

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment]
<img width="371" alt="CleanShot 2021-12-02 at 19 31 11@2x" src="https://user-images.githubusercontent.com/9141017/144524380-ed03a7ab-141d-4dba-8776-a8f2ccf91ddf.png">

This seems to work as expected on my end. Would you be able to share a schema snapshot (`directus schema snapshot ./schema.yaml`) so we can reproduce your schema locally and see if and where the problem exists? 🙂 

I'll close this for now as I believe this is a configuration problem.

**Comment by danilopolani** [comment]
Hey @rijkvanzanten ,
sorry for the delay. I've updated to Directus 9.2.2, also switched to a fresh Postgres database but the issue still happen to me.

Here's the schema snapshop, if needed I can provide also a dump of the actual database and the images I'm using.

<details>
  <summary>Schema snapshot</summary>

```yaml
version: 1
directus: 9.2.2
collections:
  - collection: categories
    meta:
      collection: categories
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: 2
      group: null
      collapse: open
    schema:
      name: categories
      schema: public
      comment: null
  - collection: posts
    meta:
      collection: posts
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: 1
      group: null
      collapse: open
    schema:
      name: posts
      schema: public
      comment: null
  - collection: posts_categories
    meta:
      collection: posts_categories
      icon: import_export
      note: null
      display_template: null
      hidden: true
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: posts_categories
      schema: public
      comment: null
fields:
  - collection: categories
    field: id
    type: integer
    schema:
      name: id
      table: categories
      data_type: integer
      default_value: nextval('categories_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: categories
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: 1
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: categories
    field: image
    type: uuid
    schema:
      name: image
      table: categories
      data_type: uuid
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: public
      foreign_key_table: directus_files
      foreign_key_column: id
    meta:
      collection: categories
      field: image
      special:
        - file
      interface: file-image
      options: null
      display: image
      display_options: null
      readonly: false
      hidden: false
      sort: 3
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: categories
    field: name
    type: string
    schema:
      name: name
      table: categories
      data_type: character varying
      default_value: null
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: categories
      field: name
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: 2
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: id
    type: integer
    schema:
      name: id
      table: posts
      data_type: integer
      default_value: nextval('posts_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: title
    type: string
    schema:
      name: title
      table: posts
      data_type: character varying
      default_value: null
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: title
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_categories
    field: id
    type: integer
    schema:
      name: id
      table: posts_categories
      data_type: integer
      default_value: nextval('posts_categories_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts_categories
      field: id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_categories
    field: posts_id
    type: integer
    schema:
      name: posts_id
      table: posts_categories
      data_type: integer
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: public
      foreign_key_table: posts
      foreign_key_column: id
    meta:
      collection: posts_categories
      field: posts_id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_categories
    field: categories_id
    type: integer
    schema:
      name: categories_id
      table: posts_categories
      data_type: integer
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: public
      foreign_key_table: categories
      foreign_key_column: id
    meta:
      collection: posts_categories
      field: categories_id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: categories
    type: alias
    schema: null
    meta:
      collection: posts
      field: categories
      special:
        - m2m
      interface: list-m2m
      options:
        template: '{{categories_id.name}}'
      display: related-values
      display_options:
        template: '{{categories_id.image.$thumbnail}}{{categories_id.name}}'
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations:
  - collection: directus_collections
    field: group
    related_collection: directus_collections
    schema:
      table: directus_collections
      column: group
      foreign_key_table: directus_collections
      foreign_key_column: collection
      foreign_key_schema: public
      constraint_name: directus_collections_group_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
    meta: null
  - collection: posts_categories
    field: posts_id
    related_collection: posts
    schema:
      table: posts_categories
      column: posts_id
      foreign_key_table: posts
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: posts_categories_posts_id_foreign
      on_update: NO ACTION
      on_delete: CASCADE
    meta:
      many_collection: posts_categories
      many_field: posts_id
      one_collection: posts
      one_field: categories
      one_collection_field: null
      one_allowed_collections: null
      junction_field: categories_id
      sort_field: null
      one_deselect_action: delete
  - collection: posts_categories
    field: categories_id
    related_collection: categories
    schema:
      table: posts_categories
      column: categories_id
      foreign_key_table: categories
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: posts_categories_categories_id_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
    meta:
      many_collection: posts_categories
      many_field: categories_id
      one_collection: categories
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: posts_id
      sort_field: null
      one_deselect_action: nullify
  - collection: categories
    field: image
    related_collection: directus_files
    schema:
      table: categories
      column: image
      foreign_key_table: directus_files
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: categories_image_foreign
      on_update: NO ACTION
      on_delete: SET NULL
    meta:
      many_collection: categories
      many_field: image
      one_collection: directus_files
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
```

</details>
