### ISSUE TITLE
MS SQL reports length -0.5 for TEXT, breaking schema snapshots

### ISSUE THREAD

**Issue by TErenberger** [directus/directus#10376]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I exported a simple collection using the CLI snapshot tool with YAML file type. The collection contains two properties, one text area and one text input.

When using this snapshot on a new DB I get an error: "Length or precision specification 0 is invalid " Upon inspecting the yaml file for things set to 0 ( I did not find any) I found a suspect max_length value of -0.5 for the text area. This was created using the  simple field creation, without any adjustments to fields other than field_name.

```yaml
 - collection: Snapshot_Test_Notification
    field: Text_Area
    type: string
    schema:
      table: Snapshot_Test_Notification
      name: Text_Area
      data_type: nvarchar
      max_length: -0.5
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      default_value: null
      is_primary_key: false
      is_unique: false
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
      is_generated: false
      generation_expression: null
    meta:
      collection: Snapshot_Test_Notification
      field: Text_Area
      special: null
      interface: input-multiline
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null 
```

### To Reproduce

1. Start with empty DB.
2. Init directus DB
3. Create new collection with defaults (all system fields off).
4. Create new Field with type "Text Area" using simple field creation.
5. Run `npx directus schema snapshot -y ./test.yaml`
6. Create new empty DB.
7. Adjust .env to point at new DB
8. Init Directus DB
9. Run `npx directus schema apply -y ./test.yaml`
8. Observe error.

### Errors Shown

18:45:37 🚨 CREATE TABLE [Snapshot_Test_Notification] ([id] int identity(1,1) not null primary key, [Message] nvarchar(255) null CONSTRAINT [snapshot_test_notification_message_default] DEFAULT null, [Text_Area] nvarchar(0) null CONSTRAINT [snapshot_test_notification_text_area_default] DEFAULT null) - Line 1: Length or precision specification 0 is invalid.  

RequestError: CREATE TABLE [Snapshot_Test_Notification] ([id] int identity(1,1) not null primary key, [Message] nvarchar(255) null CONSTRAINT [snapshot_test_notification_message_default] DEFAULT null, [Text_Area] nvarchar(0) null CONSTRAINT [snapshot_test_notification_text_area_default] DEFAULT null) - Line 1: Length or precision specification 0 is invalid.
    at RequestTokenHandler.onErrorMessage (/workspace/apps/directus-cms/node_modules/tedious/lib/token/handler.js:362:21)
    at Readable.<anonymous> (/workspace/apps/directus-cms/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at next (node:internal/streams/from:98:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What version of Directus are you using?

directus/directus:9.1 - d2c9437957ae

### What version of Node.js are you using?

16.13.0

### What database are you using?

sql server

### What browser are you using?

chrome

### What operating system are you using?

windows 10

### How are you deploying Directus?

Docker Local
