### ISSUE TITLE
O2M field that targets a collection with a manual primary key (string) has display issues

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#10645]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Possibly related to #3834

When adding new `keys` to the `keychain`, they don't get displayed but are added in the background. The new `keys` will only be displayed after saving the `keychain`.

I know this explanation might be confusing but see reproduction below.

### To Reproduce

Create 2 collections:

1. `keys` collection with manually entered string as primary key called `key`. (everything else at default)
2. `keychains` collection (default values)

Go to `keychains` collection and create a new `O2M` field targeting the `keys` collection, create a new field (foreign key) during that step called `keychain_id` in the `keys` collection. Make sure to also do the following settings:

- Disable `select button`
- Set all relational triggers to delete (cascade)
- Setup Interface and Display to show the `key` value

Reason for these options: The `keys` collection is supposed to contain unique keys that are attached to one `keychain`.

Now visit the `keychains` collection and start creating a new entry. Add a few keys to the keychain and you will see the issue happening.

The issue only occurs when adding new entries, not when selecting existing entries.

Short and sweet video:

https://user-images.githubusercontent.com/7304212/147168654-2be14110-6d31-4571-b814-08331ef84a7d.mp4

### Errors Shown

N/A

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MariaDB 10.3.32

### What browser are you using?

Firefox Latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Ubuntu Server 20.04, npm installation with a systemd service running it

**Comment by azrikahar** [comment]
Can confirm this on my end. Likely related to #10368 merged in 9.2.2.

<details>
<summary>Schema snapshot for above issue</summary>

```yaml
version: 1
directus: 9.4.2
collections:
  - collection: keychains
    meta:
      collection: keychains
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: keychains
      schema: public
      comment: null
  - collection: keys
    meta:
      collection: keys
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      name: keys
      schema: public
      comment: null
fields:
  - collection: keychains
    field: id
    type: integer
    schema:
      name: id
      table: keychains
      data_type: integer
      default_value: nextval('keychains_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: keychains
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: keys
    field: key
    type: string
    schema:
      name: key
      table: keys
      data_type: character varying
      default_value: null
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: keys
      field: key
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: keys
    field: keychain_id
    type: integer
    schema:
      name: keychain_id
      table: keys
      data_type: integer
      default_value: null
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: public
      foreign_key_table: keychains
      foreign_key_column: id
    meta:
      collection: keys
      field: keychain_id
      special: null
      interface: select-dropdown-m2o
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: keychains
    field: keys
    type: alias
    schema: null
    meta:
      collection: keychains
      field: keys
      special:
        - o2m
      interface: list-o2m
      options:
        enableSelect: false
        template: '{{key}}'
      display: related-values
      display_options:
        template: '{{key}}'
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations:
  - collection: keys
    field: keychain_id
    related_collection: keychains
    schema:
      table: keys
      column: keychain_id
      foreign_key_table: keychains
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: keys_keychain_id_foreign
      on_update: NO ACTION
      on_delete: CASCADE
    meta:
      many_collection: keys
      many_field: keychain_id
      one_collection: keychains
      one_field: keys
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: delete
```

</details>
