### ISSUE TITLE
db collation is ignored

### ISSUE THREAD

**Issue by terion-name** [directus/directus#10949]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

DB is in `utf8mb4` with `utf8mb4_general_ci`.

env contains:
```
DB_CHARSET=UTF8MB4
DB_COLLATION=utf8mb4_general_ci
```

Schema contains collation in all collections:
```yml
schema:
      name: about_blocks
      schema: gillia
      comment: ''
      collation: utf8mb4_general_ci
      engine: InnoDB
```

Yet, all tables and fields are created with `utf8mb4_0900_ai_ci` collation

### To Reproduce

n/a

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.2.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

node base docker image

### How are you deploying Directus?

Docker, kubernetes
