### ISSUE TITLE
Cannot delete collections or folders from Data Model view

### ISSUE THREAD

**Issue by ffranchina** [directus/directus#11082]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It seems impossible to delete a collection or a folder from the Data Model view of the app.
Clicking on the three dots menu > Delete collection produces no effect: it does not show anything in the console nor trigger any network call. I guess it is a Vue issue but I don't know it enough to check it by myself.
The only way I have to delete a collection is to click on it, enter in the collection view and click on the red trash bin in the top-right corner. Unfortunately this method works just for collections and not for folders.

### To Reproduce

Using the following `docker-compose.yaml`:
```yaml
version: '3'
services:
  testdatabase:
    container_name: testdatabase
    image: postgis/postgis:13-master
    networks:
      - testdirectus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

    container_name: testdirectus
    image: directus/directus:latest
    ports:
      - 8056:8055
    
    networks:
      - testdirectus
    depends_on:
      - testdatabase
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'testdatabase'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  testdirectus:
```
Logging with the default credentials (see above `docker-compose.yaml` file).
Go to Settings > Data Model > Create Collection, create a new collection.
Come back to Settings > Data Model, try to the delete the collection just created by using the respective three dots menu and clicking on Delete collection.

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Linux Ubuntu

### How are you deploying Directus?

Docker
