### ISSUE TITLE
Expose snapshot/apply endpoints in the API

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11481]
This allows you to use the schema migration logic from both the CLI and the API. This endpoint will be admin-only.

We should implement the following:

```
/server/schema/snapshot
/server/schema/apply
/server/schema/diff
```

where `diff` will return an array of changes the API will apply on upload of a the snapshot to the apply endpoint.

**Comment by CoenWarmer** [comment]
Would love this!

**Comment by infomiho** [comment]
Granularity in terms of operations that can be performed would be great, for example allow only adding of new content. Some sort of maybe change scope narrowing like: affect only X collection. It would make it a much safer tool for production databases 😄

**Comment by spawnrider** [comment]
Hi guys,

I made my own **custom endpoint for exporting and importing snapshot**. This facilitate the migration of environment when using Docker images.

Here is my custom API endpoint source : https://gist.github.com/spawnrider/bdffb17660c91f8b42235b2ad18978cf

This endpoint expose 2 API (note that I called my extension 'snapshot') : 
- **_/snapshot/export_** for exporting the current environment snapshot,
- **_/snapshot/import_** for uploading the snapshot file and apply it to the current environment.

To build it, follow the official Directus documentation : https://docs.directus.io/extensions/endpoints/
Then **add it to a custom Directus image** by importing the builed index.js file into the image :
```
FROM directus/directus:9
COPY ./snapshot/dist/index.js /directus/extensions/endpoints/snapshot/index.js
```

**Comment by tatthien** [comment]
@spawnrider Nice example

**Comment by rijkvanzanten** [comment]
Ref #13383, #13562, #11895, #11436

**Comment by rijkvanzanten** [comment]
Linear: [ENG-270](https://linear.app/directus/issue/ENG-270/expose-snapshotapply-endpoints-in-the-api)

**Comment by tedsteen** [comment]
I tried this API today and I have something like this
```js
  async getSchemaDiff(fileName: string): Promise<object> {
    const form = new FormData();
    form.append('schema', fs.createReadStream(fileName), { filename: 'schema.yaml', filepath: 'schema.yaml'});
    const res = await this.directus.transport.post(`${this.url}/schema/diff?force=true`, form, {
      headers: {
        ...form.getHeaders()
      },
    })

    return res.data
  }
  async applyDiff(diff: object) {
    return await this.directus.transport.post(`${this.url}/schema/apply`, diff)
  }
```

And then I do
```js
    const diff = await session.getSchemaDiff(schemaFilePath)
    const res = await session.applyDiff(diff)
```

When applying the diff I get the error `error:  "diff.relations[26].related_collection" must be a string`
the only thing I can see causing this is that there are some `related_collection: null` in some collections.
Example:
```yaml
  - collection: market_config_dynamic_pages
    field: item
    related_collection: null
    meta:
      junction_field: market_config_id
      many_collection: market_config_dynamic_pages
      many_field: item
      one_allowed_collections:
        - game_pages
        - landing_pages
        - promo_pages
      one_collection: null
      one_collection_field: collection
      one_deselect_action: nullify
      one_field: null
      sort_field: null
```
