### ISSUE TITLE
Cannot create items in new collection with automatic fields

### ISSUE THREAD

**Issue by Prochy20** [directus/directus#11676]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have created a new collection with fields "date_created" and "date_updated":

![Snímek obrazovky 2022-02-16 v 20 39 09](https://user-images.githubusercontent.com/54104598/154343515-7824d0f0-adc0-4b5b-904b-eda60dc7da84.png)

I added just a single field there:

![Snímek obrazovky 2022-02-16 v 20 39 48](https://user-images.githubusercontent.com/54104598/154343541-d8781e7f-6546-4687-a99c-aed752a71c29.png)

When I try to create items in this collection it just does nothing:

https://user-images.githubusercontent.com/54104598/154343611-28c66734-c030-4d26-82cc-ecfc1c027275.mov

I get only this response in console:

![Snímek obrazovky 2022-02-16 v 20 40 15](https://user-images.githubusercontent.com/54104598/154343637-130fb970-ede6-47e6-9590-3939fc98003b.png)

If I do not include that "date_created" and "date_updated" field, it creates the record as it should. All "older collections" which has the automatic fields do work normally.

I suspect this had something to do with issue I have previously reported: https://github.com/directus/directus/issues/10693 - I did what they said in following article: https://kevdees.com/disable-mysql-strict-mode-and-no_zero_date-errors-in-homestead/

![image](https://user-images.githubusercontent.com/54104598/154344618-aebcefe1-3a14-4146-b6e3-1d1457c19dca.png)

### To Reproduce

1. Create new collection with "date_updated" and "date_created" field
2. Create new record in this collection

### Errors Shown

None :/ 

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.18.0

### What database are you using?

MySQL: Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using EditLine wrapper

### What browser are you using?

Google Chrome v 96.0.4664.110

### What operating system are you using?

Desktop: MacOS Monterey 12.1 | Server: Ubuntu 18.04 LTS

### How are you deploying Directus?

Digital Ocean VPS (Using Ubuntu 18.04 LTS)

**Comment by joselcvarela** [comment]
Hello,
This is the configuration i used to run Mysql:
```
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode="ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: directus
    ports:
      - 5101:3306
    cap_add:
      - SYS_NICE
 ```
 
 and it seemed to work properly.
 We need more information, like a docker compose configuration, in order for us to reproduce the error, otherwise it's not possible to fix it 👍
