### ISSUE TITLE
Directus just keeps loading

### ISSUE THREAD

**Issue by heromiyo** [directus/directus#12180]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/39757927/158459874-31bd3d64-8253-47ed-8300-3013aadc40b1.png)

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Mp+eT+kC73oqfRJK0Sy9EOe4ZcODg5hpYRji1kE6FZk='), or a nonce ('nonce-...') is required to enable inline execution.

vendor.546e1516.js:67 Uncaught SyntaxError: Invalid or unexpected token
```

### To Reproduce

```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'xxxx_user'
      POSTGRES_PASSWORD: 'xxxx_pass'
      POSTGRES_DB: 'xxxadmin'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/home/admin/directus/uploads

      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-somekey'
      SECRET: '6116487b-cda1-52c2-b5b5-somekey'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'xxxxadmin'
      DB_USER: 'xxx_xxuser'
      DB_PASSWORD: 'xxx_pass'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'xxx@gmail.com'
      ADMIN_PASSWORD: 'xxxxxx'
      PUBLIC_URL: 'http://xxxxx.com'
      CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
```

### Errors Shown

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Mp+eT+kC73oqfRJK0Sy9EOe4ZcODg5hpYRji1kE6FZk='), or a nonce ('nonce-...') is required to enable inline execution.

vendor.546e1516.js:67 Uncaught SyntaxError: Invalid or unexpected token
```

### What version of Directus are you using?

latest

### What version of Node.js are you using?

latest

### What database are you using?

postgres

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker
