### ISSUE TITLE
"KEY" Environment Variable is missing.

### ISSUE THREAD

**Issue by joelee2017** [directus/directus#12202]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

 "KEY" Environment Variable is missing. 

### To Reproduce

yml content ：

```yaml
version: '3'
services:     
  directus:
    container_name: directus
    image: directus/directus:latest 
    ports:
      - 8055:8055
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mssql'
      DB_HOST: 'x.x.x.x'
      DB_PORT: 'xxxx'
      DB_DATABASE: 'directus'
      DB_USER: 'xxxxxxxx'
      DB_PASSWORD: 'xxxxxxxx' 

      ADMIN_EMAIL: 'admin@admin.com'
      ADMIN_PASSWORD: 'admin' 
networks:
  directus:
```

 docker-compose up -d

npx directus start

### Errors Shown

npx directus start
![image](https://user-images.githubusercontent.com/33776374/158729207-19f3ca98-c3b6-4bb7-a0fe-0804d0609d38.png)

### What version of Directus are you using?

latest

### What version of Node.js are you using?

v16.14.0

### What database are you using?

ms sql

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, unfortunately I can't seem to reproduce this on my end. Perhaps there's some indentation issue where your environment variables aren't being set properly? I'd recommend trying the following minimal compose file just to isolate any other possibilities and print out the environment variables of the container when it starts up:

```yaml
services:
  directus:
    container_name: directus
    image: directus/directus:latest
    entrypoint: ["/bin/sh", "-c"]
    command: env
    ports:
      - 8055:8055
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      ADMIN_EMAIL: 'admin@admin.com'
      ADMIN_PASSWORD: 'admin'
```

For example when I try the compose file above, logging the container does show me that KEY and SECRET etc are present:

![WindowsTerminal_dIS7HY8dkq](https://user-images.githubusercontent.com/42867097/158766442-e7651c94-cd07-4f10-b0dc-b16dd4c28474.png)

Alternatively you can also try the other slightly different syntax of setting environment variables (refer here: https://docs.docker.com/compose/compose-file/compose-file-v3/#environment) such as:

```yaml
    environment:
      - KEY=255d861b-5ea1-5996-9aa3-922530ec40b1
      - SECRET=6116487b-cda1-52c2-b5b5-c8022c45e263
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin
```

Closing this for now as I believe it's more so a docker-compose and/or compose file issue rather than a bug with Directus, but do let us know whether it's really a syntax issue here once you have the chance to confirm 👍
