### ISSUE TITLE
Inconsistent revisions after batch update

### ISSUE THREAD

**Issue by DavidPLamas** [directus/directus#12460]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Whenever the batch update feature is used with more than 100 records or when the list was sorted on the UI, the revisions stored in the database get inconsistent values.
* If you select more than 100 records, the revisions for the records after the 100th are stored with data = `null`
* If you sort the table using any of the columns, revisions get mixed between each other, that is, the revision of the record A is stored on the record B, and so on.
* If you mix both use cases, you get mixed results

### To Reproduce

1. Configure a new collection. Can be any collection, just need to make sure you have a field that can be edited after creating the record. You can use the attached snapshot for easier reproduction
2. Create at least 100 records for that collection
3. Go to the list of records
4. Make it so that you can see more than 100 items per page
5. Sort the table by any of the fields
6. Select all the records
7. Make an update
8. Everything succeeds but if you go to the database and execute the following query you will see the inconsistent records
```sql
select * from directus_revisions where collection = 'boats' and ((data is not null and item <> data->>'id') or data is null)
```

<details>
<summary>Snapshot.yaml</summary>

```yaml
version: 1
directus: 9.7.1
collections:
  - collection: boats
    meta:
      collection: boats
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: status
      archive_app_filter: true
      archive_value: archived
      unarchive_value: draft
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: boats
      comment: null
fields:
  - collection: boats
    field: id
    type: integer
    schema:
      name: id
      table: boats
      schema: public
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('boats_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: boats
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: 1
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: boats
    field: status
    type: string
    schema:
      name: status
      table: boats
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: draft
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: boats
      field: status
      special: null
      interface: select-dropdown
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      display: labels
      display_options:
        showAsDot: true
        choices:
          - background: '#00C897'
            value: published
          - background: '#D3DAE4'
            value: draft
          - background: '#F7971C'
            value: archived
      readonly: false
      hidden: false
      sort: 2
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: boats
    field: date_created
    type: timestamp
    schema:
      name: date_created
      table: boats
      schema: public
      data_type: timestamp with time zone
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: boats
      field: date_created
      special:
        - date-created
      interface: datetime
      options: null
      display: datetime
      display_options:
        relative: true
      readonly: true
      hidden: true
      sort: 4
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: boats
    field: date_updated
    type: timestamp
    schema:
      name: date_updated
      table: boats
      schema: public
      data_type: timestamp with time zone
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: boats
      field: date_updated
      special:
        - date-updated
      interface: datetime
      options: null
      display: datetime
      display_options:
        relative: true
      readonly: true
      hidden: true
      sort: 5
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: boats
    field: name
    type: string
    schema:
      name: name
      table: boats
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: boats
      field: name
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: 3
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations: []
```
</details>

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker
