### ISSUE TITLE
Foreign key constraints are not created when a collection relates to directus_users

### ISSUE THREAD

**Issue by amcnaughton** [directus/directus#12508]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

A collection that includes the `user_updated` field does not create the FK constraint to `directus_users`, therefore the directus UI complains that the relationship is not configured.

### To Reproduce

Each time you run the apply directus says its setting up the foreign key. It never actually does though.

`npx directus schema apply ./schema.yaml`
```
11:20:43 ✨ Loaded extensions: tree, morning_consult
?

Fields:
  - Update feature_flags.user_updated
    - Set foreign_key_schema to pinky
    - Set foreign_key_table to directus_users
    - Set foreign_key_column to idThe following changes will be applied:

Fields:
  - Update feature_flags.user_updated
    - Set foreign_key_schema to pinky
    - Set foreign_key_table to directus_users
    - Set foreign_key_column to id

Would you like to continue? Yes
11:23:33 ✨ Snapshot applied successfully
```

Here's the schema.yaml
```
version: 1
directus: 9.7.0
collections:
  - collection: feature_flags
    meta:
      collection: feature_flags
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: true
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: pinky
      name: feature_flags
      comment: null
fields:
  - collection: feature_flags
    field: id
    type: integer
    schema:
      name: id
      table: feature_flags
      schema: pinky
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('feature_flags_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: feature_flags
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: 1
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: feature_flags
    field: user_updated
    type: uuid
    schema:
      name: user_updated
      table: feature_flags
      schema: pinky
      data_type: uuid
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: pinky
      foreign_key_table: directus_users
      foreign_key_column: id
    meta:
      collection: feature_flags
      field: user_updated
      special:
        - user-updated
      interface: select-dropdown-m2o
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      display: user
      display_options: null
      readonly: true
      hidden: true
      sort: 3
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations: []
```

### Errors Shown

Examining the table constraints shows that no constraint was setup on table `feature_flags`.

It should be something like:

```
FOREIGN KEY ("user_updated") REFERENCES directus_users(id) 
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v16.14.0

### What database are you using?

Postgres 12.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
I'm assuming this is because there's a check in there that's a little too aggressively filtering out system tables

**Comment by br41nslug** [comment]
I was able to reproduce it using the supplied `schema.yml` however it looks like something went wrong with the instance this snapshot was taken from (or the snapshot process itself). When applying a snapshot foreign key constraints are created based on the `relations` list in the snapshot which is an empty list in the provided file.

When adding this relation it works as expected (tested in 9.7.0 and 9.10.0):
```yaml
....
relations: 
  - collection: feature_flags
    field: user_updated
    related_collection: directus_users
    schema:
      constraint_name: feature_flags_user_updated_foreign
      table: feature_flags
      column: user_updated
      foreign_key_schema: pinky
      foreign_key_table: directus_users
      foreign_key_column: id
      on_update: NO ACTION
      on_delete: SET NULL
    meta:
      many_collection: feature_flags
      many_field: user_updated
      one_collection: directus_users
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: null
      sort_field: null
      one_deselect_action: nullify
```
With this addition the CLI does return that it has created the relation
```
Fields:
  - Create feature_flags.id
  - Create feature_flags.user_updated

Relations:
  - Create feature_flags.user_updated-> directus_users

08:22:02 ✨ Snapshot applied successfully
```
