### ISSUE TITLE
LDAP 503 Error "Unexpected Error"

### ISSUE THREAD

**Issue by kbmanseau** [directus/directus#12523]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When spinning up a local instance of directus community version, LDAP auth does not work for me. When I attempt to login I see:

-  In the container logs I see: `directus    | 15:46:19 ✨ request errored POST 503 /auth/login/jumpcloud 51ms`
- Web ui shows "unexpected error"
- HTTP response "Object { code: "SERVICE_UNAVAILABLE", service: "ldap", message: "No Such Object" }"

I did a lot of digging and testing. I can recreate this behavior externally with a test ldapjs client. If I attempt to perform a client.search() before a client.bind() call I get "No Such Object"

So to test this behavior in directus I did a few things:

- I executed a .bind call first thing inside the new Promise in validateBindClient() (in api/dist/auth/drivers/ldap.js) and this worked
- Then I removed my bind call and modified the line in api/dist/auth/drivers/ldap.js `if (!(err instanceof ldapjs_1.OperationsError)) {` to `if (!(err instanceof ldapjs_1.OperationsError) && !(err instanceof ldapjs_1.NoSuchObjectError)) {`
- this checks for the nosuchobject error and performs a bind. This works properly and my user can login
- If I do a docker build with this custom change and then run from my test image ldap login works

I am not sure what the cause of this issue could be as I believe others have LDAP login working properly. Perhaps something that might be related is that we use jumpcloud as our ldap provided. Their structure puts both the users and groups at the same base DN "ou=Users,o=[org-id],dc=jumpcloud,dc=com"

Docker file being used for reference:
```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./uploads:/directus/api/uploads
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    #image: directus-test
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: ''
      SECRET: ''

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'testing'


      AUTH_DISABLE_DEFAULT: "false"
      AUTH_PROVIDERS: "string:jumpcloud"

      AUTH_JUMPCLOUD_DRIVER: "string:ldap"
      AUTH_JUMPCLOUD_CLIENT_URL: "string:ldaps://ldap.jumpcloud.com:636"

      AUTH_JUMPCLOUD_BIND_DN: "string:uid=[ldap user uid],ou=Users,o=[org-id],dc=jumpcloud,dc=com"
      AUTH_JUMPCLOUD_BIND_PASSWORD: "string:password"

      AUTH_JUMPCLOUD_USER_DN: "string:ou=Users,o=[org-id],dc=jumpcloud,dc=com"
      AUTH_JUMPCLOUD_USER_ATTRIBUTE: "uid"
      AUTH_LDAP_MAIL_ATTRIBUTE: "mail"
      AUTH_JUMPCLOUD_USER_SCOPE: "sub"

      AUTH_JUMPCLOUD_GROUP_DN: "string:ou=Users,o=[org-id],dc=jumpcloud,dc=com"
      AUTH_JUMPCLOUD_GROUP_ATTRIBUTE: "member"
      AUTH_JUMPCLOUD_GROUP_SCOPE: "sub"

      # Make sure to set this in production
      # (see https://docs.directus.io/configuration/config-options/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
```

### To Reproduce

I tested a few ways:

- local deployment
    - npm install + build + start
- local docker deployment
    - Using docker-compose 

Both ways use the latest version of directus and provide the same behavior

### Errors Shown

-  In the container logs I see: `directus    | 15:46:19 ✨ request errored POST 503 /auth/login/jumpcloud 51ms`
- Web ui shows "unexpected error"
- HTTP response in browser "Object { code: "SERVICE_UNAVAILABLE", service: "ldap", message: "No Such Object" }"

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

postgis 13 and postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Local build + docker build + docker image
