### ISSUE TITLE
SSO no longer working after version update

### ISSUE THREAD

**Issue by megamorf** [directus/directus#12616]
### Describe the Bug

Users cannot log in via OpenID provider after version upgrade.

***

We've recently did a big version update of our directus instance and have encountered a problem with the SSO setup where we need your help.

We've been using Directus with `v9.0.0-rc.69` with Auth0 as OpenID provider for many months without problems. Login to the CMS is limited to a known list of Auth0 users, a self-registration is not allowed. Users can have different roles in Directus depending on what tasks they are responsible for.

Our workflow is as follows:

1. IDP: create user in Auth0
2. Directus: create a user in with a matching email address
3. Directus: assign the correct role to the user
4. IDP: finally, send IDP password reset link to user so that he can set a password and log in to Directus

## Setup "Old"

docker-compose.yml

```yaml
version: '3.6'

services:
  directus:
    container_name: "directus-prod-sometenant"
    image: directus/directus:v9.0.0-rc.69
    volumes:
      - /opt/ourproduct/shared/cms/data/extensions/:/directus/extensions:ro
    ports:
      - 8055:8055
    restart: unless-stopped
    environment:
      KEY: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      SECRET: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

      PUBLIC_URL: "https://sometenant.ourproduct.com/cms"

      OAUTH_PROVIDERS: "auth0"
      OAUTH_AUTH0_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      OAUTH_AUTH0_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      OAUTH_AUTH0_SCOPE: "openid email profile"
      OAUTH_AUTH0_AUTHORIZE_URL: "https://login.ourproduct.com/authorize"
      OAUTH_AUTH0_ACCESS_URL: "https://login.ourproduct.com/oauth/token"
      OAUTH_AUTH0_PROFILE_URL: "https://login.ourproduct.com/userinfo"
      OAUTH_AUTH0_STATE: "state"

      # [unimportant settings omitted]
```

## Setup "New"

docker-compose.yml

```yaml
version: '3.6'

services:
  directus:
    container_name: "directus-prod-sometenant"
    image: directus/directus:9.5.2

    volumes:
      - /opt/ourproduct/shared/cms/data/extensions/:/directus/extensions:ro
    ports:
      - 8055:8055
    restart: unless-stopped
    environment:
      KEY: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      SECRET: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

      PUBLIC_URL: "https://sometenant.ourproduct.com/cms"

      AUTH_PROVIDERS: "auth0"
      AUTH_AUTH0_DRIVER: "openid"
      AUTH_AUTH0_CLIENT_ID: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      AUTH_AUTH0_CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      AUTH_AUTH0_SCOPE: "openid email profile"
      AUTH_AUTH0_ISSUER_URL: "https://login.ourproduct.com/.well-known/openid-configuration"
      AUTH_AUTH0_IDENTIFIER_KEY: "email"

      # [unimportant settings omitted]
```

## Issue description

Now the issue that we're facing is that after the upgrade with the updated environment variables, our users are not able to log in to Directus successfully.

I have dumped the database and set up the CMS locally to debug the issue. The logs events I'm seeing with 9.5.2 when a user is attempting to login via Auth0 are:

```json

{"level":10,"time":1649167014904,"pid":43,"hostname":"ba81dffd734f","msg":"[OpenID] User doesn't exist, and public registration not allowed for provider \"auth0\""}
{"level":40,"time":1649167014906,"pid":43,"hostname":"ba81dffd734f","status":401,"code":"INVALID_CREDENTIALS","extensions":{},"stack":"Error: Invalid user credentials.\n    at OpenIDAuthDriver.getUserID (/directus/node_modules/directus/dist/auth/drivers/openid.js:127:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AuthenticationService.login (/directus/node_modules/directus/dist/services/authentication.js:47:28)\n    at async /directus/node_modules/directus/dist/auth/drivers/openid.js:234:28","type":"Error","msg":"Invalid user credentials."}
{"level":30,"time":1649167014908,"pid":43,"hostname":"ba81dffd734f","req":{"id":74,"method":"GET","url":"/auth/login/auth0/callback?code=07tuTzKh9XH66zW7&state=Me7XjgM1BZ-KDPS0XLodjZr0rON9Gyfn5omPjxiU_hI","query":{"code":"07tuTzKh9XH66zW7","state":"Me7XjgM1BZ-KDPS0XLodjZr0rON9Gyfn5omPjxiU_hI"},"params":{},"headers":{"host":"localhost:8055","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"cross-site","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","referer":"http://localhost:8055/","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9","cookie":"openid.auth0=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJpZmllciI6IjBaWGlHNG91QkVnajFtYVdUcG5ZcmNfcG12OHRJdm0zdzRIN2RxdDJDZE0iLCJyZWRpcmVjdCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA1NS9hZG1pbi9sb2dpbj9jb250aW51ZSIsInByb21wdCI6ZmFsc2UsImlhdCI6MTY0OTE2NzAxMywiZXhwIjoxNjQ5MTY3MzEzLCJpc3MiOiJkaXJlY3R1cyJ9.1x7BMH18SNnH0IEY22tcBR9B6_-Jj-nVeKYdPHqzsVU"},"remoteAddress":"::ffff:172.21.0.1","remotePort":55704},"res":{"statusCode":302,"headers":{"content-security-policy":"script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob:;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'","x-powered-by":"Directus","vary":"Origin, Accept","access-control-allow-credentials":"true","access-control-expose-headers":"Content-Range","set-cookie":"openid.auth0=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT","location":"http://localhost:8055/admin/login?reason=INVALID_USER","content-type":"text/html; charset=utf-8","content-length":"150"}},"responseTime":811,"msg":"request completed"}
{"level":30,"time":1649167014930,"pid":43,"hostname":"ba81dffd734f","req":{"id":75,"method":"GET","url":"/admin/login?reason=INVALID_USER","query":{"reason":"INVALID_USER"},"params":{},"headers":{"host":"localhost:8055","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"cross-site","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","referer":"http://localhost:8055/","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9","if-none-match":"W/\"1b3e-d0Mw83DIPmBAdMXlSHfyBaA57iA\""},"remoteAddress":"::ffff:172.21.0.1","remotePort":55704},"res":{"statusCode":304,"headers":{"content-security-policy":"script-src 'self' 'unsafe-eval';worker-src 'self' blob:;child-src 'self' blob:;img-src 'self' data: blob:;connect-src 'self' https://*;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'","x-powered-by":"Directus","vary":"Origin","access-control-allow-credentials":"true","access-control-expose-headers":"Content-Range","cache-control":"no-cache","etag":"W/\"1b3e-d0Mw83DIPmBAdMXlSHfyBaA57iA\""}},"responseTime":3,"msg":"request completed"}
```

My next troubleshooting step was to add `AUTH_AUTH0_ALLOW_PUBLIC_REGISTRATION: "true"` to the "new" setup to see how a SSO user account that was provisioned by Directus differs from our manually created accounts:

### Manually created user that worked with the old setup

```json
{
  "data": {
    "id": "782c23ac-6947-45cc-b6a4-80a99df21d28",
    "first_name": "Sebastian",
    "last_name": "TestAccount",
    "email": "nem20220318@mailinator.com",
    "password": "**********",
    "location": null,
    "title": null,
    "description": null,
    "tags": null,
    "avatar": null,
    "language": "en-US",
    "theme": "auto",
    "tfa_secret": null,
    "status": "active",
    "role": "2d7bcb7b-832e-4463-8cf2-9321e38f2953",
    "token": null,
    "last_access": null,
    "last_page": null,
    "provider": "default",
    "external_identifier": null,
    "auth_data": null,
    "email_notifications": true
  }
}
```

![old-user](https://user-images.githubusercontent.com/1732128/162192841-35e8e2c5-2ff9-4ad3-86d2-d35b62477366.png)

### Auto-provisioned user that works with the new setup

```json
{
  "data": {
    "id": "dd019778-a65c-4e9d-9869-d05af59dd904",
    "first_name": null,
    "last_name": null,
    "email": "nem20220318@mailinator.com",
    "password": null,
    "location": null,
    "title": null,
    "description": null,
    "tags": null,
    "avatar": null,
    "language": "en-US",
    "theme": "auto",
    "tfa_secret": null,
    "status": "active",
    "role": null,
    "token": null,
    "last_access": "2022-04-05T14:08:58.000Z",
    "last_page": "/content",
    "provider": "auth0",
    "external_identifier": "nem20220318@mailinator.com",
    "auth_data": null,
    "email_notifications": true
  }
}
```

![new-user](https://user-images.githubusercontent.com/1732128/162192864-7cb50c71-7ce7-42d0-9182-d25956ea0cda.png)

If I compare the two it becomes obvious that the `provider` and `external_identifier` fields are different between the users which leads me to assume that this is the root cause. This also suggests that the `email` field is no longer evaluated when it comes to SSO logins.

However, updating the `provider` and `external_identifier` fields at least via GUI is not possible.

What is the correct way to keep our user creation workflow intact while also enabling existing user accounts to log in via Auth0 again.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

v16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome 99.0.4844.83

### How are you deploying Directus?

Docker
