### ISSUE TITLE
Docker secrets available without _FILE syntax

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#12876]
### Describe the Bug

It is documented, that if using secrets one should append "_FILE" the property name. ADMIN_EMAIL and ADMIN_PASSWORD also work without that.

So just like:
```
directus:
  ...
  secrets:
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      
secrets:
  ADMIN_PASSWORD:
    file: ./secrets/admin_password.txt
  ADMIN_EMAIL:
    file: ./secrets/admin_user.txt
```

This should be mandatory, I guess
```
      ADMIN_EMAIL_FILE: '/run/secrets/ADMIN_EMAIL'
      ADMIN_PASSWORD_FILE: '/run/secrets/ADMIN_PASSWORD'
```

refer to the discord discussion: https://discord.com/channels/725371605378924594/760886871965433877/966282012669390850

### To Reproduce

1. Create .txt file with your admin email as content
2. In the secrets section add 
```
ADMIN_EMAIL:
     file: ./secrets/admin_user.txt
```
3. In your directus service add a secrets section
```
    secrets:
      - ADMIN_EMAIL
```
4. Rebuild docker and run

### Errors Shown

None

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### How are you deploying Directus?

Docker
