### ISSUE TITLE
Directus default Dockerfile environment variables cause config file to be partially ignored

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#12884]
### Describe the Bug

The Directus `Dockerfile` has the following code to set some default environment variables:

```
ENV \
  DB_CLIENT="sqlite3" \
  DB_FILENAME="/directus/database/database.sqlite" \
  EXTENSIONS_PATH="/directus/extensions" \
  STORAGE_LOCAL_ROOT="/directus/uploads"
```

Defaults can definitely be nice, but what if I'd like to set a `CONFIG_PATH` and set everything in a custom config file? So in my case I add configuration to my `docker-compose.yaml` file like so:

```yaml
services:
  database:
    ...
  directus:
    ...
    volumes:
      - ./directus-config/:/directus/config/
    environment:
      - CONFIG_PATH=/directus/config/config.yaml
```

Now inside that file I set some variables like so:

```yaml
KEY: directus
SECRET: directus
ADMIN_EMAIL: directus@example.com
ADMIN_PASSWORD: directus
DB_CLIENT: postgres
DB_HOST: database
DB_PORT: 5432
DB_DATABASE: directus
DB_USER: directus
DB_PASSWORD: directus
```

With this configuration, the default `DB_CLIENT` environment file set in the `Dockerfile` will take priority over the `DB_CLIENT` value I set in my config file. That means I have to do the following in my `docker-compose.yaml` to "fight" the default environment variable configuration.

```yaml
services:
  directus:
    ...
    volumes:
      - ./directus-config/:/directus/config/
    environment:
      - CONFIG_PATH=/directus/config/config.yaml
      - DB_CLIENT=postgres
```

Now I'm either defining `DB_CLIENT` in multiple places or omitting it from my custom config file, both of which are confusing and/or prone to error. It also forces me to know the default set inside the `Dockerfile` if I want to use a custom config file and is a rather hard to catch issue.

From the Docker perspective this is intended behavior, but from the Directus perspective I'd say this is a "bug" because defaults should never override explicit values regardless of where they are defined.

### To Reproduce

I think the description above is pretty solid in this case to explain how the issue can be reproduced.

### Errors Shown

No errors. That's part of the reason this is rather hard to catch. I'm also not aware of a way to see the currently loaded configuration that Directus is using, which is something that would have really helped me find this issue.

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

Whatever version the Directus Docker image is using.

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker
