### ISSUE TITLE
Error on migrate schema from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by GustavoBlaze** [directus/directus#13988]
### Describe the Bug

I've created a schema with a lot of relationships between the colletions. At the beggining I have choosen a SQLIte3 and i decided to change to postgres for using in production.

The problem is that i used `uuid` as collection id and the SQLite doesn't support this data type natively. It creates the uuid column as `char(36)`. And when you export the schema through the cli these relations goes as `data_type: char`, `max_length: 36` and `type: string`. 

Once you have the schema in hands you try to apply in the new database and face an error, saying that is not possible to create the relationship.

### To Reproduce

- Create a project using SQLite as database
- Create some collections with id as `uuid` data type
- Create relations between these colletions (I used M2M, but it guess it can be any type)
- Export the schema
- Set up the database inside the .env as postgres
- Try to apply the schema

### Errors Shown

![image](https://user-images.githubusercontent.com/25311644/174500512-427b549c-4999-496c-8fad-068e8d6e09b9.png)

![image](https://user-images.githubusercontent.com/25311644/174500472-73cd9b4d-24a9-4144-9165-5a60c867e3ce.png)

The picture below is the `snapshot.yml` on relation section, the `data_type: char`, `max_length: 36` `type: string` has already been replaced by me (i had to do it manually)
![image](https://user-images.githubusercontent.com/25311644/174500567-44ea66a9-cf23-4caa-bfe8-805c5d9058da.png)

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14.3

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Example schema snapshot to actually reproduce it reliably:

<details>
<summary>uuid.yaml</summary>

```yaml
version: 1
directus: 9.12.2
collections:
  - collection: model_a
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: model_a
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      name: model_a
      sql: >-
        CREATE TABLE `model_a` (`id` char(36) not null, `name` varchar(255)
        null, primary key (`id`))
  - collection: model_a_model_b
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: model_a_model_b
      color: null
      display_template: null
      group: null
      hidden: true
      icon: import_export
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      name: model_a_model_b
      sql: >-
        CREATE TABLE "model_a_model_b" (`id` integer PRIMARY KEY AUTOINCREMENT
        NOT NULL, `model_a_id` char(36) NULL, `model_b_id` char(36) NULL,
        CONSTRAINT `model_a_model_b_model_b_id_foreign` FOREIGN KEY
        (`model_b_id`) REFERENCES `model_b` (`id`) ON DELETE SET NULL,
        CONSTRAINT `model_a_model_b_model_a_id_foreign` FOREIGN KEY
        (`model_a_id`) REFERENCES `model_a` (`id`) ON DELETE SET NULL)
  - collection: model_b
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: model_b
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      name: model_b
      sql: >-
        CREATE TABLE `model_b` (`id` char(36) not null, `name` varchar(255)
        null, primary key (`id`))
  - collection: tree
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: tree
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      name: tree
      sql: >-
        CREATE TABLE `tree` (`id` integer not null primary key autoincrement,
        `checkbox_tree` varchar(255) null)
fields:
  - collection: model_a
    field: id
    meta:
      collection: model_a
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: model_a
    type: uuid
  - collection: model_a
    field: m2m_b
    meta:
      collection: model_a
      conditions: null
      display: null
      display_options: null
      field: m2m_b
      group: null
      hidden: false
      interface: list-m2m
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - m2m
      translations: null
      validation: null
      validation_message: null
      width: full
    schema: null
    type: alias
  - collection: model_a
    field: name
    meta:
      collection: model_a
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      table: model_a
    type: string
  - collection: model_a_model_b
    field: id
    meta:
      collection: model_a_model_b
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: integer
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      table: model_a_model_b
    type: integer
  - collection: model_a_model_b
    field: model_a_id
    meta:
      collection: model_a_model_b
      conditions: null
      display: null
      display_options: null
      field: model_a_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: model_a
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: model_a_id
      numeric_precision: null
      numeric_scale: null
      table: model_a_model_b
    type: string
  - collection: model_a_model_b
    field: model_b_id
    meta:
      collection: model_a_model_b
      conditions: null
      display: null
      display_options: null
      field: model_b_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: model_b
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: model_b_id
      numeric_precision: null
      numeric_scale: null
      table: model_a_model_b
    type: string
  - collection: model_b
    field: id
    meta:
      collection: model_b
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: model_b
    type: uuid
  - collection: model_b
    field: m2m_a
    meta:
      collection: model_b
      conditions: null
      display: null
      display_options: null
      field: m2m_a
      group: null
      hidden: false
      interface: list-m2m
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - m2m
      translations: null
      validation: null
      validation_message: null
      width: full
    schema: null
    type: alias
  - collection: model_b
    field: name
    meta:
      collection: model_b
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      table: model_b
    type: string
  - collection: tree
    field: checkbox_tree
    meta:
      collection: tree
      conditions: null
      display: labels
      display_options: null
      field: checkbox_tree
      group: null
      hidden: false
      interface: select-multiple-checkbox-tree
      note: null
      options:
        choices:
          - text: Model A
            value: A
            children:
              - text: Series 100
                value: A-100
                children:
                  - text: Black
                    value: A-100-BK
                    children: null
                  - text: Blue
                    value: A-100-BL
                  - text: Red
                    value: A-100-RD
              - text: Series 200
                value: A-200
                children:
                  - text: Orange
                    value: A-200-OR
                  - text: Blue
                    value: A-200-BL
          - text: Model B
            value: B
            children:
              - text: Series 100
                value: B-100
                children:
                  - text: Black
                    value: B-100-BK
                  - text: White
                    value: B-100-WH
              - text: Series 300
                value: B-300
                children:
                  - text: Red
                    value: B-300-RD
                  - text: Blue
                    value: B-300-BL
          - text: Model C
            value: C
            children:
              - text: Series 100
                value: C-100
                children:
                  - text: Black
                    value: C-100-BK
                    children: null
                  - text: Red
                    value: C-100-RD
                  - text: Pink
                    value: C-100-PK
                  - text: Yellow
                    value: C-100-YW
              - text: Series 200
                value: C-200
                children:
                  - text: Black
                    value: C-200-BK
      readonly: false
      required: false
      sort: null
      special:
        - cast-csv
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: checkbox_tree
      numeric_precision: null
      numeric_scale: null
      table: tree
    type: csv
  - collection: tree
    field: id
    meta:
      collection: tree
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      data_type: integer
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      table: tree
    type: integer
relations:
  - collection: model_a_model_b
    field: model_a_id
    meta:
      junction_field: model_b_id
      many_collection: model_a_model_b
      many_field: model_a_id
      one_allowed_collections: null
      one_collection: model_a
      one_collection_field: null
      one_deselect_action: nullify
      one_field: m2m_b
      sort_field: null
    related_collection: model_a
    schema:
      column: model_a_id
      constraint_name: null
      foreign_key_column: id
      foreign_key_table: model_a
      on_delete: SET NULL
      on_update: NO ACTION
      table: model_a_model_b
  - collection: model_a_model_b
    field: model_b_id
    meta:
      junction_field: model_a_id
      many_collection: model_a_model_b
      many_field: model_b_id
      one_allowed_collections: null
      one_collection: model_b
      one_collection_field: null
      one_deselect_action: nullify
      one_field: m2m_a
      sort_field: null
    related_collection: model_b
    schema:
      column: model_b_id
      constraint_name: null
      foreign_key_column: id
      foreign_key_table: model_b
      on_delete: SET NULL
      on_update: NO ACTION
      table: model_a_model_b
```

</details>

Note: This was fixed in #12723, but could be a regression from other snapshot related PRs afterwards.
