### ISSUE TITLE
Permission Field Preset for M2O field with Dynamic Variable

### ISSUE THREAD

**Issue by piotr-cz** [directus/directus#14315]
### Describe the Bug

I'm not able to use *Dynamic Variable* as a default M2O field value with *Custom Role > Collection > Read > Field Preset*

Related Issue: #13806 and PR: #13830 (not resolved for M2O field types)

### To Reproduce

1. Create new Data Model: *Organisations*
1. Create new Data Model: *News* with field *organisation*, Many to One Relationship, Related Collection: Organisations
1. Create new field for `directus_users`: *organisation*, Many to One Relationship, Related Collection: Organisations
1. Create new Role: Manager with App Access: Enabled, Admin Access: Disabled
1. Set *Create* Permissions for News to *Use Custom*
1. Set Field Presets to
   ```json
   {
       "organisation": "$CURRENT_USER.organisation"
   }
   ```
1. Create new User with *Manger* role and log in
1. Go to Content > News > Create Item
1. The Organisation field is not filled in with value of `$CURRENT_USER.organisation`

### Errors Shown

none

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This is a slightly tricky one. As mentioned in https://github.com/directus/directus/pull/13830#issuecomment-1170405064, there is no error because it is _technically_ working now, but it's doesn't have the `organisation` field in the user store.


## What's happening

Just to share more detail, the **App** side parsing of presets passes `currentUser` as `$CURRENT_USER` to the shared parsePreset function:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/app/src/utils/parse-preset.ts#L16-L19

and `currentUser` is grabbed from the user store:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/app/src/utils/parse-preset.ts#L6

However as `currentUser` had only fetched the following fields:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/app/src/stores/user.ts#L37-L51

When it tries to do `get()` lodash function here, it couldn't find `organisation` hence defaulting to the `null` value:

https://github.com/directus/directus/blob/7ad51b29254e37b569cfe08e522d37115977b604/packages/shared/src/utils/parse-filter.ts#L88-L91

## Example of it working after adding `organisation` field to the user store on hydrate

https://user-images.githubusercontent.com/42867097/177925696-ff02facb-906a-4be4-a384-939b55f66b6d.mp4

## Schema snapshot for easier reproduction

<details>
<summary>schema.yaml</summary>

```yaml
version: 1
directus: 9.13.0
collections:
  - collection: news
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: news
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: news
      schema: public
  - collection: organisations
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: organisations
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: organisations
      schema: public
fields:
  - collection: directus_users
    field: organisation
    meta:
      collection: directus_users
      conditions: null
      display: null
      display_options: null
      field: organisation
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisations
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: organisation
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: directus_users
    type: integer
  - collection: news
    field: id
    meta:
      collection: news
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('news_id_seq'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: news
    type: integer
  - collection: news
    field: organisation
    meta:
      collection: news
      conditions: null
      display: null
      display_options: null
      field: organisation
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisations
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: organisation
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: news
    type: integer
  - collection: organisations
    field: id
    meta:
      collection: organisations
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('organisations_id_seq'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: organisations
    type: integer
  - collection: organisations
    field: name
    meta:
      collection: organisations
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisations
    type: string
relations:
  - collection: directus_users
    field: organisation
    meta:
      junction_field: null
      many_collection: directus_users
      many_field: organisation
      one_allowed_collections: null
      one_collection: organisations
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: organisations
    schema:
      column: organisation
      constraint_name: directus_users_organisation_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisations
      on_delete: SET NULL
      on_update: NO ACTION
      table: directus_users
  - collection: news
    field: organisation
    meta:
      junction_field: null
      many_collection: news
      many_field: organisation
      one_allowed_collections: null
      one_collection: organisations
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: organisations
    schema:
      column: organisation
      constraint_name: news_organisation_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisations
      on_delete: SET NULL
      on_update: NO ACTION
      table: news
```

</details>
