### ISSUE TITLE
GraphQL error `Definition object should contain 'type' property`

### ISSUE THREAD

**Issue by fballan93** [directus/directus#14491]
### Describe the Bug

after upgrading to 9.14.1 from 9.6.0 i wanted to test insights 2.0 and it keep giving me an error and wont save 

### To Reproduce

- Upgraded my Directus from 9.6.0 to 9.14.1 (Insights was working with 9.6.0) 
- run migration script 
- login
- create a time series panel (in Insights)
- select created date as date value 
- aggregation is using "Sum"
- value is "departments" which is another collection . so in my "incidents" collection a person can select a "department" and department is M2M in my "incidents" collection 
- upon saving i receive the error below 

### Errors Shown

2022-07-18T12:35:32.658493989Z 12:35:32 ✨ request completed PATCH 204 /users/me/track/page 67ms

2022-07-18T12:36:22.666921548Z 12:36:22 🚨 TypeError[employee.id]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] }) 

2022-07-18T12:36:22.666976649Z Error: TypeError[employee.id]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })

2022-07-18T12:36:22.666985749Z     at TypeMapper.convertOutputFieldConfig (/node_modules/graphql-compose/lib/TypeMapper.js:230:27)

2022-07-18T12:36:22.667001049Z     at ObjectTypeComposer.setField (/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)

2022-07-18T12:36:22.667005549Z     at /node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18

2022-07-18T12:36:22.667009849Z     at Array.forEach (<anonymous>)

2022-07-18T12:36:22.667014649Z     at ObjectTypeComposer.addFields (/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)

2022-07-18T12:36:22.667018849Z     at getTypes (/node_modules/directus/dist/services/graphql/index.js:336:105)

2022-07-18T12:36:22.667022949Z     at getReadableTypes (/node_modules/directus/dist/services/graphql/index.js:395:62)

2022-07-18T12:36:22.667026949Z     at GraphQLService.getSchema (/node_modules/directus/dist/services/graphql/index.js:122:41)

2022-07-18T12:36:22.667030949Z     at GraphQLService.execute (/node_modules/directus/dist/services/graphql/index.js:79:29)

2022-07-18T12:36:22.667035049Z     at /node_modules/directus/dist/controllers/graphql.js:27:40

2022-07-18T12:36:22.671571172Z 12:36:22 ✨ request errored POST 500 /graphql 70ms

2022-07-18T12:36:23.449759367Z 12:36:23 ✨ request completed PATCH 204 /users/me/track/page 41ms

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

node:14-lts_20220309

### What database are you using?

Azure MySQL

### What browser are you using?

Chrome , Safari 

### How are you deploying Directus?

Azure App Services

**Comment by rijkvanzanten** [comment]
Could you share a database dump or a schema snapshot of the database where this is happening? It looks like there's some typing issue in the GraphQL endpoint for your particular schema 🤔

**Comment by fballan93** [comment]
> 

I would feel more comfortable sharing a dump via email . can you direct me to where i should send it ?

**Comment by rijkvanzanten** [comment]
No prob! You can send it to rijk@directus.io

**Comment by fballan93** [comment]
Any update on this or it is an isolated issue ?

**Comment by rijkvanzanten** [comment]
> Any update on this or it is an isolated issue ?

Don't know yet 👍🏻

**Comment by eslym** [comment]
I am now facing a similar issue, the graphql suddenly broken after i restart directus
```
23:09:54 🚨 TypeError[directus_users.avatar]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })
Error: TypeError[directus_users.avatar]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })
    at TypeMapper.convertOutputFieldConfig (/usr/local/share/.config/yarn/global/node_modules/graphql-compose/lib/TypeMapper.js:230:27)
    at ObjectTypeComposer.setField (/usr/local/share/.config/yarn/global/node_modules/graphql-compose/lib/ObjectTypeComposer.js:162:46)
    at /usr/local/share/.config/yarn/global/node_modules/graphql-compose/lib/ObjectTypeComposer.js:168:18
    at Array.forEach (<anonymous>)
    at ObjectTypeComposer.addFields (/usr/local/share/.config/yarn/global/node_modules/graphql-compose/lib/ObjectTypeComposer.js:167:32)
    at getTypes (/usr/local/share/.config/yarn/global/node_modules/directus/dist/services/graphql/index.js:340:105)
    at getReadableTypes (/usr/local/share/.config/yarn/global/node_modules/directus/dist/services/graphql/index.js:399:62)
    at GraphQLService.getSchema (/usr/local/share/.config/yarn/global/node_modules/directus/dist/services/graphql/index.js:124:41)
    at GraphQLService.execute (/usr/local/share/.config/yarn/global/node_modules/directus/dist/services/graphql/index.js:81:29)
    at /usr/local/share/.config/yarn/global/node_modules/directus/dist/controllers/graphql.js:27:40
23:09:54 ✨ request errored POST 500 /graphql 15ms
```
This is a db i use for play around with directus, so i just share the schema snapshot here
```yaml
version: 1
directus: 9.15.1
collections:
  - collection: comments
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: comments
      color: null
      display_template: null
      group: posts
      hidden: false
      icon: mode_comment
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: comments
      schema: directus
  - collection: posts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: posts
      color: null
      display_template: null
      group: null
      hidden: false
      icon: article
      item_duplication_fields: null
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: posts
      schema: directus
fields:
  - collection: comments
    field: content
    meta:
      collection: comments
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-multiline
      note: null
      options: null
      readonly: false
      required: true
      sort: 7
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: content
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: text
  - collection: comments
    field: date_created
    meta:
      collection: comments
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: timestamp
  - collection: comments
    field: date_updated
    meta:
      collection: comments
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 5
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: timestamp
  - collection: comments
    field: id
    meta:
      collection: comments
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: uuid
  - collection: comments
    field: name
    meta:
      collection: comments
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: string
  - collection: comments
    field: post_id
    meta:
      collection: comments
      conditions: null
      display: related-values
      display_options:
        template: "{{title}} ({{user_created.first_name}}\_{{user_created.last_name}})"
      field: post_id
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: "{{title}} ({{user_created.first_name}}\_{{user_created.last_name}})"
      readonly: true
      required: true
      sort: 2
      special:
        - m2o
      translations: null
      validation:
        _and:
          - _and:
              - post_id:
                  _nnull: true
              - post_id:
                  _nempty: true
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: posts
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: post_id
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: string
  - collection: comments
    field: status
    meta:
      collection: comments
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            background: var(--primary)
            foreground: '#FFFFFF'
          - text: $t:draft
            value: draft
            background: '#D3DAE4'
            foreground: '#18222F'
          - text: $t:archived
            value: archived
            background: var(--warning)
            foreground: '#FFFFFF'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: draft
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      table: comments
    type: string
  - collection: directus_users
    field: nickname
    meta:
      collection: directus_users
      conditions: null
      display: null
      display_options: null
      field: nickname
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: nickname
      numeric_precision: null
      numeric_scale: null
      table: directus_users
    type: string
  - collection: posts
    field: comments
    meta:
      collection: posts
      field: comments
      special:
        - o2m
      interface: list-o2m
      options:
        template: "{{name}}:\_{{content}}"
        enableCreate: false
        enableSelect: false
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: 7
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
      validation: null
      validation_message: null
    schema: null
    type: alias
  - collection: posts
    field: content
    meta:
      collection: posts
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-rich-text-md
      note: null
      options: null
      readonly: false
      required: true
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: content
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: text
  - collection: posts
    field: date_created
    meta:
      collection: posts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 8
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: timestamp
  - collection: posts
    field: date_published
    meta:
      collection: posts
      conditions: null
      display: null
      display_options: null
      field: date_published
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: datetime
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_published
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: dateTime
  - collection: posts
    field: date_updated
    meta:
      collection: posts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 10
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: timestamp
  - collection: posts
    field: id
    meta:
      collection: posts
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: 36
      name: id
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: uuid
  - collection: posts
    field: status
    meta:
      collection: posts
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            background: var(--primary)
            foreground: '#FFFFFF'
          - text: $t:draft
            value: draft
            background: '#D3DAE4'
            foreground: '#18222F'
          - text: $t:archived
            value: archived
            background: var(--warning)
            foreground: '#FFFFFF'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: draft
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: string
  - collection: posts
    field: title
    meta:
      collection: posts
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: title
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: string
  - collection: posts
    field: user_created
    meta:
      collection: posts
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 3
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_created
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: string
  - collection: posts
    field: user_updated
    meta:
      collection: posts
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 9
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      table: posts
    type: string
relations:
  - collection: comments
    field: post_id
    meta:
      junction_field: null
      many_collection: comments
      many_field: post_id
      one_allowed_collections: null
      one_collection: posts
      one_collection_field: null
      one_deselect_action: nullify
      one_field: comments
      sort_field: null
    related_collection: posts
    schema:
      column: post_id
      constraint_name: comments_post_id_foreign
      foreign_key_column: id
      foreign_key_table: posts
      on_delete: CASCADE
      on_update: NO ACTION
      table: comments
  - collection: posts
    field: user_created
    meta:
      junction_field: null
      many_collection: posts
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: posts_user_created_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: posts
  - collection: posts
    field: user_updated
    meta:
      junction_field: null
      many_collection: posts
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: posts_user_updated_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: posts
```
