### ISSUE TITLE
Searching for large Numbers throws Integer out of range Error

### ISSUE THREAD

**Issue by funkhaus-phil** [directus/directus#14638]
### Describe the Bug

Hello, i stumbled upon a Problem while trying to search for some Ticket Numbers in Directus.

To Explain whats going on..: 
- Collection tickets
- tickets.ticket_number is primary key and also a manual string
- ticket numbers are 13 digits long at least

Is it possible to handle digits in the search bar as strings instead of integers?
Thank you for your time and great work!
Greetings, Philipp

### To Reproduce

When we search for such a number via copy and paste in the Content --> Collection --> Search Bar (remember 13 digits at least) the result is as if we didn't search at all.
When we remove 4 - 5 digits from the search we find a somewhat useful search result.
Adding back some digits after that and even going a little further, then throws the "is out of range for type integer" error.

### Errors Shown

```json
{
  "errors": [
    {
      "message": "select \"tickets\".\"ticket_number\", \"tickets\".\"personalized\", \"tickets\".\"title\", \"tickets\".\"festival\" from \"tickets\" where (LOWER(\"tickets\".\"ticket_number\") LIKE $1 or LOWER(\"tickets\".\"title\") LIKE $2 or (\"tickets\".\"festival\" = $3) or LOWER(\"tickets\".\"paylogic_id\") LIKE $4) order by \"tickets\".\"personalized\" desc limit $5 - value \"0000000000000\" is out of range for type integer",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker via Caprover

**Comment by SabrinaZhuang** [comment]
I have the same  problem with searching the large number string like 1234567890123.
`GET ?search=1234567890123`

```
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

**Comment by azrikahar** [comment]
I can't seem to reproduce this issue on the latest version `9.16.1` with PostgreSQL 14.4, and with a collection that has a large number as a manual primary key:

https://user-images.githubusercontent.com/42867097/187849505-c4c54385-0cee-4ec4-b621-9356a0667ee2.mp4

As well as using a separate client and make the same GET request with `search` query param:

https://user-images.githubusercontent.com/42867097/187850122-384859c2-a5e2-43f6-851a-811a37172438.mp4

Schema snapshot of my test above:

<details>
<summary>schema.yaml</summary>

```yaml
version: 1
directus: 9.16.1
collections:
  - collection: tickets
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: tickets
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: tickets
      schema: public
fields:
  - collection: tickets
    field: description
    meta:
      collection: tickets
      conditions: null
      display: null
      display_options: null
      field: description
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: description
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: tickets
    type: string
  - collection: tickets
    field: id
    meta:
      collection: tickets
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: 255
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: tickets
    type: string
relations: []
```
</details>

Closing this for now, but happy to re-open if this is still reproducible and when a working minimal reproduction steps is provided 👍
