### ISSUE TITLE
Oracle DB - Segmentation fault at Initializing bootstrap

### ISSUE THREAD

**Issue by efonte** [directus/directus#14674]
### Describe the Bug

When starting a custom docker image of directus with the oracle client it fails in the startup process with a segmentation fault.

If I change port 1521 to another port (e.g. 5521) it shows the error ORA-12541: TNS:no listener.

### To Reproduce

docker-compose.yml
```yml
version: '3'
services:
  database:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: 'directus'
      APP_USER: 'directus'
      APP_USER_PASSWORD: 'directus'
      ORACLE_DATABASE: 'directus'
    shm_size: '1gb'

  directus:
    build:
      context: .
      dockerfile: directus.dockerfile
    ports:
      - 8055:8055
    depends_on:
      - database
    environment:
      KEY: 'directus'
      SECRET: 'directus'

      DB_CLIENT: 'oracledb'
      DB_HOST: 'database'
      DB_PORT: '1521'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      ADMIN_EMAIL: 'directus@example.com'
      ADMIN_PASSWORD: 'directus'
```

directus.dockerfile
```Dockerfile
FROM directus/directus:latest

USER root

RUN apk --no-cache add libaio libnsl libc6-compat curl && \
    curl -o instantclient-basiclite.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -SL && \
    unzip instantclient-basiclite.zip && \
    mv instantclient*/ /usr/lib/instantclient && \
    rm instantclient-basiclite.zip && \
    ln -s /usr/lib/instantclient/libclntsh.so.21.1 /usr/lib/libclntsh.so && \
    ln -s /usr/lib/instantclient/libocci.so.21.1 /usr/lib/libocci.so && \
    ln -s /usr/lib/instantclient/libociicus.so /usr/lib/libociicus.so && \
    ln -s /usr/lib/instantclient/libnnz21.so /usr/lib/libnnz21.so && \
    ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
    ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2 && \
    npm install oracledb

ENV LD_LIBRARY_PATH /usr/lib/instantclient

```

### Errors Shown

Default port 1521:
```
❯ docker-compose up directus
directus_oracle_database_1 is up-to-date
Recreating directus_oracle_directus_1 ... done
Attaching to directus_oracle_directus_1
directus_1  | 15:44:16 ✨ Initializing bootstrap...
directus_1  | Segmentation fault
directus_oracle_directus_1 exited with code 139
```

Custom port (e.g. 5521):
```
❯ docker-compose up directus
directus_oracle_database_1 is up-to-date
Recreating directus_oracle_directus_1 ... done
Attaching to directus_oracle_directus_1
directus_1  | 15:48:45 ✨ Initializing bootstrap...
directus_1  | 15:49:10 🚨 Can't connect to the database.
directus_1  | 15:49:10 🚨 ORA-12541: TNS:no listener 
directus_1  | Error: ORA-12541: TNS:no listener
directus_oracle_directus_1 exited with code 1
```

### What version of Directus are you using?

latest (9.14.5)

### What version of Node.js are you using?

16-alpine

### What database are you using?

Oracle XE 21

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker
