### ISSUE TITLE
Schema apply attempts to delete collection(s) when re-applying the same snapshot from a different database vendor

### ISSUE THREAD

**Issue by azrikahar** [directus/directus#14687]
### Describe the Bug

First investigation: https://github.com/directus/directus/issues/13383#issuecomment-1191238970
Second investigation: https://github.com/directus/directus/issues/14677#issuecomment-1196331207

When we have a schema snapshot from a SQLite for example, applying on a Postgres database works on the first time. However when we re-apply it again without changing anything, it will mark collections for deletion, when it should say "No changes to apply." instead.

This is not specific to SQLite -> Postgres, but happens between any database vendors as their collections' "schema" is different (refer the first investigation result).

### To Reproduce

1. Apply the following minimal SQLite snapshot on a fresh Postgres database:

    ```yaml
    version: 1
    directus: 9.14.5
    collections:
      - collection: a
        meta:
          accountability: all
          archive_app_filter: true
          archive_field: null
          archive_value: null
          collapse: open
          collection: a
          color: null
          display_template: null
          group: null
          hidden: false
          icon: null
          item_duplication_fields: null
          note: null
          singleton: false
          sort: null
          sort_field: null
          translations: null
          unarchive_value: null
        schema:
          name: a
          sql: CREATE TABLE `a` (`id` integer not null primary key autoincrement)
    fields:
      - collection: a
        field: id
        meta:
          collection: a
          conditions: null
          display: null
          display_options: null
          field: id
          group: null
          hidden: true
          interface: input
          note: null
          options: null
          readonly: true
          required: false
          sort: null
          special: null
          translations: null
          validation: null
          validation_message: null
          width: full
        schema:
          data_type: integer
          default_value: null
          foreign_key_column: null
          foreign_key_table: null
          generation_expression: null
          has_auto_increment: true
          is_generated: false
          is_nullable: false
          is_primary_key: true
          is_unique: false
          max_length: null
          name: id
          numeric_precision: null
          numeric_scale: null
          table: a
        type: integer
    relations: []
    ```

2. It should apply it successfully, as shown here:

   ![WindowsTerminal_CrYJqgkJ6a](https://user-images.githubusercontent.com/42867097/181178192-0b516bb6-bf7c-442c-8cf0-eeb0dcbadaa1.png)

3. However when we re-apply the exact same schema again, it's trying to delete collections (which should not happen):

   ![WindowsTerminal_iGHUM4HN7Q](https://user-images.githubusercontent.com/42867097/181178438-003578b4-ea3a-46cd-a0fd-992edf43ecfc.png)

When we inspect the `snapshotDiff.collections` in apply-snapshot, we'll see:

```json
[
    {
        "collection": "a",
        "diff": [
            {
                "kind": "D",
                "path": [
                    "schema",
                    "comment"
                ],
                "lhs": null
            },
            {
                "kind": "D",
                "path": [
                    "schema",
                    "schema"
                ],
                "lhs": "public"
            },
            {
                "kind": "N",
                "path": [
                    "schema",
                    "sql"
                ],
                "rhs": "CREATE TABLE `a` (`id` integer not null primary key autoincrement)"
            }
        ]
    }
]
```

### Errors Shown

```
14:33:54 🚨 Cannot read properties of null (reading 'meta')
TypeError: Cannot read properties of null (reading 'meta')
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-snapshot.ts:136:84
    at Array.filter (<anonymous>)
    at C:\Users\Azri\Documents\Projects\directus\api\src\utils\apply-snapshot.ts:135:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What version of Directus are you using?

9.14.5 main branch (https://github.com/directus/directus/commit/263ee74408a52fe6d302a004e38dd16d6e6e4055)

### What version of Node.js are you using?

16.15.1

### What database are you using?

PostgreSQL 13.5

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally
