### ISSUE TITLE
Adding a new O2M relation through a schema file causes error

### ISSUE THREAD

**Issue by wodka** [directus/directus#15322]
### Describe the Bug

we have a simple table and want to add a new O2M relation. This works fine in the UI and also generates a good schema yml. When trying to apply the schema it will fail.

based on the debug output I can see that does add the field prior to trying to add the relation:

```
  knex:query SAVEPOINT trx29; trx29 +20ms
  knex:query alter table "snippet" add column "condition" uuid null default null trx29 +2ms
  knex:query SAVEPOINT trx30; trx30 +41ms
  knex:query insert into "directus_fields" ("collection", "conditions", "display", "display_options", "field", "group", "hidden", "interface", "note", "options", "readonly", "required", "sort", "special", "translations", "validation", "validation_message", "width") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) returning "id" trx30 +1ms
  knex:query RELEASE SAVEPOINT trx30; trx30 +15ms
  knex:query RELEASE SAVEPOINT trx29; trx30 +2ms
```

after that it will fail in https://github.com/directus/directus/blob/main/api/src/services/relations.ts#L140 - with `this.schema.collections[relation.collection].fields` not containing the field that was inserted a few milliseconds earlier.

Not sure how the collection entry is being updated / cached.

### To Reproduce

1. Create 2 tables
2. create snapshot file and save it as sn1.yml
3. add O2M relation to one table
4. create snapshot file and save it as sn2.yml
5. drop all tables and now apply sn1.yml
6. then apply sn2.yml and see error happening.

### Errors Shown

```
16:51:24 🚨 Failed to create relation "snippet.condition"
16:51:24 🚨 Field "condition" doesn't exist in collection "snippet" 
Error: Field "condition" doesn't exist in collection "snippet"
    at RelationsService.createOne (/node_modules/directus/dist/services/relations.js:147:19)
    at /node_modules/directus/dist/utils/apply-snapshot.js:191:44
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

CRDB

### What browser are you using?

-

### How are you deploying Directus?

locally

**Comment by wodka** [comment]
my not so optimal fix for this would be to load the schema the last time before https://github.com/directus/directus/blob/b2d127dcc87553ce4cec3a0ac6ee9e400e4cc738/api/src/utils/apply-snapshot.ts#L180 and then to update it with the new metadata fro the collections and pass it in as an argument to the releation service in https://github.com/directus/directus/blob/b2d127dcc87553ce4cec3a0ac6ee9e400e4cc738/api/src/utils/apply-snapshot.ts#L227

would that also make sense as a PR? for me it does work with applying the snapshot then!

```
17:53:05 ✨ Snapshot applied successfully
✨  Done in 63.03s.
```

**Comment by wodka** [comment]
my local solutuon as a patch file for the compiled source:

```patch
diff --git a/node_modules/directus/dist/utils/apply-snapshot.js b/node_modules/directus/dist/utils/apply-snapshot.js
index 117c7b0..3afe263 100644
--- a/node_modules/directus/dist/utils/apply-snapshot.js
+++ b/node_modules/directus/dist/utils/apply-snapshot.js
@@ -139,11 +140,16 @@ async function applySnapshot(snapshot, options) {
                 }
             }
         }
-        const fieldsService = new services_1.FieldsService({ knex: trx, schema: await (0, get_schema_1.getSchema)({ database: trx }) });
+
+        const schemaData = await (0, get_schema_1.getSchema)({ database: trx })
+
+        const fieldsService = new services_1.FieldsService({ knex: trx, schema: schemaData });
         for (const { collection, field, diff } of snapshotDiff.fields) {
             if ((diff === null || diff === void 0 ? void 0 : diff[0].kind) === 'N' && !isNestedMetaUpdate(diff === null || diff === void 0 ? void 0 : diff[0])) {
                 try {
                     await fieldsService.createField(collection, diff[0].rhs);
+
+                    schemaData.collections[collection].fields[diff[0].rhs.field] = diff[0].rhs.meta
                 }
                 catch (err) {
                     logger_1.default.error(`Failed to create field "${collection}.${field}"`);
@@ -179,7 +185,8 @@ async function applySnapshot(snapshot, options) {
                 snapshotDiff.relations = snapshotDiff.relations.filter((relation) => (relation.collection === collection && relation.field === field) === false);
             }
         }
-        const relationsService = new services_1.RelationsService({ knex: trx, schema: await (0, get_schema_1.getSchema)({ database: trx }) });
+
+        const relationsService = new services_1.RelationsService({ knex: trx, schema: schemaData });
         for (const { collection, field, diff } of snapshotDiff.relations) {
             const structure = {};
             for (const diffEdit of diff) {
```

**Comment by azrikahar** [comment]
@wodka thanks for the detailed write up and solution! I think this timing is very trippy, as I believe @licitdev in his herculean effort to test and update #14713 as we speak, pretty sure he faced the same issue recently as well 😄

We actually opted to add a bypassCache flag to getSchema and I believe he more and less added a fix for fieldsService and relationsService similar to what you did in this very recent commit: https://github.com/directus/directus/pull/14713/commits/ae18cca1e7c10e52dc801b589eee3e8e06e7991c! @licitdev just to confirm, am I understanding that commit correctly? If it is, then we should be able to mark this issue to be fixed by the same PR 👍

**Comment by wodka** [comment]
@azrikahar I just took a look at the bypassCache flag -> I think it cannot help in this case.

This problem stems from CRDB not returning the changed schema in the same transaction as it is doing schema changes in an async way. Therefore Caching is the solution I picked specifically for the addition of new columns (as they would otherwise not yet show up).

A prior attempt in trying to figure out what is happening was to also comment all the steps in get-schema to see if it is returning the correct data. Sadly with realising that all the querying is being done but the data is not yet available.

**Comment by azrikahar** [comment]
@wodka that makes sense 👍 @licitdev I think we'll need to find a common ground between this particular fix and the current changes/fixes in #14713 and verify it with the new schema tests.

**Comment by azrikahar** [comment]
@wodka would you be able to share the snapshots? Just to make sure we're testing the exact same thing on our end. You can also send it via email to `azri@directus.io` if that's preferred.

**Comment by wodka** [comment]
I created a small test case. It will create 2 tables and then the error case.

```
$ yarn directus schema apply ./step1.yml                      
yarn run v1.22.19
$ directus schema apply ./step1.yml
? The following changes will be applied:



Fields:
  - Delete example.row

Relations:
  - Delete example.row-> row

Would you like to continue? Yes
11:44:36 ✨ Snapshot applied successfully
✨  Done in 8.36s.

~/directus on  main! ⌚ 11:44:36
$ yarn directus schema apply ./step2.yml
yarn run v1.22.19
$ directus schema apply ./step2.yml
? The following changes will be applied:



Fields:
  - Create example.row

Relations:
  - Create example.row-> row

Would you like to continue? Yes
11:44:47 🚨 Failed to create relation "example.row"
11:44:47 🚨 Field "row" doesn't exist in collection "example" 
Error: Field "row" doesn't exist in collection "example"
    at RelationsService.createOne (/node_modules/directus/dist/services/relations.js:140:19)
    at /node_modules/directus/dist/utils/apply-snapshot.js:197:44
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## step1.yml

```yml
version: 1
directus: 9.16.1
collections:
  - collection: example
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: example
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: example
      schema: public
  - collection: row
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: row
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: row
      schema: public
fields:
  - collection: example
    field: id
    meta:
      collection: example
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: example
    type: uuid
  - collection: row
    field: id
    meta:
      collection: row
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: row
    type: uuid
relations: []
```

## step2.yml

```yml
version: 1
directus: 9.16.1
collections:
  - collection: example
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: example
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: example
      schema: public
  - collection: row
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: row
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: row
      schema: public
fields:
  - collection: example
    field: id
    meta:
      collection: example
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: example
    type: uuid
  - collection: example
    field: row
    meta:
      collection: example
      conditions: null
      display: null
      display_options: null
      field: row
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: row
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: row
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: example
    type: uuid
  - collection: row
    field: id
    meta:
      collection: row
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: row
    type: uuid
relations:
  - collection: example
    field: row
    meta:
      junction_field: null
      many_collection: example
      many_field: row
      one_allowed_collections: null
      one_collection: row
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: row
    schema:
      column: row
      constraint_name: example_row_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: row
      on_delete: SET NULL
      on_update: NO ACTION
      table: example
```
