### ISSUE TITLE
Fatal Error: Class "Twig Extension" not found

### ISSUE THREAD

**Issue by nathanaelphilip** [directus/directus#1595]
## Version Info
  - Directus version and branch: 6.3.9 / master
  - PHP version: 7.1
  - MySQL version: 5.6
  - Web server: Apache
  - OS name and version: MacOS

## Expected Behavior
Trying to get to installation screen

## Actual Behavior
Received this: Fatal error: Class 'Twig_Extension' not found in /app/installation/includes/Extensions/DirectusTwigHelpers.php on line 12

## Steps to Reproduce
 1. Followed instructions here: https://docs.getdirectus.com/6.3.6/#What_is_Directus?

**Comment by WellingGuzman** [comment]
Hey @nathanaelphilip, you have to install the composer dependencies by running `composer install`, if you don't want or can't run `composer` use the `build` branch.

**Comment by WellingGuzman** [comment]
We are going to make these steps clear on the documentation soon.

**Comment by nathanaelphilip** [comment]
hi, i did run that:

```
LICENSE.md    boxfile.yml   gulpfile.js   main.html     runtests.sh
api           composer.json index.php     package.json  storage
app           composer.lock installation  phpunit.php   tests
assets        customs       karma.conf.js phpunit.xml   vendor
bin           gpl.md        login.php     readme.md
```

**Comment by nathanaelphilip** [comment]
I’m using my global version of composer to do the install – would that make a difference?

**Comment by nathanaelphilip** [comment]
i see the Twig directory in the `vendor` directory:

![screen shot 2017-06-17 at 7 17 59 pm](https://user-images.githubusercontent.com/380034/27256889-b431d292-5391-11e7-90a5-613d82aaea43.png)

**Comment by WellingGuzman** [comment]
And still happening? Do you have any full php logs?

**Comment by nathanaelphilip** [comment]
Yep, still happening. The logs just show the error above. I just ran `class HELLO extends Twig_Extension{}` right after the `require $vendorAutoload` in `installation/boostrap.php` and it’s still throwing the error. It’s like it’s not getting loaded at all.

i am using `nanobox.io`, which runs it in a VM, but it’s no different than using Vagrant – i believe.

**Comment by WellingGuzman** [comment]
I've never used nanobox, but I don't think this would make any difference in loading the autoloader.

What's the setup of your nanobox?

**Comment by nathanaelphilip** [comment]
here’s my boxfile.yml: 

```
run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    display_errors: true
    extensions:
      - gd
      - mysqli
      - curl
      - zlib
      - mbstring
      - xml
      - session
```

and my root directory:

![screen shot 2017-06-19 at 7 57 20 am](https://user-images.githubusercontent.com/380034/27284022-f755e48a-54c4-11e7-948a-1ecd9ad1d26a.png)

**Comment by jksimoniii** [comment]
@nathanaelphilip 

Twig [1.x](https://twig.sensiolabs.org/doc/1.x/intro.html) does not claim support for PHP 7+ while Twig [2.x](https://twig.sensiolabs.org/doc/2.x/intro.html) requires PHP  >= 7.0.0.

I would suspect this as the issue.  You could bump `twig/twig` dependency in `composer.json` to `2.x` to see if it gets rid of that error.

But, it would probably be safer to not run on PHP 7 without vetting other dependency compatibility with PHP 7.

**Comment by nathanaelphilip** [comment]
@jksimoniii i’ll try that. thank you kind stranger.

**Comment by nathanaelphilip** [comment]
@jksimoniii i updated to 2.x and ran `composer update`, but i still get the same error. i’m going to see if other classes are able to load.

**Comment by nathanaelphilip** [comment]
i was missing some php extensions for my nanobox setup:
this is what I’m using, incase anyone else needs it.
```
run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    display_errors: true
    extensions:
      - gd
      - mysqli
      - curl
      - zlib
      - mbstring
      - xml
      - session
      - tokenizer
      - ctype
      - dom
      - pdo
      - fileinfo
      - pdo_mysql
```
