### ISSUE TITLE
API returns twice items in a relation array

### ISSUE THREAD

**Issue by mlbiche** [directus/directus#16554]
### Describe the Bug

In some specific combination of relations and permissions (see To reproduce section), the API returns an incorrect relation array for a O2M relation, where each item appears twice.

### To Reproduce

I could reproduce the issue with the following steps (sorry, it is the most minimal setup I could find):

1. Following [local installation steps](https://docs.directus.io/self-hosted/quickstart.html#_1-installation)
2. Applying the following snapshot:
<details>
<summary>snapshot.yml</summary>

```yml
version: 1
directus: 9.21.0
collections:
  - collection: benefeciary
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: benefeciary
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: benefeciary
      schema: public
  - collection: benefeciary_directus_users
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: benefeciary_directus_users
      color: null
      display_template: null
      group: null
      hidden: true
      icon: import_export
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: benefeciary_directus_users
      schema: public
  - collection: organisation
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: organisation
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: organisation
      schema: public
  - collection: relative
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: relative
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
    schema:
      comment: null
      name: relative
      schema: public
fields:
  - collection: benefeciary
    field: date_created
    meta:
      collection: benefeciary
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary
    type: timestamp
  - collection: benefeciary
    field: date_updated
    meta:
      collection: benefeciary
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary
    type: timestamp
  - collection: benefeciary
    field: id
    meta:
      collection: benefeciary
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary
    type: uuid
  - collection: benefeciary
    field: referents
    meta:
      collection: benefeciary
      conditions: null
      display: null
      display_options: null
      field: referents
      group: null
      hidden: false
      interface: list-m2m
      note: null
      options:
        enableCreate: false
      readonly: false
      required: false
      sort: null
      special:
        - m2m
      translations: null
      validation: null
      validation_message: null
      width: full
    schema: null
    type: alias
  - collection: benefeciary
    field: relatives
    meta:
      collection: benefeciary
      conditions: null
      display: null
      display_options: null
      field: relatives
      group: null
      hidden: false
      interface: list-o2m
      note: null
      options:
        template: '{{name}}'
      readonly: false
      required: false
      sort: null
      special:
        - o2m
      translations: null
      validation: null
      validation_message: null
      width: full
    schema: null
    type: alias
  - collection: benefeciary
    field: user_created
    meta:
      collection: benefeciary
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary
    type: uuid
  - collection: benefeciary
    field: user_updated
    meta:
      collection: benefeciary
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary
    type: uuid
  - collection: benefeciary_directus_users
    field: benefeciary_id
    meta:
      collection: benefeciary_directus_users
      conditions: null
      display: null
      display_options: null
      field: benefeciary_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: benefeciary
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: benefeciary_id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary_directus_users
    type: uuid
  - collection: benefeciary_directus_users
    field: directus_users_id
    meta:
      collection: benefeciary_directus_users
      conditions: null
      display: null
      display_options: null
      field: directus_users_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: directus_users_id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: benefeciary_directus_users
    type: uuid
  - collection: benefeciary_directus_users
    field: id
    meta:
      collection: benefeciary_directus_users
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: integer
      default_value: nextval('benefeciary_directus_users_id_seq'::regclass)
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: 32
      numeric_scale: 0
      schema: public
      table: benefeciary_directus_users
    type: integer
  - collection: directus_users
    field: organisation
    meta:
      collection: directus_users
      conditions: null
      display: null
      display_options: null
      field: organisation
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
        template: '{{name}}'
      readonly: false
      required: false
      sort: null
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisation
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: organisation
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: directus_users
    type: uuid
  - collection: organisation
    field: date_created
    meta:
      collection: organisation
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: timestamp
  - collection: organisation
    field: date_updated
    meta:
      collection: organisation
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: timestamp
  - collection: organisation
    field: id
    meta:
      collection: organisation
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: uuid
  - collection: organisation
    field: name
    meta:
      collection: organisation
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: string
  - collection: organisation
    field: user_created
    meta:
      collection: organisation
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: uuid
  - collection: organisation
    field: user_updated
    meta:
      collection: organisation
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: organisation
    type: uuid
  - collection: relative
    field: beneficiary
    meta:
      collection: relative
      conditions: null
      display: null
      display_options: null
      field: beneficiary
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: benefeciary
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: beneficiary
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: uuid
  - collection: relative
    field: date_created
    meta:
      collection: relative
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: timestamp
  - collection: relative
    field: date_updated
    meta:
      collection: relative
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: timestamp with time zone
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: timestamp
  - collection: relative
    field: id
    meta:
      collection: relative
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: null
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: true
      max_length: null
      name: id
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: uuid
  - collection: relative
    field: name
    meta:
      collection: relative
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: null
      data_type: character varying
      default_value: null
      foreign_key_column: null
      foreign_key_schema: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: name
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: string
  - collection: relative
    field: user_created
    meta:
      collection: relative
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_created
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: uuid
  - collection: relative
    field: user_updated
    meta:
      collection: relative
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: null
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: null
      data_type: uuid
      default_value: null
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      schema: public
      table: relative
    type: uuid
relations:
  - collection: benefeciary
    field: user_created
    meta:
      junction_field: null
      many_collection: benefeciary
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: benefeciary_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: benefeciary
  - collection: benefeciary
    field: user_updated
    meta:
      junction_field: null
      many_collection: benefeciary
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: benefeciary_user_updated_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: benefeciary
  - collection: benefeciary_directus_users
    field: benefeciary_id
    meta:
      junction_field: directus_users_id
      many_collection: benefeciary_directus_users
      many_field: benefeciary_id
      one_allowed_collections: null
      one_collection: benefeciary
      one_collection_field: null
      one_deselect_action: delete
      one_field: referents
      sort_field: null
    related_collection: benefeciary
    schema:
      column: benefeciary_id
      constraint_name: benefeciary_directus_users_benefeciary_id_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: benefeciary
      on_delete: CASCADE
      on_update: NO ACTION
      table: benefeciary_directus_users
  - collection: benefeciary_directus_users
    field: directus_users_id
    meta:
      junction_field: benefeciary_id
      many_collection: benefeciary_directus_users
      many_field: directus_users_id
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: directus_users_id
      constraint_name: benefeciary_directus_users_directus_users_id_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: benefeciary_directus_users
  - collection: directus_users
    field: organisation
    meta:
      junction_field: null
      many_collection: directus_users
      many_field: organisation
      one_allowed_collections: null
      one_collection: organisation
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: organisation
    schema:
      column: organisation
      constraint_name: directus_users_organisation_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: organisation
      on_delete: SET NULL
      on_update: NO ACTION
      table: directus_users
  - collection: organisation
    field: user_created
    meta:
      junction_field: null
      many_collection: organisation
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: organisation_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: organisation
  - collection: organisation
    field: user_updated
    meta:
      junction_field: null
      many_collection: organisation
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: organisation_user_updated_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: organisation
  - collection: relative
    field: beneficiary
    meta:
      junction_field: null
      many_collection: relative
      many_field: beneficiary
      one_allowed_collections: null
      one_collection: benefeciary
      one_collection_field: null
      one_deselect_action: nullify
      one_field: relatives
      sort_field: null
    related_collection: benefeciary
    schema:
      column: beneficiary
      constraint_name: relative_beneficiary_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: benefeciary
      on_delete: SET NULL
      on_update: NO ACTION
      table: relative
  - collection: relative
    field: user_created
    meta:
      junction_field: null
      many_collection: relative
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: relative_user_created_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: relative
  - collection: relative
    field: user_updated
    meta:
      junction_field: null
      many_collection: relative
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: relative_user_updated_foreign
      foreign_key_column: id
      foreign_key_schema: public
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: relative
```
</details>

In short terms, the database contains:

* an `Organisation` collection,
* a `Relative` collection,
* a `Beneficiary` collection,
* `Directus users` have a M2O relation to this collection. `Beneficiary` have a M2M relation to `Directus users` and a O2M relation to `Relative`

4. Adding a role with the following permissions:
<details>
<summary>Permissions dump</summary>

```sql
25	1c698b11-b901-4ba3-a503-018509689544	benefeciary	create	{}	{}	\N	*
26	1c698b11-b901-4ba3-a503-018509689544	benefeciary_directus_users	create	{}	{}	\N	*
27	1c698b11-b901-4ba3-a503-018509689544	relative	create	{}	{}	\N	*
28	1c698b11-b901-4ba3-a503-018509689544	benefeciary	read	{"_and":[{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}]}	\N	\N	id,user_created,date_created,user_updated,date_updated,referents,relatives
29	1c698b11-b901-4ba3-a503-018509689544	benefeciary	update	{"_and":[{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}]}	\N	\N	id,user_created,date_created,user_updated,date_updated,referents,relatives
30	1c698b11-b901-4ba3-a503-018509689544	benefeciary	delete	{"_and":[{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}]}	\N	\N	\N
31	1c698b11-b901-4ba3-a503-018509689544	benefeciary_directus_users	read	{"_and":[{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}]}	\N	\N	id,benefeciary_id,directus_users_id
33	1c698b11-b901-4ba3-a503-018509689544	benefeciary_directus_users	delete	{"_and":[{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}]}	\N	\N	\N
34	1c698b11-b901-4ba3-a503-018509689544	organisation	read	{"_and":[{"id":{"_eq":"$CURRENT_USER.organisation"}}]}	\N	\N	id,user_created,user_updated,date_updated,name,date_created
35	1c698b11-b901-4ba3-a503-018509689544	relative	read	{"_and":[{"beneficiary":{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}}]}	\N	\N	id,user_created,user_updated,date_updated,date_created,name,beneficiary
36	1c698b11-b901-4ba3-a503-018509689544	relative	update	{"_and":[{"beneficiary":{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}}]}	\N	\N	id,user_created,user_updated,date_updated,date_created,name,beneficiary
37	1c698b11-b901-4ba3-a503-018509689544	relative	delete	{"_and":[{"beneficiary":{"referents":{"directus_users_id":{"organisation":{"id":{"_eq":"$CURRENT_USER.organisation"}}}}}}]}	\N	\N	\N
```
(**NOTE**: `1c698b11-b901-4ba3-a503-018509689544` is the ID of my role)
</details>

In short terms, the whole permission system is based on the relation between the current user and the relation between `Organisation` and `Directus_users`:

* `Organisation` permissions are based on the relation between the current user and the `Organisation` collection
* `Beneficiary` permissions are based on its M2M relation with `Directus_users`, through the relation with `Organisation`
* `Relative` permissions are based on its M2O relation with `Beneficiary`, through the relation with `Directus_users` and then `Organisation`

6. Create 2 users with this new role
7. Log in with one of these users
8. Create a `Beneficiary` item related to the 2 new users and with a created relation with `Relative`

### Errors Shown

After the creation, the new `Beneficiary` item is shown with two relations to the same `Relative`
<img width="1440" alt="Capture d’écran 2022-11-21 à 10 47 30" src="https://user-images.githubusercontent.com/33522659/203018866-35d5367b-1649-401a-9585-a7859b4f7ec3.png">

But, when querying the database, only one item exists in the `Relative` collection.
The same issue happens when editing an existing `Beneficiary` and creating a new relation with `Relative`

The issue does not happen with administrator role, which makes me think it is related to roles and permissions.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

18.11.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome, Firefox

### How are you deploying Directus?

Running locally
