### ISSUE TITLE
Unable to upload bigger files

### ISSUE THREAD

**Issue by whis** [directus/directus#16589]
### Describe the Bug

I am deploying Directus using docker-compose (Nginx, Postgres, S3) and `MAX_PAYLOAD_SIZE` seems to be ignored for whatever reason. I tried to set the value to `100mb` and `100000000`, but in either case, I was unable to upload a file bigger than 1mb with the following error in the UI and no errors in the log.

**Unexpected Error**
`[UNKNOWN] Request failed with status code 413`

Further investigation showed that setting `MAX_PAYLOAD_SIZE` to `100kb` still allows uploading files of size up to 1MB. My assumption is that the default value is never overridden using the configuration from docker-compose.

### To Reproduce

Spin up the following _docker-compose.yml_ file and try uploading a file bigger than 1MB.

```yml
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      MAX_PAYLOAD_SIZE: '100mb'

networks:
  directus:
```

### Errors Shown

**Unexpected Error**
`[UNKNOWN] Request failed with status code 413`

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres 13

### What browser are you using?

Safari

### How are you deploying Directus?

Docker
