### ISSUE TITLE
Sendmail exited with code 1

### ISSUE THREAD

**Issue by podlomar** [directus/directus#16979]
### Describe the Bug

No matter what I try, I cannot send e-mails through SMTP relay from self-hosted Directus app, e.g. user invitations. Every time I get an error *Sendmail exited with code 1*

I am using adapted `docker-compose.yml` described in the [docker guide](https://docs.directus.io/self-hosted/installation/docker.html#docker-compose). Mine looks like this:

```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: 'xxx'
      SECRET: 'xxx'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      ADMIN_EMAIL: 'xxx'
      ADMIN_PASSWORD: 'xxx'

      PUBLIC_URL: 'xxx'

      EMAIL_FROM: 'noreply@xxx'
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: 'smtp.xxx'
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: 'xxx'
      EMAIL_SMTP_PASSWORD: 'xxx'
      EMAIL_SMTP_SECURE: false

networks:
  directus:
```

I am positive my SMTP relay works. This testing Node.js code correctly sends an email from the host machine:

```
const transporter = nodemailer.createTransport({
    host: "smtp.xxx",
    port: 587,
    secure: false,
    auth: {
      user: 'xxx',
      pass: 'xxx',
    },
  });

  const info = await transporter.sendMail({
    from: 'noreply@xxx',
    to: "my-personal-email@gmail.com",
    subject: "Hello ✔",
    text: "Hello world?",
    html: "<b>Hello world?</b>",
  });
```

### To Reproduce

1. Create a self-hosted instance with docker compose based on the above mentioned `docker-compose.yml`
2. From the Directus app send an invitation to any email address.

### Errors Shown

The Directus app shows

```
{
  "message": "Sendmail exited with code 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

Docker logs say only:

```
directus  | [21:55:28.060] ERROR: Sendmail exited with code 1
directus  |     err: {
directus  |       "type": "Error",
directus  |       "message": "Sendmail exited with code 1",
directus  |       "stack":
directus  |           Error: Sendmail exited with code 1
directus  |               at ChildProcess.<anonymous> (/directus/node_modules/nodemailer/lib/sendmail-transport/index.js:142:27)
directus  |               at Object.onceWrapper (node:events:628:26)
directus  |               at ChildProcess.emit (node:events:513:28)
directus  |               at ChildProcess._handle.onexit (node:internal/child_process:291:12)
directus  |     }
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

Whatever is inside docker image

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker
