### ISSUE TITLE
Secrets in Docker Compose aren't working correctly

### ISSUE THREAD

**Issue by SergioBlancoP** [directus/directus#17056]
### Describe the Bug

I was using secrets in Docker Compose like you explained in your [documentation](https://docs.directus.io/self-hosted/config-options.html). As you said in "Environment Variables File", environment variable values can be imported from a file, by appending _FILE... But I have tried that and it doesn't works.

### To Reproduce

My Docker Compose looks like this (the commented lines are possible things I would like to include): 
```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: 'directus'
    secrets:
      - db_password
      # - db_root_password

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055    
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'     
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      #DB_PASSWORD: 'aaa'
      DB_PASSWORD_FILE: /run/secrets/db_password
      ADMIN_EMAIL: 'admin@example.com'
      # ADMIN_EMAIL_FILE: /run/secrets/db_email
      ADMIN_PASSWORD: 'aaa'
      # ADMIN_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
     #- db_email
secrets:
  db_password:
    file: db_password.txt
  #db_email:
    #file: db_email.txt
  #db_root_password:
    #file: db_root_password.txt
networks:
  directus:
```
db_password.txt is a file with the password:
`aaa`

### Errors Shown

```
directus    | [11:43:08.897] ERROR: Can't connect to the database.
directus    | [11:43:08.897] ERROR: password authentication failed for user "directus"
directus    |     err: {
directus    |       "type": "DatabaseError",
directus    |       "message": "password authentication failed for user \"directus\"",
directus    |       "stack":
directus    |           error: password authentication failed for user "directus"
directus    |               at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus    |               at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus    |               at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus    |               at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus    |               at Socket.emit (node:events:513:28)
directus    |               at addChunk (node:internal/streams/readable:324:12)
directus    |               at readableAddChunk (node:internal/streams/readable:297:9)
directus    |               at Readable.push (node:internal/streams/readable:234:10)
directus    |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus    |       "length": 104,
directus    |       "name": "error",
directus    |       "severity": "FATAL",
directus    |       "code": "28P01",
directus    |       "file": "auth.c",
directus    |       "line": "331",
directus    |       "routine": "auth_failed"
directus    |     }
directus exited with code 1
```

### What version of Directus are you using?

latest

### What version of Node.js are you using?

-

### What database are you using?

Postgres 13-master

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment]
Secrets are only available for swarm services it looks like, are you running a docker swarm? https://docs.docker.com/engine/swarm/secrets/
> Note: Docker secrets are only available to swarm services, not to standalone containers. To use this feature, consider adapting your container to run as a service. Stateful containers can typically run with a scale of 1 without changing the container code.

**Comment by SergioBlancoP** [comment]
Yes, I have docker swarm running and I have the same problem. 

docker-stack.yml:
```
version: "3.8"
services:
    directus:
        image: directus/directus:latest
        ports:
            - target: 8055
              published: 8055
              mode: ingress
        deploy:
            replicas: 1
            resources:
                 limits:
                    cpus: '3'
                    memory: 4G
            restart_policy:
                condition: on-failure
        environment:
            KEY: '<key>'
            SECRET: '<secret>'
            DB_CLIENT: 'pg'
            DB_HOST: 'db'
            DB_PORT: '5432'
            DB_DATABASE: 'db'
            DB_USER: 'directus'
            DB_PASSWORD_FILE: '/run/secrets/password_database'
            ADMIN_EMAIL: 'admin@example.es'
            ADMIN_PASSWORD_FILE: '/run/secrets/password_admin'
        user: 1000:1001
        volumes:
            - directus_uploads:/directus/uploads
        secrets:
            - source: webnowo_database_pass_pro
              target: password_database
            - source: password_directus_admin_pro
              target: password_admin
        
          <other services>

```
Why Docker Compose in Swarm mode doesn't work? Why can I use "_FILE" in Postgres Database correctly but inside the Directus part not? So... If you could show me an example where "_FILE" works or if you could try my code, I would appreciate it.
