### ISSUE TITLE
Docker SIGKILL after second login

### ISSUE THREAD

**Issue by ixsunoff** [directus/directus#17510]
### Describe the Bug

I have a problem with Directus, installed via Docker-Compose file.

**Scenario:**
1. Login
2. Logout
3. Login again

After that I get an error in the login window with the text "unexpected error" (the error text may be different because it was translated). Directus container reloading with SIGKILL signal (logs are provided).

### **Compose file (with deleted credentials):**
```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: '***'
      POSTGRES_PASSWORD: '***'
      POSTGRES_DB: '***'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    restart: always
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '***'
      SECRET: '***'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: '***'
      DB_PASSWORD: '***'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '***'
      ADMIN_PASSWORD: '***'
```

### Error logs of the "directus" container:
```
0 verbose cli /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/directus/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/node/.npmrc Completed in 6ms
12 timing config:load:user Completed in 7ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 23ms
19 timing npm:load:configload Completed in 23ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm exec directus start
23 verbose argv "exec" "--" "directus" "start"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 6ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:/home/node/.npm/_logs
28 verbose logfile /home/node/.npm/_logs/2023-02-13T22_42_05_529Z-debug-0.log
29 timing npm:load:logFile Completed in 13ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 51ms
33 silly logfile done cleaning log files
34 timing command:exec Completed in 40045857ms
35 verbose stack Error: command failed
35 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
35 verbose stack     at ChildProcess.emit (node:events:513:28)
35 verbose stack     at maybeClose (node:internal/child_process:1091:16)
35 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
36 verbose cwd /directus
37 verbose Linux 5.4.0-137-generic
38 verbose node v18.13.0
39 verbose npm  v8.19.3
40 error path /directus
41 error command failed
42 error signal SIGKILL
43 error command sh -c -- directus start
44 verbose exit 1
45 timing npm Completed in 40046348ms
46 verbose code 1
47 error A complete log of this run can be found in:
47 error     /home/node/.npm/_logs/2023-02-13T22_42_05_529Z-debug-0.log
```

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

postgis 13

### What browser are you using?

MS Edge

### How are you deploying Directus?

Docker
