### ISSUE TITLE
background-input Variable doesn't affect wysiwyg Editor

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#17630]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

background-input Variable in Project Settings doesn't affect wysiwyg Editor because the body tag in the iframe has its own background property.

### To Reproduce

Change the background-input Variable in project settings and look at a wysiwyg interface.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Do you mean the toolbar of the WYSIWYG editor? Because it seems like the editing area itself is affected by the `background-input` variable (example with value `red`):
<img width="450" src="https://user-images.githubusercontent.com/5363448/221518130-8963c22a-a0b5-40fe-97f7-079d04d795c4.png">

**Comment by paescuj** [comment]
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by Lucas-Gruber** [comment]
These are my Settings:

```css
#app, #main-content, body {
  --primary-alt: #F3FFFE !important;
  --primary-10: #F3FFFE !important;
  --primary-25: #C4FEF8 !important;
  --primary-50: #9CF8F1 !important;
  --primary-75: #6EF3E8 !important;
  --primary-90: #53F3E6 !important;

  --primary: #00FFE8 !important;

  --primary-110: #40E2D5 !important;
  --primary-125: #3DD8CB !important;
  --primary-150: #32938B !important;
  --primary-175: #276560 !important;
  --primary-190: #1C4A46 !important;

  --v-button-background-color: #43F5E6 !important;
  --v-button-background-color-hover: #3FDFD2 !important;
  --sidebar-detail-color-active: #3FDFD2 !important;
    
    
  --background-normal: #101013;
  --background-normal-alt: #18181B;
  --background-subdued: #0D0E11;
  --card-face-color: #0D0E11;
  --background-highlight: #141418;
  --background-page: #0C0D0D;
  --module-background: #0C0D0D;
  --background-input: #F00;
  --v-input-background-color: #F00;
  --background-page-rgb: 17, 17, 17;
  --background-inverted: #fff;
}
```

I have a file attached from the Input.
![image](https://user-images.githubusercontent.com/72545889/222002898-3030e127-f24a-4a68-9cde-d75233539d33.png)
