### ISSUE TITLE
in Application O2M relation foreign keys grayed out

### ISSUE THREAD

**Issue by ctholho** [directus/directus#17681]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Creating a O2M relation field, sometimes in the directus App also referred to an `O2M Alias field` is confusing because all options in the `Foreign Key` field are grayed out – but writing in the name of the column works.

<img width="1177" alt="Screenshot 2023-03-02 at 14 16 32" src="https://user-images.githubusercontent.com/28910105/222442773-ef5325f7-f465-4003-b254-d71c8079f4e5.png"> 

I tried this with postgres and mysql.

### To Reproduce

I'm using the example from the relations docs at https://docs.directus.io/configuration/data-model/relationships.html#one-to-many-o2m

1. Use this docker-compose.yaml

```
version: "3.9"

services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'dbpass'
      POSTGRES_DB: 'mydb'

  directus:
    container_name: directus
    image: directus/directus:latest
    volumes:
      - uploads:/directus/uploads
    ports:
      - 8055:8055
    depends_on:
      - database
    environment:
      PUBLIC_URL: https://localhost:8055
      SECRET: 'my-directus-secret'
      KEY: a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6
      # db settings
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'mydb'
      DB_USER: 'dbuser'
      DB_PASSWORD: 'dbpass'
      # Admin settings if no database seed is used
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin

volumes:
  postgres:
  uploads:
```

2. Log into directus as an admin and create 2 collections with two fields each.
```
- countries
  - id
  - name
- cities
  - id
  - name
```

3. Then create a M2O field in `cities`
```
- country_id (M2O field) referencing `countries` table
```

4. Then go to `countries` collection and try to create a O2M field. Now, every column is grayed out.
5. In the field `Foreign Key*` enter `country_id` and click save. This creates the O2M relation as expected.

### Hosting Strategy

Self-Hosted (Docker Image)
