### ISSUE TITLE
Apply Schema not working 

### ISSUE THREAD

**Issue by rfos** [directus/directus#17708]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When I try to import a schema from localhost to the production server it create only the table but not the Fields.

user@myhost:/var/www/directus$ npx directus schema apply snapshot.yaml
? The following changes will be applied:

Collections:
  - Create articles

Fields:
  - Create articles.author
  - Create articles.body
  - Create articles.cover_image
  - Create articles.date_created
  - Create articles.date_updated
  - Create articles.excerpt
  - Create articles.id
  - Create articles.publish_date
  - Create articles.sort
  - Create articles.status
  - Create articles.text
  - Create articles.title

Relations:
  - Create articles.author-> directus_users
  - Create articles.cover_image-> directus_files

Would you like to continue? Yes
[20:50:27.086] INFO: Snapshot applied successfully

### To Reproduce

```yaml
version: 1
directus: 9.22.4
collections:
  - collection: articles
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: articles
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: sort
      translations: null
      unarchive_value: null
    schema:
      collation: utf8mb4_0900_ai_ci
      comment: ''
      engine: InnoDB
      name: articles
      schema: dev-directus
fields:
  - collection: articles
    field: author
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: author
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
        template: "{{first_name}}\_{{last_name}}"
      readonly: false
      required: false
      sort: 6
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: author
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
  - collection: articles
    field: body
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: body
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options: null
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: body
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: text
  - collection: articles
    field: cover_image
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: cover_image
      group: null
      hidden: false
      interface: file-image
      note: null
      options:
        folder: 5c14f9e9-2cd4-4226-9b16-78eea0b49ad9
      readonly: false
      required: false
      sort: 3
      special:
        - file
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: char
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_files
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: cover_image
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: uuid
  - collection: articles
    field: date_created
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: date_created
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 7
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: timestamp
  - collection: articles
    field: date_updated
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: date_updated
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 8
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: timestamp
  - collection: articles
    field: excerpt
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: excerpt
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options:
        folder: 5c14f9e9-2cd4-4226-9b16-78eea0b49ad9
      readonly: false
      required: false
      sort: null
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: excerpt
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: text
  - collection: articles
    field: id
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: int unsigned
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: null
      name: id
      numeric_precision: 10
      numeric_scale: 0
      table: articles
    type: integer
  - collection: articles
    field: publish_date
    meta:
      collection: articles
      conditions: null
      display: datetime
      display_options:
        format: short
      field: publish_date
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: false
      sort: 10
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: datetime
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: publish_date
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: dateTime
  - collection: articles
    field: sort
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: int
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: sort
      numeric_precision: 10
      numeric_scale: 0
      table: articles
    type: integer
  - collection: articles
    field: status
    meta:
      collection: articles
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            background: '#00C897'
          - text: $t:draft
            value: draft
            background: '#D3DAE4'
          - text: $t:archived
            value: archived
            background: '#F7971C'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:draft
            value: draft
          - text: $t:published
            value: published
      readonly: false
      required: false
      sort: 11
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: published
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
  - collection: articles
    field: text
    meta:
      collection: articles
      conditions: null
      display: null
      display_options: null
      field: text
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options:
        folder: 5c14f9e9-2cd4-4226-9b16-78eea0b49ad9
      readonly: false
      required: false
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: text
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: text
  - collection: articles
    field: title
    meta:
      collection: articles
      conditions: null
      display: formatted-value
      display_options:
        bold: true
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: title
      numeric_precision: null
      numeric_scale: null
      table: articles
    type: string
relations:
  - collection: articles
    field: author
    meta:
      junction_field: null
      many_collection: articles
      many_field: author
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: author
      constraint_name: articles_author_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: SET NULL
      on_update: NO ACTION
      table: articles
  - collection: articles
    field: cover_image
    meta:
      junction_field: null
      many_collection: articles
      many_field: cover_image
      one_allowed_collections: null
      one_collection: directus_files
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_files
    schema:
      column: cover_image
      constraint_name: articles_cover_image_foreign
      foreign_key_column: id
      foreign_key_table: directus_files
      on_delete: SET NULL
      on_update: NO ACTION
      table: articles
```

### Hosting Strategy

Self-Hosted (Custom)
