### ISSUE TITLE
Assets get lost since v9.23.2 via Docker and local storage

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#17907]
### Describe the Bug

Updating from v9.23.1 to v9.23.2 makes Directus lose track of all the images in my local storage (database id and data is still correct tho). Directus is deployed on a single node Docker Swarm, and changing back to v9.23.1 makes everything work again.

I tested v.9.23.3 but got the same results with the added drawback of #17901 and #17905 
Since I've read that #17734 was one of the changes, I tried to disable the env variable `ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION` that I pass to Directus (just for testing purposes), but didn't affect anything.

But then, the only meaningful information I was able to get were two errors in the Directus log:
```
[23:51:38.948] ERROR: Location "local" doesn't exist.
    err: {
      "type": "Error",
      "message": "Location \"local\" doesn't exist.",
      "stack":
          Error: Location "local" doesn't exist.
              at StorageManager.location (file:///directus/node_modules/@directus/storage/dist/index.js:18:19)
              at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:77:38)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /directus/node_modules/directus/dist/controllers/assets.js:126:36
    }
```
```
[23:51:38.966] ERROR: The "path" argument must be of type string. Received null
    err: {
      "type": "TypeError",
      "message": "The \"path\" argument must be of type string. Received null",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
              at new NodeError (node:internal/errors:399:5)
              at validateString (node:internal/validators:163:11)
              at join (node:path:1172:7)
              at DriverLocal.fullPath (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:11:32)
              at DriverLocal.exists (file:///directus/node_modules/@directus/storage-driver-local/dist/index.js:40:28)
              at AssetsService.getAsset (/directus/node_modules/directus/dist/services/assets.js:77:61)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async /directus/node_modules/directus/dist/controllers/assets.js:126:36
      "code": "ERR_INVALID_ARG_TYPE"
    }
```
They weren't appearing every time but mostly when I tried to load any kind of asset.

I'm happy to test stuff and provide more logs.

### To Reproduce

Currently using this docker-compose.yml
```yml
version: '3.4'

services:
  frontend:
    image: ${IMG_REPO}
    
    networks:
      - traefik-public

    stdin_open: true
    tty: true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
        - "traefik.http.routers.${PROJECT_NAME}-frontend.tls.certresolver=letsencrypt"
        - "traefik.http.routers.${PROJECT_NAME}-frontend.entrypoints=websecure"
        - "traefik.http.routers.${PROJECT_NAME}-frontend.service=${PROJECT_NAME}-frontendsvc"
        - "traefik.http.services.${PROJECT_NAME}-frontendsvc.loadbalancer.server.port=3000"


  directus:
    image: directus/directus:9.23.1

    volumes:
      # currently binding for practical reasons
      - ${LOCAL_PATH}/directus-uploads:/directus/uploads
      #- directus-uploads:/directus/uploads
      #- directus-extensions:/directus/extensions
    networks:
      - directus-network
      - traefik-public

    tty: true
    stdin_open: true
    environment:
      KEY: '${UNIQUE_KEY}'
      SECRET: '${UNIQUE_SECRET}'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '${PROJECT_NAME}-db'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_POOL_MIN: '0'
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: 'true'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      PUBLIC_URL: 'https://${DIRECTUS_URL}'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8256'
      # testing stuff with CORS
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_NAME}-backend.rule=Host(`${DIRECTUS_URL}`)"
        - "traefik.http.routers.${PROJECT_NAME}-backend.tls.certresolver=letsencrypt"
        - "traefik.http.routers.${PROJECT_NAME}-backend.entrypoints=websecure"
        - "traefik.http.routers.${PROJECT_NAME}-backend.service=${PROJECT_NAME}-backendsvc"
        - "traefik.http.services.${PROJECT_NAME}-backendsvc.loadbalancer.server.port=8055"


  database:
    image: postgis/postgis:13-master
    tty: true
    stdin_open: true
    volumes:
      - directus-db:/var/lib/postgresql/data
      # quick pg backup folder
      - ${LOCAL_PATH}/pg_dumps:/pg_dumps
    networks:
      - directus-network
    environment:
      POSTGRES_DB: '${PROJECT_NAME}-db'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}


  cache:
    image: redis:6
    networks:
      - directus-network


volumes:
  #directus-uploads:
  #directus-extensions:
  directus-db:


networks:
  directus-network:
  traefik-public:
    external: true
```

### Hosting Strategy

Self-Hosted (Docker Image)
