### ISSUE TITLE
Docker compose down wipes all RDS data

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#18088]
### Describe the Bug

Dear community.

I have a clean install, after docker system prune
I am running Directus on Docker in EC2 Linux and RDS Postgres database.
It works fine, but when I do a `docker compose down`, it wipes everything goes to oblivion.

Here is the devel-compose.yml file:

```
version: '3.4'
services:
  directus:
    container_name: docker-instance_dev
    image: directus/directus:latest
    restart: on-failure
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using local driver
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
      - type: bind
        source: ./docker-instance_dev/database
        target: /var/lib/postgresql/data
    user: "1000:1000"
    networks:
      - directus
    depends_on:
      - cache
    environment:
      HOST: "0.0.0.0"
      PORT: 8055
      KEY: 'x'
      SECRET: 'x'
      DIRECTUS_DATABASE_URL: 'postgresql://postgres:password@devel-database.id001.eu-region-3.rds.amazonaws.com:5432/devel-database-name'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      ADMIN_EMAIL: 'jorge.nunes@docker-instance.ai'
      ADMIN_PASSWORD: 'm7passw0rd'
      #PUBLIC_URL: 'https://apidev.docker-instance.ai'
  cache:
    container_name: cache-redis
    image: redis:6
    ports:
      - 6379
    networks:
      - directus
volumes:
  docker-instance_dev:
networks:
  directus:


```
Thanks for input

### To Reproduce

create devel-compose.yml file

docker compose -f devel-compose.yml up
docker compose down
docker compose -f devel-compose.yml up

check project settings or any other field.

### Hosting Strategy

Self-Hosted (Docker Image)
