### ISSUE TITLE
saml auth not working

### ISSUE THREAD

**Issue by drpdishant** [directus/directus#18087]
### Describe the Bug

SAML auth is not working despite providing the configuration as described in docs, 

Following is the error that I am getting in logs.

```
[14:26:11] GET /auth/login/saml 500 73ms
[14:26:11.987] ERROR: The "url" argument must be of type string. Received an instance of Object
    err: {
      "type": "TypeError",
      "message": "The \"url\" argument must be of type string. Received an instance of Object",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
              at new NodeError (node:internal/errors:399:5)
              at validateString (node:internal/validators:163:11)
              at Url.parse (node:url:176:3)
              at Object.urlParse (node:url:147:13)
              at buildRedirectURL (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/binding-redirect.js:74:25)
              at Object.loginRequestRedirectURL (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/binding-redirect.js:125:22)
              at ServiceProvider.createLoginRequest (/directus/node_modules/.pnpm/samlify@2.8.10/node_modules/samlify/build/src/entity-sp.js:86:51)
              at /directus/dist/auth/drivers/saml.js:112:43
              at /directus/dist/utils/async-handler.js:3:66
              at Layer.handle [as handle_request] (/directus/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
      "code": "ERR_INVALID_ARG_TYPE"
    }

```

### To Reproduce

- Setup directus with keycloak as IdP, 
- add a SAML client 
- configure the IDP metadata url in Directus ENV.

Following is the docker-compose I am using:

```
version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:  start-dev
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.kc-directus.rule=Host(`kc-directus.192.168.29.26.nip.io`)"
    - "traefik.http.routers.kc-directus.entrypoints=web"
  database:
    container_name: database
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    expose: 
    - 8055
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      EMAIL_SMTP_NAME: local
      EMAIL_SMTP_HOST: 192.168.29.26
      EMAIL_SMTP_PORT: 1025
      EMAIL_FROM: no-reply@example.com
      EMAIL_TRANSPORT: smtp
      AUTH_PROVIDERS: 'saml'
      AUTH_SAML_DRIVER: 'saml'
      AUTH_SAML_IDP_metadata: "http://kc-directus.192.168.29.26.nip.io/realms/master/protocol/saml/descriptor"
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: "directus.192.168.29.26.nip.io"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.directus.rule=Host(`directus.192.168.29.26.nip.io`)"
    - "traefik.http.routers.directus.entrypoints=web"
networks:
  default:
    external: true
    name: traefik_backend
```

Keycloak Client Config:

```
{
  "clientId": "directus",
  "name": "directus",
  "description": "",
  "rootUrl": "http://directus.192.168.29.26.nip.io",
  "adminUrl": "http://directus.192.168.29.26.nip.io/auth/login/saml",
  "baseUrl": "http://directus.192.168.29.26.nip.io/auth/login/saml",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": true,
  "clientAuthenticatorType": "client-secret",
  "redirectUris": [
    "http://directus.192.168.29.26.nip.io/*"
  ],
  "webOrigins": [
    "http://directus.192.168.29.26.nip.io"
  ],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": false,
  "publicClient": true,
  "frontchannelLogout": true,
  "protocol": "saml",
  "attributes": {
    "saml.assertion.signature": "false",
    "saml.force.post.binding": "true",
    "saml.server.signature": "true",
    "saml.server.signature.keyinfo.ext": "false",
    "saml.signing.certificate": "MIICnzCCAYcCBgGHVsZPVjANBgkqhkiG9w0BAQsFADATMREwDwYDVQQDDAhkaXJlY3R1czAeFw0yMzA0MDYxMzMyMjlaFw0zMzA0MDYxMzM0MDlaMBMxETAPBgNVBAMMCGRpcmVjdHVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQOL5o/NG+rNeAOCQbRIjl+3+FtKBlPcDA4W+xUGJrRv2c6En+XtBFLHjAigVpO0VkvbiWTJiKikXHriLXF6hCY/C5SG4p8px3vmnhFMNUQsnogOT2O6ED9Xk58+6kSDRWP25LHNmQQNBhpr4Kc3sm6V/m3k0g2WWVEPPt0HTlRt5LUz4V0mbFEUfBZWFNuLHBpLmkvPthcQmzrPt5LSyP6foX5bvEG8mmFcrkxvq8UoJ2qHesGSPpW9WxgZCt/gH9t/f9YfcZGAWA2m6q98/g/5UUN/YVT3lDESlmTi0YFJs2VXF5ED3GwnvDaXZAn8YVbN6ZRi8ZSMi4CfB4CvmQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQA9y9uNK32GMEKPtDGlft+zBb8UJmpy0ilq9jWcwtkP/GcMlpLh6euGcFuImfFV1oDq0dSz6mGCxRCcDfJu7I9gs6zZ5k2aBvF4W/wVtdJK3iKXm+Rzw3y7LOYarENIloOdKYWqHBUuPDVbEOPN/0UiUsBPtY0J26p3U2KhqVihQULGA2vqMDhOX3aOi+PuQXCYGeqUZQKRN8elLRq7OvLO/lMTxlP23yvkq0dE9110OD1onTnY5C40sd60wwDIdW45wD2gjv2N4SErqxxoYB9ZDrJooAK9nsMymbOPDYM1k7ZTHUmtD209J0apLVKzgjQWQe6jswuRJRRnjX/ccKxG",
    "saml.artifact.binding.identifier": "EnZLi7fNMy99STeFGirygV33Bqw=",
    "saml.artifact.binding": "false",
    "saml.signature.algorithm": "RSA_SHA256",
    "saml_force_name_id_format": "false",
    "saml.client.signature": "true",
    "saml.authnstatement": "true",
    "display.on.consent.screen": "false",
    "saml_name_id_format": "transient",
    "saml.signing.private.key": "MIIEowIBAAKCAQEAsQOL5o/NG+rNeAOCQbRIjl+3+FtKBlPcDA4W+xUGJrRv2c6En+XtBFLHjAigVpO0VkvbiWTJiKikXHriLXF6hCY/C5SG4p8px3vmnhFMNUQsnogOT2O6ED9Xk58+6kSDRWP25LHNmQQNBhpr4Kc3sm6V/m3k0g2WWVEPPt0HTlRt5LUz4V0mbFEUfBZWFNuLHBpLmkvPthcQmzrPt5LSyP6foX5bvEG8mmFcrkxvq8UoJ2qHesGSPpW9WxgZCt/gH9t/f9YfcZGAWA2m6q98/g/5UUN/YVT3lDESlmTi0YFJs2VXF5ED3GwnvDaXZAn8YVbN6ZRi8ZSMi4CfB4CvmQIDAQABAoIBACnqyFQIjP5Vp6LKF+wVtFHMrly4R2sArDzJkF0UQTDkrRDzk9nmgW4y6RCK0Wc3Em8WBw59yLCdGNDSg6FVvDizct375cYgAS19NGMNfxGlC3jeCJ95ouuqiENLpEMnBrvlnGdTCHf56tidZJreFjUhdVD69oLcV1ReuuC8x/he5ffifuGrcIa+Rk40CjAzU4RDlqzVF5FOngNxc6RwuQ3rb0ddUI0ogLV9D9JMkMClA8bbN2E+gx5+pzvXXA60lGhCHrcY2K6QIj9uGFcXtvhZXgBK6CFfR2UtC10lEaA6pJkQjgQJWHa8J24TWGIz18Xz1VI7AiMnnw4RncY9h2UCgYEA7c0fpIfk8e0g/LZzUzduQOFXctBsIVm9531HQ2oFxV/RrpvXBgQBBumX06QYE4FkVMTtCd+gm+kQ3W4xe6O7J0JPlUgv4gHErYYXxcHL+22DJb6ThmUQ0nMufPkV1EX7jCAzhGf3jJJzD8s/xKl1KJvohlb/R3tClSN+Ve4bP40CgYEAvo+CFRwkRrBB5znH8D/xWbnHqy781az2rBZX47+EeYiGlGTk0dIu2vqnhkEf4C5KodNg1GcO09mMv2NIzoz0DMTgeeQOgzkYZ9HzYEBdfpYMyi0UcuZtbeEtVQ0yHFnf1ZbWb5D0/OgNjbuc2jvKx9974C9idJkLGhCKxehYdz0CgYAkXlWzjREHqvN7ks/Kb1TOWWhNZ/DRnO79Q1ytw75ENGZWJQFaqywZCYqt1I/WE9jrWf7Cns/qaFeq9dpdhWnvFCYlt5eTIiAZRcPG+9+dgV8oW6AmUrii5vi6JkIfZ+CTyqz2WAw1FITCapxDEIOZhVanjRCXtxM0yevdaoACVQKBgDm9njrrRgqtSarYlT61AVqgsmGqYS4VtMC8HHGEDI4O0kiQsczqFQyBOtWxUglJvY9/Ty3M9G840i8D1IHRr/lWhnYopkUYvc5njYkyt6Gtsb5pHnMaYzoSKvxEfVSd3vcHN36iu7kOT10M5iAyUeVyUETD1t9hqD2DmakSGAw5AoGBANwqJ4nqPrGTWCAdCMyaLkaP269NOUzYzZ64Au5Ax/jKJ2EiATeeqr31yDS/dRkmaPf4w+IfEjnLn6patM99j9BTL1jYQgAVzlSY7+7cK13d3w0P5uH5b4polJ2gEsTd0qp8o+KFAWzatNK/U/2SspB4pi0sLvzP1VMK8e/LzKUb",
    "saml.allow.ecp.flow": "false",
    "saml_signature_canonicalization_method": "http://www.w3.org/2001/10/xml-exc-c14n#",
    "saml.onetimeuse.condition": "false",
    "saml.server.signature.keyinfo.xmlSigKeyInfoKeyNameTransformer": "NONE"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "defaultClientScopes": [
    "role_list"
  ],
  "optionalClientScopes": [],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
```

After Configuring the endpoints and clients correctly, you'll see the login with saml button on login page, but it will throw internal server error upon invocation.

### Hosting Strategy

Self-Hosted (Docker Image)
