### ISSUE TITLE
Collection/field creation/changes saved to DB but not displayed in Directus in v9.23.2–v9.24.0 (self-hosted Docker)

### ISSUE THREAD

**Issue by rowild** [directus/directus#18110]
### Describe the Bug

After running `docker compose pull [service]` and restarting the app (`docker compose down` and `docker compose up -d`, all done on DigitalOcean with SQLite) fields of a collection are not updated anymore.

https://user-images.githubusercontent.com/213803/230712051-ae5dfe3d-4ec8-44b0-8e2a-c324249ae49b.mp4

### To Reproduce

- Update an existing self-installed Directus 9.23 installation to 9.24
- Change the value of some field of a collection and save.
- Re-open the just edited field.

(The content has not been updated.)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rowild** [comment]
Further things I did:
- a SQLite `PRAGMA integrity_check`
- Check the rights of the db file itself as well as the parent directory (which must be writeable)
That didn't change anything.

I eventually stopped docker, deleted all containers and images and ran `docker compose` again, but even that didn't change the problem.

**Comment by br41nslug** [comment]
I am unfortunately unable to reproduce this 😬 Could you try reproducing it with all caches disabled "CACHE_ENABLED"/"CACHE_SCHEMA"/"CACHE_PERMISSIONS" and inspect the actual API call done when trying to apply changes?

**Comment by rowild** [comment]
Thank you for your feedbacks, @br41nslug & @rijkvanzanten! I did what you told me – I am sorry, I was not aware of the CACHE parameter options! Here is what I did:

I tried a new local installation with a new database and that one works indeed fine!

But as soon as I use my existing SQLite file – by replacing the just created, empty new data.db file – the problem as described above remains.

So next I execute `docker compose down`, delete all containers and images and make sure to set those CACHE* options you recommend to false in my docker-compose.yml. Eventually `docker compose up -d` creates a Directus 9.24 instance with my old database file (the one with all the data), on which I can work now (change fields, create new collections, ...).

Buuuuut ... when I then go back to the yml file and enable all cache options again (and do all the docker compose down and up stuff), I am again facing the same problem as initially described.

I also experimented with CACHE_AUTO_PURGE, but to no avail. 
I assume changing KEY and SECRET would be counter-productive?

This happens locally as well as on DigitalOcean.
And I should mention that I only tried the above things with SQLite, not any other db.

Do you happen to have any other ideas?
I'd be happy to provide my database file, if you think that could help. Or my DigitalOcean account. 

(I remember that I created my data with Directus 9.11 (or 15?), locally. Then, after 5, 6 months, I tried DigitalOcean, and as soon as the setup worked there, I copied over that old database file. I had to do some work (like changing the IDs of the user groups etc), but I eventually could manipulate it. And I still can do so with v9.23.1, but not any version after that...)  

Thank you again for your time!

**Comment by rowild** [comment]
I think I found the problem. As soon as I add "PUBLIC_URL: 'https://localhost:8057'" (port matches the port mapping `8057:8055`) the infos are still written to the database, but Directus does not display that info anymore. However, it still recognises that a collection already exists should you try to create one that has the same name.

Steps to reproduce:

**STEP 1: setup**

- create a Directus Docker setup using SQLite on basis of the Quickstart yaml
- add redis as cache
- do NOT add a PUBLIC_URL yet

You can use this file:

```yaml
version: '3'
services:

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    networks:
      - directus
    depends_on:
      - cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      # PUBLIC_URL: 'https://127.0.0.1:8055'

networks:
  directus:
```

- run `docker compose up -d`
- create a collection and a field; edit it (to test, if an update works)

So far everything should be working. Continue with

**STEP 2: break it**

- run `docker compose down`
- run `docker rm [container]`
- run `docker rmi [images]`   ## to make sure the redis cache is removed
- add the PUBLIC_URL to the `docker-compose.yml`
- run `docker compose up --force-recreate --build -d`
- In Directus, go to collections and create a new one -- this should FAIL now
- Try creating a collection with the same name again -- Directus will say that this collection already exists
- Try editing a field from collection 1 -- the changes won't last

**STEP 3: downgrade to 9.23.1**

- go to `docker-compose.yml` and replace `directus/directus:latest` with `directus/directus:9.23.1`
- run `docker compose pull directus && docker compose up --force-recreate --build -d`
- In Directus, create a new collection (with a new name) -- now it works (and collections from previous tries will be shown, too)
- Edit fields as before -- changes will be reflected now

Beginning with Directus:9.23.2 these behaviours are broken.

**STEP 4: fixing it again**

Unfortunately, simply removing the PUBLIC_URL from the yml file won't fix the problem. Not even stopping and deleting any images in order to get rid of the redis cache. It seems that at this point the db file is corrupt. (Sometimes a process is running that quickly creates and deletes a `[data.db].db-journaled` file – not sure what this does. Only completely deleting any cache and using a previously backupped database file will make the system work again. (Or turning of cache as mentioned earlier.)

Only tested with SQLite in my local environment (MacBook M2).

Here is a video with my workflow with STEP 1 and STEP 2 (sorry, didn't record the downgrade):
https://dl.rowild.at/directus-not-saving-collections__2023-04-11.mp4

Is my understanding of `PUBLIC_URL` wrong?
