### ISSUE TITLE
Creating translations field not possible on collection

### ISSUE THREAD

**Issue by schroedan** [directus/directus#18380]
### Describe the Bug

Creating a translations field on new table with the name `advertisements` in an empty database does not work. The described steps below work for other table names.

### To Reproduce

1. Create `docker-compose.yaml` with the following content:
```
version: '3'
services:
  directus:
    image: directus/directus:10.0.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
```
2. Execute `docker compose up -d`
3. Sign in with provided admin credentials
4. Create new collection with name `advertisements` and check all optional system fields
5. Create translations field in advanced mode
6. See the following errors:
```
{
  "errors": [
    {
      "message": "Field \"advertisements_id\" doesn't exist in collection \"advertisements_translations\"",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
```
{
  "errors": [
    {
      "message": "Field \"languages_code\" doesn't exist in collection \"advertisements_translations\"",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
```
{
  "stack": "AxiosError: Network Error\n    at v.onerror (http://localhost:8055/admin/assets/use-sync-0cbce98c.js:3:4376)",
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {}
}
```

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)
