### ISSUE TITLE
Errors while overwriting options.transport for the pino logger

### ISSUE THREAD

**Issue by philipkaiser** [directus/directus#18497]
### Describe the Bug

If you want to configure the internally used pino instance, you can pass configuration options via environment variables named `LOGGER_*`. This way, you should be able to pass `LOGGER_TRANSPORT` to overwrite the transport settings. Doing so results in the error message / stack seen below when starting the directus docker container:

```
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at isAbsolute (node:path:1157:5)
    at fixTarget (/directus/node_modules/pino/lib/transport.js:115:9)
    at transport (/directus/node_modules/pino/lib/transport.js:110:22)
    at normalizeArgs (/directus/node_modules/pino/lib/tools.js:291:16)
    at pino (/directus/node_modules/pino/pino.js:86:28)
    at Object.<anonymous> (/directus/node_modules/directus/dist/logger.js:72:35)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I tried a lot of different values for `LOGGER_TRANSPORT`. It seems the problem occurs only when specifying one or multiple targets.

### To Reproduce

1. create a `docker-compose.yml` file
```yaml
version: "3.2"
services:
  my-directus:
    container_name: my-directus
    image: directus/directus:10.0
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./extensions:/directus/extensions
      - ./data:/directus/database
      - ./logs:/directus/logs
    env_file:
      - ./.env
```

2. create a `.env` file in the same directory as the `docker-compose.yml`
```
PUBLIC_URL=http://localhost:8055
PORT=8055
ACCESS_TOKEN_TTL=1d
KEY=255d861b-5ea1-5996-9aa3-922530ec40b1
SECRET=6116487b-cda1-52c2-b5b5-c8022c45e263
ADMIN_EMAIL=ab@c.com
ADMIN_PASSWORD=1234
LOGGER_TRANSPORT='{ "target": "pino/file", "options":{"destination":"/directus/logs/error.log"}}'
```

3. run `docker-compose up`

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)
