### ISSUE TITLE
Deleted field appears in snapshot, failing import

### ISSUE THREAD

**Issue by HaraldNordgren** [directus/directus#18619]
### Describe the Bug

Exporting a snapshot from our production instance and importing into a Dockerized Directus instance with Postgres fails like this.

This is a column that we deleted, but somehow it still hangs around. We also tried to disable all caches before the snapshot export, but it's still the same:

```
[10:06:43.545] ERROR: Failed to create relation "foodItem.externalFoodId"
[10:06:43.546] ERROR: Field "externalFoodId" doesn't exist in collection "foodItem"
    err: {
      "type": "InvalidPayloadException",
      "message": "Field \"externalFoodId\" doesn't exist in collection \"foodItem\"",
      "stack":
          Error: Field "externalFoodId" doesn't exist in collection "foodItem"
              at RelationsService.createOne (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/relations.js:122:19)
              at file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/utils/apply-diff.js:201:44
      "status": 400,
      "code": "INVALID_PAYLOAD",
      "extensions": {}
    }
```

### To Reproduce

Snippet from the snapshot:

```yaml
version: 1
directus: 10.1.0
vendor: postgres
...
  - collection: foodItem
    field: externalFoodId
    related_collection: food
    meta:
      junction_field: null
      many_collection: foodItem
      many_field: externalFoodId
      one_allowed_collections: null
      one_collection: food
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
```

Related to: https://github.com/directus/directus/issues/16503

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)
