### ISSUE TITLE
cannot hydrate schema on Directus docker deploy

### ISSUE THREAD

**Issue by Sandros94** [directus/directus#18706]
### Describe the Bug

While creating a reproduction for other issues (one of which #17117), I've noticed that it is not easily possible to hydrate Directus schema on deployment while using a custom command inside the docker-compose stack.

Like the official dockerfile, this command first bootstrap and start Directus and then runs the `schema apply --yes` with the locally bindend (in read-only) schema.yml.

What happens is simply nothing, I must manually execute the schema apply command.

### To Reproduce

As per the other issue, you can find the files in [this branch](https://github.com/Sandros94/test-nuxt3app/tree/directus).

The two important files are:
<details>
  <summary>docker-compose-dev.yml</summary>
  
  ```yml
  version: '3.4'

  services:
    directus:
      image: directus/directus:10.1

      user: node
      command: sh -c "node /directus/cli.js bootstrap && node /directus/cli.js start && node /directus/cli.js schema apply --yes /directus/schema.yml"

      volumes:
        - ./schema.yml:/directus/schema.yml:ro
      #  - directus-uploads:/directus/uploads
      #  - directus-extensions:/directus/extensions
      ports:
        - 8055:8055

      tty: true
      stdin_open: true
      environment:
        KEY: 'second-key'
        SECRET: 'second-secret'
        DB_CLIENT: 'pg'
        DB_HOST: 'database'
        DB_PORT: '5432'
        DB_DATABASE: 'directus-db'
        DB_USER: 'directus'
        DB_PASSWORD: 'directus'
        DB_POOL__MIN: '0'
        CACHE_ENABLED: 'true'
        CACHE_STORE: 'redis'
        CACHE_REDIS: 'redis://cache:6379'
        # CACHE_AUTO_PURGE is for recreating the cache every time the db content is update/created/deleted - this will change in the future
        CACHE_AUTO_PURGE: 'true'
        ADMIN_EMAIL: 'user@example.com'
        ADMIN_PASSWORD: 'password'
        ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8256'
        CORS_ENABLED: "true"
        CORS_ORIGIN: "true"
        CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "www.google.com google.com www.youtube.com youtube.com"

      depends_on:
        - database
        - cache


    database:
      image: postgis/postgis:13-master
      tty: true
      stdin_open: true
      #volumes:
      #  - directus-db:/var/lib/postgresql/data
      #  - directus-db_dumps:/db_dumps
      environment:
        POSTGRES_DB: 'directus-db'
        POSTGRES_USER: 'directus'
        POSTGRES_PASSWORD: 'directus'


    cache:
      image: redis:6
      depends_on:
        - database


  #volumes:
    #directus-uploads:
    #directus-extensions:
    #directus-db:
    #directus-db_dumps:
  ```
</details>

<details>
  <summary>schema.yml</summary>
  
  ```yml
  version: 1
  directus: 10.1.0
  vendor: postgres
  collections:
    - collection: links
      meta:
        accountability: all
        archive_app_filter: true
        archive_field: status
        archive_value: archived
        collapse: open
        collection: links
        color: null
        display_template: null
        group: null
        hidden: false
        icon: null
        item_duplication_fields: null
        note: null
        singleton: false
        sort: null
        sort_field: null
        translations: null
        unarchive_value: draft
      schema:
        name: links
  fields:
    - collection: links
      field: date
      type: date
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: date
        group: null
        hidden: false
        interface: datetime
        note: null
        options: null
        readonly: false
        required: true
        sort: 4
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: date
        table: links
        data_type: date
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: id
      type: uuid
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: id
        group: null
        hidden: true
        interface: input
        note: null
        options: null
        readonly: true
        required: false
        sort: 1
        special:
          - uuid
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: id
        table: links
        data_type: uuid
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: false
        is_unique: true
        is_primary_key: true
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: link
      type: string
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: link
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: link
          placeholder: link
        readonly: false
        required: true
        sort: 3
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: link
        table: links
        data_type: character varying
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: name
      type: string
      meta:
        collection: links
        conditions: null
        display: null
        display_options: null
        field: name
        group: null
        hidden: false
        interface: input
        note: null
        options:
          placeholder: name
        readonly: false
        required: true
        sort: 2
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: name
        table: links
        data_type: character varying
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: links
      field: status
      type: string
      meta:
        collection: links
        conditions: null
        display: labels
        display_options:
          choices:
            - text: Hidden
              value: hidden
              background: '#292929'
            - text: Visible
              value: visible
              background: '#00FF00'
          showAsDot: true
        field: status
        group: null
        hidden: false
        interface: select-dropdown
        note: null
        options:
          choices:
            - text: Hidden
              value: hidden
            - text: Visible
              value: visible
        readonly: false
        required: false
        sort: 5
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: status
        table: links
        data_type: character varying
        default_value: hidden
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
  relations: []
  ```
</details>

### Directus Version

v10.1

### Hosting Strategy

Self-Hosted (Docker Image)
