### ISSUE TITLE
Directus with Mysql, Map layout & Calendar layout not working properly

### ISSUE THREAD

**Issue by vvoila** [directus/directus#18757]
### Describe the Bug

Using Directus with Mysql 5 or Mysql 8 the map layout and calendar layout is not working as expected.

### To Reproduce

1. Prepare Mysql 5 or MySql 8 and create directus database
2. Create docker-compose.yml with following configuration:

```
version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'mysql'
      DB_HOST: 'localhost'
      DB_PORT: 3306
      DB_DATABASE: 'directus'
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
    network_mode: host

```
and run with docker-compose up -d

3. Create Events data model with the following field: Title, Date From (Datetime), Date To (Datetime)
3.1 Insert data
3.2 Set layout display to Calendar, the calendar will be displayed as follow:
![image](https://github.com/directus/directus/assets/107702456/cca83250-4175-4dcc-ac73-241b34bc1255)

Note that using sqlite, calendar is showing properly,

4. Create Locations data model with the following field: Title, Position (Map)
4.1 Insert data
4.2 Set layout display to Map, the map will be displayed as follow:
![image](https://github.com/directus/directus/assets/107702456/b4e3595c-7335-4933-8538-c702f38c6f97)

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by darioguarascio** [comment]
same issue, using postgresql. I noticed when trying using maps as visualization

**Comment by YannickArmspach** [comment]
To fix this temporarily, simply add the following CSS in "Project Settings > Custom CSS"

```css
.private-view .content-wrapper{
   height:100%!important;
}
```

**Comment by licitdev** [comment]
@YannickArmspach Nice! Thank you! 👍 
Here's a more accurate temporary workaround that does not introduce scrolling.
 
```css
.private-view #main-content .content-wrapper{
   display: contents;
}
```
