### ISSUE TITLE
/schema/apply returns Cannot read properties of null (reading 'meta')

### ISSUE THREAD

**Issue by ithan** [directus/directus#18787]
### Describe the Bug

When trying to migrate 1 snapshot from prod to stage, I get Cannot read properties of null (reading 'meta')

I'm using a 'copy-paste' of the code in https://docs.directus.io/guides/migration/node.html#migrate-your-data-model-with-node-js

I can't share the yml that I need to import due to company policies, but here is a simplified version:

```yml
hash: ~
diff:
  collections:
    - collection: test_collection
      diff:
        - kind: 'N'
          path:
            - meta
            - preview_url
          rhs: null
  fields:
    - collection: test_groups_test
      field: id
      diff:
        - kind: E
          path:
            - schema
            - has_auto_increment
          lhs: false
          rhs: true
  relations:
    - collection: test_extra_properties
      field: test_id
      related_collection: test
      diff:
        - kind: 'N'
          path:
            - schema
          rhs:
            table: test_extra_properties
            column: test_id
            foreign_key_table: test
            foreign_key_column: id
            constraint_name: test_extra_properties_test_id_foreign
            on_update: NO ACTION
            on_delete: SET NULL

```

I'm using directus 10.2.1 dockerized 

### To Reproduce

Create 2 instances of directus with some differences on them, and try to migrate the most up to date one to the previous one  using /schema/apply following the instructions from https://docs.directus.io/guides/migration/node.html#migrate-your-data-model-with-node-js

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)
