### ISSUE TITLE
New version of docker is not working with redis enabled Directus 10.4.0 ECONNREFUSED 127.0.0.1:6379 

### ISSUE THREAD

**Issue by kieusonlam** [directus/directus#19036]
### Describe the Bug

Cannot start directus container with redis cache enabled, here is the error in logs:
```
[03:37:15.040] WARN: [cache] Error: connect ECONNREFUSED 127.0.0.1:6379
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:6379",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:6379
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 6379
    }
[03:37:15.040] WARN: [system-cache] Error: connect ECONNREFUSED 127.0.0.1:6379
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:6379",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:6379
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 6379
    }
```

### To Reproduce

Fresh start with docker compose:

```
version: '3'
services:
  database:
    container_name: ${PREFIX}-database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: ${PREFIX}-cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: ${PREFIX}-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: 'xxx'
      SECRET: 'xxx'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'xxxx
      ADMIN_PASSWORD: 'xxxx'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:
    name: ${PREFIX}

```

### Directus Version

v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)
