### ISSUE TITLE
KnexTimeoutError on docker-compose up

### ISSUE THREAD

**Issue by Zyles** [directus/directus#19209]
### Describe the Bug

I am trying to do a docker install following the docs but I am unable to connect to an external postgreSQL db.

PostgreSQL 13.11

```
docker-compose.yml:
version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/home/http/project/database
      - ./uploads:/home/http/project/uploads
    environment:
      KEY: 'xxxx'
      SECRET: 'xxxxxx'
      ADMIN_EMAIL: 'xxxxxx'
      ADMIN_PASSWORD: 'xxxxxxxx'
      DB_CLIENT: 'pg'
      DB_HOST: '123.123.123.13'
      DB_DATABASE: 'xxxx'
      DB_PORT: '5432'
      DB_USER: 'xxxx'
      DB_PASSWORD: 'xxxxx'
      DB_SSL: 'true'
      WEBSOCKETS_ENABLED: 'true'
```

`sudo docker-compose up`

Error:
```
directus_1  | [22:39:34.388] INFO: Initializing bootstrap...
directus_1  | [22:42:59.521] ERROR: Can't connect to the database.
directus_1  | [22:42:59.521] ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
directus_1  |     err: {
directus_1  |       "type": "KnexTimeoutError",
directus_1  |       "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
```

### To Reproduce

See above.

### Directus Version

latest docker

### Hosting Strategy

Self-Hosted (Docker Image)
