### ISSUE TITLE
CORS configuration issue in docker-compose.yml

### ISSUE THREAD

**Issue by clye-palo** [directus/directus#19242]
### Describe the Bug

I am spinning up Directus using the configuration as shown below using my own server.
I want to call `http://<directus_cms_server>:8055` from `http://localhost:5173`.
After setting `CORS_ORIGIN` to whitelist `http://localhost:5173`, (i.e. CORS_ORIGIN: 'http://localhost:5173') I am still not able to call Directus CMS and am getting the following error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<directus_cms_server>:8055/items...
```

I have also referenced https://github.com/directus/directus/issues/12259 for help but in vain.

Anyone knows how to resolve this please?

### To Reproduce

Spin up directus from `docker-compose.yml` as follows, then create a frontend using vite to make an API call to directus CMS.
```
image: directus/directus:10.2.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    environment:
      KEY: '<key>'
      SECRET: '<secret>'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:5173'
      CORS_METHODS: 'GET,POST,PATCH,DELETE,OPTIONS'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
      CORS_MAX_AGE: '180000'

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: 'http://localhost:5173'
```

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)
