### ISSUE TITLE
Error when playing QuickTime MOV files

### ISSUE THREAD

**Issue by thoschu** [directus/directus#19268]
### Describe the Bug

In our frontend, MP4 and QuickTime MOV files are played, which are stored in Directus and persisted in an Azure Blob storage. If a .mov file is to be played in the frontend, an HTTP Error 206 and 416 occurs sporadically. No issues with MP4 files.

![error image](https://db3pap002files.storage.live.com/y4mZcwVgOKj-1oSTLKy4DW6-pKHbL39CrqFBWtwLwQNLcQAtbO1_3OZmzV4x3iNaEkOWkUEZaBJzMT28geZfTZ18bmsF7MweeL2a1rlEZReaKB4XVm00j6ZL3ys_3kdMku8Dp6-MzhpUpvuAEXwZLvpkrhWKBmgZXNNsBxbgIbStJ3PxSI-X9rWMvHH1CYrLEGM795gfMZ3wB5-2ALABpMUal6zO-8wmP8i9EckfkgyQOc?encodeFailures=1&width=499&height=148 "Error")

Video does not play and throws exception in dev tools...

### To Reproduce

1. Azure storgae account
2. Roll out directus with docker and azure configuration.

```yaml
version: "3"
networks:
  directus1:
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_directus_azure
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "directus"
    ports:
      - "3306:3306"
    networks:
      - directus1
  directus:
    image: directus/directus:latest
    container_name: directus_azure
    ports:
      - "8077:8055"
    environment:
      DIRECTUS_APP_ENV: "development1"
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      ADMIN_EMAIL: "thoschulte@gamail.com"
      ADMIN_PASSWORD: "password"
      CORS_ENABLED: true
      CORS_ORIGIN: true
      # FILE STORAGE
      STORAGE_LOCATIONS: "cloud"
      STORAGE_CLOUD_DRIVER: "azure"
      STORAGE_CLOUD_CONTAINER_NAME: "mov-file-issue-poc"
      STORAGE_CLOUD_ENDPOINT: "https://teststorage01.blob.core.windows.net"
      STORAGE_CLOUD_ACCOUNT_NAME: "teststorage01"
      STORAGE_CLOUD_ACCOUNT_KEY: "0zq6ZegxxxxxxxxxxxxxxxxxxxxxxxxesGyuMk2Q=="
    networks:
      - directus1
  directus2:
    image: directus/directus:latest
    container_name: directus_no_azure
    ports:
      - "8066:8055"
    environment:
      DIRECTUS_APP_ENV: "development2"
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      ADMIN_EMAIL: "thoschulte@gmail.com"
      ADMIN_PASSWORD: "password"
    networks:
      - directus1
```
3. Save MOV file in directus. 
4. Load the video in the frontend.

### Directus Version

v9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)
