### ISSUE TITLE
Files cannot be uploaded in a fresh docker instance.

### ISSUE THREAD

**Issue by hansluebken** [directus/directus#19291]
### Describe the Bug

I have installed the Directus Docker instance on Ubuntu 22.04 using the following example docker-compose.yml. After logging in, it is not possible to upload files within Directus.

Error message:
{
  "message": "timeout exceeded",
  "name": "AxiosError",
  "code": "ECONNABORTED",
  "config": {}
}

```
version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.4.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: 'https://directus.mydomain.de'
```

nginx reverse proxy conf:

```
server {
#   listen 443 ssl http2;
    server_name eee.xxx.de;

    # Include your SSL details here #

    location / {
        proxy_pass http://127.0.0.1:8055;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        add_header X-Cache $upstream_cache_status;

        proxy_connect_timeout 30s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 30s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        client_max_body_size 100M;  # Set your desired maximum file size here
    }

    access_log  /var/log/nginx/eee.xxx.de.log;
    error_log  /var/log/nginx/eee.xxx.de.error.log;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/eee.xxx.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/eee.xxx.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = eee.xxx.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name eee.xxx.de;
    return 404; # managed by Certbot


}
```

Any Ideas??

### To Reproduce

Trying to install a fresh Directus Docker instance with the customized example docker-compose.yml.

### Directus Version

V10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)
