### ISSUE TITLE
Docs DocSearch-Button-Key Display Error

### ISSUE THREAD

**Issue by marcellocurto** [directus/directus#19307]
### Page

https://docs.directus.io/reference/items.html

### Describe the Inaccuracy

The CMD icon in the search bar is at the wrong place.
However this seem to happen only on Safari, not with other browsers I have tested.
My Safari version is 16.5.2 (18615.2.9.11.10).
Interestingly it works on Safari Technology Preview.

I played around with the CSS a bit and what fixed it for me was to change the following from:
```css
.DocSearch-Button .DocSearch-Button-Key {
    display: block;
}
```

To:
```css
.DocSearch-Button .DocSearch-Button-Key {
    display: flex;
    padding-top: 0;
    padding-bottom: 0;
}
```

Here is a screenshot that shows how it looks for me:
<img width="203" alt="Screenshot 2023-07-31 at 15 44 18" src="https://github.com/directus/directus/assets/10226442/5835aaf4-94bf-4ad4-8012-4cf7d39c3e68">
