### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by eiacopini** [directus/directus#19533]
### Describe the Bug

I get a 502 Bad Gateway error if I try to reach domain.cloud/directus. The error is nginx connect() failed (111 connection refused) while connecting to upstream client xxxx server: domain.cloud request GET /directus HTTP/1.1 upstream http://172.18.0.7:8055/directus host: "domain.cloud"

### To Reproduce

```
directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    expose:
       - 8055
    volumes:
      - ./directus/uploads:/directus/uploads
    depends_on:
      - geonode    <-- NGINX
      - db              <-- POSTGRES
    environment:
      KEY: 'xxxxx'
      SECRET: 'xxxxxx'
      PUBLIC_URL: "https://dominio.cloud/directus/"
      NODE_ENV: production
#      HOST 127.0.0.1
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_DATABASE: "test"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      SCRIPT_NAME: /directus
      SERVE_APP: true
      ROOT_REDIRECT: ./directus/admin
      ADMIN_EMAIL: 'xxx@xxx'
      ADMIN_PASSWORD: 'password'
```

this is my conf in nginx sites-enabled

```
location /directus {
       set $upstream directus:8055;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Script-Name /directus;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_pass http://$upstream;
        proxy_redirect off;

}
```

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)
