### ISSUE TITLE
Data model is empty when trying to configure database only model

### ISSUE THREAD

**Issue by Zbaskik** [directus/directus#19564]
### Describe the Bug

Hi!
I'm using Directus with pre created database in MS SQL.
When I go to Data Model settings and try to configure database only model it returns no fields (screenshot below)
![Zrzut ekranu 2023-08-31 o 18 39 54](https://github.com/directus/directus/assets/17710635/c90bf985-1d10-418b-8679-81996b5b7f0f)

It happens only to some of the tables. When I open another one in the same database everything is working fine. (as per screenshot below)
![Zrzut ekranu 2023-08-31 o 18 55 36](https://github.com/directus/directus/assets/17710635/2cb57d5f-03a3-405a-b8b2-8d6d0f52fdaa)

Additionally, when I open this collection in Content view I get error:
```
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```
![Zrzut ekranu 2023-08-31 o 18 57 13](https://github.com/directus/directus/assets/17710635/421218cd-8cf9-42d6-86dd-c9078c1c5002)

I'm using docker compose, with latest stable version of Directus (10.6.1). I've compared permissions and sizes of table that is working and the one that is not. Permissions are the same and sizes are similar.

Thanks in advance!

### To Reproduce

1. Create docker-compose.yml file (I've replaced sensitive data with "X"):
```
version: '3'
services:
  cache:
    image: redis:6

  directus:
    image: directus/directus:10.6.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mssql'
      DB_HOST: 'XXX.XXX.X.XX'
      DB_PORT: 'XXXXX'
      DB_DATABASE: 'XXXXXX'
      DB_USER: 'XXXXX'
      DB_PASSWORD: 'XXXXXXX'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

```

2. Connect with MS SQL database
3. Try to configure database only tables

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)
