### ISSUE TITLE
Add guide for configuring third party storage locations

### ISSUE THREAD

**Issue by dnk8n** [directus/directus#19733]
### Page

https://docs.directus.io/self-hosted/config-options.html

### Describe the Inaccuracy

The docs don't explain if an extension needs to be installed or not. Googling independently I find https://www.npmjs.com/package/@directus/storage-driver-supabase and not sure if it is still needed or not.

Trying the following Dockerfile fails:

```
FROM directus/directus:10
RUN npm install @directus/storage-driver-supabase
```

From what I could find, the following environment variables should be enough:

```
  STORAGE_LOCATIONS: ...
  STORAGE_SUPABASE_SERVICE_ROLE: ...
  STORAGE_SUPABASE_BUCKET: ...
  STORAGE_SUPABASE_PROJECT_ID: ...
```

There is no indication about which of these are required or not (I had to guess that STORAGE_<LOCATION>_ENDPOINT is optional, as surely STORAGE_SUPABASE_PROJECT_ID covers it).

If I could work with someone knowledgeable, I am happy to full in the gaps. This kind of barrier to entry is not a good experience for someone new to the entire ecosystem.

**Comment by br41nslug** [comment]
> The docs don't explain if an extension needs to be installed or not. 

It doesnt explain this because extensions for storage drivers are not a thing currently (perhaps in the future). And the config options are intended to be a reference for the config options not complete guides on integration with other systems.

Having said that perhaps guides for more complex configurations like this and sso authentication for instance would not be a bad plan 🤔

**Comment by dnk8n** [comment]
I as a user, am still at a loss about how to configure my system to use Supabase as storage. Whatever words you can wright to dispel that confusion, is what deserves to be written in your docs.

Maybe I am missing something. Is it impossible to use supabase as a storage option? The docs seem to hint that it is possible.

**Comment by br41nslug** [comment]
I can't help you there unfortunately, i've never used supabase myself.

**Comment by DanielBiegler** [comment]
@dnk8n 

1. You dont need an additional package. You found our internal package that is already included in Directus, you can find them here in the repository under `/packages`. We create lots of internal packages to make our platform as extendable and flexible as possible. Building our own functionality as plugins allows us to make these available to users after enough polish. The native Supabase support was proposed in #16903 which then got implemented by our wonderful community in #19135 - you may be interested in checking those out for more context. 
2. Like you already discovered we feature the variables you need in [the docs](https://docs.directus.io/self-hosted/config-options.html#supabase-supabase).
3. Can you provide more information please? What exactly isnt working? Does Directus complain about the storage location? What happens if you try uploading a file? Maybe you can show a screen recording or logs. Are there any error messages you encounter? How do your env variables look like? We'd love to help but its difficult to diagnose your problem without any pointers whatsoever.

Cheers!

**Comment by dnk8n** [comment]
Here is my docker compose config, with some redactions:

`> docker compose config`

```
name: rethinkcode
services:
  cache:
    image: redis:7
    networks:
      default: null
  directus:
    depends_on:
      cache:
        condition: service_started
        required: true
    environment:
      ADMIN_EMAIL: dean@rethinkcode.org
      ADMIN_PASSWORD: devpassword
      DB_CLIENT: pg
      DB_DATABASE: postgres
      DB_HOST: db.***.supabase.co
      DB_PASSWORD: ***
      DB_PORT: "5432"
      DB_SSL__CA: /prod-ca-2021.crt
      DB_SSL__REJECT_UNAUTHORIZED: "false"
      DB_SSLMODE: require
      DB_USER: postgres
      KEY: ***
      PUBLIC_URL: http://localhost:8055
      SECRET: ***
      STORAGE_LOCATIONS: supabase
      STORAGE_SUPABASE_BUCKET: directus
      STORAGE_SUPABASE_PROJECT_ID: ***
      STORAGE_SUPABASE_SERVICE_ROLE: ey***
    image: directus/directus:10
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8055
      published: "8055"
      protocol: tcp
    volumes:
    - type: bind
      source: /home/dean/src/rethinkcode.org/rethinkcode/directus/uploads
      target: /directus/uploads
      bind:
        create_host_path: true
    - type: bind
      source: /home/dean/src/rethinkcode.org/rethinkcode/directus/extensions
      target: /directus/extensions
      bind:
        create_host_path: true
    - type: bind
      source: /home/dean/src/rethinkcode.org/rethinkcode/directus/prod-ca-2021.crt
      target: /prod-ca-2021.crt
      bind:
        create_host_path: true
networks:
  default:
    name: rethinkcode_default
```

And screenshotted are how my actual yaml is configured and the error I get:

![Screenshot from 2023-09-19 13-51-19](https://github.com/directus/directus/assets/3307753/06ba8161-efa1-4a1d-80b6-13c0f34be070)
![Screenshot from 2023-09-19 13-54-19](https://github.com/directus/directus/assets/3307753/34b07f2a-1864-4656-b4d3-2dd6b789ac06)
