### ISSUE TITLE
Capital letters in Collection name causes issues

### ISSUE THREAD

**Issue by dinglewanker** [directus/directus#19971]
### Describe the Bug

When creating a Collection like "LoveTable" works.  But when you go back to the DataModel page and try to add a new Field.  It gives a error.  Looks like it's it's trying to reference a lowercased .frm filename.  When the mysql filename is actually Capitalized.  Example below is looking for "lovetable.frm" when the file that created was "LoveTable.frm"  

`{
  "errors": [
    {
      "message": "alter table LoveTable add Name varchar(255) null - ER_NOT_FORM_FILE: Incorrect information in file: './mydatabase/lovetable.frm'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

### To Reproduce

Using docker compose file....

```
version: "3.8"
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}   # set the root password
      MYSQL_DATABASE: "${DB_DATABASE}"             # database name to create on startup
      MYSQL_USER: "${DB_USER}"                     # new user to create on startup
      MYSQL_PASSWORD: "${DB_PASSWORD}"             # password for the new user
    ports:
      #- ${DB_PORT}:3306
      - "127.0.0.1:${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  directus:
    image: directus/directus:10.6.3
    ports:
      - ${DUS_PORT}:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: 'zzz'     # Run `uuidgen`
      SECRET: 'zzz'  # Run `openssl rand -hex 32`
      DB_CLIENT: "mysql"              # Use MySQL as the database client
      DB_HOST: "database"             # database is the name of the database container
      DB_PORT: ${DB_PORT}
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      ADMIN_EMAIL: '${DUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DUS_ADMIN_PASSWORD}'

```

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)
