### ISSUE TITLE
Map buttons are styled as white on white

### ISSUE THREAD

**Issue by D3VL-Jack** [directus/directus#20001]
### Describe the Bug

The Buttons for the map input are styled incorrectly

Light:
![image](https://github.com/directus/directus/assets/21148384/701eff4f-4122-4828-8170-b620ed242677)

Dark:
![image](https://github.com/directus/directus/assets/21148384/96fd0263-5e00-4282-8d10-36dd187d6fee)

the issue is in class `mapbox-gl-draw_ctrl-draw-btn`
```css
.mapbox-gl-draw_ctrl-draw-btn {
    border-color: #000000e6;
    color: #ffffff80;
    width: 30px;
    height: 30px
}
```
Removing `color: #ffffff80;` fixes the issue.
as does adding this
```css
.mapbox-gl-draw_ctrl-draw-btn {
    color: unset;
}
```

Light: 
![image](https://github.com/directus/directus/assets/21148384/28fb51fc-7dea-46be-aa0a-d562c1019a09)

Dark:
![image](https://github.com/directus/directus/assets/21148384/950962d9-8b4e-4a54-9155-9ab0b7e5da91)

I'm unable to locate exactly where this style is coming. 

### To Reproduce

Open a map interface, switch between dark & light mode

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)
