### ISSUE TITLE
Insights QoL - Font CSS Var No Longer Work

### ISSUE THREAD

**Issue by ConnorSimply** [directus/directus#20061]

**Comment by ConnorSimply** [comment]
@rijkvanzanten Anything special about how fonts work with the new theming? The below no longer worls.
```css
&.sans-serif {
   font-family: var(--family-sans-serif);
}

&.serif {
    font-family: var(--family-serif);
}

&.monospace {
    font-family: var(--family-monospace);
}
```
