### ISSUE TITLE
Docker Guide doesn't work with colima

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#20088]
### Page

https://docs.directus.io/self-hosted/docker-guide.html

### Describe the Inaccuracy

When I run the `docker-compose.yml` with [colima](https://github.com/abiosoft/colima), it doesn't work.

Note: We can't use Docker Desktop [because the license](https://www.docker.com/blog/updating-product-subscriptions/).

```yml
version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.4.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
```

The error is:

```
~/Desktop/directus-colima with node(v18.16.1) ⌚ 19:44:43
$ docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:colima
[+] Running 5/0
 ✔ Network directus-colima_default                                                                                                                         Created                                                     0.0s 
 ✔ Container directus-colima-database-1                                                                                                                    Created                                                     0.0s 
 ✔ Container directus-colima-cache-1                                                                                                                       Created                                                     0.0s 
 ! database The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                             0.0s 
 ✔ Container directus-colima-directus-1                                                                                                                    Created                                                     0.0s 
Attaching to directus-colima-cache-1, directus-colima-database-1, directus-colima-directus-1
Error response from daemon: error while creating mount source path '/Users/abdonrd/Desktop/directus-colima/data/database': chown /Users/abdonrd/Desktop/directus-colima/data/database: permission denied
```

**Comment by br41nslug** [comment]
> database The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  

As the error suggests this seems to be an issue with ARM (presumably a m1 mac or something) and the Database docker. This should probably be an arm/colima issue with `postgis`.

Did you try uncommenting the M1 part? 
![image](https://github.com/directus/directus/assets/9389634/454cd534-c144-4125-b296-924308634576)

**Comment by abdonrd** [comment]
Sorry @br41nslug, I pasted the wrong log... 🤦‍♂️ 

```
~/Desktop/directus-colima with node(v18.16.1) ⌚ 7:42:28
$ docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:colima
[+] Running 3/0
 ✔ Container directus-colima-cache-1     Running                                                                                                                                                                       0.0s 
 ✔ Container directus-colima-database-1  Recreated                                                                                                                                                                     0.0s 
 ✔ Container directus-colima-directus-1  Recreated                                                                                                                                                                     0.0s 
Attaching to directus-colima-cache-1, directus-colima-database-1, directus-colima-directus-1
directus-colima-database-1  | chown: changing ownership of '/var/lib/postgresql/data': Permission denied
directus-colima-database-1 exited with code 1
directus-colima-directus-1  | 
directus-colima-directus-1  | [11:42:32.770] INFO: Initializing bootstrap...
directus-colima-directus-1  | [11:42:57.900] ERROR: Can't connect to the database.
directus-colima-directus-1  | [11:42:57.900] ERROR: getaddrinfo ENOTFOUND database
directus-colima-directus-1  |     err: {
directus-colima-directus-1  |       "type": "Error",
directus-colima-directus-1  |       "message": "getaddrinfo ENOTFOUND database",
directus-colima-directus-1  |       "stack":
directus-colima-directus-1  |           Error: getaddrinfo ENOTFOUND database
directus-colima-directus-1  |               at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
directus-colima-directus-1  |       "errno": -3008,
directus-colima-directus-1  |       "code": "ENOTFOUND",
directus-colima-directus-1  |       "syscall": "getaddrinfo",
directus-colima-directus-1  |       "hostname": "database"
directus-colima-directus-1  |     }
directus-colima-directus-1 exited with code 1
```

The error I wanted to show was the database volume error:
```
chown: changing ownership of '/var/lib/postgresql/data':
```

Fixed if we remove this:
```yml
volumes:
  - ./data/database:/var/lib/postgresql/data
```

But of course, we would lose the data...

**Comment by br41nslug** [comment]
Yeah removing it isnt really a fix 😂 Double check your permissions on the database folder, I cannot attest to specific colima things tho as im not familiar with the software and it is not explicitly supported.

**Comment by abdonrd** [comment]
> Yeah removing it isnt really a fix 😂 

Exactly! Haha
I mentioned that only to reflect that the problem is related to the volume.

**Comment by rijkvanzanten** [comment]
@abdonrd I similarly have no experience with Colima, but could you check if it has any special requirements for the "network" settings in the docker compose file? That error indicates to me that the directus container can't reach the database under hostname `database`. Docker makes that hostname available in their networking setup based on the name of the key in the file, but I don't know if colima matches that behavior

**Comment by abdonrd** [comment]
> @abdonrd I similarly have no experience with Colima, but could you check if it has any special requirements for the "network" settings in the docker compose file?

As far as I know, no.
In fact, if I just comment the database volume on this line, everything works fine.

```yml
version: '3'
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    # volumes:
    #   - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
  directus:
    image: directus/directus:10.4.0
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
```

> That error indicates to me that the directus container can't reach the database under hostname `database`. Docker makes that hostname available in their networking setup based on the name of the key in the file, but I don't know if colima matches that behavior

But I think that the error of not being able to connect to the database is due to the previous error:

```
chown: changing ownership of '/var/lib/postgresql/data': Permission denied
```
