### ISSUE TITLE
OAuth2 with VK provder: Code challenge method is unsupported

### ISSUE THREAD

**Issue by dbelyaeff** [directus/directus#20189]
### Describe the Bug

Trying to implement VK.com as OAuth provider. 

Get error:
```
{
"error": "invalid_request",
"error_description": "Code challenge method is unsupported"
}
```

If there any way to remove code challenge from OAuth authorize url?

### To Reproduce

```yaml
      AUTH_PROVIDERS: "vk"
      AUTH_VK_ICON: "vk"
      AUTH_VK_LABEL: "VK"
      AUTH_VK_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_VK_IDENTIFIER_KEY: "email"
      AUTH_VK_DRIVER: "oauth2"
      AUTH_VK_SCOPE: "email"
      AUTH_VK_CLIENT_ID: "string:<ID>"
      AUTH_VK_CLIENT_SECRET: "<SECRET>"
      AUTH_VK_AUTHORIZE_URL: "https://oauth.vk.com/authorize?client_id=<ID>"
      AUTH_VK_ACCESS_URL: "https://api.vk.com/oauth/token"
      AUTH_VK_PROFILE_URL: "https://vk.com/settings"
      AUTH_VK_PARAMS: "display=page"
```

### Directus Version

v10.7

### Hosting Strategy

Self-Hosted (Docker Image)
