### ISSUE TITLE
"PM2 error" flooding log

### ISSUE THREAD

**Issue by bstrr** [directus/directus#20243]
### Describe the Bug

When using the official 10.7.1 docker image on DigitalOcean's App Platform, PM2 is flooding the log with:

```
PM2 error: Error: ESPIPE: invalid seek, read
PM2 error: Error caught while calling pidusage
```

My guess is the user 'node' does not have the rights to pull usage-info on the PID. I don't know if it is an issue outside of DigitalOcean's App Platform.

There was no issue or similar issues prior to PM2 being introduced (just for good measure).

### To Reproduce

Run the official 10.7.1 docker image (on DigitalOcean's App Platform).

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
@bstrr Can you try adding the `PIDUSAGE_USE_PS=true` environment variable? From what I can tell in this `pm2` issue https://github.com/Unitech/pm2/issues/4360#issuecomment-1374375430 your hunch is correct: PM2 attempts to use something that DigitalOcean App Platform explicitly denies.

**Comment by bstrr** [comment]
That causes log-flooding with the following:

```
2023-10-30T18:35:01: PM2 error: Error caught while calling pidusage
2023-10-30T18:35:01: PM2 error: Error: ps: unrecognized option: p
BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.
 
Usage: ps [-o COL1,COL2=HEADER] [-T]
 
Show list of processes
 
       -o COL1,COL2=HEADER     Select columns for display
       -T                      Show threads

```

**Comment by StephenGunn** [comment]
this is happening on v10.7.2 - both with and without the environment variable change

**Comment by jonathan-np-dev** [comment]
I can confirm, 10.7.2 logs flooded with these errors. 

Running on Digitalocean App Platform.

**Comment by danielduckworth** [comment]
I am getting the same log flooding.

**Comment by hamilton-lima** [comment]
Same error on 10.8.0

**Comment by getglad** [comment]
> after doing the proper setup the error is gone.

@hamilton-lima - would you mind what you configured as the proper setup? I'm lost how the `PM2_PUBLIC_KEY`/`PM2_SECRET_KEY` would be known at container start up

**Comment by paescuj** [comment]
It seems like DigitalOcean provides a limited/different procfs on their platform and `pidusage` struggles with that one.
This issue can usually be circumvented by setting `PIDUSAGE_USE_PS=true`, but `pidusage` doesn't work with `ps` the Directus image comes with (BusyBox since we're running on Alpine).
A solution would be to build a customized image with a `ps` implementation that works with `pidusage` and use that on DigitalOcean:
```Dockerfile
FROM directus/directus:10.8.1

USER root
RUN apk --no-cache add procps
USER node

ENV PIDUSAGE_USE_PS=true
```

Seems to work locally. Could you confirm it works on DigitalOcean too?

(Ideally, this would be addressed on `pidusage`'s / `pm2`'s side 😇)

**Comment by hamilton-lima** [comment]
> > after doing the proper setup the error is gone.
> 
> @hamilton-lima - would you mind what you configured as the proper setup? I'm lost how the `PM2_PUBLIC_KEY`/`PM2_SECRET_KEY` would be known at container start up

Some overall comments about my setup
- I  have two directus running to test effects of changes to the schema and how to apply the changes to a second Directus
- This is a local setup for tests only :)
- The schema.yml file contains the most updated version of the schema exported from the main Directus
- The Dockerfile is changed to apply the schema before starting Directus
- The KEY and SECRET environment variables I mentioned are in the `local.env` file, could be done in the `docker-compose.yaml` as well, But I like this way :)

Here are the files

docker-compose.yml
```
version: '2.2'
services:
  database-play:
    platform: linux/x86_64
    container_name: database-play
    image: mysql:8.0.28
    env_file: local.env
    volumes:
      - mysql-volume-local-play:/var/lib/mysql
      - ./_settings/local-database-setup-scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - '3360:3306'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  cache-play:
    container_name: cache-play
    image: redis:6
    ports:
      - 6379:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    extra_hosts:
      - 'host.docker.internal:host-gateway'      

  directus:
    container_name: directus
    build:
      context: ./directus
    image: mhc/local/directus
    environment:
      - DB_DATABASE=directus
      - DB_USER=directus
      - DB_PASSWORD=directus
    env_file: local.env
    restart: always
    ports:
      - 8055:8055
    volumes:
      - directus-local-play:/directus/database
      - directus-local-play:/directus/uploads
      - directus-local-play:/directus/extensions
      - directus-local-play:/directus/snapshots
    depends_on:
      - database-play
      - cache-play
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  directus2:
    container_name: directus2
    build:
      context: ./directus
    image: mhc/local/directus
    environment:
      - DB_DATABASE=directus2
      - DB_USER=directus2
      - DB_PASSWORD=directus2
    env_file: local.env
    restart: always
    ports:
      - 2055:8055
    volumes:
      - directus-local-play2:/directus/database
      - directus-local-play2:/directus/uploads
      - directus-local-play2:/directus/extensions
      - directus-local-play2:/directus/snapshots
    depends_on:
      - database-play
      - cache-play
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  mysql-volume-local-play:
  directus-local-play:
  directus-local-play2:
```

local.env
```
MYSQL_HOST=database
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=local
MYSQL_USER=localuser
MYSQL_PASSWORD=localuser

PUBLIC_URL=http://localhost:8055
DB_CLIENT=mysql
DB_HOST=database-play
DB_PORT=3306
CACHE_ENABLED=true
CACHE_STORE=redis-play
CACHE_REDIS=redis://redis-play:6379
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=admin
KEY=79920737-3b71-4c23-937e-ac5989826706
SECRET=c6aa2a8d-60c4-4ddc-8e79-8267d5ee9b89
```

snapshot.sh
```
#!/bin/bash
docker exec -it directus npx directus schema snapshot /directus/snapshots/schema.yml
docker cp directus:/directus/snapshots/schema.yml .
```

Dockerfile
```
FROM directus/directus:10.8.1
COPY schema.yml /directus/schema.yml

CMD : \
    && node cli.js bootstrap \
    && node cli.js schema apply --yes /directus/schema.yml \
    && pm2-runtime start ecosystem.config.cjs \
    ;
```
