### ISSUE TITLE
Extension auto-reload not work for new way of creating extensions

### ISSUE THREAD

**Issue by MarvinXu** [directus/directus#20380]
### Describe the Bug

> the old way:
./extensions/\<extension-type>/\<extension-name>/index.js
or the new way
./extensions/directus-extension-\<extension-name>/package.json

Setting `EXTENSIONS_AUTO_RELOAD: true`  works for the old way of creating extension, but not work for the new way. See Reproduce Steps.

### To Reproduce

```yml
version: "3"
services:
  directus:
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      EXTENSIONS_AUTO_RELOAD: true
```
```bash
docker compose up
# error for permission reasons. folders auto created.
sudo chown -R marv:marv database extensions uploads
cd extensions 
npx create-directus-extension@latest
cd directus-extension-test
npm run dev

# open another terminal
docker compose up
# change extension code and save, no effect in the console

# open another terminal
mkdir extensions/hooks/test1
vi extensions/hooks/test1/index.js
# save. then in directus log shows 'Reloading extensions'. both two hooks' changes are shown
```

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)
