### ISSUE TITLE
EMAIL_SENDGRID_API_KEY is not correctly forwarded

### ISSUE THREAD

**Issue by mario4rma** [directus/directus#20430]
### Describe the Bug

I try to send the "Reset Password" template with sendgrid. 
Everything is set up in the config, but I receive a 401 from sendgrid

this is the error that I receive
```
{
    "errors": [{
        "message": "The provided authorization grant is invalid, expired, or revoked",
        "field": null,
        "help": null
    }]
}
```

Here is the part of the evn config
```
PUBLIC_URL="https://cms.mydomain.at/"

#Security
PASSWORD_RESET_URL_ALLOW_LIST="https://cms.mydomain.at/admin/reset-password"

LOG_LEVEL="debug"
LOG_STYLE="raw"

EMAIL_VERIFY_SETUP=true
EMAIL_FROM="directus@mydomain.at"
EMAIL_TRANSPORT="sendgrid"
EMAIL_SENDGRID_API_KEY="SG.XXXX.YYYYY50"
``` 

The API-KEY is correct I can use it with cURL without problems.
I also double checked the spelling of the env_vars.

The error message that I receive from sendgrid can only be reproduced when I enter a wrong API_KEY.
Neither wrong headers nor a missing API-KEY results in the above mentioned error.
- It looks like that the directus API is somehow messing up the provided API-KEY
or
- there is an CORS issue because in the error response there is also this, and they mention this URL [https://sendgrid.com/docs/Classroom/Basics/API/cors.html](https://sendgrid.com/docs/Classroom/Basics/API/cors.html)
```
  message: "[email] Unauthorized (401)\n  The provided authorization grant is invalid, expired, or revoked\n    null\n    null"
    err: {
      "type": "ResponseError",
      "message": "Unauthorized",
      "stack":
          Error: Unauthorized
              at Request._callback (node_modules/@sendgrid/clientclasses/client.js:124:25)
              at self.callback (node_modules/request/request.js:185:22)
              at Request.emit (node:events:517:28)
              at Request.<anonymous> (node_modules/request/request.js:1154:10)
              at Request.emit (node:events:517:28)
              at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
              at Object.onceWrapper (node:events:631:28)
              at IncomingMessage.emit (node:events:529:35)
              at endReadableNT (node:internal/streams/readable:1368:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "code": 401,
      "response": {
  "headers": {
          "server": "nginx",
          "date": "Wed, 15 Nov 2023 12:40:43 GMT",
          "content-type": "application/json",
          "content-length": "116",
          "connection": "close",
          "access-control-allow-origin": "https://sendgrid.api-docs.io",
          "access-control-allow-methods": "POST",
          "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
          "access-control-max-age": "600",
          "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html",
          "strict-transport-security": "max-age=600; includeSubDomains"
        },
        "body": {
          "errors": [
            {
              "message": "The provided authorization grant is invalid, expired, or revoked",
              "field": null,
              "help": null
            }
          ]
        }
      }
    }
```

### To Reproduce

- Fresh installation of directus 
- Create Sendgrid Free Account
- Add PASSWORD_RESET_URL_ALLOW_LIST and EMAIL_SENDGRID_API_KEY to your env
- try the "Forgot password" from the login screen

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mario4rma** [comment]
Thanks for the response. 
Just set up everything again on my local machine.
This is my docker-compose

```
version: "3"
services:
  directus:
    image: directus/directus:10.7.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "accounts.digital@test.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      EMAIL_VERIFY_SETUP: true
      EMAIL_FROM: "directus@mydomain.com"
      EMAIL_TRANSPORT: "sendgrid"
      EMAIL_SENDGRID_API_KEY: "SG.xxx50"
```
and you are right, everything is working as expected. 
But as soon as I deployed this to my GoogleCloud Environment (CloudRun) I receive the mentioned error.

I just added the CORS theory because it was mentioned in the response, so I thought maybe CloudRun is messing up some headers.

I just redeployed everything to CloudRun and now everything is working. 
Finally I found the issue - the sendgrid-api-key was replaced by a CloudRun Env variable which had the wrong value 🤦
