### ISSUE TITLE
CLI create-directus-extension not installing dependencies inside docker image

### ISSUE THREAD

**Issue by vpedrosa** [directus/directus#20533]
### Describe the Bug

When trying to create a bundle extension in fresh project, CLI command create-directus-extension does not install dependencies properly inside docker image.
Output:
```
/directus/extensions/directus-extension-bundle-clockify $ npm run add

> directus-extension-bundle-clockify@1.0.0 add
> directus-extension add

sh: directus-extension: not found
```

### To Reproduce

Create new directus instance with default docker compose:

```
version: "3"
services:
  database:
    image: postgres:16-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
```

Exec bash in terminal `docker compose exec directus -it /bin/sh`
Then navigate to extensions, create new one (`npx create-directus-extension@latest`) (tested with bundle and endpoint) and try to run any npm commands. 

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)
