### ISSUE TITLE
After successfully installing directus with Docker on Windows, cannot restart it

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20805]
### Describe the Bug

I successfully installed directus with Docker on Windows, and worked with it to create collections, etc.
It worked like a charm :)

The installation was made from an adaptation of https://docs.directus.io/self-hosted/quickstart.html
```
version: "3"
services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: "127.0.0.1"
      DB_PORT: "5432"
      DB_DATABASE: "mydb"
      DB_USER: "postgres"
      DB_PASSWORD: "mypassword"
      DB_SSL: "false"
      WEBSOCKETS_ENABLED: true

```

But after restarting the computer, I'm unable to access to http://localhost:8055/ despite running
>docker compose up --detach --force-recreate
[+] Running 3/3
 ✔ Container directus-database-1  Started 
 ✔ Container directus-cache-1     Started                                                                                                                                                    
 ✔ Container directus-directus-1  Started

Second:
From my docker-compose.yml, the postgresql db was installed  in C:\directus\data\database\base
and the Docjer logs say that it found it and is connected to it.
But I can't see the DB in pgAdmin4.
I use triggers and need to have access to the DB.
Should I have installed it in C:\Program Files\PostgreSQL\16\data with?
`- ./data/database:/Program Files/PostgreSQL/16/data
`
But as it is installed in  C:\directus\data\database\base and contains some work,
how do I transfer it from C:\directus\data\database\base to reimport it in C:\Program Files\PostgreSQL\16\data?

### To Reproduce

Install Docker on Windows 11
Create the docker-compose.yml above
Run Docker
It works

But after restarting the computer, and running
`docker compose up --detach --force-recreate`
`http://localhost:8055/` does not work

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)
