### ISSUE TITLE
Directus cant build without empty extension directories

### ISSUE THREAD

**Issue by emrahaydemir** [directus/directus#20973]
### Describe the Bug

Hi, i just tried to build directus from my ubuntu server with docker. i added 2 extensions i developed for hook and endpoint. i cloned my repo with git. i tried to build my .yml file with docker compose but i got an error that directus could not load the extensions folder.

`.yml` file
```
version: "3"
services:
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "hidden"
      SECRET: "hidden"
      ADMIN_EMAIL: "hidden"
      ADMIN_PASSWORD: "hidden"
      DB_CLIENT: "pg"
      DB_HOST: "hidden"
      DB_SSL__REJECT_UNAUTHORIZED: false
      DB_PORT: 12345
      DB_USER: "hidden"
      DB_PASSWORD: "hidden"
      DB_DATABASE: "directus"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET, POST, PUT, PATCH, DELETE"
      CORS_HEADERS: "content-type"
      CORS_EXPOSED_HEADERS: ""
      CORS_MAX_AGE: "0"
      CORS_CREDENTIALS: "false"

```

```
ERROR: Failed to sync extensions
ERROR: Extension folder "/directus/extensions/interfaces" couldn't be opened
    err: {
      "type": "Error",
      "message": "Extension folder \"/directus/extensions/interfaces\" couldn't be opened",
      "stack":
          Error: Extension folder "/directus/extensions/interfaces" couldn't be opened
              at ensureExtensionDirs (file:///directus/node_modules/.pnpm/file+packages+extensions_vue@3.3.4/node_modules/@directus/extensions/dist/node.js:11:13)
              at async ExtensionManager.load (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:137:13)
              at async ExtensionManager.initialize (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/extensions/manager.js:123:13)
              at async loadExtensions (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/cli/load-extensions.js:17:5)
              at async createCli (file:///directus/node_modules/.pnpm/file+api_vue@3.3.4/node_modules/@directus/api/dist/cli/index.js:20:5)
    }

```

since i just built my server i thought it was a problem with directory access at first. i checked access but no problem. then i thought it might be a version issue and i updated my directus version but again the problem was not solved. on my personal pc all configurations looked fine. then i noticed that when i was committing with github it was ignoring empty folders in the extensions folder. so in the directus directory on my server there were only 2 extension directories (hooks & endpoints). i immediately **added the .gitkeep file to all empty extension** directories and **the problem was solved**. 

![Screenshot 2024-01-05 132414](https://github.com/directus/directus/assets/35865864/afc3316d-523f-4220-a5b3-499eb73f19c1)

### To Reproduce

Just like in the development environment, directus should ignore empty directories in the extensions directory when building. if these directories cannot be found, it should exhibit "empty directory" behaviour.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)
