### ISSUE TITLE
Loading extensions from external storage Supabase not working

### ISSUE THREAD

**Issue by ArcherTrent** [directus/directus#21098]
### Describe the Bug

I try to make an external loading of extensions (and also emails templates as they are in the extensions folder on local extensions) from Supabase but nothing is fetched.
I can upload and retrieve files through Directus application into Supabase bucket, so I assume this part is well configured.
If I set a EXTENSIONS_PATH with a non existing folder in supabase bucket, I got well an error, so I assume the folder 'directus_extensions' in the bucket is well found.
I **do** see [this trace](https://github.com/directus/directus/blob/8d4b57168a4e98416b7dd30f439ba49ac1f8a07e/api/src/extensions/lib/sync-extensions.ts#L55) in the logs.

ps: email template seems not working with external storage, as the external storage folder is fetched why not taking also the emails templates this way?

### To Reproduce

I'm using a pure Directus image from docker-hub v10.8.3 on DigitalOcean App.
Database and storage are on Supabase.
I'm using this extension: https://github.com/utomic-media/directus-extension-field-actions
![image](https://github.com/directus/directus/assets/4159124/2f594171-52d2-455d-997a-bfee7f4e196f)
![image](https://github.com/directus/directus/assets/4159124/d2d849f1-b200-420d-8d80-ae5347d059f1)

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
> I do **not** see [this trace](https://github.com/directus/directus/blob/8d4b57168a4e98416b7dd30f439ba49ac1f8a07e/api/src/extensions/lib/sync-extensions.ts#L55) in the logs.

I assume you have `LOG_LEVEL` set to `trace`. [^1]
Are there any other anomalies in the logs?
Is the server starting, erroring out or hanging forever?

https://docs.directus.io/self-hosted/config-options.html#general

**Comment by paescuj** [comment]
Okay, so far so good 😄👍

I think it is intended that the extensions (`directus_extensions` folder) is directly uploaded into the storage location (Supabase bucket in your case), that is not via Directus. Could you try that?

**Comment by ArcherTrent** [comment]
I already uploaded the folders on this screenshot via Supabase webapp, not through Directus assets (and therefore they kept their original names and not 'uuid names' from Directus.
![image](https://github.com/directus/directus/assets/4159124/124f03a6-0ecf-47a1-accd-a25e408a5307)

**Comment by Natetronn** [comment]
I've been testing this as well, without success. Everything else seems to work fine, however. This is the docker-compose.yml I was using (with minor edits to test with). No extensions show up in the Settings > Extensions, however.

```
version: "3"
services:
  directus:
    container_name: directus
    image: directus/directus:10.8.3
    # build:
    #   context: ./
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
     #  - ./uploads:/directus/uploads
     # - ./extensions:/directus/extensions
      - ./temp:/directus/temp
    environment:
      KEY: "63eef6e0-888a-429d-9a55-6276ee5d7c2c"
      SECRET: "c1101a3c-817b-40c8-a223-1f8716728451"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "123"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      TEMP_PATH: "./temp"
      STORAGE_LOCATIONS: "supabase"
      STORAGE_SUPABASE_DRIVER: "supabase"
      STORAGE_SUPABASE_ROOT: ""
      STORAGE_SUPABASE_HEALTHCHECK_THRESHOLD: 750
      STORAGE_SUPABASE_SERVICE_ROLE: "<admin_service_role>"
      STORAGE_SUPABASE_BUCKET: "directus"
      STORAGE_SUPABASE_PROJECT_ID: "<project_id>"
      # STORAGE_SUPABASE_ENDPOINT:
      EXTENSIONS_PATH: "./extensions" # also tried /extensions and extensions (the latter gives me an error)
      EXTENSIONS_MUST_LOAD: false
      EXTENSIONS_AUTO_RELOAD: true
      # EXTENSIONS_CACHE_TTL: ""
      EXTENSIONS_LOCATION: "supabase"
```
You can see it uploaded the favicon to root fine, so supabase was setup correctly. I have an extension (that is working fine otherwise) located in extensions directory. I also tested extension installation via Dockerfile and that worked fine as well; I could see the extension was in the settings.

![image](https://github.com/directus/directus/assets/582149/f212323f-b4a8-4ae7-86a9-44f2d1164f89)

I set `LOG_LEVEL` to trace, but I'm not seeing anything out of the ordinary (no errors, anyway).
