### ISSUE TITLE
After installing successfully with docker, can't see the modifications although correctly logged

### ISSUE THREAD

**Issue by Pachat** [directus/directus#21100]
### Describe the Bug

When updating the user or creating a collection, Directus says that it updates or create.
But nothing is updated nor created (Page not found) despite the fact that Activity correctly shows the logs

In fact, if i create in a collection "first" (=> Page not found) and I don't see it in the collections list.
If then i again create the collection "first", I get `[INVALID_PAYLOAD] Invalid payload. Collection "first" already exists.`
So I stop docker and restart it with `docker compose up`
Then I see the "first" collection in the collections list.

I looks like that it registers but cannot read the modifications made during the session.

### To Reproduce

Install with Docker (I based my installation on https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose)
```

version: "3"
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "AVNS_y73uLmmQY73UvRE"
      POSTGRES_DB: "joie"

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "..."
      SECRET: "..."

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "mydb"
      DB_USER: "postgres"
      DB_PASSWORD: "my password"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "...@..."
      ADMIN_PASSWORD: "..."

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
      # PUBLIC_URL="http://localhost:8033"

      # PRESSURE (for Cypress)
      PRESSURE_LIMITER_ENABLED: "false"

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    #      - .env

```

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)
