### ISSUE TITLE
Error: getaddrinfo ENOTFOUND database

### ISSUE THREAD

**Issue by tburd** [directus/directus#21253]
### Describe the Bug

Hello all!

I am trying to setup Directus with traefik, and I am using the docker-compose reference from the Docs.
I have seen similar issues here and in forums, but none of the proposed solutions helped me solving this.

I cannot understand why there is a problem with the database connection.
Any ideas or suggestions?

```
root@server_erdtr:~/directus# docker compose up
[+] Running 3/3
 ✔ Container directus-cache-1     Created                                                                                                                                  0.0s
 ✔ Container directus-database-1  Recreated                                                                                                                                0.1s
 ✔ Container directus-directus-1  Recreated                                                                                                                                0.1s
Attaching to directus-cache-1, directus-database-1, directus-directus-1
directus-cache-1     | 1:C 30 Jan 2024 19:04:34.265 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
directus-cache-1     | 1:C 30 Jan 2024 19:04:34.265 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
directus-cache-1     | 1:C 30 Jan 2024 19:04:34.265 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.272 * monotonic clock: POSIX clock_gettime
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * Running mode=standalone, port=6379.
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 # Server initialized
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * Loading RDB produced by version 6.2.14
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * RDB age 3192 seconds
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * RDB memory usage when created 0.77 Mb
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 # Done loading RDB, keys loaded: 0, keys expired: 0.
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * DB loaded from disk: 0.000 seconds
directus-cache-1     | 1:M 30 Jan 2024 19:04:34.274 * Ready to accept connections
directus-database-1  | The files belonging to this database system will be owned by user "postgres".
directus-database-1  | This user must also own the server process.
directus-database-1  |
directus-database-1  | The database cluster will be initialized with locale "en_US.utf8".
directus-database-1  | The default database encoding has accordingly been set to "UTF8".
directus-database-1  | The default text search configuration will be set to "english".
directus-database-1  |
directus-database-1  | Data page checksums are disabled.
directus-database-1  |
directus-database-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
directus-database-1  | creating subdirectories ... ok
directus-database-1  | selecting dynamic shared memory implementation ... posix
directus-database-1  | selecting default max_connections ... 100
directus-database-1  | selecting default shared_buffers ... 128MB
directus-database-1  | selecting default time zone ... Etc/UTC
directus-database-1  | creating configuration files ... ok
directus-database-1  | running bootstrap script ... ok
directus-database-1  | performing post-bootstrap initialization ... ok
directus-database-1  | syncing data to disk ... ok
directus-database-1  |
directus-database-1  | initdb: warning: enabling "trust" authentication for local connections
directus-database-1  | You can change this by editing pg_hba.conf or using the option -A, or
directus-database-1  | --auth-local and --auth-host, the next time you run initdb.
directus-database-1  |
directus-database-1  | Success. You can now start the database server using:
directus-database-1  |
directus-database-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
directus-database-1  |
directus-database-1  | waiting for server to start....2024-01-30 19:04:35.871 UTC [49] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
directus-database-1  | 2024-01-30 19:04:35.873 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
directus-database-1  | 2024-01-30 19:04:35.881 UTC [50] LOG:  database system was shut down at 2024-01-30 19:04:35 UTC
directus-database-1  | 2024-01-30 19:04:35.892 UTC [49] LOG:  database system is ready to accept connections
directus-database-1  |  done
directus-database-1  | server started
directus-database-1  | CREATE DATABASE
directus-database-1  |
directus-database-1  |
directus-database-1  | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/10_postgis.sh
directus-database-1  | CREATE DATABASE
directus-database-1  | Loading PostGIS extensions into template_postgis
directus-database-1  | CREATE EXTENSION
directus-database-1  | CREATE EXTENSION
directus-database-1  | You are now connected to database "template_postgis" as user "postgres".
directus-database-1  | CREATE EXTENSION
directus-database-1  | CREATE EXTENSION
directus-database-1  | Loading PostGIS extensions into directus
directus-database-1  | CREATE EXTENSION
directus-database-1  | CREATE EXTENSION
directus-database-1  | You are now connected to database "directus" as user "postgres".
directus-database-1  | CREATE EXTENSION
directus-database-1  | CREATE EXTENSION
directus-database-1  |
directus-database-1  | waiting for server to shut down...2024-01-30 19:04:41.951 UTC [49] LOG:  received fast shutdown request
directus-database-1  | .2024-01-30 19:04:41.954 UTC [49] LOG:  aborting any active transactions
directus-database-1  | 2024-01-30 19:04:41.962 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
directus-database-1  | 2024-01-30 19:04:41.963 UTC [51] LOG:  shutting down
directus-database-1  | 2024-01-30 19:04:42.109 UTC [49] LOG:  database system is shut down
directus-database-1  |  done
directus-database-1  | server stopped
directus-database-1  |
directus-database-1  | PostgreSQL init process complete; ready for start up.
directus-database-1  |
directus-database-1  | 2024-01-30 19:04:42.212 UTC [1] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
directus-database-1  | 2024-01-30 19:04:42.218 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
directus-database-1  | 2024-01-30 19:04:42.221 UTC [1] LOG:  listening on IPv6 address "::", port 5432
directus-database-1  | 2024-01-30 19:04:42.223 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
directus-database-1  | 2024-01-30 19:04:42.228 UTC [72] LOG:  database system was shut down at 2024-01-30 19:04:42 UTC
directus-database-1  | 2024-01-30 19:04:42.236 UTC [1] LOG:  database system is ready to accept connections
directus-directus-1  | Error: getaddrinfo ENOTFOUND database
directus-directus-1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
directus-directus-1  |   errno: -3008,
directus-directus-1  |   code: 'ENOTFOUND',
directus-directus-1  |   syscall: 'getaddrinfo',
directus-directus-1  |   hostname: 'database'
directus-directus-1  | }
directus-directus-1 exited with code 1
```

### To Reproduce

Run $ docker-compose up

docker-compose.yml
```
version: "3"
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "directus"

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    networks:
      - proxy
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec4022"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e264"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "postgres"
      DB_PASSWORD: "password"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "MYEMAIL@gmail.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: "https://directus.MYDOMAIN.com"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directus.rule=Host(`directus.MYDOMAIN.com`)"
      - "traefik.http.routers.directus.entrypoints=websecure"
      - "traefik.http.services.directus.loadbalancer.server.port=8055"
      - "traefik.http.routers.directus.service=directus"

networks:
  proxy:
    external: true

```

### Directus Version

v.10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)
