### ISSUE TITLE
Unable to connect to existing local PostgreSQL database using directus

### ISSUE THREAD

**Issue by Yogesh7920** [directus/directus#21398]
### Describe the Bug

I have a local PostgreSQL database hosted by Supabase docker compose. When I run the following command I am able to connect to the database

` psql -h localhost -p 5432 -U postgres `

But when I try to connect using self hosted directus it doesn't work.
I am getting the following error 

```
directus-directus-1  | Error: connect ECONNREFUSED 127.0.0.1:5432
directus-directus-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
directus-directus-1  |   errno: -111,
directus-directus-1  |   code: 'ECONNREFUSED',
directus-directus-1  |   syscall: 'connect',
directus-directus-1  |   address: '127.0.0.1',
directus-directus-1  |   port: 5432
directus-directus-1  | }
```

The following is the directus docker compose file

```
version: "3"
services:
  directus:
    image: directus/directus:10.9.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      DB_CLIENT: "pg"
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "your-super-secret-and-long-postgres-password"
      WEBSOCKETS_ENABLED: "true"
```

### To Reproduce

Have an already self-hosted PostgreSQL, and try to use Directus over it. 

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)
