### ISSUE TITLE
Unable to use Google to authenticate

### ISSUE THREAD

**Issue by rfos** [directus/directus#21462]
### Describe the Bug

After changing the default provider to Google, I'm unable to login in Directus.
From the terminal I see the following error:

```
[11:27:19.428] WARN: [OpenID] Failed to register user. User not unique
    err: {
      "type": "",
      "message": "Value for field \"email\" in collection \"directus_users\" has to be unique.",
      "stack":
          DirectusError: Value for field "email" in collection "directus_users" has to be unique.
              at UsersService.checkUniqueEmails (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/services/users.js:47:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async UsersService.createMany (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/services/users.js:166:17)
              at async UsersService.createOne (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/services/users.js:154:24)
              at async OpenIDAuthDriver.getUserID (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/auth/drivers/openid.js:171:13)
              at async AuthenticationService.login (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/services/authentication.js:43:22)
              at async file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/auth/drivers/openid.js:286:28
      "name": "DirectusError",
      "extensions": {
        "collection": "directus_users",
        "field": "email"
      },
      "code": "RECORD_NOT_UNIQUE",
      "status": 400
    }
[11:27:19.774] WARN: Invalid provider.
    err: {
      "type": "",
      "message": "Invalid provider.",
      "stack":
          DirectusError: Invalid provider.
              at OpenIDAuthDriver.getUserID (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/auth/drivers/openid.js:176:23)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async AuthenticationService.login (file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/services/authentication.js:43:22)
              at async file:///var/www/mydomain.com/teste-docker/node_modules/@directus/api/dist/auth/drivers/openid.js:286:28
      "name": "DirectusError",
      "code": "INVALID_PROVIDER",
      "status": 403
    }
```

This is the docker-compose.yml

```
version: "3"
services:
  directus:
    image: directus/directus:10.9.2 
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      KEY: "dc09f96f-42be-4c6c-90de-8403a8a4bba5"
      SECRET: "7EvI8LJkZBkC9mzqLZux87EgBVVY16Hl"
      ADMIN_EMAIL: "reinaldo.ferro@gmail.com"
      ADMIN_PASSWORD: "XXXXXX"
      WEBSOCKETS_ENABLED: "true"
      PUBLIC_URL: "https://api.XXXXXX.com"
      AUTH_PROVIDERS: "google"
      AUTH_GOOGLE_DRIVER: "openid"
      AUTH_GOOGLE_CLIENT_ID: "XXXXXXXXXX-c09uf8s581v337ashr9c4rjoeerg39ev.apps.googleusercontent.com"
      AUTH_GOOGLE_CLIENT_SECRET: "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" # Replace XXXX with the Client Secret from Step 6
      AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
      AUTH_GOOGLE_IDENTIFIER_KEY: "email"
      AUTH_GOOGLE_ICON: "google"
      AUTH_GOOGLE_SCOPE: "email"
      AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true" # This allows users to be automatically created on logins. Use "false" if you want to create users manually
      AUTH_GOOGLE_DEFAULT_ROLE_ID: "XXXXXXXX-4269-41d7-a01c-a0a07c9d0c83" # Replace XXXX with the role ID you would want      

```
<img width="649" alt="Screenshot 2024-02-18 at 12 32 33" src="https://github.com/directus/directus/assets/217889/74a60a6f-ed14-4564-87b5-d354c9e14d8a">

### To Reproduce

After install docker image I can access Directus using the default ADMIN user (explicit in ADMIN_EMAIL and ADMIN_PASSWORD.

Go to Directus Users management, change the default provider to Google, logout and try to login again I received the error:

`User belongs to a different auth provider`

### Directus Version

10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)
