### ISSUE TITLE
`/schema/diff` ignores new field to be created

### ISSUE THREAD

**Issue by JohJonker** [directus/directus#21486]
### Describe the Bug

When `POST`ing an updated YAML schema to `/schema/diff?force`, the diffing algorithm does not identify the below new field (`collections`) as missing, i.e. needing to be added. It is excluded from the diff response returned and so the change is ignored when then applying the diff.

Here is a minimal representation of the schema YAML I'm sending to `/schema/diff`. The new field I'm hoping to create is 'collections' on the 'categories' collection:

```yaml
version: 1
directus: 9.23.4
vendor: mysql
collections:
- collection: categories
  ...
- collection: articles
  ...
- collection: projects
  ...
- collection: clients
  ...
fields:
- collection: categories
  field: blurb
  ...
- collection: categories
  field: collections
  type: json
  meta:
    collection: categories
    conditions: null
    display: null
    display_options: null
    field: collections
    group: null
    hidden: false
    interface: select-multiple-checkbox
    note: Limit this category to only be used for specific content.
    options:
      choices:
        - text: Articles
          value: articles
        - text: Projects
          value: projects
        - text: Clients
          value: clients
      itemsShown: 30
    readonly: false
    required: true
    sort: 1
    special:
      - cast-json
    translations: null
    validation: null
    validation_message: null
    width: full
  schema:
    name: collections
    table: categories
    data_type: longtext
    default_value:
      - insights
      - showcases
      - indicators
    max_length: 4294967295
    numeric_precision: null
    numeric_scale: null
    is_nullable: true
    is_unique: false
    is_primary_key: false
    is_generated: false
    generation_expression: null
    has_auto_increment: false
    foreign_key_table: null
    foreign_key_column: null
```

Here is a minimal representation of the response returned from `/schema/diff`:

```json
{
    "data": {
        "hash": "###",
        "diff": {
            "collections": [
                {
                    "collection": "categories",
                    "diff": [
                        {
                            "kind": "D",
                            "path": [
                                "meta",
                                "preview_url"
                            ],
                            "lhs": null
                        },
                        {
                            "kind": "D",
                            "path": [
                                "meta",
                                "versioning"
                            ],
                            "lhs": false
                        }
                    ]
                },
            ],
            "fields": [],
            "relations": []
        }
    }
}
```

What I've tried, without any change in the result:
1. Updating the `directus` version in the YAML to match the server's version and omitting the `?force` parameter when making the API call.
2. Converting the YAML schema to JSON and trying to diff based on that.
3. Updating the field's `display` value to see if that triggers the diff.

Other notes that may be relevant:
1. I have a moderately large number of collections (29), fields (371) and relations (69) in total. The only new field is the one above, i.e. all the others are present on the server.

### To Reproduce

I appreciate the reproducing this will be hard. Here is my guess:

1. Set up a Directus instance with a number of collections and fields, including a 'categories' collection.
2. Export a schema dump with `/schema/snapshot?export=yaml`.
3. Modify the schema YAML to include the above new field `collections` on the `categories` collection.
4. Diff the updated schema against the server with `/schema/diff?force`.
5. See that the new field is omitted from the returned diff.

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)
