### ISSUE TITLE
Import endpoint returns 403 forbidden since 10.9.1 (even being admin)

### ISSUE THREAD

**Issue by 8byr0** [directus/directus#21491]
### Describe the Bug

In some cases, importing a csv file in a collection results in 403 forbidden response. 

It occurs both on the datastudio app and the api.

After spending hours experimenting I decided to downgrade to 10.8.3, working. Then 10.9.0: working. And from 10.9.1 it happens.

I checked the changelog and noticed a PR about permissions check: #21152

Context:
- It happened first on a VPS self hosted instance
- I replicated locally (see below)
- I am doing it with my admin account
- It works as expected using 10.8.3 and 10.9.0

### To Reproduce

# Setup a clean environment:

```yaml
# docker-compose.yaml
version: '3.3'
services:
  dev-pg-db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  directus-debug:
    container_name: directus-debug
    image: directus/directus:10.9.2
    ports:
      - 8056:8055
    depends_on:
      - dev-pg-db
    links:
      - dev-pg-db
    environment:
      LOG_LEVEL: "trace"
      LOGGER_LEVEL: "trace"
      KEY: "255d86db-5da1-5e96-faa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8044f45e263"
      DB_CLIENT: "pg"
      DB_HOST: "dev-pg-db"
      DB_PORT: "5432"
      DB_DATABASE: "directus-debug"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      CONTENT_SECURITY_POLICY_DIRECTIVES__CONNECT_SRC: "'self' https://* http://* http://localhost:7700"

      CACHE_ENABLED: "false"
      ADMIN_EMAIL: "mail@domain.com"
      ADMIN_PASSWORD: "Password123!"

volumes:
  pg_data:
    driver: local
```

## Create a collection 
> I reused the same fields as in my real project):
id: auto incremented int
sort, user_created, user_updated, date_created, date_updated: all default fields
name_fr: string
name_en: string
description_fr: multiline string
description_en: multiline string
is_online: boolean
kind_of_selection: dropdown with a single choice having value "selection-standard"

![image](https://github.com/directus/directus/assets/21955112/ce21c076-9469-49e7-8e88-471ab05e479c)

## Go to your collection page and import sample dataset
Use the following dataset to import into your collection
<details>
<summary>sample_data.csv</summary>

### CSV content

```csv
id;name_fr
1;name_fr
2;name_fr
3;name_fr
4;name_fr
5;name_fr
6;name_fr
7;name_fr
8;name_fr
9;name_fr
10;name_fr
11;name_fr
12;name_fr
13;name_fr
14;name_fr
15;name_fr
16;name_fr
17;name_fr
18;name_fr
19;name_fr
20;name_fr
21;name_fr
22;name_fr
23;name_fr
24;name_fr
25;name_fr
26;name_fr
27;name_fr
28;name_fr
29;name_fr
30;name_fr
31;name_fr
32;name_fr
33;name_fr
34;name_fr
35;name_fr
36;name_fr
37;name_fr
38;name_fr
39;name_fr
40;name_fr
41;name_fr
42;name_fr
43;name_fr
44;name_fr
45;name_fr
46;name_fr
47;name_fr
48;name_fr
49;name_fr
50;name_fr
51;name_fr
52;name_fr
53;name_fr
54;name_fr
55;name_fr
56;name_fr
57;name_fr
58;name_fr
59;name_fr
60;name_fr
61;name_fr
62;name_fr
63;name_fr
64;name_fr
65;name_fr
66;name_fr
67;name_fr
68;name_fr
69;name_fr
70;name_fr
71;name_fr
72;name_fr
73;name_fr
74;name_fr
75;name_fr
76;name_fr
77;name_fr
78;name_fr
79;name_fr
80;name_fr
81;name_fr
82;name_fr
83;name_fr
84;name_fr
85;name_fr
86;name_fr
87;name_fr
88;name_fr
89;name_fr
90;name_fr
91;name_fr
92;name_fr
93;name_fr
94;name_fr
95;name_fr
96;name_fr
97;name_fr
98;name_fr
99;name_fr
100;name_fr
101;name_fr
102;name_fr
103;name_fr
104;name_fr
105;name_fr
106;name_fr
107;name_fr
108;name_fr
109;name_fr
110;name_fr
111;name_fr
112;name_fr
113;name_fr
114;name_fr
115;name_fr
116;name_fr
117;name_fr
118;name_fr
119;name_fr
120;name_fr
121;name_fr
122;name_fr
123;name_fr
124;name_fr
125;name_fr
126;name_fr
127;name_fr
128;name_fr
129;name_fr
130;name_fr
131;name_fr
132;name_fr
133;name_fr
134;name_fr
135;name_fr
136;name_fr
137;name_fr
138;name_fr
139;name_fr
140;name_fr
141;name_fr
142;name_fr
143;name_fr
144;name_fr
145;name_fr
146;name_fr
147;name_fr
148;name_fr
149;name_fr
150;name_fr
151;name_fr
152;name_fr
153;name_fr
154;name_fr
155;name_fr
156;name_fr
157;name_fr
158;name_fr
159;name_fr
```

</details>

## Get a forbidden message
![image](https://github.com/directus/directus/assets/21955112/b3128b88-b343-440a-8066-c1f00e75720a)

### Server logs
```sh
[17:50:51] POST /utils/import/selections 403 33ms
[17:50:51.330] TRACE: [0.546ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [7ae5e655-2ff7-4dba-b0a3-5ecda6094416, 1]
[17:50:51.359] DEBUG: You don't have permission to access this.
    err: {
      "type": "",
      "message": "You don't have permission to access this.",
      "stack":
          DirectusError: You don't have permission to access this.
              at validateKeys (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/utils/validate-keys.js:18:19)
              at ItemsService.upsertOne (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/services/items.js:611:13)
              at file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.19/node_modules/@directus/api/dist/services/import-export.js:98:38
              at /directus/node_modules/.pnpm/async@3.2.5/node_modules/async/dist/async.js:151:38
              at /directus/node_modules/.pnpm/async@3.2.5/node_modules/async/dist/async.js:4018:13
              at Object.process (/directus/node_modules/.pnpm/async@3.2.5/node_modules/async/dist/async.js:1681:21)
              at /directus/node_modules/.pnpm/async@3.2.5/node_modules/async/dist/async.js:1533:23
              at /directus/node_modules/.pnpm/async@3.2.5/node_modules/async/dist/async.js:74:45
              at node:internal/process/task_queues:140:7
              at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
      "name": "DirectusError",
      "code": "FORBIDDEN",
      "status": 403
    }
```

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)
