### ISSUE TITLE
Email not initializing

### ISSUE THREAD

**Issue by lulezi** [directus/directus#21550]
### Describe the Bug

On startup, no entry regarding email setup status is logged, even though I set `EMAIL_VERIFY_SETUP: true`. Also, no emails are sent.

### To Reproduce

I'm using the following `docker-compose.yml`:

```yml
version: "3"

services:
  directus:
    image: directus/directus:10.9.3
    container_name: directus
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      PUBLIC_URL: "${PUBLIC_URL}"
      # ADMIN_EMAIL: "admin@example.com"
      # ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      EMAIL_VERIFY_SETUP: true
      EMAIL_FROM: "info@example.com" # the actual email
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "smtp.postmarkapp.com"
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_SECURE: false
      EMAIL_SMTP_IGNORE_TLS: true
      EMAIL_SMTP_USER: "smtp-user" # the actual smtp user (UUID)
      EMAIL_SMTP_PASSWORD: "smtp-password" # the actual smtp password (UUID)
```

### Directus Version

10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)
