### ISSUE TITLE
Image preview broken when serving Directus from subdirectory

### ISSUE THREAD

**Issue by girtskokars** [directus/directus#21815]
### Describe the Bug

Starting from v10.10.0, in most instances, the assets are requested using an absolute path, ignoring the subdirectory Directus is served from, e.g, `http://localhost/assets/xxx` not `http://localhost/subdirectory/assets/xxx`

### To Reproduce

Serve Directus from subdirectory, e.g., using reverse proxy.

### docker-compose.yml
```
services:
  directus:
    container_name: subdirectory-directus
    image: directus/directus:10.10.2
    restart: unless-stopped
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: xxx
      SECRET: xxx
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/db.sqlite
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      PUBLIC_URL: http://localhost/directus

  caddy:
    container_name: subdirectory-caddy
    image: caddy/caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
```

### Caddyfile
```
:80 {
  redir /directus /directus/

  handle /directus/* {
    uri strip_prefix /directus
    reverse_proxy directus:8055
  }
}
```

### Directus Version

v10.10.3

### Hosting Strategy

Self-Hosted (Docker Image)
