### ISSUE TITLE
QUERY_LIMIT_DEFAULT breaks Flows

### ISSUE THREAD

**Issue by koljam** [directus/directus#22038]
### Describe the Bug

When setting the environment variable QUERY_LIMIT_DEFAULT to -1 the flows screen breaks: The operations array is empty, so the flow doesn't have a starting operation. This results in the screen (and also the processing of the flow) to stop after the initial trigger, because there are no operations in the operations array.

### To Reproduce

```
  directustest:
    image: directus/directus:10.10.4
    environment:
      KEY: "key"
      SECRET: "secret_key"
      DB_CLIENT: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: directus_test
      DB_USER: root
      DB_PASSWORD: password
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'
      FLOWS_RUN_SCRIPT_TIMEOUT: 30000
      QUERY_LIMIT_DEFAULT: -1
      PUBLIC_URL: "http://api.directus.test"
    depends_on:
      - mysql
      - traefik
    networks:
      - traefik-proxy
```

1. Set up a docker container similar to the one above
2. Try to set up an example flow (e.g. CRON -> Log to Console)
3. Save
4. See the "Log to Console"-Operation vanish
5. Remove the  QUERY_LIMIT_DEFAULT: -1
6. Try steps 1-3 again and see it work

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)
