### ISSUE TITLE
Websocket disconecting after auth status Ok

### ISSUE THREAD

**Issue by Simerca** [directus/directus#22177]
### Describe the Bug

Hi ! I Hope your fine,
I have a problem with Websocket on directus Self Hosted: 
The websocket disconect after authentification 2 second after the connection open
```shell
directus-dev-directusdev-1  | [18:16:17.628] DEBUG: WebSocket#268bbcc5-aa50-4fff-b0dc-19d693fa2bb9 connected
directus-dev-directusdev-1  | [18:16:17.628] TRACE: WebSocket#268bbcc5-aa50-4fff-b0dc-19d693fa2bb9 authenticated as {"user":"7372f72c-8d5e-44ae-840e-da0b3e2f602c","role":"8a2f3ca1-46da-4b1c-a1b5-f3261d577f6c","admin":true,"app":true}
directus-dev-directusdev-1  | [18:16:19.627] DEBUG: WebSocket#268bbcc5-aa50-4fff-b0dc-19d693fa2bb9 connection closed
```
 
Auth ping say Ok, but WS is disconnecting every time without error
```shell
{"type":"auth", "access_token":"xxxx"}
{"type":"auth","status":"ok"}
```

This is my Docker-compose.yml

```
services:
  directusdev:
    image: directus/directus:10.10.4
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - web
    restart: always
    ports:
      - 8056:80
    environment:
      PORT: 80
      KEY: 'XX'
      SECRET: 'XX'
      ADMIN_EMAIL: 'X@XX'
      ADMIN_PASSWORD: 'XXX!'
      DB_CLIENT: 'mysql'
      DB_HOST: 'XXX'
      DB_PORT: '3306'
      DB_DATABASE: 'XXX'
      DB_USER: 'XX'
      DB_PASSWORD: 'XX'
      WEBSOCKETS_ENABLED: true
      CORS_ENABLED: true
      CORS_METHODS: GET,POST,PATCH,DELETE
      PRESSURE_LIMITER_ENABLED: false
      LOG_LEVEL: 'trace'
 ```

### To Reproduce

- directus/directus:10.10.4
- enable websocket
- connect on it

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)
