### ISSUE TITLE
Restart VM , Directus in Docker 

### ISSUE THREAD

**Issue by cyrsis** [directus/directus#22185]
### Describe the Bug

Every time restart the VM,

Directus start with following errors

```
06:10:27.142] WARN: [system-cache] Error: getaddrinfo EAI_AGAIN cache
    err: {
      "type": "Error",
      "message": "getaddrinfo EAI_AGAIN cache",
      "stack":
          Error: getaddrinfo EAI_AGAIN cache
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
      "errno": -3001,
      "code": "EAI_AGAIN",
      "syscall": "getaddrinfo",
      "hostname": "cache"
    }
```

### To Reproduce

Restart Virtual Machine

Directus in itself with following docker compose

```
version: '3.7'
services:
  cache:
    image: redis:6
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    restart: always
    volumes:
      - ./data/extensions:/directus/extensions
      - ./data/uploads:/directus/uploads
      - ./data/database:/directus/database
    depends_on:
      - cache
    environment:
      PUBLIC_URL: 'https://somedomain.com'
      KEY: '255d861b-2bd4-4c8c-8422-dfbbc1e02bb9'  # replace this with your own key
      SECRET: '6116487b-cda1-4f59-8f46-3c8249447144'  # replace this with your own secret
      DB_CLIENT: 'pg'
      DB_HOST: '192.168.41.42'
      DB_PORT: '5432'
      DB_DATABASE: 'postgres'
      DB_USER: 'admin'
      DB_PASSWORD: 'admin'
      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'


```

Then error is  when do docker logs XXX

Error is

```
06:10:27.142] WARN: [system-cache] Error: getaddrinfo EAI_AGAIN cache
    err: {
      "type": "Error",
      "message": "getaddrinfo EAI_AGAIN cache",
      "stack":
          Error: getaddrinfo EAI_AGAIN cache
              at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
      "errno": -3001,
      "code": "EAI_AGAIN",
      "syscall": "getaddrinfo",
      "hostname": "cache"
    }
```

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I think it's because you've set `restart: always` on the `directus` service but not on the `cache`. This means after a VM restart, only the former services is started again.

You should be able to fix this by adding the `restart` option to the `cache` service as well:
```yaml
# ...
  cache:
    image: redis:6
    restart: always
# ...
```
