### ISSUE TITLE
I can't create items using the REST API

### ISSUE THREAD

**Issue by maxacarvalho** [directus/directus#22451]
### Describe the Bug

Hi,

I'm trying out Directus using Docker to see if it will be a good fit for my needs.
I have a very basic project running locally.

I created one collection called `payloads`. The collection has one field, `input`, and it's set as mandatory.

Now, I'm trying to use the REST API to create an item. It won't work, it gives me an error saying the required field `input` is not present.
If I change the field to be optional I can create the item but the payload is not recognised.

Here's the cURL request (I'm using Postman):
```bash
curl --location 'http://localhost:8055/items/payloads' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer rxRy-AS39AfvUd-1OWgHT7ZQ5OlFS5B-' \
--data '{
    "input": {
        "test": "test"
    }
}'
```

And the response:
```json
{
    "errors": [
        {
            "message": "Validation failed for field \"input\". Value is required.",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "input",
                "type": "required"
            }
        }
    ]
}
```

### Start a new self-hosted project

Here's my docker-compose schema:
```yaml
services:
  app:
    image: directus/directus:10
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - mysql
    environment:
      KEY: "integra-hub"
      SECRET: "integra-hub"
      ADMIN_EMAIL: "integra-hub@integra-hub.com"
      ADMIN_PASSWORD: "secret"
      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: "integra-hub"
      DB_USER: "integra-hub"
      DB_PASSWORD: "secret"
      WEBSOCKETS_ENABLED: "true"
    networks:
      - integra-hub

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'integra-hub'
      MYSQL_USER: 'integra-hub'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - database:/var/lib/mysql
    networks:
      - integra-hub

networks:
  integra-hub:
    driver: bridge

volumes:
  database:
    driver: local
```

## Create a collection
- Name: `payloads`
- Fields:
  - id
  - date_created
  - date_updated
  - input (`JSON` | `required`)

## Use Postman to send a request

curl --location 'http://localhost:8055/items/payloads' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer rxRy-AS39AfvUd-1OWgHT7ZQ5OlFS5B-' \
--data '{
    "input": {
        "test": "test"
    }
}'

### Directus Version

v10.11.00

### Hosting Strategy

Self-Hosted (Docker Image)
