### ISSUE TITLE
System relations appear in schema snapshot

### ISSUE THREAD

**Issue by stuikomma** [directus/directus#22843]
### Describe the Bug

When bootstrapping a brand new directus instance and then dumping the schema (`/directus/cli.js schema snapshot`), you get two system relations that should be ignored.

```yaml
version: 1
directus: 10.12.1
vendor: postgres
collections: []
fields: []
relations:
  - collection: directus_settings
    field: public_registration_role
    related_collection: directus_roles
    meta: null
    schema:
      table: directus_settings
      column: public_registration_role
      foreign_key_table: directus_roles
      foreign_key_column: id
      constraint_name: directus_settings_public_registration_role_foreign
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: directus_webhooks
    field: migrated_flow
    related_collection: directus_flows
    meta: null
    schema:
      table: directus_webhooks
      column: migrated_flow
      foreign_key_table: directus_flows
      foreign_key_column: id
      constraint_name: directus_webhooks_migrated_flow_foreign
      on_update: NO ACTION
      on_delete: SET NULL
```

Expected:
```yaml
version: 1
directus: 10.12.1
vendor: postgres
collections: []
fields: []
relations: []
```

### To Reproduce

1. start directus instance from scratch
2. take a schema snapshot
3. resulting file should contain no relations

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.4
