### ISSUE TITLE
v11.0.0-rc3. In Docker, 'filename' env is incompatible with MySQL2

### ISSUE THREAD

**Issue by cliqer** [directus/directus#22969]
### Describe the Bug

This is the warning in the console when using mariadb:
```terminal
Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```

### Directus Version

`v11.0.0-rc.3`

### Hosting Strategy

Docker

### Database

MariaDB

**Comment by br41nslug** [comment]
Do you happen to have an unused `DB_FILENAME` setting in your environment?

**Comment by paescuj** [comment]
@br41nslug This is a result of https://github.com/directus/directus/blob/08095a293a437f8d6c97592caea52e04217b1b30/Dockerfile#L56

**Comment by br41nslug** [comment]
Ah so it's specifically in the docker image that explains why i couldnt repro it locally.

**Comment by paescuj** [comment]
Fixed in #22970 👍

**Comment by sonyarianto** [comment]
I upgrade Directus from previous version 10.x to 11 and that warning still there

`service-directus    | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection`

I am using Docker and mysql2.

```
service-directus:
    container_name: service-directus
    image: directus/directus # https://hub.docker.com/r/directus/directus
    volumes:
      - volume-directus:/directus/database
      - volume-directus-uploads:/directus/uploads
      - volume-directus-extensions:/directus/extensions
    environment:
      KEY: xxx
      SECRET: xxx
      ADMIN_EMAIL: xxx
      ADMIN_PASSWORD: xxx
      DB_CLIENT: mysql2
      DB_HOST: service-mysql
      DB_DATABASE: xxx
      DB_USER: xxx
      DB_PORT: 3306
      DB_PASSWORD: xxx
      CACHE_ENABLED: true
      CACHE_STORE: redis
      CACHE_TTL: 3000
      CACHE_AUTO_PURGE: true
      REDIS: redis://service-redis:6379
      CACHE_HOST: service-redis
      PUBLIC_URL: https://xxx
    networks:
      - network-infra
    depends_on:
      service-mysql:
        condition: service_healthy
```

Is that related data on volume still not updated maybe?
