### ISSUE TITLE
Media / Files uploaded with tus protocol breaks the upload functionality

### ISSUE THREAD

**Issue by navanshu** [directus/directus#23091]
### Describe the Bug

Uploading any file when tus is enabled the endpoint doesn't return the id maybe so the Client app missies the id

here are requests that are made in the browser
![image](https://github.com/user-attachments/assets/bba3d867-e45b-41fc-bae5-354ee69e6304)
![image](https://github.com/user-attachments/assets/1c256114-477a-494a-a143-a292b55e570e)
![image](https://github.com/user-attachments/assets/c2d5d3d5-296e-4a04-b994-497b8dd7801e)
![image](https://github.com/user-attachments/assets/a13dbaa7-5925-4d05-ad5d-7065e739b865)

### To Reproduce

here is the env of my directus
```yaml
      DB_CLIENT: pg
      DB_HOST: ------------
      REFRESH_TOKEN_COOKIE_SECURE: true
      HSTS_ENABLED: true
      CORS_ENABLED: true
      CORS_ORIGIN: -----------
      CORS_CREDENTIALS: true
      REDIS_ENABLED: true
      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: 'redis'
      REDIS: -------------------
      #
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 10000
      #
      TUS_ENABLED: true
      #
      STORAGE_LOCATIONS: minio
      STORAGE_MINIO_DRIVER: s3
      #
      STORAGE_MINIO_KEY: -------------
      STORAGE_MINIO_SECRET: ----------
      STORAGE_MINIO_BUCKET: ----------
      STORAGE_MINIO_ENDPOINT: ----------
      STORAGE_MINIO_REGION: us-east-1
      STORAGE_MINIO_S3_FORCE_PATH_STYLE: true
      #
      WEBSOCKETS_ENABLED: true
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: --------
      #
      PRESSURE_LIMITER_ENABLED: false
      MAX_RELATIONAL_DEPTH: 15
      PM2_INSTANCES: 3
```

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres:15.2
