### ISSUE TITLE
Official docker image for directus:10.13.3 claims it belongs to directus:10.13.2

### ISSUE THREAD

**Issue by aramcheck** [directus/directus#23637]
### Describe the Bug

When you start an environment that uses "directus:10.13.3" the logs and Directus console claims it belongs to 10.13.2. The images seems to be different but it's difficult to be sure that we're running the intended version.

![Screenshot 2024-09-11 at 9 36 08 AM](https://github.com/user-attachments/assets/db7282b8-1176-4281-a82f-50c8bd6d4fbc)
![Screenshot 2024-09-11 at 9 37 00 AM](https://github.com/user-attachments/assets/82dc962d-24d8-44a8-b558-7bd55211f805)

### To Reproduce

Follow the simple self-hosting quick start using a docker compose file similar to the one below:

```
services:
  directus:
    image: directus/directus:10.13.3
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"

```

Start the environment (`docker compose up`).

Verify that logs and console claim it is Directus 10.3.2.

### Directus Version

v10.13.3

### Hosting Strategy

Self-Hosted (Docker Image)
