### ISSUE TITLE
Upload File failed

### ISSUE THREAD

**Issue by miauyo** [directus/directus#23659]
### Describe the Bug

[FAILED_VALIDATION] Validation failed for field "uploaded_on". Value is required.

### To Reproduce

When I upload a file
![image](https://github.com/user-attachments/assets/c2283c33-98ed-49df-acda-eb79d06df850)

### Directus Version

11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql8

**Comment by paescuj** [comment]
I think that is a result of the failing migration in #23647, as the `uploaded_on` field is now missing.

You can either try to manually create the missing table column in your database

```sql
alter table directus_files add uploaded_on timestamp
```

or you could also run the migration again [^1]
```shell
# Create a database backup first!

# Repeat until the "Update files date fields" migration has been undone
npx directus database migrate:down

# Then repeat until all outstanding migrations have been applied again
npx directus database migrate:up
```

As I assume that this is the cause, I'll close this issue for now. Happy to keep discussing in this thread, and we'll reopen if it turns out to be a different problem 👍🏻

[^1]: https://docs.directus.io/self-hosted/upgrades-migrations.html#downgrading-a-project

**Comment by HemboPagi** [comment]
i have the  _uploaded_on_ field present, but still getting this error

**Comment by mvillamizar74** [comment]
Hi, I have just installed Directus 11.1.1 on MariaDB, it has field uploaded_on present, but I am getting the same error

**Comment by AKhateeb** [comment]
Me too same error, anyone can help us resolving the issue :(

**Comment by paescuj** [comment]
We couldn't reproduce this so far. In order for us to be able to help, we need a reproducible setup. Thanks!

---

The `compose.yaml` file used when trying to reproduce the issue:
```yaml
services:
  database:
    image: mariadb:11.5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_DATABASE: "directus"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
```
