### ISSUE TITLE
On production: FATAL:  role "directus" does not exist

### ISSUE THREAD

**Issue by BorisKamp** [directus/directus#23753]
### Describe the Bug

On production my postgres service in docker keeps logging the following:
`postgis.directus.cebv.nl   | 2024-09-27 13:40:00.833 UTC [277] FATAL:  role "directus" does not exist`
This is outputted every ten seconds.

Any clue what this might be?

### To Reproduce

This is my docker compose file:
```
...
  postgis:
    container_name: postgis.directus.cebv.nl
    image: postgis/postgis:16-master
    restart: unless-stopped  
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data
    env_file: .env.postgis
    ports:
      - 5432:5432    
    networks: 
      - cebv-portal-net
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
...
```

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres 16
