### ISSUE TITLE
Threading failure

### ISSUE THREAD

**Issue by haerth** [directus/directus#23885]
### Describe the Bug

I have Directus running via Docker (see configuration). The PostgreSQL database runs remotely via Neon.tech. The server runs for several days without any problems until I realize that I can no longer log in. I see the usual login screen, but I get an error when logging in. On the server I then see an “ERROR: Threading failure”. The server is somehow stuck in this state and I can't figure out how this happened. After a restart everything works as normal again. I suspect that something is building up over time. Maybe some cache is full or I'm simply overlooking something important?

My remote Postgre does not show any open or idle connections, I had also tried several configurations for the connection here (without success).

Do you have any ideas? 

My Docker Configuration:
```
services:
  directus:
    image: 'directus/directus:11.1.0'
    volumes:
      - './uploads:/directus/uploads'
      - './extensions:/directus/extensions'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - '${PUBLIC_URL}/admin/login'
      interval: 120s
      timeout: 60s
      retries: 1
    environment:
      PORT: 8055
      PUBLIC_URL: '${PUBLIC_URL}'
      TELEMETRY: false
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'
      ADMIN_EMAIL: example@example.com
      ADMIN_PASSWORD: '${ADMIN_PASS}'
      DB_CLIENT: pg
      DB_CONNECTION_STRING: '${DB_URL}'
      DB_POOL__MIN: 0
      DB_POOL__MAX: 100
      DB_POOL__DESTROY_TIMEOUT_MILLIS: 1000
      DB_POOL__IDLE_TIMEOUT_MILLIS: 500
      DB_POOL__REAP_INTERVAL_MILLIS: 500
      DB_POOL__CREATE_RETRY_INTERVAL_MILLIS: 500
      WEBSOCKETS_ENABLED: false
      STORAGE_LOCATIONS: s3
      STORAGE_S3_DRIVER: s3
      STORAGE_S3_KEY: '${AWS_ACCESS_KEY_ID}'
      STORAGE_S3_SECRET: '${AWS_SECRET_ACCESS_KEY}'
      STORAGE_S3_BUCKET: '${S3_BUCKET_NAME}'
      STORAGE_S3_REGION: eu-central-1
      STORAGE_S3_ENDPOINT: s3.amazonaws.com
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 10000
      HASH_PARALLELISM: 2
      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      QUERY_LIMIT_DEFAULT: -1
      LOGGER_HTTP_USE_LEVEL: trace
      LOGGER_LEVEL: trace
```

Error message after login attempt on the Directus login page:
```
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

The error on the server:
<img width="1721" alt="Screenshot 2024-08-25 at 22 58 03" src="https://github.com/user-attachments/assets/c43c81bd-4666-441c-ad74-27491e3a968e">

### To Reproduce

I haven't found an answer to this yet, which makes testing a bit hard at the moment. I've had the error again and again for a good 6 months and haven't been able to find a way to provoke it.

### Directus Version

10.13.0 -> 11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL via Neon
