### ISSUE TITLE
Double mustaches in Update Data operation's payload and IDs lead to errors for non-admin users

### ISSUE THREAD

**Issue by RawmanGrey** [directus/directus#24025]
### Describe the Bug

Flow with event hook blocking items updates (at least in my use case) has to end with requested update. To achieve that, I use "Update Data" operation: by toggling raw editor and entering `{{$trigger.keys}}` to "IDs" field and `{{$trigger.payload}}` to "Payload" field. Update Data operation takes permissions from trigger. 

Problem is, if flow is triggered by update initiated by non-admin user*, it results in 403 error: `"You don't have permission to access field \"0\" in collection \"collection\" or it does not exist. Queried in root."`. Despite the error, update is applied to item. 

I suppose, this is related to #23989 

* User has all required permissions to alter collection and can do so if flow is disabled.

### To Reproduce

I was able to reproduce this issue on below docker compose:
```
name: test-directus

services:
  postgis:
    container_name: test--postgis
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  directus:
    image: directus/directus:11.2.1
    container_name: test--directus
    ports:
      - 8055:8055
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - KEY=secret
      - SECRET=secret
      - ADMIN_EMAIL=admin@mail.com
      - ADMIN_PASSWORD=password
      - DB_CLIENT=pg
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVE_APP=true

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8055/server/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  default:
    name: test-network
```
To reproduce:
1) Log into admin account and create "test" collection with simple text input field "name". Create item there.
2) Create new flow, triggered by item update in "test" collection. Choose blocking type.
2.2) Add Update Data operation, choose "test" collection, click on "{}" button next to "IDs" field and input `{{$trigger.keys}}` there. click on "{}" button next to "Payload" field and enter `{{$trigger.payload}}` there. Save Flow.  
3) Create new user, grant him permissions to perform updates on "test" collection. 
4) Login to new user, try updating item and witness error.

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis:16-3.4
