### ISSUE TITLE
Required property is not available in the openAPI schema

### ISSUE THREAD

**Issue by Zyles** [directus/directus#24121]
### Describe the Bug

I am using codegen to generate the frontend interface based on the OpenAPI schema at `/server/specs/oas`  using the NPM package `swagger-typescript-api`.

In the OpenAPI documentation regarding the required flags <https://swagger.io/docs/specification/v3_0/data-models/data-types/> we can read:

```
Required Properties
By default, all object properties are optional. You can specify the required properties in the required list:

type: object
properties:
  id:
    type: integer
  username:
    type: string
  name:
    type: string
required:
  - id
  - username

Note that required is an object-level attribute, not a property attribute:

type: object
properties:
  id:
    type: integer
    required: true # Wrong!

required: # Correct
  - id

An empty list required: [] is not valid. If all properties are optional, do not specify the required keyword.
```

Looking at my generated schema from Directus I do not see any required properties for the object:
```
ItemsJobs:
      type: object
      properties:
        id:
          nullable: false
          type: string
          format: uuid
        status:
          nullable: false
          type: string
        sort:
          nullable: true
          type: integer
 
...

      x-collection: jobs
  parameters:
```

The required flag only exists on the parameters property.

This creates optional interfaces which is incorrect after codegen. Example:
```
export interface ItemsJobs {
  /** @format uuid */
  id?: string;
  status?: string;
  sort?: number | null;

...

}
```

The solution:

Add required property on the collections properties property to mark required fields for proper automatic codegen.

### To Reproduce

1. Create collection
2. Add fields and mark them as required
3. Run codegen using `swagger-typescript-api` or check the schema source
4. Fields are marked as optional

### Directus Version

11.2.2

### Hosting Strategy

Self-Hosted (Docker Image)
