### ISSUE TITLE
Unable to attach debugger for custom extensions

### ISSUE THREAD

**Issue by Ayo91** [directus/directus#24209]
### Page

https://docs.directus.io/self-hosted/docker-guide.html

### Describe the Inaccuracy

Do you know how to debug extensions? A few days invested trying to debug custom extensions and almost impossible. Im running directus on docker and using visual studio code. Anyone is able to debug? I had read a lot on github, internet but anything help me here...
```
Docker-compose main config:
version: "3"
services:
  directus:
    image: directus/directus:11.2.2
    ports:
      - 8055:8055
      - "9229:9229"  # Debugger
    volumes:
      - ./database:/directus/database:rw
      - ./uploads:/directus/uploads:rw
      - ./extensions:/directus/extensions
```
Visual studio code launch.json file:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Directus",
      "port": 9229,
      "address": "localhost",
      "localRoot": "${workspaceFolder}/extensions",
      "remoteRoot": "/directus/extensions",
      "restart": true,
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
  ]
}
```
It seems that the debugger is attached in a proper way because the docker logs show: "-directus-1  | Debugger attached."

However, the breakpoints in my custom extension api are not working. Support is welcome, thanks a lot.

Other hint:
If I add a breakpoint in the dist folder, in the compiled typescript api file and add a breakpoint there, they are reachable but only when  the docker container start. If I do an api call, not stop anymore
