### ISSUE TITLE
PostgreSQL Error During Deployment via Coolify

### ISSUE THREAD

**Issue by korayguler** [directus/directus#24216]
### Describe the Bug
When deploying a Docker Compose file via Coolify, I encounter the following error in PostgreSQL logs. This error also appears when using postgis:13

`ERROR: constraint "directus_comments_collection_foreign" of relation "directus_comments" does not exist
`

Questions
- Does this error cause any problems for my setup, or can it be safely ignored?
- Why does Directus recommend using PostGIS?

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PosgreSQL

![image](https://github.com/user-attachments/assets/af054c5d-ce99-4616-8b61-c9791d59cde3)

### Docker Compose
```

version: '3.8'
services:
  directus:
    image: 'directus/directus:11.3.2'
    restart: unless-stopped
    ports:
      - '${DIRECTUS_PORT}:8055'
    volumes:
      - 'directus-uploads:/directus/uploads'
      - 'directus-extensions:/directus/extensions'
      - 'directus-templates:/directus/templates'
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'
      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PASSWORD}'
      PUBLIC_URL: '${DIRECTUS_PUBLIC_URL}'
      DB_CLIENT: '${DB_CLIENT}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      CACHE_ENABLED: '${CACHE_ENABLED}'
      CACHE_STORE: '${CACHE_STORE}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      WEBSOCKETS_ENABLED: '${WEBSOCKETS_ENABLED}'
      CORS_ENABLED: '${CORS_ENABLED}'
      CORS_ORIGIN: '${CORS_ORIGIN}'
      RATE_LIMITER_ENABLED: '${RATE_LIMITER_ENABLED}'
      RATE_LIMITER_STORE: '${RATE_LIMITER_STORE}'
      RATE_LIMITER_POINTS: '${RATE_LIMITER_POINTS}'
      RATE_LIMITER_DURATION: '${RATE_LIMITER_DURATION}'
      EMAIL_FROM: '${EMAIL_FROM}'
      EMAIL_TRANSPORT: '${EMAIL_TRANSPORT}'
      EMAIL_SMTP_HOST: '${EMAIL_SMTP_HOST}'
      EMAIL_SMTP_PORT: '${EMAIL_SMTP_PORT}'
      EMAIL_SMTP_USER: '${EMAIL_SMTP_USER}'
      EMAIL_SMTP_PASSWORD: '${EMAIL_SMTP_PASSWORD}'
      EMAIL_SMTP_SECURE: '${EMAIL_SMTP_SECURE}'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:8055/admin/login'
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - directus
  postgresql:
    image: 'postgres:17.2-alpine'
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - 'directus-postgresql-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}'
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - directus
  redis:
    image: 'redis:7.4.1-alpine'
    restart: unless-stopped
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    volumes:
      - 'directus-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '-a'
        - '${REDIS_PASSWORD}'
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - directus
volumes:
  directus-uploads: null
  directus-extensions: null
  directus-templates: null
  directus-postgresql-data: null
  directus-redis-data: null
networks:
  directus:
    name: directus_network

```
