### ISSUE TITLE
Files table uploaded_on has an incorrect default

### ISSUE THREAD

**Issue by robertgroot-paqt** [directus/directus#24226]
### Describe the Bug

When running the migrations using mysql 5.7, the result of the `directus_files` table column `uploaded_on` is a zero date `0000-00-00 00:00:00` instead of `NULL` as the column is not nullable. This crashes mysql unless you change the mysql mode to allow zero dates (https://github.com/directus/directus/issues/23883). However, changing the zero date is not a fix, because the default is still incorrect and validation fails (see https://github.com/directus/directus/issues/23883) during a file upload. 

I'm aware this is fixed by using mysql 8, but mysql 5.7 is still widely used 😞. When running the migrations in mysql 8, the result is a nullable column.

### To Reproduce

Use the compose:

```yml
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    # https://github.com/directus/directus/issues/23390#issuecomment-2311833688
    # Remove NO_ZERO_IN_DATE,NO_ZERO_DATE from sql modes
    # command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    networks:
      - application
    environment:
      MYSQL_DATABASE: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: directus
      MYSQL_ROOT_PASSWORD: directus
    healthcheck:
      test: ["CMD", "mysqladmin", "-ppassword", "ping"]

  directus:
    image: directus/directus
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8055:8055
    networks:
      - application
    environment:
      DB_CLIENT: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: directus
      DB_PASSWORD: directus
      DB_DATABASE: directus

      WEBSOCKETS_ENABLED: "true" 

networks:
  application:
```

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql
