### ISSUE TITLE
Connection to Supabase PostgreSQL fails in Directus Docker 🐋

### ISSUE THREAD

**Issue by Mlamalerie** [directus/directus#24280]
### Describe the Bug

I'm trying to connect Directus to my Supabase PostgreSQL database. I get a connection error 
## Error
```
Attaching to directus-1
directus-1  | KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
directus-1  |     at Client_PG.acquireConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/client.js:332:26)
directus-1  |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/execution/runner.js:305:28)
directus-1  |     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/execution/runner.js:30:19)
directus-1  |     at async Postgres.hasTable (file:///directus/node_modules/.pnpm/@directus+schema@file+packages+schema_mysql2@3.11.3_pg@8.13.0_sqlite3@5.1.7_tedious@18.6.1/node_modules/@directus/schema/dist/index.js:454:20)
directus-1  |     at async isInstalled (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/index.js:239:12)
directus-1  |     at async loadExtensions (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/cli/load-extensions.js:10:23)
directus-1  |     at async createCli (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/cli/index.js:20:5) {
directus-1  |   sql: '\n' +
directus-1  |     '\t\t SELECT\n' +
directus-1  |     '\t\t\trel.relname AS name\n' +
directus-1  |     '\t\t FROM\n' +
directus-1  |     '\t\t\tpg_class rel\n' +
directus-1  |     '\t\t WHERE\n' +
directus-1  |     "\t\t\trel.relnamespace IN ('public'::regnamespace)\n" +
directus-1  |     "\t\t\tAND rel.relkind = 'r'\n" +
directus-1  |     '\t\t\tAND rel.relname = ?\n' +
directus-1  |     '\t\t ORDER BY rel.relname\n' +
directus-1  |     '\t  ',
directus-1  |   bindings: [ 'directus_collections' ]
directus-1  | }
directus-1 exited with code 1
}
```
## My docker-compose.yml
```yaml
version: "3.7"
  services:
    directus:
      image: directus/directus
      ports:
        - 8055:8055
      volumes:
        - ./extensions:/directus/extensions
      environment:
        ADMIN_EMAIL: 'admin@example.com'
        ADMIN_PASSWORD: 'xxxxx'
        KEY: 'xxxxx'
        SECRET: 'xxxxx'
        # Supabase connection
        DB_CLIENT: 'pg'
        DB_HOST: 'aws-0-eu-west-2.pooler.supabase.com'
        DB_PORT: '5432'
        DB_DATABASE: 'postgres'
        DB_USER: 'postgres.[project-ref]'
        DB_PASSWORD: 'xxxxx'
```

Both approaches result in the same error. I can confirm that:
- The database credentials are correct (tested with psql)
- The connection works with SQLite configuration (with a another database sql)
- I'm using the latest Directus Docker image
Has anyone successfully connected Directus to Supabase? Would appreciate a working example or tutorial.

### To Reproduce

read  above

### Directus Version

v11

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment]
@Mlamalerie Are you running this docker compose locally? Gut feeling says that your docker container isn't connected to the host networking, meaning it can't connect to third party URLS

**Comment by Mlamalerie** [comment]
Yes, i'm testing running locally, sorry I should have made it clear it’s true. 

(I updated the details of the errors on my initial post)

![image](https://github.com/user-attachments/assets/381b6bc4-1115-4558-9ad0-f7a07cf9e411)

**Comment by rijkvanzanten** [comment]
If my memory serves me well, you can have your local docker compose use your laptops networking stack by adding `network_mode: 'host'` to the `directus` service. I would help google more but am about to head out for christmas eve and all that 🙂

**Comment by Mlamalerie** [comment]
Haha no problem, happy christmas and thank you for your reactivity : 

I try with 'network_mode: 'host'' : 

```
version: "3.7"
  services:
    directus:
      network_mode: 'host'
      image: directus/directus
      ports:
        - 8055:8055
      volumes:
        - ./extensions:/directus/extensions
      environment:
        ADMIN_EMAIL: 'admin@example.com'
        ADMIN_PASSWORD: 'xxxxx'
        KEY: 'xxxxx'
        SECRET: 'xxxxx'
        # Supabase connection
        DB_CLIENT: 'pg'
        DB_HOST: 'aws-0-eu-west-2.pooler.supabase.com'
        DB_PORT: '5432'
        DB_DATABASE: 'postgres'
        DB_USER: 'postgres.[project-ref]'
        DB_PASSWORD: 'xxxxx'
```
     
 But get the same error... : 
 
 ```
[+] Running 2/1
 ✔ Container directus-first-directus-1                                 Recreated                                                                                  0.2s 
 ! directus Published ports are discarded when using host network mode                                                                                            0.0s 
Attaching to directus-1
directus-1  | KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
directus-1  |     at Client_PG.acquireConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/client.js:332:26)
directus-1  |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/execution/runner.js:305:28)
directus-1  |     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.13.0/node_modules/knex/lib/execution/runner.js:30:19)
directus-1  |     at async Postgres.hasTable (file:///directus/node_modules/.pnpm/@directus+schema@file+packages+schema_mysql2@3.11.3_pg@8.13.0_sqlite3@5.1.7_tedious@18.6.1/node_modules/@directus/schema/dist/index.js:454:20)
directus-1  |     at async isInstalled (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/database/index.js:239:12)
directus-1  |     at async loadExtensions (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/cli/load-extensions.js:10:23)
directus-1  |     at async createCli (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.7.5_@unhead+vue@1.11.7_vue@3.5.11_typescript@5.6.3___en_duledcsxwterzqzubwdazkocs4/node_modules/@directus/api/dist/cli/index.js:20:5) {
directus-1  |   sql: '\n' +
directus-1  |     '\t\t SELECT\n' +
directus-1  |     '\t\t\trel.relname AS name\n' +
directus-1  |     '\t\t FROM\n' +
directus-1  |     '\t\t\tpg_class rel\n' +
directus-1  |     '\t\t WHERE\n' +
directus-1  |     "\t\t\trel.relnamespace IN ('public'::regnamespace)\n" +
directus-1  |     "\t\t\tAND rel.relkind = 'r'\n" +
directus-1  |     '\t\t\tAND rel.relname = ?\n' +
directus-1  |     '\t\t ORDER BY rel.relname\n' +
directus-1  |     '\t  ',
directus-1  |   bindings: [ 'directus_collections' ]
directus-1  | }
directus-1 exited with code 1
```

I also try with : 

```
DB_POOL_MIN: '1'
DB_POOL_MAX: '1'
```

But the same 🥲🥲🥲🥲
