### ISSUE TITLE
API Create Batch

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#24338]
### Page

- https://docs.directus.io/self-hosted/config-options.html
- https://docs.directus.io/guides/extensions/hooks-validate-number-twilio.html#add-hook-to-directus

### Describe the Inaccuracy

I think this is a problem of mine, probably because i couldn't find the correct information about the docs.

So i have a ton of items which i need to sync/create in directus.
Speaking of 1000 items each with 30 relations which brings me to 30.000 items.
So i read that creating in a batch with "createMany" should be better than creating each item sequentially.

the problem is that i get a knex timeout error.

I also made sure that the PG Database has a pool of 800 connections, each container has a max of 100 connections.
I am using in the hook the hook provided db connection.
But still this seems very slow to me, as such an update takes around 5min to create (on a production server).

I dont know what to do else. Any ideas?

```
  # The Directus database - postgres with data volume
  # https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose
  rocket-meals-database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    restart: ${RESTART}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U directus" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_MAX_CONNECTIONS: "800" # Optional, adjust based on your needs
      POSTGRES_SHARED_BUFFERS: "16GB"  # Optional, adjust based on your RAM # General: 25% of the total system memory -> Default 16GB
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    networks:
      - directus_network
```

Directus database
```
      # Database
      # Debug database
      #DB_CLIENT: 'sqlite3' # https://docs.directus.io/configuration/config-options/
      #DB_FILENAME: './database/data.db'
      # Production database
      DB_CLIENT: "pg"
      DB_HOST: "rocket-meals-database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      DB_POOL__destroyTimeoutMillis: 1000
      DB_POOL__idleTimeoutMillis: 500
      DB_POOL__reapIntervalMillis: 500
      DB_POOL__createRetryIntervalMillis: 500
      DB_POOL__MIN: 100
      DB_POOL__MAX: 100
      DB_POOL__propagateCreateError: false
```
I also tried with propagateCreateError to false, but this seems more of a workaround. In the previous express and nodejs server the creation of such large amount of data was no problem.

```ts
[19:00:56.831] WARN: An error was thrown while executing action "foodoffers_foods_attributes_values.items.create"
[19:00:56.832] WARN: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    err: {
      "type": "KnexTimeoutError",
      "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
      "stack":
          KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
              at Client_PG.acquireConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/client.js:332:26)
              at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/execution/runner.js:305:28)
              at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_pg@8.12.0/node_modules/knex/lib/execution/runner.js:30:19)
              at async run (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:40:26)
              at async runAst (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/database/run-ast/run-ast.js:26:16)
              at async ItemsService.readByQuery (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@18.19.45_@unhead+vue@1.9.9_vue@3.4.27_typescript@5.4.5___e_m3k5vy5wr7txl4ii3ls7kgdvt4/node_modules/@directus/api/dist/services/items.js:373:25)
              at async xo.readAllItems (file:///directus/extensions/directus-extension-rocket-meals-bundle/dist/api.js?t=1736269247042:8:125249)
              at async r (file:///directus/extensions/directus-extension-rocket-meals-bundle/dist/api.js?t=1736269247042:8:274497)
              at async o (file:///directus/extensions/directus-extension-rocket-meals-bundle/dist/api.js?t=1736269247042:8:274934)
              at async EventEmitter.<anonymous> (file:///directus/extensions/directus-extension-rocket-meals-bundle/dist/api.js?t=1736269247042:8:275095)
      "name": "KnexTimeoutError"
    }
```

**Comment by rijkvanzanten** [comment]
What is the hook that you're currently running to make these updates? Are you able to reduce the batch size down? You've increased the maximum number of connections, but if you insert all items as one call, you still only use one. Depending on the type of data, you could parallelize the insertion so it's utilizing those connections more effectively.

I'm afraid this is a bit too specific to track as a bug in Directus, as there's a lot of variables at play that we don't directly control, like the hosting environment, CPU performance, database type, hook code etc etc, so I'll close this for now. Happy to keep discussing in the thread below though 🙂

**Comment by NilsBaumgartner1994** [comment]
Hi @rijkvanzanten thanks for your time. I've already saw: https://github.com/directus/directus/discussions/11051 which had similar experiences with batch creation. 

The batch size is currently 100. The main focus is a stable insertion/creation of the items.

So maybe let me break down the steps, in order to track down, where i made a mistake:

1. Use the current event transaction: 
```
export default defineHook(async ({action, init, filter}, apiContext) => { // the global Api context

action( // the action hook
        collection + ".items.update",
        async (event, eventContext) => {

let database = this.eventContext?.database || this.apiContext.database; // https://github.com/directus/directus/discussions/11051#discussioncomment-2014806
```
So in this step i assume that it is better to reuse the current database transaction connection?

2. Prepare the batches
```
const batchSize = 100;

const myFoodOffersService = await this.myDatabaseHelper.getFoodoffersHelper(); // getter of the itemsService with apiContext and eventContext and correct tablename

let batchIndex = 1;
const amountOfBatches = Math.ceil(foodoffersToCreate.length / batchSize);
for (let i = 0; i < foodoffersToCreate.length; i += batchSize) {
    const batch = foodoffersToCreate.slice(i, i + batchSize);
    // Step 4 await
    await myFoodOffersService.createManyItems(batch);
}
```

3. Create the ItemsService
```
const {ItemsService} = this.apiContext.services;
let schema = this.eventContext?.schema; // https://github.com/directus/directus/discussions/11051#discussioncomment-2014806
if(!schema){
       schema = await this.apiContext.getSchema();
}

return new ItemsService(tablename, {
       accountability: null, //this makes us admin
       knex: database,
       schema: schema,
});
```


4. Call of the createMany Items
```
async createManyItems(create: Partial<T>[]): Promise<PrimaryKey[]>{
        const itemsServiceCreator = new ItemsServiceCreator(this.apiContext, this.eventContext);
        let itemsService = await itemsServiceCreator.getItemsService<T>(this.tablename);
        return await itemsService.createMany(create);
    }
```

5. Directus Server
So I am running 8 containers of directus (replicates) and one PG database

Directus Container
```
deploy:
      mode: replicated
      replicas: ${DIRECTUS_REPLICAS:-1}  # Default to 1 if DIRECTUS_REPLICAS is not set
      endpoint_mode: vip # Virtual IP - https://docs.docker.com/compose/compose-file/deploy/#endpoint_mode
      ....
environment:
      DB_CLIENT: "pg"
      DB_HOST: "rocket-meals-database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
```

PG Database:
```
  rocket-meals-database:
    image: postgis/postgis:13-master
    restart: ${RESTART}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U directus" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_MAX_CONNECTIONS: "800" # Optional, adjust based on your needs
      POSTGRES_SHARED_BUFFERS: "16GB"  # Optional, adjust based on your RAM # General: 25% of the total system memory -> Default 16GB
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
```

The server is running on a 64GB RAM machine.

----------

Maybe i am missing an important step somewhere?
