### ISSUE TITLE
Migration from 11.1.0 to 11.3.5 not applied automatically using docker

### ISSUE THREAD

**Issue by PrudyAk** [directus/directus#24403]
### Describe the Bug

Hello,
we are using Docker in our project to start Directus. 
In the docker-compose file i changed the directus version from 11.1.0 to 11.3.5 and rebuilt/relaunched to container.
Directus not start correctly and i become this Error:

```
[09:08:06.963] INFO: Skipping CLI extensions initialization due to outstanding migrations.
[09:08:06.980] INFO: Initializing bootstrap...
[09:08:06.985] INFO: Database already initialized, skipping install
[09:08:06.986] INFO: Running migrations...
[09:08:06.998] INFO: Applying Consolidate Content Versioning...
error: alter table "directus_versions" add column "delta" json - column "delta" of relation "directus_versions" already exists
    at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:35:38)
    at TLSSocket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 141,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '7044',
  routine: 'check_for_column_name_collision'
  ```

We are using the official Directus image and here is our Docker file:

```yaml
version: "3"

networks:
  default:
    name: ${STACK_PRFX}

services:
  database:
    container_name: ${STACK_PRFX}-database
    image: postgres:14.13
    volumes:
      - ./data:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 2s
      timeout: 20s
      retries: 10

  directus_extension:
    container_name: ${STACK_PRFX}-directus-extension
    image: node:current-alpine
    volumes:
      - ${EXTENSION_SOURCE_DIR}:/directus
      - ~/.ssh:/tmp/.ssh
      - ~/.git-credentials:/tmp/.git-credentials
    entrypoint: ""
    command: sh -c "
      apk update && apk add git openssh &&
      cd /directus && mkdir -p /root/.ssh &&
      cp -r /tmp/.ssh/* /root/.ssh || true &&
      cp -r /tmp/.git-credentials /root/.git-credentials &&
      git config --global http.sslVerify false &&
      git config --global credential.helper store &&
      [ \"$(ls -A .)\" ] || git clone ${EXTENSION_REPO_URL} . &&
      git config --global --add safe.directory /directus &&
      [ -z "${EXTENSION_BRANCH}" ] || git checkout $EXTENSION_BRANCH &&
      npm config set strict-ssl false &&
      npm install --loglevel verbose && npm run build
      "

  directus:
    container_name: ${STACK_PRFX}-directus
    image: directus/directus:11.3.5

    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ${EXTENSION_SOURCE_DIR}/dist:/directus/extensions/directus-extension-bonus/dist
      - ${EXTENSION_SOURCE_DIR}/package.json:/directus/extensions/directus-extension-bonus/package.json
    depends_on:
      database:
        condition: service_healthy
      directus_extension:
        condition: service_completed_successfully
    env_file:
      - .env

  directus_scripts:
    container_name: ${STACK_PRFX}-directus_scripts
    build:
      context: "./python"
    environment:
      DIRECTUS_BASE_URL: http://directus:8055
      DIRECTUS_API_KEY: ${DIRECTUS_API_KEY}
      DIRECTORY: ${DIRECTORY}
      SCRIPT: ${SCRIPT}
    profiles:
      - directus_scripts
    volumes:
      - ./../../directus_deployment:/usr/src/app/directus_deployment
    command: sh -c "
      cd $DIRECTORY && python $SCRIPT
      "
```      

### To Reproduce

Migrate from 11.1.0 → 11.3.5 using docker and relaunch the container

### Directus Version

v11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres:14.13
