### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error when connecting to Supabase through Session pooler (free tier)

### ISSUE THREAD

**Issue by Cherkenco** [directus/directus#24471]
### Describe the Bug

Hi,

I've been trying for days to connect my Directus container to Supabase using the Session pooler, as Directus is not able to resolve the IPv6 of the direct connection, and It's been impossible, due to SELF_SIGNED_CERT_IN_CHAIN error:

Error: self-signed certificate in certificate chain
at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
at TLSSocket.emit (node:events:524:28)
at TLSSocket._finishInit (node:_tls_wrap:1078:8)
at ssl.onhandshakedone (node:_tls_wrap:864:12) {
code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
exited with code 0

So I was wondering if any of you has been able to connect in that way or if is it a bug? I've tried everything:

DB_SSL -> true
DB_SSL__REQUIRE -> true
DB_SSL__REJECT_UNAUTHORIZED -> true and false
DB_SSL__CA_FILE -> path to file
DB_SSL__CA -> single line cert content

The only way to run the container seems to be adding NODE_TLS_REJECT_UNAUTHORIZED=0 to .env file, which is obviously not recommended for production.

### To Reproduce

Just try to run a Directus 11.4.0 instance on a container and set up Supabase Session Pooler connection in .env file.

### Directus Version

11.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Supabase

**Comment by rijkvanzanten** [comment]
This reminds me of https://github.com/directus/directus/issues/24280, but the symptoms sound different.

**Comment by paescuj** [comment]
> [...] as Directus is not able to resolve the IPv6 of the direct connection [...]

Directus itself doesn't have any issues connecting to an IPv6 address, if so it's related to the environment (host, ...) instead.
In case of Docker, you need to enable IPv6 [^1]. For example via your compose file:
```yaml
services:
  directus:
    image: directus/directus:11.4.0
    ports:
      - 8055:8055
    volumes:
      - ./supabase.ca.crt:/supabase.ca.crt
    environment:
      SECRET: "replace-with-secure-random-value"

      DB_CLIENT: "pg"
      DB_HOST: "db.<...>.supabase.co"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "your-db-password"
      DB_SSL__CA_FILE: "/supabase.ca.crt"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

networks:
  default:
    enable_ipv6: true
```

Depending on your use case, you could also use `network_mode: host` as shown in https://github.com/directus/directus/issues/24280#issuecomment-2562846150.

Btw. the session pooler connection worked tool in my test, using a similar compose file as above. If you still need to use that for some reason, ensure the DB host, user and CA file are all correctly configured.

In accordance with the above comments, I consider this issue as solved 👍 

[^1]: Please note that IPv6 in Docker may not always be available depending on your host and version or may need to be enabled first via the daemon configuration.
