### ISSUE TITLE
Api: Deleting a collection causes the project to halt

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#24681]
### Describe the Bug

When deleting a collection our project freezes and no other requests are served.
This seems to be related to the amount of Activity and Revisions that we have, which is more than 1M

The collection deletion process first destroys the table, then tries to delete all the related data on Revisions.

The query to database is:
```sql
delete from directus_revisions where collection = '<collection>'
```

This query takes much time because for each record that tries to delete, database first needs to check the `parent` foreign key, which points to itself. Since there's millions of records, this will take long time to run because it needs to go though all 1M records for reach record 

The same happens with `version` pointing to `directus_versions`, but not so critical as this table is usually small.

My suggestion is on of those:
- Remove foreign keys from Activity and Revisions tables
- Add indexes to relevant fields on these tables

### To Reproduce

- Run postgres through docker compose and run this service:
<details><summary>Code</summary>

```yaml
  postgres:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: directus
    ports:
      - 5100:5432
    volumes:
      - /var/lib/postgresql/data
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 256M
```

</details>

- Create multiple entries on Activity and Revisions. For example, create a collection with Accountability set to track all and create 10 fields
- Create a script to inject 1M records into this collection with all fields filled
- Try to delete the collection

### Directus Version

v11.4.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres 13
