### ISSUE TITLE
Public Policies permissions Not working. Unaccessible table items without authentication-

### ISSUE THREAD

**Issue by EddiePiazza** [directus/directus#24995]
### Describe the Bug

Hi,
after making all kind of tests I confirm there is a problem with permissions. It's the first time I am facing this weirf issue.

I created a collection under /items/version
I added the collection with read permissions on public policy as on a Public_Frontend Policy where I am using a token to be used by the main domain to be used as SSR queries (never mind).

The fact is that even accessing dorectly via Directus domain (not using the main site domain) the table remains unaccessible:
{"errors":[{"message":"You don't have permission to access collection \"version\" or it does not exist. Queried in root.","extensions":{"reason":"You don't have permission to access collection \"version\" or it does not exist. Queried in root.","code":"FORBIDDEN"}}]}

just if I login as admin from the main site or the database I can Access to the data 
directus.domain/items/version
{"data":{"id":1,"app_version":"0.0.106","compile_date":"2025-03-23T12:00:00"}}

### To Reproduce

I just created a new collection, no matters what to do, impossible to access to any new collection from public side without aythentication.
The problem is not new, I have this problem since very long time but I am now trying to fix it without results.

Micght be a problem with cockroachDb.

Here is my docker-compose:

```
services:
  directus:
    image: directus/directus:latest
    user: root
    ports:
      - "8055:8055"
    networks:  # Añadimos configuración explícita de red
      - directus-network
    #healthcheck:  # Añadimos healthcheck para asegurar arranque correcto
      #test: ["CMD", "node", "-e", "require('http').request('http://localhost:8055/server/health', (r) => {if (r.statusCode !== 200) throw new Error('Health check failed')}).end()"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 30s
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      #- /var/lib/cockroach/certs/ca.crt:/directus/certs/ca.crt
    environment:
      # General
      HOST: "0.0.0.0"
      PORT: 8055
      PUBLIC_URL: "..."
      MAX_PAYLOAD_SIZE: "1mb"
      COMPRESSION_ENABLED: "true"  
      ROOT_REDIRECT: "./admin"
      TZ: "Europe/Madrid"
      
      # WebSockets y Logs
      WEBSOCKETS_ENABLED: "true"
      LOG_LEVEL: "info"
      LOG_STYLE: "pretty"
      WEBSOCKETS_LOGS_ENABLED: "true"
      WEBSOCKETS_LOGS_LEVEL: "info"
      WEBSOCKETS_LOGS_STYLE: "pretty"
      WEBSOCKETS_LOGS_CONN_LIMIT: "2000"

      # Ajustamos timeouts de arranque
      SERVER_STARTUP_TIMEOUT: "10000"  # 60 segundos para arrancar

      # CORS
      CORS_ENABLED: "true"
      CORS_ORIGIN: "..."
      CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS,PUT,PROPFIND"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization,Pragma,cache-control,expires"
      CORS_EXPOSED_HEADERS: "Content-Range"
      CORS_CREDENTIALS: "false"
      
      # Seguridad
      SECRET: "_5yerGA3DOyTPVfWvOZJR9pRp0Et4sjo"
      ADMIN_EMAIL: "admin@dropbowl.com"
      ADMIN_PASSWORD: "e53731229D"
      KEY: "d5239e2d-c95d-49aa-97a5-ffa05c334837"
      ACCESS_TOKEN_TTL: "24h"
      REFRESH_TOKEN_TTL: "7d"
      SESSION_COOKIE_TTL: "1d"
      SESSION_COOKIE_SECURE: "true"
      SESSION_COOKIE_HTTPONLY: "true"
      SESSION_COOKIE_DOMAIN: "dropbowl.com"
      SESSION_COOKIE_SAMESITE: "Strict"

      # Base de datos (CockroachDB)
      DB_CLIENT: "cockroachdb"
      DB_HOST: "..."
      DB_PORT: "..."
      DB_DATABASE: "..."
      DB_USER: "..."
      DB_PASSWORD: "..."
      DB_SSL: "true"
      DB_SSL_CA: "/directus/certs/ca.crt"
      DB_SSL_MODE: "require"
      DB_SSL_REJECT_UNAUTHORIZED: "false"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

      # Pool de conexiones (simplificado al máximo)
      DB_POOL__MIN: "5"
      DB_POOL__MAX: "100"

      # Almacenamiento de archivos
      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/.../directus"

      # Redis optimizado
      REDIS_ENABLED: "true"
      REDIS_HOST: "redis"
      REDIS_PORT: "..."
      REDIS_USERNAME: "..."
      REDIS_PASSWORD: "..."
      REDIS_DB: "0"
      CACHE_NAMESPACE: "directus-cache"
      REDIS_RETRY_STRATEGY: "function(times) { return Math.min(times * 50, 2000); }"

      # Caché optimizado
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_TTL: "2m"
      CACHE_SCHEMA_TTL: "24h"
      CACHE_VALUE_MAX_SIZE: "10mb"
      CACHE_AUTO_PURGE: "true"
      CACHE_AUTO_PURGE_IGNORE_LIST: "directus_activity,directus_presets"
      CACHE_SCHEMA: "true"

      # Rate Limiting optimizado
      RATE_LIMITER_ENABLED: "true"
      RATE_LIMITER_POINTS: "10000"
      RATE_LIMITER_DURATION: "60"
      RATE_LIMITER_GLOBAL_ENABLED: "true"
      RATE_LIMITER_GLOBAL_POINTS: "100000"
      RATE_LIMITER_GLOBAL_DURATION: "60"


      # Optimización de consultas y rendimiento
      QUERY_LIMIT_DEFAULT: "5000"
      QUERY_LIMIT_MAX: "10000"
      RELATIONAL_BATCH_SIZE: "50000"
      EXPORT_BATCH_SIZE: "100000"

      # PM2 - Configuración optimizada
      PM2_INSTANCES: "20"
      PM2_EXEC_MODE: "cluster"
      PM2_AUTO_RESTART: "true"
      PM2_MAX_MEMORY_RESTART: "1G"
      PM2_KILL_TIMEOUT: "3000"
      PM2_LISTEN_TIMEOUT: "30000"

      # Optimización del servidor
      SERVER_KEEP_ALIVE_TIMEOUT: "60000"
      SERVER_HEADERS_TIMEOUT: "60000"
      SERVER_SHUTDOWN_TIMEOUT: "10000"
      ACTIVITY_TRACKER_ENABLED: "false"

    deploy:
      resources:
        limits:
          cpus: '18.0'
          memory: 28G
        reservations:
          cpus: '10.0'
          memory: 20G

    restart: always

  redis:
    networks:
      - directus-network
    #healthcheck:
      #test: ["CMD", "redis-cli", "ping"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 30s
    image: redis:alpine
    command: redis-server --maxmemory 6gb --maxmemory-policy allkeys-lru --activedefrag yes --hz 100 --dynamic-hz yes --maxclients 10000
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 12G
        reservations:
          cpus: '3.0'
          memory: 8G
    restart: always

networks:
  directus-network:
    driver: bridge

volumes:
  redis-data:
```

### Directus Version

v11.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

CockroachDB
