### ISSUE TITLE
SSO OAuth false positive validation error

### ISSUE THREAD

**Issue by jonathan-chin** [directus/directus#25095]
### Describe the Bug

I am trying to connect an OAuth provider for SSO. when receiving the token back during the workflow, Directus throws the following error:

```
WARN: [OAuth2] Unknown RP error
"type": "RPError"
"message": "id_token detected in the response, you must use client.callback() instead of client.oauthCallback()"
```

indeed, the response from our provider, [ClassLink](https://www.classlink.com/), provides a response with the following properties:

`access_token`, `token_type`, `response_type`, and `id_token`

currently, Directus detects `id_token` and throws an error, believing that it's indicative of an OpenId response instead of an OAuth response. however, I don't believe there is any restriction on the OAuth spec to also include `id_token` in the response. I believe our auth provider is providing a fully valid response.

because of this, I cannot proceed with the SSO workflow.

### To Reproduce

use the following `docker-compose.yml` configuration. note that this is specifically happening with [ClassLink](https://www.classlink.com/), a global auth provider serving 22 million students.

```
services:
  postgres:
    image: postgres:13
    container_name: directus_postgres
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: abcdef
      POSTGRES_DB: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - directus_network

  directus:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - "8055:8055"
    environment:
      ADMIN_EMAIL: abc@def.com
      ADMIN_PASSWORD: abcdef
      AUTH_PROVIDERS: classlink
      AUTH_CLASSLINK_DRIVER: openid
      AUTH_CLASSLINK_CLIENT_ID: abcdef
      AUTH_CLASSLINK_CLIENT_SECRET: abcdef
      AUTH_CLASSLINK_ISSUER_URL: https://launchpad.classlink.com/.well-known/openid-configuration
      REFRESH_TOKEN_COOKIE_SECURE: false
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: abcdef
      PUBLIC_URL: http://localhost:8055
      SECRET: abcdef
    depends_on:
      - postgres
    networks:
      - directus_network

volumes:
  postgres_data:

networks:
  directus_network:
```

run it and try to login with a ClassLink test account.

I've verified my test account credentials with a small scale nodejs script and the authorization and data exchange run as expected.

### Directus Version

v11.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres 13

**Comment by licitdev** [comment]
Kindly confirm if your env is `AUTH_CLASSLINK_DRIVER: openid` as listed above, as your error message points to `[OAuth2]`, which does not match up.

**Comment by jonathan-chin** [comment]
> Kindly confirm if your env is `AUTH_CLASSLINK_DRIVER: openid` as listed above, as your error message points to `[OAuth2]`, which does not match up.

sorry! when the error is first encountered, the driver is indeed listed as oauth2. I copied and pasted a later version trying to get it to work, which is when I tried treating to provider as openid.

here is the oauth configuration:

```
services:
  postgres:
    image: postgres:13
    container_name: directus_postgres
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: abcdef
      POSTGRES_DB: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - directus_network

  directus:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - "8055:8055"
    environment:
      ADMIN_EMAIL: abc@def.com
      ADMIN_PASSWORD: abcdef
      AUTH_CLASSLINK_DRIVER: oauth2                                                                                                        
      AUTH_CLASSLINK_CLIENT_ID: abcdef                                                               
      AUTH_CLASSLINK_CLIENT_SECRET: abcdef                                                                       
      AUTH_CLASSLINK_AUTHORIZE_URL: https://launchpad.classlink.com/oauth2/v2/auth                                                         
      AUTH_CLASSLINK_ACCESS_URL: https://launchpad.classlink.com/oauth2/v2/token                                                           
      AUTH_CLASSLINK_PROFILE_URL: https://nodeapi.classlink.com/v2/my/profileinfo                                                          
      AUTH_CLASSLINK_SCOPE: profile                                                                                                        
      AUTH_CLASSLINK_ALLOW_PUBLIC_REGISTRATION: true                                                                                       
      AUTH_CLASSLINK_DEFAULT_ROLE_ID: abcdef
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: abcdef
      PUBLIC_URL: http://localhost:8055
      SECRET: abcdef
    depends_on:
      - postgres
    networks:
      - directus_network

volumes:
  postgres_data:

networks:
  directus_network:
```
