### ISSUE TITLE
Wrong user name and password for first login

### ISSUE THREAD

**Issue by aliSadegh** [directus/directus#25175]
### Describe the Bug

When I try to log in with the correct username and password, it says, "Wrong usename and password".

Here's a screenshot:

![Image](https://github.com/user-attachments/assets/d51f56d6-97d6-4373-8fc6-1168c1982e7b)

### To Reproduce

Deploy with docker compose file:
```
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.7.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: "alisadeghalisadeghalisadeghalisade"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@test.com"
      ADMIN_PASSWORD: "d1r3ctu5"

```

docker logs:

```
cache-1     | 1:C 07 May 2025 15:00:03.022 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache-1     | 1:C 07 May 2025 15:00:03.022 # Redis version=6.2.18, bits=64, commit=00000000, modified=0, pid=1, just started
cache-1     | 1:C 07 May 2025 15:00:03.022 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache-1     | 1:M 07 May 2025 15:00:03.022 * monotonic clock: POSIX clock_gettime
cache-1     | 1:M 07 May 2025 15:00:03.023 * Running mode=standalone, port=6379.
cache-1     | 1:M 07 May 2025 15:00:03.023 # Server initialized
cache-1     | 1:M 07 May 2025 15:00:03.023 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache-1     | 1:M 07 May 2025 15:00:03.024 * Loading RDB produced by version 6.2.18
cache-1     | 1:M 07 May 2025 15:00:03.024 * RDB age 342 seconds
cache-1     | 1:M 07 May 2025 15:00:03.024 * RDB memory usage when created 0.78 Mb
cache-1     | 1:M 07 May 2025 15:00:03.024 # Done loading RDB, keys loaded: 3, keys expired: 2.
cache-1     | 1:M 07 May 2025 15:00:03.024 * DB loaded from disk: 0.000 seconds
cache-1     | 1:M 07 May 2025 15:00:03.024 * Ready to accept connections
database-1  |
database-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database-1  |
database-1  | 2025-05-07 15:00:03.242 UTC [1] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database-1  | 2025-05-07 15:00:03.242 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database-1  | 2025-05-07 15:00:03.242 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database-1  | 2025-05-07 15:00:03.245 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database-1  | 2025-05-07 15:00:03.251 UTC [26] LOG:  database system was shut down at 2025-05-07 14:54:21 UTC
database-1  | 2025-05-07 15:00:03.259 UTC [1] LOG:  database system is ready to accept connections
directus-1  | [15:00:15.889] INFO: Initializing bootstrap...
directus-1  | [15:00:15.899] INFO: Database already initialized, skipping install
directus-1  | [15:00:15.900] INFO: Running migrations...
directus-1  | [15:00:15.918] INFO: Done
directus-1  | 2025-05-07T15:00:16: PM2 log: Launching in no daemon mode
directus-1  | 2025-05-07T15:00:16: PM2 log: App [directus:0] starting in -cluster mode-
directus-1  | 2025-05-07T15:00:19: PM2 log: App [directus:0] online
directus-1  | [15:00:22.225] WARN: "PUBLIC_URL" should be a full URL
directus-1  | [15:00:22.231] WARN: Upload directory (/directus/uploads) is not read/writeable!
directus-1  | [15:00:22.305] INFO: Server started at http://0.0.0.0:8055
directus-1  | [15:00:29] POST /auth/refresh 400 24ms
directus-1  | [15:00:34] GET / 302 5ms
directus-1  | [15:00:34] GET /admin 304 3ms
directus-1  | [15:00:35] GET /extensions/sources/index.js 200 24ms
directus-1  | [15:00:35] POST /auth/refresh 400 8ms
directus-1  | [15:00:35] GET /server/info 304 15ms
directus-1  | [15:00:35] GET /auth?sessionOnly 304 13ms
directus-1  | [15:00:35] GET /translations?fields[]=language&fields[]=key&fields[]=value&filter[language][_eq]=en-US&limit=-1 403 21ms
directus-1  | [15:00:51] POST /auth/login 401 517ms
directus-1  | [15:01:05] POST /auth/refresh 400 10ms

```

### Directus Version

11.7.2

### Hosting Strategy

Self-Hosted (Docker Image)
