### ISSUE TITLE
HELM chart issue with HPA

### ISSUE THREAD

**Issue by micxba** [directus/directus#25297]
### Describe the Bug

The HELM chart template for the HPA uses the "new" `autoscaling/v2` API but the values file still acts as if it was using `autoscaling/v2beta2`. This result in errors like:

```sh
HorizontalPodAutoscaler.autoscaling "directus" is invalid: [spec.metrics[0].resource.target.type: Required value: must specify a metric target type, spec.metrics[0].resource.target.type: Invalid value: "": must be either Utilization, Value, or AverageValue, spec.metrics[0].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization]
```
To remedy the issue the template should be updated e.g. from:

```yaml
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
```

to 

```yaml
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
```

respectively for memory:

```yaml
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
```

### To Reproduce

Install the HELM template version 2.0.2 with HPA enabled.

### Directus Version

v.11.8.0

### Hosting Strategy

Self-Hosted (Docker Image)
