### ISSUE TITLE
Support for multiple and non default schemas in Postgres through DB_SEARCH_PATH

### ISSUE THREAD

**Issue by JosePVB** [directus/directus#3228]
I just found out about this project and the work to integrate Postgres looks very promising!

I am trying to use the `directus/directus:v9.0.0-rc.18` Docker image with an existing Postgres 11 database that has multiple schemas. I couldn't find documentation on how the `DB_SEARCH_PATH` environment variable should be passed so that Directus can find all the tables I am interested in.

Here is what I have tried, and what Directus has logged.

In my docker-compose.yaml, I have the following service definition:
```yaml
  directus:
    image: directus/directus:v9.0.0-rc.18
    ports:
      - 8055:8055
    environment:
      KEY: mykey
      SECRET: mysecret
      DB_CLIENT: pg
      DB_HOST: dbhost
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: db
      DB_SEARCH_PATH: "public,my_schema"
      DIRECTUS_ADMIN_EMAIL: admin@example.com
      DIRECTUS_ADMIN_PASSWORD: pass
```
Directus logged:
```
directus               | 02:09:25 Detected comma in searchPath "public,my_schema".If you are trying to specify multiple schemas, use Array syntax: ['public', 'my_schema']
```

After seeing that message, I changed `DB_SEARCH_PATH` to `"['public', 'my_schema']"`, but then received this log:
```
directus               | 02:13:24 Detected comma in searchPath "['public', 'my_schema']".If you are trying to specify multiple schemas, use Array syntax: ['['public'', ' 'my_schema]']
```

After I couldn't get multiple schemas to work, I specified `DB_SEARCH_PATH` as just `my_schema`, to manage just the tables in that schema. However, the admin page on the UI was then blank due to a 503 response:
```
02:39:21 ✨ request errored GET 503 /server/info 51ms
```

The `directus_*` tables are created in `my_schema`, but it then seems that Directus is unable to use/find them. This behavior does not happen when `DB_SEARCH_PATH` is specified as the default, `public` schema. Please let me know if I should create a separate issue for just this behavior.

I appreciate the help! Please let me know if there is additional information that would be helpful to have.
