### ISSUE TITLE
Connecting to Azure Blob storage

### ISSUE THREAD

**Issue by Zoly90** [directus/directus#5156]
Hi I'm totally new to Directus, so I apologies in advance if this is not a bug, I may be missing something.
For our current project we need to connect Directus to Azure data storage, so I tried this out for testing purposes, I created the following docker-compose file.

```
version: '3.4'

services:
    database:
        container_name: database
        image: postgres:12
        volumes:
          - ./data/database:/var/lib/postgresql/data
        networks:
          - directus
        environment:
          POSTGRES_USER: 'directus'
          POSTGRES_PASSWORD: 'directus'
          POSTGRES_DB: 'directus'

    directus:
        container_name: directus
        image: directus/directus:v9.0.0-rc.24
        ports:
          - 8055:8055
        networks:
          - directus
        depends_on:
          - database
        environment:
          KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
          SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

          DB_CLIENT: 'pg'
          DB_HOST: 'database'
          DB_PORT: '5432'
          DB_DATABASE: 'directus'
          DB_USER: 'directus'
          DB_PASSWORD: 'directus'
          
          STORAGE_LOCATIONS: 'azure'
          
          STORAGE_AZURE_DRIVER: 'azure'
          STORAGE_AZURE_CONTAINER_NAME: 'vita-system'
          STORAGE_AZURE_ACCOUNT_NAME: 'fileandmediastorage'
          STORAGE_AZURE_ACCOUNT_KEY: 'LbbNAA+zdUyknGJ+qiG2oKgbPQ4vB4BPyfyg4b4CCgFOwpOBKYa9fYqMU4aBV0QoQi+HpY+LHxu2QMOsk5qCjQ=='
          STORAGE_AZURE_ENDPOINT: 'https://fileandmediastorage.blob.core.windows.net/vita-system'

          ADMIN_EMAIL: 'admin@example.com'
          ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:
```

But when I try to upload a photo in a collection I encounter this error message:
![image](https://user-images.githubusercontent.com/20513066/115348387-3ed47780-a1bb-11eb-97e5-26f76f318522.png)

The browser that I am using it's Chrome.

Am I missing something or this would be a bug? Please help me out!
