### ISSUE TITLE
BASE_URL not redirecting properly

### ISSUE THREAD

**Issue by Meldiron** [directus/directus#5542]
Environment: Docker (docker-compose)
Directus: ` image: directus/directus:v9.0.0-rc.61`
Database:  `image: mysql:5.7`

No errors or warnings in logs.

Directus (and Traefik) config:

```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my_project.rule=Host(`mydomain.com`) && PathPrefix(`/my-project`)"
      - "traefik.http.routers.my_project.entrypoints=websecure"
      - "traefik.http.routers.my_project.tls.certresolver=myresolver"
      - "traefik.http.middlewares.my_project_m.stripprefix.prefixes=/my-project"
      - "traefik.http.routers.my_project.middlewares=my_project_m@docker"
    environment:
      PUBLIC_URL: "https://mydomain.com/my-project"
```

If I visit `https://mydomain.com/my-project/`, it redirects me to `https://mydomain.com/my-project/admin/login` and everything works as expected.

Problem is, if I visit `https://mydomain.com/my-project` (last `/` missing), it redirects me to `https://mydomain.com/admin` and that results in 404 error.

I tried to add `/` at the end of PUBLIC_URL, but it didnt help.

Insomnia timeline shows these information:
```
GET https://mydomain.com/my-project

< HTTP/2 302 
< access-control-allow-credentials: true
< access-control-expose-headers: Content-Range
< content-type: text/plain; charset=utf-8
< date: Fri, 07 May 2021 16:32:40 GMT
< location: ./admin
< vary: Origin, Accept
< x-powered-by: Directus
< content-length: 29
```
