### ISSUE TITLE
Utils endpoint returns route not found

### ISSUE THREAD

**Issue by franusierra** [directus/directus#5913]
I try to access the utils endpoints on the api as stated [here](https://docs.directus.io/reference/api/system/utilities/) it returns the error ROUTE_NOT_FOUND on all endpoints. 

I am deploying using for development the following docker compose on windows docker desktop:
```
directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./DirectusCMS/uploads:/directus/uploads
    networks:
      - directus
      - servicemesh
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '*********'
      ADMIN_PASSWORD: '*********'

      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: '***********'
      EMAIL_SMTP_USER: '*************'
      EMAIL_SMTP_PASSWORD: '*********'
      EMAIL_SMTP_PORT: ***
```

For example:
{"errors":[{"message":"Route /utils/hash/generate doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}
{"errors":[{"message":"Route /utils/hash/verify doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}
{"errors":[{"message":"Route /utils doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}

I checked on /dist/app.js and the route "/utils" is added to the express router so I don't actually know what might be going on, any ideas?

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 5.4.72-microsoft-standard-WSL2
Node: 14.16.1
