### ISSUE TITLE
Directus Docker:  Failed to read value from file when upgrading from rc74

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#6364]
1) The issue and what you expected to happen
Upgrading from rc74 to rc75 and rc 76 results in 

`cms-directus | Failed to read value from file "local.nginx.conf", defined in environment variable "NGINX_CONFIG_FILE".`

As soon as I go back to rc74 the error disappears. as soon as I switch to rc75,76 it appears.  The directus container isn't even accessing the NGINX_CONFIG_FILE variable. it seems to me that something conflicts with reading my .env

2) Your environment:
    rc75, rc76
    postgres 
    docker

3) Any other relevant information we might need to reproduce this issue

```
directus:
    restart: always
    image: directus/directus:v9.0.0-rc.75
    container_name: cms-directus
    volumes:
      - './directus/uploads:/directus/uploads'
    env_file:
      .env  
    ports:
      - "${DIRECTUS_EXTERNAL_PORT}:${DIRECTUS_INTERNAL_PORT}"
    depends_on:
      - postgres
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      PORT: ${DIRECTUS_EXTERNAL_PORT}
     
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: ${POSTGRES_PORT_INTERNAL}
      DB_DATABASE: ${DIRECTUS_POSTGRES_DB}
      DB_USER: ${POSTGRES_ROOT_USER}
      DB_PASSWORD: ${POSTGRES_ROOT_PASSWORD}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      CACHE_ENABLED: "false"
    networks:
      - network-internal
      - network-external
```
