### ISSUE TITLE
Permission denied with RC.83 and Docker

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#6574]
### Describe the Bug

Can't launch Directus RC.83 with Docker compose.
No problem with RC.82

This is the Docker output : 

```shell
npm WARN exec The following package was not found and will be installed: directus

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated har-validator@5.1.5: this library is no longer supported

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

npm WARN deprecated querystring@0.2.0: The

npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

sh: directus: Permission denied

npm notice 
npm notice New minor version of npm available! 7.15.1 -> 7.19.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.0>
npm notice Run `npm install -g npm@7.19.0` to update!
npm notice 

```

### To Reproduce

Docker composer file :

```yaml
    api:
        env_file:
            - "./.directus.env"
        image: directus/directus:v9.0.0-rc.83
        ports:
            - 3103:8055
        user: "${UID}:${GID}"
        volumes:
            - ./data2/uploads:/directus/uploads
            - ./data2/extensions:/directus/extensions
```

### What version of Directus are you using?

RC.83

### What version of Node.js are you using?

The one provided by the docker container

### What database are you using?

Mariadb  10.5.11

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker Compose V2
