### ISSUE TITLE
Exposing/Running directus on a port other than 8055 prevents the admin app from loading

### ISSUE THREAD

**Issue by gerolds** [directus/directus#6858]
### Describe the Bug

Exposing/Running directus on a port other than 8055 prevents the admin app from loading. Broken since rc.84.

### To Reproduce

try to access `localhost:8080` from compose.yaml:

```
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    networks:
      - default

  directus:
    image: directus/directus:9.0.0-rc.85
    ports:
      - 8080:8055
    depends_on:
      - db
    environment:
      KEY: directus
      SECRET: directus
      ADMIN_EMAIL: user@example.com
      ADMIN_PASSWORD: directus
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus
    networks:
      - default

networks:
  default:
```

### What version of Directus are you using?

9.0.0.rc.85

### What version of Node.js are you using?

official docker image

### What database are you using?

official docker image

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

docker compose
