### ISSUE TITLE
OAuth with Keycloak results in SERVICE UNAVAILABLE error

### ISSUE THREAD

**Issue by Jason-CKY** [directus/directus#7427]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [ ] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am trying to use keycloak as my oauth provider to authenticate into the directus app, but the directus app returns SERVICE UNAVAILABLE error after logging in on keycloak. This issue is very similar to #6749 , except I am using a docker-compose for all my services instead of npx. I was unable to resolve this issue even when the keycloak user has the same email address as the directus admin account.

### To Reproduce

The docker-compose.yml file is listed here:

```
version: "3.7"
services:

  database:
    image: postgres:12
    volumes:
      - ./db_volume/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    
  directus:
    image: directus/directus:latest
    ports:
      - 8080:8080
    volumes:
      - ./directus_volume/uploads:/directus/uploads
      - ./directus_volume/extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - database
      - keycloak
    environment:
      OAUTH_PROVIDERS: "keycloak"
      OAUTH_KEYCLOAK_KEY: "directus-ui"
      OAUTH_KEYCLOAK_SECRET: "f570f154-9f14-47d3-8e0f-df1892f377c1"
      OAUTH_KEYCLOAK_AUTHORIZE_URL: "http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/auth"
      OAUTH_KEYCLOAK_ACCESS_URL: "http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/token"
      OAUTH_KEYCLOAK_SCOPE: "openid email"
      OAUTH_KEYCLOAK_PROFILE_URL: "http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/userinfo"

      PUBLIC_URL: "http://localhost:8080"
      PORT: 8080
      KEY: $KEY
      SECRET: $SECRET

      DB_CLIENT: $DB_CLIENT
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password"
    
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "9090:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password

      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    networks:
      - keycloak
    depends_on:
      - postgres
 
  postgres:
    image: postgres:12
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak

networks:
  directus: {}
  keycloak: {}
```
Create a realm called `myrealm` on keycloak (localhost:9090)
Create a client under `myrealm` called `directus-ui` as follows:
![image](https://user-images.githubusercontent.com/27609953/129528131-71b5dcf9-96b3-4329-8a2b-ec8af3854b88.png)
![image](https://user-images.githubusercontent.com/27609953/129528198-a9a26de7-2b91-476d-babe-9ce797ecc266.png)

create user with same email address as the default admin user

![image](https://user-images.githubusercontent.com/27609953/129529477-7c146863-3a0f-469c-8b46-ace4cd89f257.png)

Try to login via keycloak oauth yields the following error:
![image](https://user-images.githubusercontent.com/27609953/129530265-d26d7c95-0a8a-4366-a783-eec0f3f55b4e.png)

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

docker

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, gonna preface this with I've never used keycloak before, but I wanted to help so I just tried running a similar setup and it worked. Here's a short video showing the successful login process:

https://user-images.githubusercontent.com/42867097/129583640-46acd2f5-9f1e-4004-b7e5-54db69d316aa.mp4

---

## docker-compose.yml used here

```yaml
services:
    directus:
        image: directus/directus:latest
        container_name: directus
        ports:
            - 8055:8055
        environment:
            - KEY
            - SECRET
            - PUBLIC_URL=http://192.168.0.111:8055
            - ADMIN_EMAIL=admin@example.com
            - ADMIN_PASSWORD=password
            # Database
            - DB_CLIENT=pg
            - DB_HOST=directus-postgres
            - DB_PORT=5432
            - DB_USER=directus
            - DB_PASSWORD=password
            - DB_DATABASE=directus_db
            # Oauth
            - OAUTH_PROVIDERS=keycloak
            - OAUTH_KEYCLOAK_KEY=directus-ui
            - OAUTH_KEYCLOAK_SECRET=<secret from keycloak directus-ui client Credentials page>
            - OAUTH_KEYCLOAK_AUTHORIZE_URL=http://192.168.0.111:9090/auth/realms/myrealm/protocol/openid-connect/auth
            - OAUTH_KEYCLOAK_ACCESS_URL=http://192.168.0.111:9090/auth/realms/myrealm/protocol/openid-connect/token
            - OAUTH_KEYCLOAK_SCOPE=openid email
            - OAUTH_KEYCLOAK_PROFILE_URL=http://192.168.0.111:9090/auth/realms/myrealm/protocol/openid-connect/userinfo
        depends_on:
            - directus-postgres
            - keycloak
        networks:
            - directus
      
    directus-postgres:
        image: postgres:alpine
        container_name: directus-postgres
        environment:
            - POSTGRES_USER=directus
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=directus_db
        networks:
            - directus
    
    keycloak:
        image: mylesagray/keycloak-arm:latest
        container_name: keycloak
        ports:
            - 9090:8080
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            # Database
            - DB_VENDOR=postgres
            - DB_ADDR=keycloak-postgres
            - DB_USER=keycloak
            - DB_PASSWORD=password
            - DB_DATABASE=keycloak_db
        depends_on:
            - keycloak-postgres
        networks:
            - keycloak

    keycloak-postgres:
        image: postgres:alpine
        container_name: keycloak-postgres
        environment:
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=keycloak_db
        networks:
            - keycloak
            
networks:
    directus:
    keycloak:
```

## Notable differences in my compose file vs yours

### Probably unimportant differences

- I used `192.168.0.111` instead of `localhost` since that's my docker host's local IP. 

- I used the default  port `8055` for directus instead of yours `8080`.

- I'm using a different keycloak image, only because my docker host is arm64 and the official keycloak image doesn't support it. However I can assure you it's the latest version based on my screenshot here (highlighted keycloak version & host architecture):
![chrome_HO8UBJtNOz](https://user-images.githubusercontent.com/42867097/129584972-22c892aa-439c-4a65-bc87-9ea188441907.png)
    I don't think you'll need to change keycloak image you are using.

### Might be of importance differences

- The `DB_VENDOR` I set it as `postgres` (lowercase) in reference to the official docs: https://github.com/keycloak/keycloak-containers/blob/15.0.1/server/README.md#database. Whereas yours is set as `POSTGRES`, but I also doubt it's anything really since you are still able to access keycloak just fine.

- some Keycloak env variables I didn't declare it since they already have default values (such as `DB_SCHEMA=public`) as seen in the official docs.

- The way I defined the environment variables in compose file is

    ```yaml
        environment:
            - key=value
    ```
    
    whereas you did
    
    ```yaml
        environment:
            key: value
    ```
    
    typically that should not be of any issue, but I personally do recall/experience some issue with the way docker compose interpolate the strings/values long time ago, so perhaps you can try using the way I did just as another form of testing.
    
## Other debugging suggestions

- If the directus database already has existing data, maybe you can try using another fresh volume or bind mount to test whether it helps or not.

- Also just comment out the uploads and extensions directory bind mount to directus to ensure nothing else possibly causes the issue for you.

- Do double check the `OAUTH_KEYCLOAK_SECRET` you're using is correct. Sample screenshot from my keycloak setup: 
![image](https://user-images.githubusercontent.com/42867097/129587172-ca9709ff-8fac-455f-9108-f43c0be8a3fa.png)

- If ultimately you are still unable to get things to work, you can just try running my docker compose directly (maybe just change the keycloak image back to the official one since mine is for arm64) and see does it work for you. Also note that my directus `KEY` & `SECRET` is not defined in the compose file, so make sure to fill in that value when you try it.

Hope you'll be able to resolve your issue. Do let us know if you have any update.

**Comment by Jason-CKY** [comment]
Thanks for the reply. I have tried again with your docker compose file directly (with the relevant changes):
 ```
      version: "3.7"
      services:
        directus:
            image: directus/directus:latest
            container_name: directus
            ports:
                - 8055:8055
            environment:
                - KEY=255d861b-5ea1-5996-9aa3-922530ec40b1
                - SECRET=6116487b-cda1-52c2-b5b5-c8022c45e263
                - PUBLIC_URL=http://localhost:8055
                - ADMIN_EMAIL=admin@example.com
                - ADMIN_PASSWORD=password
                # Database
                - DB_CLIENT=pg
                - DB_HOST=directus-postgres
                - DB_PORT=5432
                - DB_USER=directus
                - DB_PASSWORD=password
                - DB_DATABASE=directus_db
                # Oauth
                - OAUTH_PROVIDERS=keycloak
                - OAUTH_KEYCLOAK_KEY=directus-ui
                - OAUTH_KEYCLOAK_SECRET=62b3c57b-16b3-43cb-a99b-219c8f119457
                - OAUTH_KEYCLOAK_AUTHORIZE_URL=http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/auth
                - OAUTH_KEYCLOAK_ACCESS_URL=http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/token
                - OAUTH_KEYCLOAK_SCOPE=openid email
                - OAUTH_KEYCLOAK_PROFILE_URL=http://localhost:9090/auth/realms/myrealm/protocol/openid-connect/userinfo
            depends_on:
                - directus-postgres
                - keycloak
            networks:
                - directus
          
        directus-postgres:
            image: postgres:12
            container_name: directus-postgres
            environment:
                - POSTGRES_USER=directus
                - POSTGRES_PASSWORD=password
                - POSTGRES_DB=directus_db
            networks:
                - directus
        
        keycloak:
            image: quay.io/keycloak/keycloak:15.0.1
            container_name: keycloak
            ports:
                - 9090:8080
            environment:
                - KEYCLOAK_USER=admin
                - KEYCLOAK_PASSWORD=admin
                # Database
                - DB_VENDOR=postgres
                - DB_ADDR=keycloak-postgres
                - DB_USER=keycloak
                - DB_PASSWORD=password
                - DB_DATABASE=keycloak_db
            depends_on:
                - keycloak-postgres
            networks:
                - keycloak
      [](url)
        keycloak-postgres:
            image: postgres:12
            container_name: keycloak-postgres
            environment:
                - POSTGRES_USER=keycloak
                - POSTGRES_PASSWORD=password
                - POSTGRES_DB=keycloak_db
            networks:
                - keycloak
            volumes:
              - ./keycloak-db:/var/lib/postgresql/data
      networks:
        directus:
        keycloak:
```

[Screencast from 17-08-2021 09:27:52.zip](https://github.com/directus/directus/files/6996388/Screencast.from.17-08-2021.09.27.52.zip)

It results in the following error:
![Screenshot from 2021-08-17 09-29-25](https://user-images.githubusercontent.com/27609953/129649402-e24fb6fd-1ce2-498a-acce-b2ce85c198de.png)

Seems like directus is unable to connect to keycloak due to "ECONNREFUSED".  I googled this issue and found a [github issue](https://github.com/oidc-wp/openid-connect-generic/issues/53) that seem to suggest that both the browser (host machine) and the application (my docker container) must be able to connect to keycloak for openid to work. If so, then I suspect the reason you could make it work was due to using the docker host local IP instead of `localhost`. Since the user on #6749 used npx to create the directus instance locally, localhost works for him, but my directus container connects to itself with localhost.

May I know how to retrieve the docker host local IP? 

![Screenshot from 2021-08-17 09-38-43](https://user-images.githubusercontent.com/27609953/129649961-8d9ac4d9-63a3-42d5-a4c4-eccada022dee.png)
