### ISSUE TITLE
drive-azure crashes when deleting files when storage root is set to `''`

### ISSUE THREAD

**Issue by guillecro** [directus/directus#7788]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello!

We are using the docker image `ghcr.io/directus/directus:9.0.0-rc.91

We are using Azure as our File Storage and after setting everything, it works! We can upload pictures and all, but when we try to delete, or edit the picture with crop or any editing, it is not working as expected. It says **The requested URI does not represent any resource on the server.**

![image](https://user-images.githubusercontent.com/8771166/131929654-b4d8b793-2e27-4a11-8923-159df9562c0a.png)

Here are some server logs.

```bash
23:48:00 🚨 E_UNKNOWN: An unknown error happened with the file uploads/ccd0a42b-d221-4ea8-b1bd-4dd85fac6ab7.
Error code: RestError
Original stack:
RestError: The requested URI does not represent any resource on the server.
RequestId:a6567228-301e-0043-6e54-a06219000000
Time:2021-09-02T23:48:00.0590358Z
    at handleErrorResponse (/directus/node_modules/@azure/core-http/dist/index.js:3132:19)
    at /directus/node_modules/@azure/core-http/dist/index.js:3068:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StorageRetryPolicy.attemptSendRequest (/directus/node_modules/@azure/storage-blob/dist/index.js:14657:24)
    at async TracingPolicy.sendRequest (/directus/node_modules/@azure/core-http/dist/index.js:4282:30)
    at async StorageClientContext.sendOperationRequest (/directus/node_modules/@azure/core-http/dist/index.js:4638:31)
    at async ContainerClient.listBlobFlatSegment (/directus/node_modules/@azure/storage-blob/dist/index.js:22315:30) 
UnknownException: E_UNKNOWN: An unknown error happened with the file uploads/ccd0a42b-d221-4ea8-b1bd-4dd85fac6ab7.

Error code: RestError
Original stack:
RestError: The requested URI does not represent any resource on the server.
RequestId:a6567228-301e-0043-6e54-a06219000000
Time:2021-09-02T23:48:00.0590358Z
    at handleErrorResponse (/directus/node_modules/@azure/core-http/dist/index.js:3132:19)
    at /directus/node_modules/@azure/core-http/dist/index.js:3068:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StorageRetryPolicy.attemptSendRequest (/directus/node_modules/@azure/storage-blob/dist/index.js:14657:24)
    at async TracingPolicy.sendRequest (/directus/node_modules/@azure/core-http/dist/index.js:4282:30)
    at async StorageClientContext.sendOperationRequest (/directus/node_modules/@azure/core-http/dist/index.js:4638:31)
    at async ContainerClient.listBlobFlatSegment (/directus/node_modules/@azure/storage-blob/dist/index.js:22315:30)
    at handleError (/directus/node_modules/@directus/drive-azure/dist/AzureBlobWebServices.js:13:12)
    at AzureBlobWebServicesStorage.flatList (/directus/node_modules/@directus/drive-azure/dist/AzureBlobWebServices.js:189:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FilesService.uploadOne (/directus/node_modules/directus/dist/services/files.js:43:30)
    at async Busboy.<anonymous> (/directus/node_modules/directus/dist/controllers/files.js:66:32)
23:48:00 ✨ request errored PATCH 500 /files/ccd0a42b-d221-4ea8-b1bd-4dd85fac6ab7 107ms
```

```js
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file f12c8360-0910-4917-bf78-f0563d87c4d8.\n\nError code: RestError\nOriginal stack:\nRestError: The requested URI does not represent any resource on the server.\nRequestId:a2808cdd-c01e-0019-3954-a06498000000\nTime:2021-09-02T23:41:51.9444233Z\n    at handleErrorResponse (/directus/node_modules/@azure/core-http/dist/index.js:3132:19)\n    at /directus/node_modules/@azure/core-http/dist/index.js:3068:49\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async StorageRetryPolicy.attemptSendRequest (/directus/node_modules/@azure/storage-blob/dist/index.js:14657:24)\n    at async TracingPolicy.sendRequest (/directus/node_modules/@azure/core-http/dist/index.js:4282:30)\n    at async StorageClientContext.sendOperationRequest (/directus/node_modules/@azure/core-http/dist/index.js:4638:31)\n    at async ContainerClient.listBlobFlatSegment (/directus/node_modules/@azure/storage-blob/dist/index.js:22315:30)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

The resource does exist in my azure thou

![image](https://user-images.githubusercontent.com/8771166/131930232-bae696be-c7a0-4feb-874f-4f4945ed0b78.png)

### To Reproduce

So we have an Azure Storage Container and our File Storage portion looks like this (I will hide the secrets)

```yaml
# [...]
      # File Storage
      # --------------------
      # A CSV of storage locations (eg: 'local' (default),'digitalocean','amazon') to use. You can use any names you'd like for these keys.
      STORAGE_LOCATIONS: 'azure'
      # For each of the storage locations listed, you must provide the following configuration:
      # Where to store the files on disk
      # NOTE: We were told its not neccesary to set up this variable.. A user said: "I don't think so, at least currently I have a directus project using azure blob storage without this variable and everything is working fine"
      # STORAGE_AZURE_ROOT: ''
      # Which driver to use, either local, s3, gcs, azure
      STORAGE_AZURE_DRIVER: 'azure'
      # Azure Driver Envs:
      # Azure Storage container
      STORAGE_AZURE_CONTAINER_NAME: 'my-container/my-folder'
      # Azure Storage account name
      STORAGE_AZURE_ACCOUNT_NAME: 'my-account'
      # Azure Storage key
      STORAGE_AZURE_ACCOUNT_KEY: 'my-key'
      # Azure URL
      STORAGE_AZURE_ENDPOINT: 'https://my-account.blob.core.windows.net'
# [...]
```

### What version of Directus are you using?

ghcr.io/directus/directus:9.0.0-rc.91

### What version of Node.js are you using?

Version shipped with directus/directus:9.0.0-rc.91 (npm 7.20.3)

### What database are you using?

mysql:5.7

### What browser are you using?

Chome and Firefox (latest)

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker (directus/directus:9.0.0-rc.91)

**Comment by guillecro** [comment]
Quick update and sorry about bothering.
We found out 2 problems, I will explain and hopefully this will stay as a reference.

1. We regenerated the Access Key. It might have been one of the reasons but its on our end.
2. Also, the error happened because if you dont set `STORAGE_AZURE_ROOT` it will fail like it failed.

The problem was because using `STORAGE_AZURE_CONTAINER_NAME: 'my-container/my-folder'` and not setting `STORAGE_AZURE_ROOT` (Defaults is `''`) gives this error. Uploading works fine, you can see it and everything, but editing or deleting gives this error, and also it doesnt sync with the Storage. So now we fixed it and everything works perfectly!

```yaml
# [...]
      # File Storage
      # --------------------
      # A CSV of storage locations (eg: 'local' (default),'digitalocean','amazon') to use. You can use any names you'd like for these keys.
      STORAGE_LOCATIONS: 'azure'
      # For each of the storage locations listed, you must provide the following configuration:
      # Where to store the files on disk
      STORAGE_AZURE_ROOT: 'my-folder'
      # Which driver to use, either local, s3, gcs, azure
      STORAGE_AZURE_DRIVER: 'azure'
      # Azure Driver Envs:
      # Azure Storage container
      STORAGE_AZURE_CONTAINER_NAME: 'my-container'
      # Azure Storage account name
      STORAGE_AZURE_ACCOUNT_NAME: 'my-account'
      # Azure Storage key
      STORAGE_AZURE_ACCOUNT_KEY: 'my-key'
      # Azure URL
      STORAGE_AZURE_ENDPOINT: 'https://my-account.blob.core.windows.net'
# [...]
```

Anyways, sorry for the fake issue, but I hope this helps anyone in the future.
Thank you Directus team!
