### ISSUE TITLE
Permissions issue when accessing custom endpoint

### ISSUE THREAD

**Issue by geantas** [directus/directus#8213]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I've created a custom endpoint which takes an existing endpoint, filters out the required item and responds with the data. However, if I try to access it from an application, I am getting an error:
```json
{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
```
There is no setting to enable access to the extension in application's dashboard, as it's custom made endpoint. It also does not use any junction tables.
I am using pre-configured docker-compose.yml file to run Directus on my server. Here's the configuration for the specific part:
```yaml
directus:
  container_name: directus
  image: directus/directus:latest
  restart: unless-stopped
  ports:
    - 8055:8055
  volumes:
    # By default, uploads are stored in /directus/uploads
    # Always make sure your volumes matches the storage root when using
    # local driver
    - ./uploads:/directus/uploads
    # Make sure to also mount the volume when using SQLite
    # - ./database:/directus/database
    # If you want to load extensions from the host
    - ./extensions:/directus/extensions
  networks:
    - directus
  depends_on:
    - cache
    - database
  environment:
    KEY: 'XXX'
    SECRET: 'XXX'

    DB_CLIENT: 'mysql'
    DB_HOST: 'database'
    DB_PORT: '3306'
    DB_DATABASE: 'XXX'
    DB_USER: 'XXX'
    DB_PASSWORD: 'XXXXX'

    CACHE_ENABLED: 'true'
    CACHE_STORE: 'redis'
    CACHE_REDIS: 'redis://cache:6379'

    ADMIN_EMAIL: 'XXX@XXX.XX'
    ADMIN_PASSWORD: 'XXXXX'

    EXTENSIONS_PATH: './extensions'

    # Make sure to set this in production
    # (see https://docs.directus.io/reference/environment-variables/#general)
    PUBLIC_URL: 'https://XXXXX'
```

### To Reproduce

1. Get `docker-compose.yml` file from official documentation.
3. Run docker container on your server: ``docker-compose up -d`
3. Extend the Directus application by adding a new endpoint.
4. Try to access the endpoint you've created.
5. See error "You don't have permission to access this."

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

v12.22.6

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker
