### ISSUE TITLE
Insights Module - Editing a Panel, have to select the details again

### ISSUE THREAD

**Issue by mark-james** [directus/directus#8252]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When selecting a panel to edit, the previous selections are not displayed. 

![image](https://user-images.githubusercontent.com/26987752/134435915-72037fdb-42e3-4bcc-97ce-0b694082e0d6.png)

![image](https://user-images.githubusercontent.com/26987752/134436128-014289e9-7926-459c-b5df-eed1824d11e0.png)

### To Reproduce

Create a panel and then edit the panel again.

### What version of Directus are you using?

rc94

### What version of Node.js are you using?

Whatever is in the docker image directus:9.0.0-rc.94

### What database are you using?

postgres 12 via docker

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Hi, I tried to reproduce it on rc.94 to no avail, as seen here:
![pEpUTjLkqp](https://user-images.githubusercontent.com/42867097/134480869-33849d71-54aa-4df2-811a-67475cf16639.gif)

Can you try to check is there any error log in the console tab or failed network requests in the network tab in DevTools? Or perhaps logs from Directus itself?

**Comment by mark-james** [comment]
Hi @azrikahar,
I can't see any errors in the console or the networks tab. The docker log file doesn't seem to be showing up anything either. I've also tried safari as a second browser, it has the same behaviour.

I upgrade my local docker instance from rc92 to 94, not sure if that upgrade could've caused any issues.
I had a couple of customer extensions which I've now stripped out. Still the same behaviour.

Video below.

https://user-images.githubusercontent.com/26987752/134487533-1c116dea-a088-4383-830a-0d69155329eb.mp4

**Comment by azrikahar** [comment]
@mark-james hmm that is strange indeed. Thank you very much for the great video!

Would you mind spinning up a fresh local instance using the latest rc.94 image and see how it goes? That would help a ton to confirm whether it's an issue related to upgrades (92 to 94) rather than rc.94 itself 👍

**Comment by mark-james** [comment]
No problem @azrikahar.

I've just done so and still had the same problem. 

The docker-compose file I'm running locally was pulled from the directus docs. Below for reference -
```
version: '3.2'
services:
  database:
    container_name: database
    image: postgres:12
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:9.0.0-rc.94
    ports:
      - 8055:8055
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume When using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:

```
