### ISSUE TITLE
Snapshot file not empty in new project without any changes

### ISSUE THREAD

**Issue by paescuj** [directus/directus#8318]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The snapshot file (created via `npx directus schema snapshot ./snapshot.yaml`) contains information (namely about `directus_dashboards`, `directus_panels`, `directus_settings`) in new projects where no changes have been made yet.

Example:
```yaml
version: 1
directus: 9.0.0-rc.94
collections:
  - collection: directus_dashboards
    meta: null
    schema:
      name: directus_dashboards
      schema: public
      comment: null
  - collection: directus_panels
    meta: null
    schema:
      name: directus_panels
      schema: public
      comment: null

[...]

relations:
  - collection: directus_settings
    field: storage_default_folder
    related_collection: directus_folders
    schema:
      table: directus_settings
      column: storage_default_folder
      foreign_key_table: directus_folders
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: directus_settings_storage_default_folder_foreign
      on_update: NO ACTION
      on_delete: SET NULL
```

I think it's because those collections, fields & relations are missing in [system-data](https://github.com/directus/directus/tree/main/api/src/database/system-data), right?

### To Reproduce

1. Create a new Directus project
2. Run `npx directus schema snapshot ./snapshot.yaml`
3. Inspect snapshot file

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

Docker Image

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker
