### ISSUE TITLE
Empty collection list after schema migration

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#8377]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created a local collection with two fields:
1. slug (primary key, string, slugified)
2. name

After this I took a snapshot of this schema and applied it to our staging environment. That seemed to work and I can add data to that collection in staging. However, the collection data list in the app stays empty after adding more data (added two, see screenshot)

Locally the list shows up fine after adding data.

![CleanShot 2021-09-28 at 12 06 33](https://user-images.githubusercontent.com/4633876/135067770-04c702d6-f625-4cd8-b9a0-e89acb02389b.png)

### To Reproduce

see above

### What version of Directus are you using?

RC95

### What version of Node.js are you using?

14 lts

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Not able to reproduce this on my end..

1. Setup a new fresh installation
2. Added a collection `articles` with a "Manually entered string" for it's id named `slug`
3. Added a regular string field `name`
4. Created snapshot:

<details>
<summary>Snapshot</summary>

```yaml
version: 1
directus: 9.0.0-rc.95
collections:
  - collection: articles
    meta:
      collection: articles
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
    schema:
      name: articles
      schema: dbo
      catalog: directus
fields:
  - collection: articles
    field: slug
    type: string
    schema:
      table: articles
      name: slug
      data_type: nvarchar
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      default_value: null
      is_primary_key: true
      is_unique: true
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
      is_generated: false
      generation_expression: null
    meta:
      collection: articles
      field: slug
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
  - collection: articles
    field: name
    type: string
    schema:
      table: articles
      name: name
      data_type: nvarchar
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      default_value: null
      is_primary_key: false
      is_unique: false
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
      is_generated: false
      generation_expression: null
    meta:
      collection: articles
      field: name
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
relations: []
```

</details>

5. Applied snapshot on an empty installation
