### ISSUE TITLE
Error message not showing up on saving an entry that conflicts constraints

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#8868]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am trying to add an entry to a column that violates the following constraints:

`CREATE UNIQUE INDEX ON i18n ((project IS NULL), key) WHERE project IS NULL;`

After saving, the backend correctly fails, but no error message is shown on the UI

![image](https://user-images.githubusercontent.com/3661363/137617613-53667ef0-c941-4867-9ff2-44994e64b389.png)

### To Reproduce

Saving an entry that violates some constraints

### Errors Shown

none

### What version of Directus are you using?

9.0.0-rc.98

### What version of Node.js are you using?

16.11.1

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-37-generic

### How are you deploying Directus?

Docker

**Comment by mr-sanders** [comment]
I'm having such a problem with the case when I have any restrictions (e.g. the "Value has to be unique" rule for "slug" or "required" for the "title") inside the "translations" field. The "translations" field itself is marked as "required" to make restrictions for "slug" and "title" works. I try to save a new item and don't see an error. I'm doing it from the admin panel via the "Create Item" page with an existing slug value or with an empty title. By the way, I have a 400 error with "Field \"slug\" has to be unique" message in the network tab of the Developer Tools.

**Comment by jaycammarano** [comment]
> I'm having such a problem with the case when I have any restrictions (e.g. the "Value has to be unique" rule for "slug" or "required" for the "title") inside the "translations" field. The "translations" field itself is marked as "required" to make restrictions for "slug" and "title" works. I try to save a new item and don't see an error. I'm doing it from the admin panel via the "Create Item" page with an existing slug value or with an empty title. By the way, I have a 400 error with "Field "slug" has to be unique" message in the network tab of the Developer Tools.

Do you mind sharing a snapshot of your database? I'm having trouble visualizing what fields are in your database.

**Comment by mr-sanders** [comment]
@jaycammarano Sorry for the long response. This is my schema:
<details>
<summary>Schema Snapshot</summary>

```yaml
version: 1
directus: 9.5.1
collections:
  - collection: languages
    meta:
      collection: languages
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: languages
      comment: null
  - collection: posts
    meta:
      collection: posts
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: status
      archive_app_filter: true
      archive_value: archived
      unarchive_value: draft
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: posts
      comment: null
  - collection: posts_translations
    meta:
      collection: posts_translations
      icon: import_export
      note: null
      display_template: null
      hidden: true
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: null
      group: null
      collapse: open
    schema:
      schema: public
      name: posts_translations
      comment: null
fields:
  - collection: languages
    field: code
    type: string
    schema:
      name: code
      table: languages
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: true
      is_primary_key: true
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: languages
      field: code
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: languages
    field: name
    type: string
    schema:
      name: name
      table: languages
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: languages
      field: name
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: id
    type: uuid
    schema:
      name: id
      table: posts
      schema: public
      data_type: uuid
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: true
      is_primary_key: true
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: id
      special:
        - uuid
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: status
    type: string
    schema:
      name: status
      table: posts
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: draft
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: status
      special: null
      interface: select-dropdown
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      display: labels
      display_options:
        showAsDot: true
        choices:
          - background: '#00C897'
            value: published
          - background: '#D3DAE4'
            value: draft
          - background: '#F7971C'
            value: archived
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts
    field: meta
    type: string
    schema:
      name: meta
      table: posts
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts
      field: meta
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: posts_translations
    field: id
    type: integer
    schema:
      name: id
      table: posts_translations
      schema: public
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('posts_translations_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts_translations
      field: id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_translations
    field: posts_id
    type: uuid
    schema:
      name: posts_id
      table: posts_translations
      schema: public
      data_type: uuid
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: public
      foreign_key_table: posts
      foreign_key_column: id
    meta:
      collection: posts_translations
      field: posts_id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_translations
    field: languages_id
    type: string
    schema:
      name: languages_id
      table: posts_translations
      schema: public
      data_type: character varying
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: public
      foreign_key_table: languages
      foreign_key_column: code
    meta:
      collection: posts_translations
      field: languages_id
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: true
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: posts_translations
    field: title
    type: string
    schema:
      name: title
      table: posts_translations
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts_translations
      field: title
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: posts_translations
    field: slug
    type: string
    schema:
      name: slug
      table: posts_translations
      schema: public
      data_type: character varying
      is_nullable: false
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: 255
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: true
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: posts_translations
      field: slug
      special: null
      interface: input
      options:
        slug: true
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
  - collection: posts
    field: translations
    type: alias
    schema: null
    meta:
      collection: posts
      field: translations
      special:
        - translations
      interface: translations
      options:
        languageField: name
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      translations: null
      note: null
      conditions: null
      required: true
      group: null
relations:
  - collection: posts_translations
    field: languages_id
    related_collection: languages
    schema:
      constraint_name: posts_translations_languages_id_foreign
      table: posts_translations
      column: languages_id
      foreign_key_schema: public
      foreign_key_table: languages
      foreign_key_column: code
      on_update: NO ACTION
      on_delete: CASCADE
    meta:
      many_collection: posts_translations
      many_field: languages_id
      one_collection: languages
      one_field: null
      one_collection_field: null
      one_allowed_collections: null
      junction_field: posts_id
      sort_field: null
      one_deselect_action: nullify
  - collection: posts_translations
    field: posts_id
    related_collection: posts
    schema:
      constraint_name: posts_translations_posts_id_foreign
      table: posts_translations
      column: posts_id
      foreign_key_schema: public
      foreign_key_table: posts
      foreign_key_column: id
      on_update: NO ACTION
      on_delete: CASCADE
    meta:
      many_collection: posts_translations
      many_field: posts_id
      one_collection: posts
      one_field: translations
      one_collection_field: null
      one_allowed_collections: null
      junction_field: languages_id
      sort_field: null
      one_deselect_action: delete
```

</details> 

Both posts.translations.title and posts.translations.slug produce silent 400 errors if violate restrictions (obligation for both or uniqueness for slug). Errors for posts.meta work properly.
