### ISSUE TITLE
Migrating from rc91 to rc100: Unknown character set: 'utf8mb4_general_ci'

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#9264]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Migrating from rc91 to rc100 leads to a database character set error

### To Reproduce

Migrate from rc91 to rc100

```yaml
  directus-...:
    container_name: directus-...
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    volumes:
      - /...
    networks:
      - directus
    depends_on:
      - directus-cache
    environment:
      CACHE_SCHEMA: 'false'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 20000
      # LOG_LEVEL: 'trace'

      DB_CLIENT: 'mysql'
      DB_HOST: '...'
      DB_PORT: '3306'
      DB_DATABASE: 'directus_tc01'
      DB_USER: 'directus'
      DB_PASSWORD: '...'
      DB_CHARSET: 'utf8mb4_general_ci'
```

I've tried various character sets. Directus tables use the collation `utf8mb4_0900_ai_ci` (which I've also tried). I have two other Directus containers running with the same config but I wisely left them on rc91 while attempting to test rc100.

### Errors Shown

19:47:51 ✨ Initializing bootstrap...
19:47:51 ✨ Database already initialized, skipping install
19:47:51 ✨ Running migrations...
19:47:51 ✨ Applying Add Insights...
Error: ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'utf8mb4_general_ci'
    at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)

### What version of Directus are you using?

rc100

### What version of Node.js are you using?

14.17.3

### What database are you using?

MySQL 8.0.24

### What browser are you using?

-

### What operating system are you using?

Docker

### How are you deploying Directus?

Docker
