### ISSUE TITLE
Folder ID should not be in the schema snapshot

### ISSUE THREAD

**Issue by AlexisWalravens** [directus/directus#9464]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I you add a default folder to an file/image field and then create a snapshot of the schema, the id of the folder is stored in the snapshot.

When applying the snapshot, it will set an id of a folder that doesn't exist to the file/image field.

--- 
I don't know what would be a good solution, but I thought the folders should be created upon applying the schema and so store the folder structure in the schema somehow. 

The context of how I discoverd that is the following:
I have a **local instance** of directus to make changes to the schema and update directus and then **deploy** it to my **live instance**.  

I have a git repo that contains:
* The extensions folder
* The package.json with the directus version and packages that I use in my custom endpoints/hooks
* Dockerfile to run a local mairadb
* A snapshot of the latest schema changes

When pushed I have a webhook that triggers the deployment and run the following:
* Dump the DB
* Stop directus pm2 process
* Pull the main git branch
* `npm update`
* `npx directus database migrate:latest`
* `npx directus schema apply ./snapshot.yaml`
* start Directus pm2 process

Here is what my image field looks like in the snapshot:
```` yaml
  - collection: pages
    field: image
    type: string
    schema:
      name: image
      table: pages
      data_type: char
      default_value: null
      generation_expression: null
      max_length: 36
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_column: null
      foreign_key_table: null
      comment: ''
    meta:
      collection: pages
      field: image
      special: null
      interface: file-image
      options:
        folder: baf2ae23-20f2-49b1-94ba-d48e701f4352
      display: image
      display_options: null
      readonly: false
      hidden: false
      sort: 7
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
````

### To Reproduce

1. Create a folder
2. Create a collection
3. Add a image field to that collection
4. Set the newly created folder as default folder for the newly created image field
5. run npx directus schema snapshot ./snapshot.yaml

### What version of Directus are you using?

v9.0.0-rc.101

### What version of Node.js are you using?

16.13.0

### What database are you using?

MaraiDB 10.6.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11 WSL

### How are you deploying Directus?

locally
